import type { StaticHotelRoomOption } from "@/lib/hotels/hotelRoomOptions";

export type StaticHotelRecord = {
  id: string;
  slug: string;
  name: string;
  city: string;
  country: string;
  region: string;
  aliases: readonly string[];
  location: string;
  latitude: number;
  longitude: number;
  neighbourhood: string;
  propertyType: string;
  classificationStars: 1 | 2 | 3 | 4 | 5;
  amenities: readonly string[];
  imageUrl: string;
  imageUrls: readonly string[];
  imageProvenance: string;
  roomSummary: string;
  bedSummary: string;
  description: string;
  indicativeNightlyPrice: number;
  currency: "USD";
  lastReviewed: string;
  searchTags: readonly string[];
  interestTags: readonly string[];
  familySuitable: boolean;
  businessSuitable: boolean;
  accessibility: readonly string[];
  roomOptions: readonly StaticHotelRoomOption[];
};

const londonImage =
  "/images/premium/homepage/destinations/kurioticket-homepage-destination-london-tower-bridge-thames-001.jpg";
const parisImage =
  "/images/premium/homepage/destinations/kurioticket-homepage-destination-paris-eiffel-tower-buildings-001.jpg";
const newYorkImage =
  "/images/premium/homepage/destinations/kurioticket-homepage-destination-new-york-statue-liberty-skyline-001.jpg";
const hotelImage =
  "/images/premium/hotels/kurioticket-hotels-hero-bellboy-guest-arrival-lobby-001.jpg";

const staticHotelGalleryImages = [
  hotelImage,
  londonImage,
  parisImage,
  newYorkImage,
  "/images/premium/homepage/destinations/kurioticket-homepage-destination-miami-skyline-waterfront-001.jpg",
  "/images/premium/homepage/destinations/kurioticket-homepage-destination-las-vegas-strip-night-drone-001.jpg",
  "/images/premium/homepage/destinations/kurioticket-homepage-destination-los-angeles-palm-skyline-001.jpg",
  "/images/premium/homepage/kurioticket-homepage-hero-businesswoman-modern-city-luggage-001.jpg",
  "/images/premium/packages/kurioticket-packages-hero-tropical-resort-001.jpg",
  "/images/premium/cars/kurioticket-cars-hero-coastal-convertible-001.jpg",
] as const;

function buildStaticHotelGallery(primaryImage: string, hotelId: string) {
  const remainingImages = staticHotelGalleryImages.filter(
    (image) => image !== primaryImage,
  );
  const offset =
    [...hotelId].reduce(
      (total, character) => total + character.charCodeAt(0),
      0,
    ) % remainingImages.length;
  const rotated = remainingImages.map(
    (_image, index, images) => images[(index + offset) % images.length]!,
  );

  return [primaryImage, ...rotated] as const;
}

const common = {
  propertyType: "Hotel",
  currency: "USD" as const,
  lastReviewed: "2026-08-02",
  imageProvenance: "Kurioticket approved repository asset",
  accessibility: [
    "Accessibility features should be confirmed directly with the property",
  ],
};

const planningRoom = ({
  hotelId,
  id,
  name,
  bedConfiguration,
  features,
  mealPlan,
  cancellationInfo,
  basePrice,
  multiplier = 1,
}: {
  hotelId: string;
  id: string;
  name: string;
  bedConfiguration: string;
  features: string[];
  mealPlan: string;
  cancellationInfo: string;
  basePrice: number;
  multiplier?: number;
}): StaticHotelRoomOption => ({
  id: `${hotelId}-${id}`,
  name,
  bedConfiguration,
  features,
  mealPlan,
  cancellationInfo,
  taxesAndFeesIncluded: undefined,
  indicativeNightlyPrice: Math.round(basePrice * multiplier),
  currency: "USD",
});

function buildPlanningRooms({
  hotelId,
  roomSummary,
  bedSummary,
  basePrice,
}: {
  hotelId: string;
  roomSummary: string;
  bedSummary: string;
  basePrice: number;
}): readonly StaticHotelRoomOption[] {
  return [
    planningRoom({
      hotelId,
      id: "room-only",
      name: `${roomSummary} — room-only estimate`,
      bedConfiguration: bedSummary,
      features: ["Planning room category", "Wi-Fi"],
      mealPlan: "Room only",
      cancellationInfo:
        "Planning estimate only; final terms are not yet confirmed.",
      basePrice,
    }),
    planningRoom({
      hotelId,
      id: "breakfast",
      name: `${roomSummary} — breakfast estimate`,
      bedConfiguration: bedSummary,
      features: ["Breakfast planning allowance", "Wi-Fi"],
      mealPlan: "Breakfast included in planning estimate",
      cancellationInfo:
        "Planning estimate only; final terms are not yet confirmed.",
      basePrice,
      multiplier: 1.12,
    }),
    planningRoom({
      hotelId,
      id: "flexible",
      name: `${roomSummary} — flexible estimate`,
      bedConfiguration: bedSummary,
      features: ["Flexible planning terms", "Wi-Fi"],
      mealPlan: "Room only",
      cancellationInfo:
        "Flexible planning terms; final terms are not yet confirmed.",
      basePrice,
      multiplier: 1.18,
    }),
  ];
}

function verifiedCatalogueHotel(
  input: Omit<
    StaticHotelRecord,
    "slug" | "propertyType" | "currency" | "imageUrls" | "roomOptions"
  >,
): StaticHotelRecord {
  return {
    ...input,
    slug: input.id,
    propertyType: "Hotel",
    currency: "USD",
    imageUrls: buildStaticHotelGallery(input.imageUrl, input.id),
    roomOptions: buildPlanningRooms({
      hotelId: input.id,
      roomSummary: input.roomSummary,
      bedSummary: input.bedSummary,
      basePrice: input.indicativeNightlyPrice,
    }),
  };
}

const staticHotelProperties: readonly StaticHotelRecord[] = [
  {
    ...common,
    id: "the-savoy-london",
    slug: "the-savoy-london",
    name: "The Savoy",
    city: "London",
    country: "United Kingdom",
    region: "England",
    aliases: ["london", "lon", "united kingdom", "uk", "england"],
    location: "Strand, London",
    latitude: 51.5104,
    longitude: -0.1208,
    neighbourhood: "Covent Garden",
    classificationStars: 5,
    amenities: ["Wi-Fi", "Concierge", "Fitness centre", "Indoor pool"],
    imageUrl: londonImage,
    imageUrls: buildStaticHotelGallery(londonImage, "the-savoy-london"),
    roomSummary: "Classic room options",
    bedSummary: "Bed configuration varies by room",
    description:
      "A landmark hotel on the Strand, well placed for the West End and the River Thames.",
    indicativeNightlyPrice: 760,
    roomOptions: [
      planningRoom({
        hotelId: "the-savoy-london",
        id: "room-only",
        name: "Classic room options — room-only estimate",
        bedConfiguration: "Bed configuration varies by room",
        features: ["Planning room category", "Wi-Fi"],
        mealPlan: "Room only",
        cancellationInfo:
          "Planning estimate only; final terms are not yet confirmed.",
        basePrice: 760,
      }),
      planningRoom({
        hotelId: "the-savoy-london",
        id: "breakfast",
        name: "Classic room options — breakfast estimate",
        bedConfiguration: "Bed configuration varies by room",
        features: ["Breakfast planning allowance", "Wi-Fi"],
        mealPlan: "Breakfast included in planning estimate",
        cancellationInfo:
          "Planning estimate only; final terms are not yet confirmed.",
        basePrice: 760,
        multiplier: 1.12,
      }),
      planningRoom({
        hotelId: "the-savoy-london",
        id: "flexible",
        name: "Classic room options — flexible estimate",
        bedConfiguration: "Bed configuration varies by room",
        features: ["Flexible planning terms", "Wi-Fi"],
        mealPlan: "Room only",
        cancellationInfo:
          "Flexible planning terms; final terms are not yet confirmed.",
        basePrice: 760,
        multiplier: 1.18,
      }),
    ],
    searchTags: ["central", "west end", "luxury"],
    interestTags: ["culture", "dining"],
    familySuitable: true,
    businessSuitable: true,
  },
  {
    ...common,
    id: "park-plaza-westminster-bridge",
    slug: "park-plaza-westminster-bridge",
    name: "Park Plaza Westminster Bridge London",
    city: "London",
    country: "United Kingdom",
    region: "England",
    aliases: ["london", "lon", "united kingdom", "uk", "england"],
    location: "200 Westminster Bridge Rd, Lambeth, London SE1 7UT",
    latitude: 51.501,
    longitude: -0.1167,
    neighbourhood: "South Bank",
    classificationStars: 4,
    amenities: ["Wi-Fi", "Fitness centre", "Indoor pool", "Restaurant"],
    imageUrl: londonImage,
    imageUrls: buildStaticHotelGallery(
      londonImage,
      "park-plaza-westminster-bridge",
    ),
    roomSummary: "Guest room and studio options",
    bedSummary: "Bed configuration varies by room",
    description:
      "A South Bank property near Westminster Bridge and major central London sights.",
    indicativeNightlyPrice: 290,
    roomOptions: [
      planningRoom({
        hotelId: "park-plaza-westminster-bridge",
        id: "room-only",
        name: "Guest room and studio options — room-only estimate",
        bedConfiguration: "Bed configuration varies by room",
        features: ["Planning room category", "Wi-Fi"],
        mealPlan: "Room only",
        cancellationInfo:
          "Planning estimate only; final terms are not yet confirmed.",
        basePrice: 290,
      }),
      planningRoom({
        hotelId: "park-plaza-westminster-bridge",
        id: "breakfast",
        name: "Guest room and studio options — breakfast estimate",
        bedConfiguration: "Bed configuration varies by room",
        features: ["Breakfast planning allowance", "Wi-Fi"],
        mealPlan: "Breakfast included in planning estimate",
        cancellationInfo:
          "Planning estimate only; final terms are not yet confirmed.",
        basePrice: 290,
        multiplier: 1.12,
      }),
      planningRoom({
        hotelId: "park-plaza-westminster-bridge",
        id: "flexible",
        name: "Guest room and studio options — flexible estimate",
        bedConfiguration: "Bed configuration varies by room",
        features: ["Flexible planning terms", "Wi-Fi"],
        mealPlan: "Room only",
        cancellationInfo:
          "Flexible planning terms; final terms are not yet confirmed.",
        basePrice: 290,
        multiplier: 1.18,
      }),
    ],
    searchTags: ["south bank", "westminster", "family"],
    interestTags: ["sightseeing", "culture"],
    familySuitable: true,
    businessSuitable: true,
  },
  {
    ...common,
    id: "park-plaza-county-hall-london",
    slug: "park-plaza-county-hall-london",
    name: "Park Plaza County Hall London",
    city: "London",
    country: "United Kingdom",
    region: "England",
    aliases: ["london", "lon", "united kingdom", "uk", "england"],
    location: "1 Addington St, Lambeth, London SE1 7RY",
    latitude: 51.5014,
    longitude: -0.1163,
    neighbourhood: "South Bank",
    classificationStars: 4,
    amenities: ["Wi-Fi", "Restaurant", "Fitness centre", "Spa"],
    imageUrl: hotelImage,
    imageUrls: buildStaticHotelGallery(
      hotelImage,
      "park-plaza-county-hall-london",
    ),
    roomSummary: "Superior room and studio options",
    bedSummary: "Bed configuration varies by room",
    description:
      "A South Bank hotel beside County Hall, with family-oriented room categories and quick access to Waterloo and Westminster.",
    indicativeNightlyPrice: 260,
    roomOptions: buildPlanningRooms({
      hotelId: "park-plaza-county-hall-london",
      roomSummary: "Superior room and studio options",
      bedSummary: "Bed configuration varies by room",
      basePrice: 260,
    }),
    searchTags: ["south bank", "waterloo", "family"],
    interestTags: ["sightseeing", "culture"],
    familySuitable: true,
    businessSuitable: true,
    accessibility: [
      "Accessible accommodation features are available; confirm the selected room directly with the property",
    ],
  },
  {
    ...common,
    id: "citizenm-tower-of-london",
    slug: "citizenm-tower-of-london",
    name: "citizenM Tower of London",
    city: "London",
    country: "United Kingdom",
    region: "England",
    aliases: ["london", "lon", "united kingdom", "uk", "england"],
    location: "40 Trinity Square, London EC3N 4DJ",
    latitude: 51.51016,
    longitude: -0.07643,
    neighbourhood: "Tower Hill",
    classificationStars: 4,
    amenities: ["Wi-Fi", "Restaurant", "Bar", "Workspaces"],
    imageUrl: londonImage,
    imageUrls: buildStaticHotelGallery(londonImage, "citizenm-tower-of-london"),
    roomSummary: "Smart king room options",
    bedSummary: "XL king bed",
    description:
      "A technology-led Tower Hill hotel with compact smart rooms, shared living spaces and a rooftop bar overlooking central London landmarks.",
    indicativeNightlyPrice: 230,
    roomOptions: buildPlanningRooms({
      hotelId: "citizenm-tower-of-london",
      roomSummary: "Smart king room options",
      bedSummary: "XL king bed",
      basePrice: 230,
    }),
    searchTags: ["tower hill", "city of london", "smart hotel"],
    interestTags: ["sightseeing", "business", "design"],
    familySuitable: false,
    businessSuitable: true,
    accessibility: [
      "Accessible routes and mobility-accessible rooms are available; confirm the selected room directly with the property",
    ],
  },
  {
    ...common,
    id: "the-clermont-london-charing-cross",
    slug: "the-clermont-london-charing-cross",
    name: "The Clermont London, Charing Cross",
    city: "London",
    country: "United Kingdom",
    region: "England",
    aliases: ["london", "lon", "united kingdom", "uk", "england"],
    location: "Strand, Charing Cross, London WC2N 5HX",
    latitude: 51.5084,
    longitude: -0.12472,
    neighbourhood: "Charing Cross",
    classificationStars: 4,
    amenities: ["Wi-Fi", "Restaurant", "Bar", "Fitness centre"],
    imageUrl: hotelImage,
    imageUrls: buildStaticHotelGallery(
      hotelImage,
      "the-clermont-london-charing-cross",
    ),
    roomSummary: "Classic, superior and studio options",
    bedSummary: "Bed configuration varies by room",
    description:
      "A Victorian railway hotel on the Strand, connecting central London transport with Trafalgar Square, Covent Garden and the West End.",
    indicativeNightlyPrice: 310,
    roomOptions: buildPlanningRooms({
      hotelId: "the-clermont-london-charing-cross",
      roomSummary: "Classic, superior and studio options",
      bedSummary: "Bed configuration varies by room",
      basePrice: 310,
    }),
    searchTags: ["charing cross", "strand", "west end"],
    interestTags: ["culture", "theatre", "business"],
    familySuitable: true,
    businessSuitable: true,
  },
  {
    ...common,
    id: "sea-containers-london",
    slug: "sea-containers-london",
    name: "Sea Containers London",
    city: "London",
    country: "United Kingdom",
    region: "England",
    aliases: ["london", "lon", "united kingdom", "uk", "england"],
    location: "20 Upper Ground, South Bank, London SE1 9PD",
    latitude: 51.5083955,
    longitude: -0.1066386,
    neighbourhood: "South Bank",
    classificationStars: 5,
    amenities: ["Wi-Fi", "Restaurant", "Fitness centre", "Spa"],
    imageUrl: londonImage,
    imageUrls: buildStaticHotelGallery(londonImage, "sea-containers-london"),
    roomSummary: "Guest room, suite and family options",
    bedSummary: "Double, queen and king configurations vary by room",
    description:
      "A design-focused riverside hotel on the South Bank with dining, rooftop spaces, a cinema, spa and fitness facilities.",
    indicativeNightlyPrice: 360,
    roomOptions: buildPlanningRooms({
      hotelId: "sea-containers-london",
      roomSummary: "Guest room, suite and family options",
      bedSummary: "Double, queen and king configurations vary by room",
      basePrice: 360,
    }),
    searchTags: ["south bank", "riverside", "design hotel"],
    interestTags: ["culture", "dining", "wellness"],
    familySuitable: true,
    businessSuitable: true,
    accessibility: [
      "The property states that disabled guests have access; confirm the selected room directly with the property",
    ],
  },
  {
    ...common,
    id: "london-marriott-hotel-county-hall",
    slug: "london-marriott-hotel-county-hall",
    name: "London Marriott Hotel County Hall",
    city: "London",
    country: "United Kingdom",
    region: "England",
    aliases: ["london", "lon", "united kingdom", "uk", "england"],
    location: "London County Hall, Westminster Bridge Road, London SE1 7PB",
    latitude: 51.50171,
    longitude: -0.11886,
    neighbourhood: "South Bank",
    classificationStars: 5,
    amenities: ["Wi-Fi", "Restaurant", "Fitness centre", "Indoor pool"],
    imageUrl: hotelImage,
    imageUrls: buildStaticHotelGallery(
      hotelImage,
      "london-marriott-hotel-county-hall",
    ),
    roomSummary: "Guest room and suite options",
    bedSummary: "Bed configuration varies by room",
    description:
      "A five-star County Hall hotel on the South Bank, close to Westminster Bridge, with river-facing rooms, dining and leisure facilities.",
    indicativeNightlyPrice: 520,
    roomOptions: buildPlanningRooms({
      hotelId: "london-marriott-hotel-county-hall",
      roomSummary: "Guest room and suite options",
      bedSummary: "Bed configuration varies by room",
      basePrice: 520,
    }),
    searchTags: ["south bank", "westminster", "river thames"],
    interestTags: ["sightseeing", "dining", "wellness"],
    familySuitable: true,
    businessSuitable: true,
    accessibility: [
      "Accessible routes and room features are available; confirm the selected room directly with the property",
    ],
  },
  {
    ...common,
    id: "shangri-la-the-shard-london",
    slug: "shangri-la-the-shard-london",
    name: "Shangri-La The Shard, London",
    city: "London",
    country: "United Kingdom",
    region: "England",
    aliases: ["london", "lon", "united kingdom", "uk", "england"],
    location: "31 St Thomas Street, London SE1 9QU",
    latitude: 51.50453,
    longitude: -0.08673,
    neighbourhood: "London Bridge",
    classificationStars: 5,
    amenities: ["Wi-Fi", "Restaurant", "Bar", "Indoor pool"],
    imageUrl: londonImage,
    imageUrls: buildStaticHotelGallery(
      londonImage,
      "shangri-la-the-shard-london",
    ),
    roomSummary: "Skyline room and suite options",
    bedSummary: "Bed configuration varies by room",
    description:
      "A five-star hotel occupying upper floors of The Shard at London Bridge, with skyline rooms, restaurants and an indoor infinity pool.",
    indicativeNightlyPrice: 650,
    roomOptions: buildPlanningRooms({
      hotelId: "shangri-la-the-shard-london",
      roomSummary: "Skyline room and suite options",
      bedSummary: "Bed configuration varies by room",
      basePrice: 650,
    }),
    searchTags: ["london bridge", "southwark", "skyline"],
    interestTags: ["sightseeing", "dining", "luxury"],
    familySuitable: true,
    businessSuitable: true,
    accessibility: [
      "Accessible access is available; confirm the selected room and required features directly with the property",
    ],
  },
  {
    ...common,
    id: "hotel-le-six-paris",
    slug: "hotel-le-six-paris",
    name: "Hôtel Le Six",
    city: "Paris",
    country: "France",
    region: "Île-de-France",
    aliases: ["paris", "par", "france", "ile de france", "île-de-france"],
    location: "Rue Stanislas, Paris",
    latitude: 48.843,
    longitude: 2.327,
    neighbourhood: "Montparnasse",
    classificationStars: 4,
    amenities: ["Wi-Fi", "Spa", "Bar", "Breakfast available"],
    imageUrl: parisImage,
    imageUrls: buildStaticHotelGallery(parisImage, "hotel-le-six-paris"),
    roomSummary: "Classic and superior room options",
    bedSummary: "Bed configuration varies by room",
    description:
      "A boutique property in Montparnasse with convenient access to the Left Bank.",
    indicativeNightlyPrice: 260,
    roomOptions: [
      planningRoom({
        hotelId: "hotel-le-six-paris",
        id: "room-only",
        name: "Classic and superior room options — room-only estimate",
        bedConfiguration: "Bed configuration varies by room",
        features: ["Planning room category", "Wi-Fi"],
        mealPlan: "Room only",
        cancellationInfo:
          "Planning estimate only; final terms are not yet confirmed.",
        basePrice: 260,
      }),
      planningRoom({
        hotelId: "hotel-le-six-paris",
        id: "breakfast",
        name: "Classic and superior room options — breakfast estimate",
        bedConfiguration: "Bed configuration varies by room",
        features: ["Breakfast planning allowance", "Wi-Fi"],
        mealPlan: "Breakfast included in planning estimate",
        cancellationInfo:
          "Planning estimate only; final terms are not yet confirmed.",
        basePrice: 260,
        multiplier: 1.12,
      }),
      planningRoom({
        hotelId: "hotel-le-six-paris",
        id: "flexible",
        name: "Classic and superior room options — flexible estimate",
        bedConfiguration: "Bed configuration varies by room",
        features: ["Flexible planning terms", "Wi-Fi"],
        mealPlan: "Room only",
        cancellationInfo:
          "Flexible planning terms; final terms are not yet confirmed.",
        basePrice: 260,
        multiplier: 1.18,
      }),
    ],
    searchTags: ["left bank", "montparnasse", "boutique"],
    interestTags: ["culture", "dining"],
    familySuitable: true,
    businessSuitable: true,
  },
  {
    ...common,
    id: "citizenm-paris-gare-de-lyon",
    slug: "citizenm-paris-gare-de-lyon",
    name: "citizenM Paris Gare de Lyon",
    city: "Paris",
    country: "France",
    region: "Île-de-France",
    aliases: ["paris", "par", "france", "ile de france", "île-de-france"],
    location: "Rue de Lyon, Paris",
    latitude: 48.8457,
    longitude: 2.3726,
    neighbourhood: "Gare de Lyon",
    classificationStars: 4,
    amenities: ["Wi-Fi", "Restaurant", "Bar", "Workspaces"],
    imageUrl: parisImage,
    imageUrls: buildStaticHotelGallery(
      parisImage,
      "citizenm-paris-gare-de-lyon",
    ),
    roomSummary: "Compact modern room options",
    bedSummary: "Large bed configuration",
    description:
      "citizenM Paris Gare de Lyon offers stylish, tech-savvy rooms and a vibrant social atmosphere just steps away from Gare de Lyon. Perfect for travelers who want convenience, comfort and a modern stay in the heart of Paris.",
    indicativeNightlyPrice: 210,
    roomOptions: [
      planningRoom({
        hotelId: "citizenm-paris-gare-de-lyon",
        id: "room-only",
        name: "Compact modern room options — room-only estimate",
        bedConfiguration: "Large bed configuration",
        features: ["Planning room category", "Wi-Fi"],
        mealPlan: "Room only",
        cancellationInfo:
          "Planning estimate only; final terms are not yet confirmed.",
        basePrice: 210,
      }),
      planningRoom({
        hotelId: "citizenm-paris-gare-de-lyon",
        id: "breakfast",
        name: "Compact modern room options — breakfast estimate",
        bedConfiguration: "Large bed configuration",
        features: ["Breakfast planning allowance", "Wi-Fi"],
        mealPlan: "Breakfast included in planning estimate",
        cancellationInfo:
          "Planning estimate only; final terms are not yet confirmed.",
        basePrice: 210,
        multiplier: 1.12,
      }),
      planningRoom({
        hotelId: "citizenm-paris-gare-de-lyon",
        id: "flexible",
        name: "Compact modern room options — flexible estimate",
        bedConfiguration: "Large bed configuration",
        features: ["Flexible planning terms", "Wi-Fi"],
        mealPlan: "Room only",
        cancellationInfo:
          "Flexible planning terms; final terms are not yet confirmed.",
        basePrice: 210,
        multiplier: 1.18,
      }),
    ],
    searchTags: ["gare de lyon", "modern", "transit"],
    interestTags: ["city break", "business"],
    familySuitable: false,
    businessSuitable: true,
  },
  {
    ...common,
    id: "arlo-midtown-new-york",
    slug: "arlo-midtown-new-york",
    name: "Arlo Midtown",
    city: "New York",
    country: "United States",
    region: "New York",
    aliases: ["new york", "nyc", "new york city", "united states", "usa"],
    location: "West 38th Street, New York",
    latitude: 40.7547,
    longitude: -73.9945,
    neighbourhood: "Midtown Manhattan",
    classificationStars: 4,
    amenities: ["Wi-Fi", "Fitness centre", "Restaurant", "Terrace"],
    imageUrl: newYorkImage,
    imageUrls: buildStaticHotelGallery(newYorkImage, "arlo-midtown-new-york"),
    roomSummary: "City room and suite options",
    bedSummary: "Bed configuration varies by room",
    description:
      "A Midtown Manhattan property within reach of Times Square and Hudson Yards.",
    indicativeNightlyPrice: 280,
    roomOptions: [
      planningRoom({
        hotelId: "arlo-midtown-new-york",
        id: "room-only",
        name: "City room and suite options — room-only estimate",
        bedConfiguration: "Bed configuration varies by room",
        features: ["Planning room category", "Wi-Fi"],
        mealPlan: "Room only",
        cancellationInfo:
          "Planning estimate only; final terms are not yet confirmed.",
        basePrice: 280,
      }),
      planningRoom({
        hotelId: "arlo-midtown-new-york",
        id: "breakfast",
        name: "City room and suite options — breakfast estimate",
        bedConfiguration: "Bed configuration varies by room",
        features: ["Breakfast planning allowance", "Wi-Fi"],
        mealPlan: "Breakfast included in planning estimate",
        cancellationInfo:
          "Planning estimate only; final terms are not yet confirmed.",
        basePrice: 280,
        multiplier: 1.12,
      }),
      planningRoom({
        hotelId: "arlo-midtown-new-york",
        id: "flexible",
        name: "City room and suite options — flexible estimate",
        bedConfiguration: "Bed configuration varies by room",
        features: ["Flexible planning terms", "Wi-Fi"],
        mealPlan: "Room only",
        cancellationInfo:
          "Flexible planning terms; final terms are not yet confirmed.",
        basePrice: 280,
        multiplier: 1.18,
      }),
    ],
    searchTags: ["midtown", "manhattan", "times square"],
    interestTags: ["city break", "business"],
    familySuitable: true,
    businessSuitable: true,
  },
  {
    ...common,
    id: "pod-times-square",
    slug: "pod-times-square",
    name: "Pod Times Square",
    city: "New York",
    country: "United States",
    region: "New York",
    aliases: ["new york", "nyc", "new york city", "united states", "usa"],
    location: "West 42nd Street, New York",
    latitude: 40.758,
    longitude: -73.9934,
    neighbourhood: "Hell's Kitchen",
    classificationStars: 3,
    amenities: ["Wi-Fi", "Restaurant", "Bar", "Luggage storage"],
    imageUrl: newYorkImage,
    imageUrls: buildStaticHotelGallery(newYorkImage, "pod-times-square"),
    roomSummary: "Compact room options",
    bedSummary: "Queen or bunk-bed configurations",
    description:
      "A compact city hotel near Times Square and the Theater District.",
    indicativeNightlyPrice: 175,
    roomOptions: [
      planningRoom({
        hotelId: "pod-times-square",
        id: "room-only",
        name: "Compact room options — room-only estimate",
        bedConfiguration: "Queen or bunk-bed configurations",
        features: ["Planning room category", "Wi-Fi"],
        mealPlan: "Room only",
        cancellationInfo:
          "Planning estimate only; final terms are not yet confirmed.",
        basePrice: 175,
      }),
      planningRoom({
        hotelId: "pod-times-square",
        id: "breakfast",
        name: "Compact room options — breakfast estimate",
        bedConfiguration: "Queen or bunk-bed configurations",
        features: ["Breakfast planning allowance", "Wi-Fi"],
        mealPlan: "Breakfast included in planning estimate",
        cancellationInfo:
          "Planning estimate only; final terms are not yet confirmed.",
        basePrice: 175,
        multiplier: 1.12,
      }),
      planningRoom({
        hotelId: "pod-times-square",
        id: "flexible",
        name: "Compact room options — flexible estimate",
        bedConfiguration: "Queen or bunk-bed configurations",
        features: ["Flexible planning terms", "Wi-Fi"],
        mealPlan: "Room only",
        cancellationInfo:
          "Flexible planning terms; final terms are not yet confirmed.",
        basePrice: 175,
        multiplier: 1.18,
      }),
    ],
    searchTags: ["times square", "theater district", "value"],
    interestTags: ["sightseeing", "nightlife"],
    familySuitable: true,
    businessSuitable: false,
  },
  {
    ...common,
    id: "hotel-gracery-shinjuku",
    slug: "hotel-gracery-shinjuku",
    name: "Hotel Gracery Shinjuku",
    city: "Tokyo",
    country: "Japan",
    region: "Kantō",
    aliases: ["tokyo", "tyo", "japan", "shinjuku"],
    location: "Kabukicho, Shinjuku, Tokyo",
    latitude: 35.6952,
    longitude: 139.7029,
    neighbourhood: "Shinjuku",
    classificationStars: 4,
    amenities: ["Wi-Fi", "Restaurant", "Concierge", "Laundry service"],
    imageUrl: hotelImage,
    imageUrls: buildStaticHotelGallery(hotelImage, "hotel-gracery-shinjuku"),
    roomSummary: "Single, double and twin room options",
    bedSummary: "Bed configuration varies by room",
    description:
      "A central Shinjuku hotel with strong rail connections across Tokyo.",
    indicativeNightlyPrice: 165,
    roomOptions: [
      planningRoom({
        hotelId: "hotel-gracery-shinjuku",
        id: "room-only",
        name: "Single, double and twin room options — room-only estimate",
        bedConfiguration: "Bed configuration varies by room",
        features: ["Planning room category", "Wi-Fi"],
        mealPlan: "Room only",
        cancellationInfo:
          "Planning estimate only; final terms are not yet confirmed.",
        basePrice: 165,
      }),
      planningRoom({
        hotelId: "hotel-gracery-shinjuku",
        id: "breakfast",
        name: "Single, double and twin room options — breakfast estimate",
        bedConfiguration: "Bed configuration varies by room",
        features: ["Breakfast planning allowance", "Wi-Fi"],
        mealPlan: "Breakfast included in planning estimate",
        cancellationInfo:
          "Planning estimate only; final terms are not yet confirmed.",
        basePrice: 165,
        multiplier: 1.12,
      }),
      planningRoom({
        hotelId: "hotel-gracery-shinjuku",
        id: "flexible",
        name: "Single, double and twin room options — flexible estimate",
        bedConfiguration: "Bed configuration varies by room",
        features: ["Flexible planning terms", "Wi-Fi"],
        mealPlan: "Room only",
        cancellationInfo:
          "Flexible planning terms; final terms are not yet confirmed.",
        basePrice: 165,
        multiplier: 1.18,
      }),
    ],
    searchTags: ["shinjuku", "central", "transit"],
    interestTags: ["city break", "shopping"],
    familySuitable: true,
    businessSuitable: true,
  },
  {
    ...common,
    id: "shibuya-stream-excel-hotel-tokyu",
    slug: "shibuya-stream-excel-hotel-tokyu",
    name: "Shibuya Stream Hotel",
    city: "Tokyo",
    country: "Japan",
    region: "Kantō",
    aliases: ["tokyo", "tyo", "japan", "shibuya"],
    location: "Shibuya, Tokyo",
    latitude: 35.657,
    longitude: 139.7038,
    neighbourhood: "Shibuya",
    classificationStars: 4,
    amenities: ["Wi-Fi", "Restaurant", "Fitness centre", "Laundry service"],
    imageUrl: hotelImage,
    imageUrls: buildStaticHotelGallery(
      hotelImage,
      "shibuya-stream-excel-hotel-tokyu",
    ),
    roomSummary: "Modern city room options",
    bedSummary: "Bed configuration varies by room",
    description:
      "A contemporary property connected to the Shibuya district and transport network.",
    indicativeNightlyPrice: 240,
    roomOptions: [
      planningRoom({
        hotelId: "shibuya-stream-excel-hotel-tokyu",
        id: "room-only",
        name: "Modern city room options — room-only estimate",
        bedConfiguration: "Bed configuration varies by room",
        features: ["Planning room category", "Wi-Fi"],
        mealPlan: "Room only",
        cancellationInfo:
          "Planning estimate only; final terms are not yet confirmed.",
        basePrice: 240,
      }),
      planningRoom({
        hotelId: "shibuya-stream-excel-hotel-tokyu",
        id: "breakfast",
        name: "Modern city room options — breakfast estimate",
        bedConfiguration: "Bed configuration varies by room",
        features: ["Breakfast planning allowance", "Wi-Fi"],
        mealPlan: "Breakfast included in planning estimate",
        cancellationInfo:
          "Planning estimate only; final terms are not yet confirmed.",
        basePrice: 240,
        multiplier: 1.12,
      }),
      planningRoom({
        hotelId: "shibuya-stream-excel-hotel-tokyu",
        id: "flexible",
        name: "Modern city room options — flexible estimate",
        bedConfiguration: "Bed configuration varies by room",
        features: ["Flexible planning terms", "Wi-Fi"],
        mealPlan: "Room only",
        cancellationInfo:
          "Flexible planning terms; final terms are not yet confirmed.",
        basePrice: 240,
        multiplier: 1.18,
      }),
    ],
    searchTags: ["shibuya", "modern", "transit"],
    interestTags: ["shopping", "dining"],
    familySuitable: true,
    businessSuitable: true,
  },
  ...[
    verifiedCatalogueHotel({
      id: "novotel-paris-les-halles",
      name: "Novotel Paris Les Halles",
      city: "Paris",
      country: "France",
      region: "Île-de-France",
      aliases: ["paris", "par", "france", "ile de france", "île-de-france"],
      location: "8 Place Marguerite de Navarre, 75001 Paris",
      latitude: 48.86053,
      longitude: 2.346531,
      neighbourhood: "Les Halles",
      classificationStars: 4,
      amenities: [
        "Wi-Fi",
        "Fitness centre",
        "Restaurant",
        "Wheelchair accessible",
      ],
      imageUrl: parisImage,
      imageProvenance: "Kurioticket approved Paris destination fallback",
      roomSummary: "Superior, executive and suite options",
      bedSummary: "Bed configuration varies by room",
      description:
        "A family-friendly central Paris hotel beside Les Halles and Châtelet transport links.",
      indicativeNightlyPrice: 310,
      lastReviewed: "2026-08-25",
      searchTags: ["central", "les halles", "transit"],
      interestTags: ["culture", "sightseeing"],
      familySuitable: true,
      businessSuitable: true,
      accessibility: [
        "Wheelchair-accessible facilities and rooms are available; confirm the selected room directly with the property",
      ],
    }),
    verifiedCatalogueHotel({
      id: "pullman-paris-tour-eiffel",
      name: "Pullman Paris Tour Eiffel",
      city: "Paris",
      country: "France",
      region: "Île-de-France",
      aliases: ["paris", "par", "france", "ile de france", "île-de-france"],
      location:
        "18 Avenue de Suffren, entrance at 22 Rue Jean Rey, 75015 Paris",
      latitude: 48.855976,
      longitude: 2.293221,
      neighbourhood: "Grenelle",
      classificationStars: 4,
      amenities: [
        "Wi-Fi",
        "Fitness centre",
        "Restaurant",
        "Wheelchair accessible",
      ],
      imageUrl: parisImage,
      imageProvenance: "Kurioticket approved Paris destination fallback",
      roomSummary: "Classic, superior and suite options",
      bedSummary: "Bed configuration varies by room",
      description:
        "A four-star Left Bank hotel near the Eiffel Tower with rooms and suites for leisure and business stays.",
      indicativeNightlyPrice: 390,
      lastReviewed: "2026-08-25",
      searchTags: ["eiffel tower", "left bank", "business"],
      interestTags: ["sightseeing", "dining"],
      familySuitable: true,
      businessSuitable: true,
      accessibility: [
        "Wheelchair-accessible facilities are listed; confirm the selected room directly with the property",
      ],
    }),
    verifiedCatalogueHotel({
      id: "novotel-paris-centre-tour-eiffel",
      name: "Novotel Paris Centre Tour Eiffel",
      city: "Paris",
      country: "France",
      region: "Île-de-France",
      aliases: ["paris", "par", "france", "ile de france", "île-de-france"],
      location: "61 Quai de Grenelle, 75015 Paris",
      latitude: 48.849778,
      longitude: 2.282836,
      neighbourhood: "Grenelle",
      classificationStars: 4,
      amenities: ["Wi-Fi", "Restaurant", "Fitness centre", "Indoor pool"],
      imageUrl: parisImage,
      imageProvenance: "Kurioticket approved Paris destination fallback",
      roomSummary: "Classic, executive and family room options",
      bedSummary: "Bed configuration varies by room",
      description:
        "A family-oriented four-star hotel on the Seine in Paris's 15th arrondissement.",
      indicativeNightlyPrice: 260,
      lastReviewed: "2026-08-25",
      searchTags: ["eiffel tower", "seine", "family"],
      interestTags: ["sightseeing", "family"],
      familySuitable: true,
      businessSuitable: true,
      accessibility: [
        "Accessibility features should be confirmed for the selected room directly with the property",
      ],
    }),
    verifiedCatalogueHotel({
      id: "pullman-paris-montparnasse",
      name: "Pullman Paris Montparnasse",
      city: "Paris",
      country: "France",
      region: "Île-de-France",
      aliases: ["paris", "par", "france", "ile de france", "île-de-france"],
      location: "19 Rue du Commandant René Mouchotte, 75014 Paris",
      latitude: 48.8383719,
      longitude: 2.3209274,
      neighbourhood: "Montparnasse",
      classificationStars: 4,
      amenities: ["Wi-Fi", "Restaurant", "Bar", "Fitness centre"],
      imageUrl: parisImage,
      imageProvenance: "Kurioticket approved Paris destination fallback",
      roomSummary: "Classic, deluxe and family room options",
      bedSummary: "Bed configuration varies by room",
      description:
        "A large contemporary hotel close to Gare Montparnasse with dining, rooftop and meeting facilities.",
      indicativeNightlyPrice: 285,
      lastReviewed: "2026-08-25",
      searchTags: ["montparnasse", "transit", "business"],
      interestTags: ["dining", "city break"],
      familySuitable: true,
      businessSuitable: true,
      accessibility: [
        "Accessibility features should be confirmed for the selected room directly with the property",
      ],
    }),
    verifiedCatalogueHotel({
      id: "hotel-fabric-paris",
      name: "Hôtel Fabric",
      city: "Paris",
      country: "France",
      region: "Île-de-France",
      aliases: ["paris", "par", "france", "ile de france", "île-de-france"],
      location: "31 Rue de la Folie-Méricourt, 75011 Paris",
      latitude: 48.863063,
      longitude: 2.3728001,
      neighbourhood: "Oberkampf",
      classificationStars: 4,
      amenities: ["Wi-Fi", "Fitness centre", "Hammam", "Breakfast available"],
      imageUrl: parisImage,
      imageProvenance: "Kurioticket approved Paris destination fallback",
      roomSummary: "Club, superior and family room options",
      bedSummary: "Bed configuration varies by room",
      description:
        "A boutique four-star hotel in a converted textile workshop between République and Bastille.",
      indicativeNightlyPrice: 245,
      lastReviewed: "2026-08-25",
      searchTags: ["oberkampf", "boutique", "bastille"],
      interestTags: ["design", "dining"],
      familySuitable: true,
      businessSuitable: true,
      accessibility: [
        "Accessibility features should be confirmed for the selected room directly with the property",
      ],
    }),
    verifiedCatalogueHotel({
      id: "le-bristol-paris",
      name: "Le Bristol Paris",
      city: "Paris",
      country: "France",
      region: "Île-de-France",
      aliases: ["paris", "par", "france", "ile de france", "île-de-france"],
      location: "112 Rue du Faubourg Saint-Honoré, 75008 Paris",
      latitude: 48.8718267,
      longitude: 2.3150084,
      neighbourhood: "Faubourg Saint-Honoré",
      classificationStars: 5,
      amenities: ["Wi-Fi", "Concierge", "Spa", "Indoor pool"],
      imageUrl: parisImage,
      imageProvenance: "Kurioticket approved Paris destination fallback",
      roomSummary: "Guest room and suite options",
      bedSummary: "Bed configuration varies by room",
      description:
        "An established Paris palace hotel on Rue du Faubourg Saint-Honoré with dining and wellness facilities.",
      indicativeNightlyPrice: 1250,
      lastReviewed: "2026-08-25",
      searchTags: ["faubourg saint honore", "luxury", "spa"],
      interestTags: ["luxury", "dining", "wellness"],
      familySuitable: true,
      businessSuitable: true,
      accessibility: [
        "Accessibility requirements should be confirmed for the selected room directly with the property",
      ],
    }),
    verifiedCatalogueHotel({
      id: "new-york-marriott-marquis",
      name: "New York Marriott Marquis",
      city: "New York",
      country: "United States",
      region: "New York",
      aliases: ["new york", "nyc", "new york city", "united states", "usa"],
      location: "1535 Broadway, New York, NY 10036",
      latitude: 40.7585971,
      longitude: -73.9861935,
      neighbourhood: "Times Square",
      classificationStars: 4,
      amenities: ["Wi-Fi", "Fitness centre", "Restaurant", "Business centre"],
      imageUrl: newYorkImage,
      imageProvenance: "Kurioticket approved New York destination fallback",
      roomSummary: "Guest room, family connector and suite options",
      bedSummary: "Bed configuration varies by room",
      description:
        "A large Times Square hotel with restaurants, fitness facilities and extensive meeting space.",
      indicativeNightlyPrice: 390,
      lastReviewed: "2026-08-25",
      searchTags: ["times square", "theater district", "business"],
      interestTags: ["theatre", "sightseeing"],
      familySuitable: true,
      businessSuitable: true,
      accessibility: [
        "Accessible routes and room features are available; confirm the selected room directly with the property",
      ],
    }),
    verifiedCatalogueHotel({
      id: "the-plaza-new-york",
      name: "The Plaza, A Fairmont Hotel",
      city: "New York",
      country: "United States",
      region: "New York",
      aliases: ["new york", "nyc", "new york city", "united states", "usa"],
      location: "768 Fifth Avenue, New York, NY 10019",
      latitude: 40.764268,
      longitude: -73.974155,
      neighbourhood: "Midtown East",
      classificationStars: 5,
      amenities: ["Wi-Fi", "Fitness centre", "Spa", "Concierge"],
      imageUrl: newYorkImage,
      imageProvenance: "Kurioticket approved New York destination fallback",
      roomSummary: "Guest room and suite options",
      bedSummary: "Bed configuration varies by room",
      description:
        "A historic five-star hotel at Fifth Avenue and Central Park South with dining and wellness services.",
      indicativeNightlyPrice: 950,
      lastReviewed: "2026-08-25",
      searchTags: ["central park", "fifth avenue", "luxury"],
      interestTags: ["luxury", "shopping", "culture"],
      familySuitable: true,
      businessSuitable: true,
      accessibility: [
        "Accessible rooms and amenities are available on request; confirm the selected room directly with the property",
      ],
    }),
    verifiedCatalogueHotel({
      id: "the-standard-high-line-new-york",
      name: "The Standard, High Line",
      city: "New York",
      country: "United States",
      region: "New York",
      aliases: ["new york", "nyc", "new york city", "united states", "usa"],
      location: "848 Washington Street, New York, NY 10014",
      latitude: 40.7408822,
      longitude: -74.0079129,
      neighbourhood: "Meatpacking District",
      classificationStars: 4,
      amenities: ["Wi-Fi", "Fitness centre", "Restaurant", "Rooftop bar"],
      imageUrl: newYorkImage,
      imageProvenance: "Kurioticket approved New York destination fallback",
      roomSummary: "City-view room and suite options",
      bedSummary: "Bed configuration varies by room",
      description:
        "A design-focused Meatpacking District hotel above the High Line with dining and rooftop venues.",
      indicativeNightlyPrice: 425,
      lastReviewed: "2026-08-25",
      searchTags: ["high line", "meatpacking", "design"],
      interestTags: ["nightlife", "design", "dining"],
      familySuitable: false,
      businessSuitable: true,
      accessibility: [
        "Accessibility features should be confirmed for the selected room directly with the property",
      ],
    }),
    verifiedCatalogueHotel({
      id: "citizenm-new-york-times-square",
      name: "citizenM New York Times Square",
      city: "New York",
      country: "United States",
      region: "New York",
      aliases: ["new york", "nyc", "new york city", "united states", "usa"],
      location: "218 West 50th Street, New York, NY 10019",
      latitude: 40.7615659,
      longitude: -73.9849656,
      neighbourhood: "Theater District",
      classificationStars: 4,
      amenities: ["Wi-Fi", "Fitness centre", "Bar", "Workspaces"],
      imageUrl: newYorkImage,
      imageProvenance: "Kurioticket approved New York destination fallback",
      roomSummary: "Compact smart room options",
      bedSummary: "Bed configuration varies by room",
      description:
        "A technology-led hotel near Times Square and Broadway with shared living and work spaces.",
      indicativeNightlyPrice: 295,
      lastReviewed: "2026-08-25",
      searchTags: ["times square", "theater district", "smart hotel"],
      interestTags: ["theatre", "business"],
      familySuitable: false,
      businessSuitable: true,
      accessibility: [
        "Accessibility features should be confirmed for the selected room directly with the property",
      ],
    }),
    verifiedCatalogueHotel({
      id: "hilton-new-york-times-square",
      name: "Hilton New York Times Square",
      city: "New York",
      country: "United States",
      region: "New York",
      aliases: ["new york", "nyc", "new york city", "united states", "usa"],
      location: "234 West 42nd Street, New York, NY 10036",
      latitude: 40.7562126,
      longitude: -73.988438,
      neighbourhood: "Times Square",
      classificationStars: 4,
      amenities: ["Wi-Fi", "Fitness centre", "Restaurant", "Concierge"],
      imageUrl: newYorkImage,
      imageProvenance: "Kurioticket approved New York destination fallback",
      roomSummary: "High-floor guest room and suite options",
      bedSummary: "Bed configuration varies by room",
      description:
        "A high-rise Times Square hotel with skyline views, dining and fitness facilities.",
      indicativeNightlyPrice: 330,
      lastReviewed: "2026-08-25",
      searchTags: ["times square", "midtown", "skyline"],
      interestTags: ["sightseeing", "theatre"],
      familySuitable: true,
      businessSuitable: true,
      accessibility: [
        "Accessibility features should be confirmed for the selected room directly with the property",
      ],
    }),
    verifiedCatalogueHotel({
      id: "st-regis-new-york",
      name: "The St. Regis New York",
      city: "New York",
      country: "United States",
      region: "New York",
      aliases: ["new york", "nyc", "new york city", "united states", "usa"],
      location: "2 East 55th Street at Fifth Avenue, New York, NY 10022",
      latitude: 40.7612458,
      longitude: -73.9743323,
      neighbourhood: "Midtown East",
      classificationStars: 5,
      amenities: ["Wi-Fi", "Fitness centre", "Restaurant", "Concierge"],
      imageUrl: newYorkImage,
      imageProvenance: "Kurioticket approved New York destination fallback",
      roomSummary: "Guest room and suite options",
      bedSummary: "Bed configuration varies by room",
      description:
        "A five-star Midtown hotel at Fifth Avenue with restaurants, fitness facilities and concierge service.",
      indicativeNightlyPrice: 1100,
      lastReviewed: "2026-08-25",
      searchTags: ["fifth avenue", "midtown", "luxury"],
      interestTags: ["luxury", "shopping", "dining"],
      familySuitable: true,
      businessSuitable: true,
      accessibility: [
        "Accessible room and public-area features are available; confirm the selected room directly with the property",
      ],
    }),
    verifiedCatalogueHotel({
      id: "imperial-hotel-tokyo",
      name: "Imperial Hotel, Tokyo",
      city: "Tokyo",
      country: "Japan",
      region: "Tokyo",
      aliases: ["tokyo", "tyo", "japan"],
      location: "1-1-1 Uchisaiwai-cho, Chiyoda-ku, Tokyo 100-8558",
      latitude: 35.6718986,
      longitude: 139.7589849,
      neighbourhood: "Hibiya",
      classificationStars: 5,
      amenities: ["Wi-Fi", "Fitness centre", "Restaurants", "Indoor pool"],
      imageUrl: hotelImage,
      imageProvenance: "Kurioticket approved neutral hotel fallback",
      roomSummary: "Guest room and suite options",
      bedSummary: "Bed configuration varies by room",
      description:
        "A long-established five-star Hibiya hotel near Ginza and the Imperial Palace with extensive dining and leisure facilities.",
      indicativeNightlyPrice: 520,
      lastReviewed: "2026-08-25",
      searchTags: ["hibiya", "ginza", "luxury"],
      interestTags: ["culture", "dining", "luxury"],
      familySuitable: true,
      businessSuitable: true,
      accessibility: [
        "Barrier-free access information is published; confirm the selected room directly with the property",
      ],
    }),
    verifiedCatalogueHotel({
      id: "park-hotel-tokyo",
      name: "Park Hotel Tokyo",
      city: "Tokyo",
      country: "Japan",
      region: "Tokyo",
      aliases: ["tokyo", "tyo", "japan"],
      location:
        "Shiodome Media Tower, 1-7-1 Higashi-Shimbashi, Minato-ku, Tokyo 105-7227",
      latitude: 35.6633462,
      longitude: 139.759628,
      neighbourhood: "Shiodome",
      classificationStars: 4,
      amenities: ["Wi-Fi", "Restaurant", "Bar", "Spa"],
      imageUrl: hotelImage,
      imageProvenance: "Kurioticket approved neutral hotel fallback",
      roomSummary: "Art-inspired guest room and suite options",
      bedSummary: "Bed configuration varies by room",
      description:
        "An art-focused high-rise hotel in Shiodome with restaurants, a bar and spa services.",
      indicativeNightlyPrice: 250,
      lastReviewed: "2026-08-25",
      searchTags: ["shiodome", "art hotel", "business"],
      interestTags: ["art", "dining"],
      familySuitable: true,
      businessSuitable: true,
      accessibility: [
        "A barrier-free room is available; confirm the selected room directly with the property",
      ],
    }),
    verifiedCatalogueHotel({
      id: "tokyo-station-hotel",
      name: "The Tokyo Station Hotel",
      city: "Tokyo",
      country: "Japan",
      region: "Tokyo",
      aliases: ["tokyo", "tyo", "japan"],
      location: "1-9-1 Marunouchi, Chiyoda-ku, Tokyo 100-0005",
      latitude: 35.6790703,
      longitude: 139.7652988,
      neighbourhood: "Marunouchi",
      classificationStars: 5,
      amenities: ["Wi-Fi", "Fitness centre", "Restaurants", "Spa"],
      imageUrl: hotelImage,
      imageProvenance: "Kurioticket approved neutral hotel fallback",
      roomSummary: "Palace-side, dome-side and suite options",
      bedSummary: "Bed configuration varies by room",
      description:
        "A historic hotel within Tokyo Station's Marunouchi building with dining, fitness and spa facilities.",
      indicativeNightlyPrice: 480,
      lastReviewed: "2026-08-25",
      searchTags: ["tokyo station", "marunouchi", "transit"],
      interestTags: ["history", "dining", "business"],
      familySuitable: true,
      businessSuitable: true,
      accessibility: [
        "Accessibility requirements should be confirmed for the selected room directly with the property",
      ],
    }),
    verifiedCatalogueHotel({
      id: "shibuya-excel-hotel-tokyu",
      name: "Shibuya Excel Hotel Tokyu",
      city: "Tokyo",
      country: "Japan",
      region: "Tokyo",
      aliases: ["tokyo", "tyo", "japan", "shibuya"],
      location: "1-12-2 Dogenzaka, Shibuya-ku, Tokyo 150-0043",
      latitude: 35.6586784,
      longitude: 139.6997166,
      neighbourhood: "Shibuya",
      classificationStars: 4,
      amenities: ["Wi-Fi", "Restaurants", "Bar", "Meeting rooms"],
      imageUrl: hotelImage,
      imageProvenance: "Kurioticket approved neutral hotel fallback",
      roomSummary: "Standard, superior and accessible room options",
      bedSummary: "Bed configuration varies by room",
      description:
        "A Shibuya Mark City hotel directly connected to Shibuya Station with varied room categories and dining.",
      indicativeNightlyPrice: 265,
      lastReviewed: "2026-08-25",
      searchTags: ["shibuya", "transit", "business"],
      interestTags: ["shopping", "dining"],
      familySuitable: true,
      businessSuitable: true,
      accessibility: [
        "An accessible room and barrier-free route are published; confirm the selected room directly with the property",
      ],
    }),
    verifiedCatalogueHotel({
      id: "mitsui-garden-hotel-ginza-premier",
      name: "Mitsui Garden Hotel Ginza Premier",
      city: "Tokyo",
      country: "Japan",
      region: "Tokyo",
      aliases: ["tokyo", "tyo", "japan", "ginza"],
      location: "8-13-1 Ginza, Chuo-ku, Tokyo 104-0061",
      latitude: 35.6740081,
      longitude: 139.7721408,
      neighbourhood: "Ginza",
      classificationStars: 5,
      amenities: ["Wi-Fi", "Restaurant", "Bar", "Laundry service"],
      imageUrl: hotelImage,
      imageProvenance: "Kurioticket approved neutral hotel fallback",
      roomSummary: "Moderate, superior and premier room options",
      bedSummary: "Bed configuration varies by room",
      description:
        "A high-rise Ginza hotel with city views, restaurant and lounge facilities near Shimbashi.",
      indicativeNightlyPrice: 285,
      lastReviewed: "2026-08-25",
      searchTags: ["ginza", "shimbashi", "city views"],
      interestTags: ["shopping", "dining"],
      familySuitable: true,
      businessSuitable: true,
      accessibility: [
        "Accessibility requirements should be confirmed for the selected room directly with the property",
      ],
    }),
    verifiedCatalogueHotel({
      id: "hotel-metropolitan-tokyo-marunouchi",
      name: "Hotel Metropolitan Tokyo Marunouchi",
      city: "Tokyo",
      country: "Japan",
      region: "Tokyo",
      aliases: ["tokyo", "tyo", "japan", "marunouchi"],
      location: "Sapia Tower, 1-7-12 Marunouchi, Chiyoda-ku, Tokyo 100-0005",
      latitude: 35.6837194,
      longitude: 139.768587,
      neighbourhood: "Marunouchi",
      classificationStars: 4,
      amenities: ["Wi-Fi", "Restaurant", "Fitness room", "Laundry service"],
      imageUrl: hotelImage,
      imageProvenance: "Kurioticket approved neutral hotel fallback",
      roomSummary: "City-view guest room and suite options",
      bedSummary: "Bed configuration varies by room",
      description:
        "A high-rise hotel connected to Tokyo Station's Nihonbashi side with city-view rooms and dining.",
      indicativeNightlyPrice: 235,
      lastReviewed: "2026-08-25",
      searchTags: ["tokyo station", "marunouchi", "transit"],
      interestTags: ["business", "sightseeing"],
      familySuitable: true,
      businessSuitable: true,
      accessibility: [
        "Accessibility requirements should be confirmed for the selected room directly with the property",
      ],
    }),
  ],
];

// Each property owns its planning room facts; the helper above only standardizes pricing metadata.
export const staticHotelCatalogue: readonly StaticHotelRecord[] =
  staticHotelProperties;

export const supportedStaticHotelDestinations = [
  "London",
  "Paris",
  "New York",
  "Tokyo",
] as const;
