import type { NormalizedCarResult } from "@/lib/cars/types";

type StaticOfferFixture = Omit<
  NormalizedCarResult["offers"][number],
  "id" | "totalPrice" | "currency" | "bookingProviderName" | "rentalCompanyName"
>;
export type StaticCarTemplate = Omit<
  NormalizedCarResult,
  "id" | "pickupLocation" | "returnLocation" | "offers"
> & { id: string; offerFixtures: readonly StaticOfferFixture[] };
const base = {
  orSimilar: true,
  airConditioning: true,
  shuttleRequired: false,
  requiredDocuments: [
    "Valid driving licence",
    "Passport or government-issued ID",
    "Payment card in the main driver's name",
  ],
  includedItems: [
    "Local taxes shown in the offer",
    "Standard roadside assistance",
  ],
  importantInformation: [
    "Vehicle model is representative; the category and core specifications apply.",
    "Kurioticket generates this deterministic comparison fixture; it is not real-time supplier availability.",
  ],
  inventorySource: "kurioticket-static-cars" as const,
};
const offer = (
  pricePerDay: number,
  freeCancellation: boolean,
  payAtPickup: boolean,
): StaticOfferFixture => ({
  pricePerDay,
  freeCancellation,
  payAtPickup,
  taxesAndFeesIncluded: true,
});
export const staticCarCatalogue: readonly StaticCarTemplate[] = [
  {
    ...base,
    id: "city-mini",
    category: "mini",
    categoryLabel: "Mini",
    modelName: "Fiat 500",
    imageUrl: "/images/cars/results/fiat-500.webp",
    imageAlt: "Fiat 500 representative rental vehicle",
    passengers: 4,
    bags: 1,
    doors: 3,
    transmission: "manual",
    fuelPolicy: "full-to-full",
    mileagePolicy: "limited",
    limitedMileageKm: 600,
    pickupType: "city-location",
    shuttleRequired: false,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 7.5,
    supplierReviewCount: 120,
    recommendationScore: 77,
    depositAmount: 300,
    excessAmount: 700,
    minimumDriverAge: 21,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(31, true, false)],
  },
  {
    ...base,
    id: "economy-yaris",
    category: "economy",
    categoryLabel: "Economy",
    modelName: "Toyota Yaris",
    imageUrl: "/images/cars/results/toyota-yaris.webp",
    imageAlt: "Toyota Yaris representative rental vehicle",
    passengers: 5,
    bags: 2,
    doors: 5,
    transmission: "automatic",
    fuelPolicy: "same-to-same",
    mileagePolicy: "unlimited",
    pickupType: "airport-counter",
    shuttleRequired: false,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 7.7,
    supplierReviewCount: 137,
    recommendationScore: 89,
    depositAmount: 330,
    excessAmount: 735,
    minimumDriverAge: 21,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(38, false, true)],
  },
  {
    ...base,
    id: "compact-golf",
    category: "compact",
    categoryLabel: "Compact",
    modelName: "Volkswagen Golf",
    imageUrl: "/images/cars/results/volkswagen-golf.webp",
    imageAlt: "Volkswagen Golf representative rental vehicle",
    passengers: 5,
    bags: 3,
    doors: 5,
    transmission: "manual",
    fuelPolicy: "full-to-full",
    mileagePolicy: "unlimited",
    pickupType: "shuttle",
    shuttleRequired: true,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 7.9,
    supplierReviewCount: 154,
    recommendationScore: 84,
    depositAmount: 360,
    excessAmount: 770,
    minimumDriverAge: 21,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(43, true, false)],
  },
  {
    ...base,
    id: "compact-corolla",
    category: "compact",
    categoryLabel: "Compact",
    modelName: "Toyota Corolla",
    imageUrl: "/images/cars/results/toyota-corolla.webp",
    imageAlt: "Toyota Corolla representative rental vehicle",
    passengers: 5,
    bags: 3,
    doors: 4,
    transmission: "automatic",
    fuelPolicy: "full-to-full",
    mileagePolicy: "unlimited",
    pickupType: "airport-counter",
    shuttleRequired: false,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 8.1,
    supplierReviewCount: 171,
    recommendationScore: 93,
    depositAmount: 390,
    excessAmount: 805,
    minimumDriverAge: 21,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(49, true, false)],
  },
  {
    ...base,
    id: "intermediate-octavia",
    category: "intermediate",
    categoryLabel: "Intermediate",
    modelName: "Skoda Octavia",
    imageUrl: "/images/cars/results/skoda-octavia.webp",
    imageAlt: "Skoda Octavia representative rental vehicle",
    passengers: 5,
    bags: 4,
    doors: 5,
    transmission: "automatic",
    fuelPolicy: "same-to-same",
    mileagePolicy: "limited",
    limitedMileageKm: 900,
    pickupType: "city-location",
    shuttleRequired: false,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 8.3,
    supplierReviewCount: 188,
    recommendationScore: 73,
    depositAmount: 420,
    excessAmount: 840,
    minimumDriverAge: 25,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(55, false, true)],
  },
  {
    ...base,
    id: "fullsize-camry",
    category: "full-size",
    categoryLabel: "Full-size",
    modelName: "Toyota Camry",
    imageUrl: "/images/cars/results/toyota-camry.webp",
    imageAlt: "Toyota Camry representative rental vehicle",
    passengers: 5,
    bags: 4,
    doors: 4,
    transmission: "automatic",
    fuelPolicy: "full-to-full",
    mileagePolicy: "unlimited",
    pickupType: "airport-counter",
    shuttleRequired: false,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 8.5,
    supplierReviewCount: 205,
    recommendationScore: 86,
    depositAmount: 450,
    excessAmount: 875,
    minimumDriverAge: 25,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(64, true, false)],
  },
  {
    ...base,
    id: "suv-qashqai",
    category: "suv",
    categoryLabel: "SUV",
    modelName: "Nissan Qashqai",
    imageUrl: "/images/cars/results/nissan-qashqai.webp",
    imageAlt: "Nissan Qashqai representative rental vehicle",
    passengers: 5,
    bags: 4,
    doors: 5,
    transmission: "automatic",
    fuelPolicy: "full-to-full",
    mileagePolicy: "unlimited",
    pickupType: "shuttle",
    shuttleRequired: true,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 8.7,
    supplierReviewCount: 222,
    recommendationScore: 91,
    depositAmount: 480,
    excessAmount: 910,
    minimumDriverAge: 25,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(72, true, true)],
  },
  {
    ...base,
    id: "suv-duster",
    category: "suv",
    categoryLabel: "SUV",
    modelName: "Dacia Duster",
    imageUrl: "/images/cars/results/dacia-duster.webp",
    imageAlt: "Dacia Duster representative rental vehicle",
    passengers: 5,
    bags: 3,
    doors: 5,
    transmission: "manual",
    fuelPolicy: "same-to-same",
    mileagePolicy: "limited",
    limitedMileageKm: 700,
    pickupType: "city-location",
    shuttleRequired: false,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 8.9,
    supplierReviewCount: 239,
    recommendationScore: 69,
    depositAmount: 510,
    excessAmount: 945,
    minimumDriverAge: 25,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(58, false, true)],
  },
  {
    ...base,
    id: "luxury-c-class",
    category: "luxury",
    categoryLabel: "Luxury",
    modelName: "Mercedes-Benz C-Class",
    imageUrl: "/images/cars/results/mercedes-benz-c-class.webp",
    imageAlt: "Mercedes-Benz C-Class representative rental vehicle",
    passengers: 5,
    bags: 3,
    doors: 4,
    transmission: "automatic",
    fuelPolicy: "full-to-full",
    mileagePolicy: "limited",
    limitedMileageKm: 500,
    pickupType: "meet-and-greet",
    shuttleRequired: false,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 9.1,
    supplierReviewCount: 256,
    recommendationScore: 88,
    depositAmount: 540,
    excessAmount: 980,
    minimumDriverAge: 25,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(118, true, false)],
  },
  {
    ...base,
    id: "van-touran",
    category: "van",
    categoryLabel: "People carrier",
    modelName: "Volkswagen Touran",
    imageUrl: "/images/cars/results/volkswagen-touran.webp",
    imageAlt: "Volkswagen Touran representative rental vehicle",
    passengers: 7,
    bags: 4,
    doors: 5,
    transmission: "automatic",
    fuelPolicy: "full-to-full",
    mileagePolicy: "unlimited",
    pickupType: "airport-counter",
    shuttleRequired: false,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 9.3,
    supplierReviewCount: 273,
    recommendationScore: 87,
    depositAmount: 570,
    excessAmount: 1015,
    minimumDriverAge: 25,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(83, true, true)],
  },
  {
    ...base,
    id: "van-tourneo",
    category: "van",
    categoryLabel: "Van",
    modelName: "Ford Tourneo",
    imageUrl: "/images/cars/results/ford-tourneo.webp",
    imageAlt: "Ford Tourneo representative rental vehicle",
    passengers: 8,
    bags: 5,
    doors: 5,
    transmission: "manual",
    fuelPolicy: "same-to-same",
    mileagePolicy: "limited",
    limitedMileageKm: 1000,
    pickupType: "shuttle",
    shuttleRequired: true,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 7.5,
    supplierReviewCount: 290,
    recommendationScore: 75,
    depositAmount: 600,
    excessAmount: 1050,
    minimumDriverAge: 25,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(78, false, true)],
  },
  {
    ...base,
    id: "economy-clio",
    category: "economy",
    categoryLabel: "Economy",
    modelName: "Renault Clio",
    imageUrl: undefined,
    imageAlt: "Renault Clio representative rental vehicle",
    passengers: 5,
    bags: 2,
    doors: 5,
    transmission: "manual",
    fuelPolicy: "full-to-full",
    mileagePolicy: "limited",
    limitedMileageKm: 750,
    pickupType: "city-location",
    shuttleRequired: false,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 7.7,
    supplierReviewCount: 307,
    recommendationScore: 82,
    depositAmount: 630,
    excessAmount: 1085,
    minimumDriverAge: 21,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(35, true, false)],
  },
  {
    ...base,
    id: "economy-208",
    category: "economy",
    categoryLabel: "Economy",
    modelName: "Peugeot 208",
    imageUrl: undefined,
    imageAlt: "Peugeot 208 representative rental vehicle",
    passengers: 5,
    bags: 2,
    doors: 5,
    transmission: "automatic",
    fuelPolicy: "full-to-full",
    mileagePolicy: "unlimited",
    pickupType: "airport-counter",
    shuttleRequired: false,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 7.9,
    supplierReviewCount: 324,
    recommendationScore: 80,
    depositAmount: 660,
    excessAmount: 1120,
    minimumDriverAge: 21,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(40, false, true)],
  },
  {
    ...base,
    id: "economy-corsa",
    category: "economy",
    categoryLabel: "Economy",
    modelName: "Opel Corsa",
    imageUrl: undefined,
    imageAlt: "Opel Corsa representative rental vehicle",
    passengers: 5,
    bags: 2,
    doors: 5,
    transmission: "manual",
    fuelPolicy: "same-to-same",
    mileagePolicy: "unlimited",
    pickupType: "shuttle",
    shuttleRequired: true,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 8.1,
    supplierReviewCount: 341,
    recommendationScore: 78,
    depositAmount: 690,
    excessAmount: 1155,
    minimumDriverAge: 21,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(37, true, true)],
  },
  {
    ...base,
    id: "economy-i20",
    category: "economy",
    categoryLabel: "Economy",
    modelName: "Hyundai i20",
    imageUrl: undefined,
    imageAlt: "Hyundai i20 representative rental vehicle",
    passengers: 5,
    bags: 2,
    doors: 5,
    transmission: "automatic",
    fuelPolicy: "full-to-full",
    mileagePolicy: "limited",
    limitedMileageKm: 800,
    pickupType: "city-location",
    shuttleRequired: false,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 8.3,
    supplierReviewCount: 358,
    recommendationScore: 81,
    depositAmount: 720,
    excessAmount: 1190,
    minimumDriverAge: 21,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(39, false, false)],
  },
  {
    ...base,
    id: "compact-civic",
    category: "compact",
    categoryLabel: "Compact",
    modelName: "Honda Civic",
    imageUrl: undefined,
    imageAlt: "Honda Civic representative rental vehicle",
    passengers: 5,
    bags: 3,
    doors: 5,
    transmission: "automatic",
    fuelPolicy: "full-to-full",
    mileagePolicy: "unlimited",
    pickupType: "airport-counter",
    shuttleRequired: false,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 8.5,
    supplierReviewCount: 375,
    recommendationScore: 90,
    depositAmount: 750,
    excessAmount: 1225,
    minimumDriverAge: 21,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(53, true, false)],
  },
  {
    ...base,
    id: "compact-focus",
    category: "compact",
    categoryLabel: "Compact",
    modelName: "Ford Focus",
    imageUrl: undefined,
    imageAlt: "Ford Focus representative rental vehicle",
    passengers: 5,
    bags: 3,
    doors: 5,
    transmission: "manual",
    fuelPolicy: "same-to-same",
    mileagePolicy: "limited",
    limitedMileageKm: 850,
    pickupType: "shuttle",
    shuttleRequired: true,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 8.7,
    supplierReviewCount: 392,
    recommendationScore: 76,
    depositAmount: 780,
    excessAmount: 1260,
    minimumDriverAge: 21,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(46, false, true)],
  },
  {
    ...base,
    id: "compact-mazda3",
    category: "compact",
    categoryLabel: "Compact",
    modelName: "Mazda 3",
    imageUrl: undefined,
    imageAlt: "Mazda 3 representative rental vehicle",
    passengers: 5,
    bags: 3,
    doors: 5,
    transmission: "automatic",
    fuelPolicy: "full-to-full",
    mileagePolicy: "unlimited",
    pickupType: "city-location",
    shuttleRequired: false,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 8.9,
    supplierReviewCount: 409,
    recommendationScore: 85,
    depositAmount: 810,
    excessAmount: 1295,
    minimumDriverAge: 21,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(51, true, false)],
  },
  {
    ...base,
    id: "intermediate-passat",
    category: "intermediate",
    categoryLabel: "Intermediate",
    modelName: "Volkswagen Passat",
    imageUrl: undefined,
    imageAlt: "Volkswagen Passat representative rental vehicle",
    passengers: 5,
    bags: 4,
    doors: 4,
    transmission: "automatic",
    fuelPolicy: "full-to-full",
    mileagePolicy: "limited",
    limitedMileageKm: 950,
    pickupType: "airport-counter",
    shuttleRequired: false,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 9.1,
    supplierReviewCount: 426,
    recommendationScore: 83,
    depositAmount: 840,
    excessAmount: 1330,
    minimumDriverAge: 25,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(61, false, true)],
  },
  {
    ...base,
    id: "suv-tucson",
    category: "suv",
    categoryLabel: "SUV",
    modelName: "Hyundai Tucson",
    imageUrl: undefined,
    imageAlt: "Hyundai Tucson representative rental vehicle",
    passengers: 5,
    bags: 4,
    doors: 5,
    transmission: "automatic",
    fuelPolicy: "full-to-full",
    mileagePolicy: "unlimited",
    pickupType: "shuttle",
    shuttleRequired: true,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 9.3,
    supplierReviewCount: 443,
    recommendationScore: 88,
    depositAmount: 870,
    excessAmount: 1365,
    minimumDriverAge: 25,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(69, true, false)],
  },
  {
    ...base,
    id: "suv-sportage",
    category: "suv",
    categoryLabel: "SUV",
    modelName: "Kia Sportage",
    imageUrl: undefined,
    imageAlt: "Kia Sportage representative rental vehicle",
    passengers: 5,
    bags: 4,
    doors: 5,
    transmission: "manual",
    fuelPolicy: "same-to-same",
    mileagePolicy: "limited",
    limitedMileageKm: 800,
    pickupType: "city-location",
    shuttleRequired: false,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 7.5,
    supplierReviewCount: 460,
    recommendationScore: 79,
    depositAmount: 900,
    excessAmount: 1400,
    minimumDriverAge: 25,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(65, false, true)],
  },
  {
    ...base,
    id: "suv-rav4",
    category: "suv",
    categoryLabel: "SUV",
    modelName: "Toyota RAV4",
    imageUrl: undefined,
    imageAlt: "Toyota RAV4 representative rental vehicle",
    passengers: 5,
    bags: 4,
    doors: 5,
    transmission: "automatic",
    fuelPolicy: "full-to-full",
    mileagePolicy: "unlimited",
    pickupType: "airport-counter",
    shuttleRequired: false,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 7.7,
    supplierReviewCount: 477,
    recommendationScore: 92,
    depositAmount: 930,
    excessAmount: 1435,
    minimumDriverAge: 25,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(76, true, true)],
  },
  {
    ...base,
    id: "suv-xc60",
    category: "suv",
    categoryLabel: "Premium SUV",
    modelName: "Volvo XC60",
    imageUrl: undefined,
    imageAlt: "Volvo XC60 representative rental vehicle",
    passengers: 5,
    bags: 4,
    doors: 5,
    transmission: "automatic",
    fuelPolicy: "full-to-full",
    mileagePolicy: "limited",
    limitedMileageKm: 650,
    pickupType: "meet-and-greet",
    shuttleRequired: false,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 7.9,
    supplierReviewCount: 494,
    recommendationScore: 89,
    depositAmount: 960,
    excessAmount: 1470,
    minimumDriverAge: 25,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(104, false, false)],
  },
  {
    ...base,
    id: "luxury-3series",
    category: "luxury",
    categoryLabel: "Luxury",
    modelName: "BMW 3 Series",
    imageUrl: undefined,
    imageAlt: "BMW 3 Series representative rental vehicle",
    passengers: 5,
    bags: 3,
    doors: 4,
    transmission: "automatic",
    fuelPolicy: "full-to-full",
    mileagePolicy: "unlimited",
    pickupType: "airport-counter",
    shuttleRequired: false,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 8.1,
    supplierReviewCount: 511,
    recommendationScore: 91,
    depositAmount: 990,
    excessAmount: 1505,
    minimumDriverAge: 25,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(109, true, false)],
  },
  {
    ...base,
    id: "luxury-a4",
    category: "luxury",
    categoryLabel: "Luxury",
    modelName: "Audi A4",
    imageUrl: undefined,
    imageAlt: "Audi A4 representative rental vehicle",
    passengers: 5,
    bags: 3,
    doors: 4,
    transmission: "automatic",
    fuelPolicy: "same-to-same",
    mileagePolicy: "limited",
    limitedMileageKm: 600,
    pickupType: "city-location",
    shuttleRequired: false,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 8.3,
    supplierReviewCount: 528,
    recommendationScore: 86,
    depositAmount: 1020,
    excessAmount: 1540,
    minimumDriverAge: 25,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(112, false, true)],
  },
  {
    ...base,
    id: "luxury-eclass",
    category: "luxury",
    categoryLabel: "Luxury",
    modelName: "Mercedes-Benz E-Class",
    imageUrl: undefined,
    imageAlt: "Mercedes-Benz E-Class representative rental vehicle",
    passengers: 5,
    bags: 4,
    doors: 4,
    transmission: "automatic",
    fuelPolicy: "full-to-full",
    mileagePolicy: "unlimited",
    pickupType: "meet-and-greet",
    shuttleRequired: false,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 8.5,
    supplierReviewCount: 545,
    recommendationScore: 94,
    depositAmount: 1050,
    excessAmount: 1575,
    minimumDriverAge: 25,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(139, true, false)],
  },
  {
    ...base,
    id: "suv-captur",
    category: "suv",
    categoryLabel: "Compact SUV",
    modelName: "Renault Captur",
    imageUrl: undefined,
    imageAlt: "Renault Captur representative rental vehicle",
    passengers: 5,
    bags: 3,
    doors: 5,
    transmission: "manual",
    fuelPolicy: "full-to-full",
    mileagePolicy: "limited",
    limitedMileageKm: 700,
    pickupType: "shuttle",
    shuttleRequired: true,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 8.7,
    supplierReviewCount: 562,
    recommendationScore: 74,
    depositAmount: 1080,
    excessAmount: 1610,
    minimumDriverAge: 25,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(57, false, true)],
  },
  {
    ...base,
    id: "suv-3008",
    category: "suv",
    categoryLabel: "SUV",
    modelName: "Peugeot 3008",
    imageUrl: undefined,
    imageAlt: "Peugeot 3008 representative rental vehicle",
    passengers: 5,
    bags: 4,
    doors: 5,
    transmission: "automatic",
    fuelPolicy: "same-to-same",
    mileagePolicy: "unlimited",
    pickupType: "airport-counter",
    shuttleRequired: false,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 8.9,
    supplierReviewCount: 579,
    recommendationScore: 87,
    depositAmount: 1110,
    excessAmount: 1645,
    minimumDriverAge: 25,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(71, true, false)],
  },
  {
    ...base,
    id: "van-c4picasso",
    category: "van",
    categoryLabel: "People carrier",
    modelName: "Citroën Grand C4 SpaceTourer",
    imageUrl: undefined,
    imageAlt: "Citroën Grand C4 SpaceTourer representative rental vehicle",
    passengers: 7,
    bags: 4,
    doors: 5,
    transmission: "automatic",
    fuelPolicy: "full-to-full",
    mileagePolicy: "limited",
    limitedMileageKm: 900,
    pickupType: "city-location",
    shuttleRequired: false,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 9.1,
    supplierReviewCount: 596,
    recommendationScore: 80,
    depositAmount: 1140,
    excessAmount: 1680,
    minimumDriverAge: 25,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(81, false, true)],
  },
  {
    ...base,
    id: "van-vclass",
    category: "van",
    categoryLabel: "Premium van",
    modelName: "Mercedes-Benz V-Class",
    imageUrl: undefined,
    imageAlt: "Mercedes-Benz V-Class representative rental vehicle",
    passengers: 8,
    bags: 5,
    doors: 5,
    transmission: "automatic",
    fuelPolicy: "full-to-full",
    mileagePolicy: "unlimited",
    pickupType: "meet-and-greet",
    shuttleRequired: false,
    rentalCompanyName: "Static fixture operator",
    supplierRating: 9.3,
    supplierReviewCount: 613,
    recommendationScore: 93,
    depositAmount: 1170,
    excessAmount: 1715,
    minimumDriverAge: 25,
    pickupInstructions:
      "Follow the pickup instructions supplied with the selected offer.",
    offerFixtures: [offer(148, true, false)],
  },
];
export const getStaticCarId = (id: string) => `static-car-${id}`;
