import { planStagedProductionPackPromotionTargets } from "./stagedProductionPackPromotionTargets";
import {
  buildStagedProductionPromotionChecklist,
  type StagedPromotionChecklist,
} from "./stagedProductionPromotionChecklist";
import type { StagedProductionMarketImagePack } from "./stagedProductionPacks";

export type StagedPromotionSnippet = {
  valid: boolean;
  errors: string[];
  warnings: string[];
  batchId: string;
  market: string;
  targetFiles: string[];
  entriesToPromote: number;
  snippet: string;
  checklist: StagedPromotionChecklist;
};

function formatPromotionEntry(entry: unknown): string {
  return `${JSON.stringify(entry, null, 2)},`;
}

export function buildStagedProductionPromotionSnippet(
  batchId: string,
  market: string,
  stagedPacks?: StagedProductionMarketImagePack[],
): StagedPromotionSnippet {
  const checklist = buildStagedProductionPromotionChecklist(batchId, market, stagedPacks);
  const plan = planStagedProductionPackPromotionTargets(batchId, market, stagedPacks);
  const targetFiles = checklist.targetFiles;
  const entriesToPromote = checklist.entriesToPromote;
  const warnings = Array.from(new Set([...checklist.warnings, ...plan.warnings]));
  const errors = Array.from(new Set([...checklist.errors, ...plan.errors]));

  if (!checklist.valid || !plan.valid) {
    return {
      valid: false,
      errors,
      warnings,
      batchId,
      market,
      targetFiles,
      entriesToPromote,
      snippet: "",
      checklist,
    };
  }

  const snippetSections = plan.targets.map((target) => {
    const entries = target.entries.map(formatPromotionEntry).join("\n");

    return [
      `// Promotion batch: ${batchId}`,
      `// Market: ${market}`,
      `// Target file: ${target.targetFile}`,
      "// Generated by staged promotion snippet builder.",
      "// Review before committing.",
      "",
      entries,
    ].join("\n");
  });

  return {
    valid: true,
    errors,
    warnings,
    batchId,
    market,
    targetFiles,
    entriesToPromote,
    snippet: snippetSections.join("\n\n"),
    checklist,
  };
}
