import assert from "node:assert/strict";
import test from "node:test";
import { createDefaultDealsSearch } from "./dealsSearchParams";
import { buildDealsSearchFingerprint, clearDealsTripPlan, createDealsTripPlan, DEALS_TRIP_PLAN_TTL_MS, getDealsTripPlanReadiness, isDealsTripPlanExpired, markDealsProviderOpened, updateDealsTripPlan, validateDealsInternalPath, type DealsTripPlanFlight, type DealsTripPlanHotel } from "./dealsTripPlan";

const flight: DealsTripPlanFlight = { id: "f1", provider: "P", airline: "Air", origin: "LOS", destination: "LAX", departure: "2026-08-01T10:00:00Z", arrival: "2026-08-01T20:00:00Z", duration: "10h", sourcePrice: 100, sourceCurrency: "USD", resultReceivedAt: 100 };
const hotel: DealsTripPlanHotel = { id: "h1", provider: "H", name: "Stay", location: "LA", checkIn: "2026-08-01", checkOut: "2026-08-03", sourcePrice: 200, sourceCurrency: "USD", resultReceivedAt: 100 };
test("plan creation, replacement, clearing and opened semantics", () => { const empty = createDealsTripPlan({ mode: "hotel-flight", searchFingerprint: "x", resultsPath: "/deals/results?q=x" }, 100); assert.equal(empty.expiresAt - empty.createdAt, DEALS_TRIP_PLAN_TTL_MS); const selected = updateDealsTripPlan(empty, { flight, hotel }, 101); assert.equal(selected.flight?.id, "f1"); assert.equal(updateDealsTripPlan(selected, { flight: { ...flight, id: "f2" } }, 102).flight?.id, "f2"); assert.equal(markDealsProviderOpened(selected, "flight", 103).opened.flight, 103); assert.deepEqual(clearDealsTripPlan(selected, 104).opened, {}); assert.equal(clearDealsTripPlan(selected).flight, undefined); assert.equal(isDealsTripPlanExpired(empty, empty.expiresAt), true); assert.doesNotMatch(JSON.stringify(selected), /booked/i); });
test("readiness follows every Deals mode and cars never blocks", () => { assert.deepEqual(getDealsTripPlanReadiness("hotel-flight", {} as never).missing, ["flight", "hotel"]); assert.equal(getDealsTripPlanReadiness("hotel-flight-car", { flight, hotel }).ready, true); assert.equal(getDealsTripPlanReadiness("flight-car", { flight }).ready, true); assert.equal(getDealsTripPlanReadiness("hotel-car", { hotel }).ready, true); });
test("fingerprint is deterministic, ordered and mode-sensitive", () => { const a = createDefaultDealsSearch(); a.flightOriginCode = "LOS"; const b = { ...a }; assert.equal(buildDealsSearchFingerprint(a), buildDealsSearchFingerprint(b)); b.flightOriginCode = "ABV"; assert.notEqual(buildDealsSearchFingerprint(a), buildDealsSearchFingerprint(b)); b.flightOriginCode = "LOS"; b.mode = "flight-car"; assert.notEqual(buildDealsSearchFingerprint(a), buildDealsSearchFingerprint(b)); });
test("internal path allowlists reject open redirects and malformed encoding", () => { assert.equal(validateDealsInternalPath("/deals/results?q=x"), "/deals/results?q=x"); assert.equal(validateDealsInternalPath("/cars/results?q=x", "/cars/results"), "/cars/results?q=x"); for (const path of ["https://evil.test/deals/results", "//evil.test", "/other", "/deals/results?x=%ZZ", "/deals/results#evil"]) assert.equal(validateDealsInternalPath(path), null); });
