import assert from "node:assert/strict";
import test from "node:test";
import { createDefaultDealsSearch } from "./dealsSearchParams";
import { buildDealsSearchFingerprint, clearDealsTripPlan, createDealsTripPlan, DEALS_TRIP_PLAN_TTL_MS, getDealsTripPlanReadiness, getNextDealsProviderStep, isDealsTripPlanExpired, markDealsProviderOpened, updateDealsTripPlan, validateDealsInternalPath, type DealsTripPlanCar, type DealsTripPlanFlight, type DealsTripPlanHotel } from "./dealsTripPlan";

const flight: DealsTripPlanFlight = { id: "f1", provider: "P", airline: "Air", origin: "LOS", destination: "LAX", departure: "2026-08-01T10:00:00Z", arrival: "2026-08-01T20:00:00Z", duration: "10h", sourcePrice: 100, sourceCurrency: "USD", resultReceivedAt: 100 };
const car: DealsTripPlanCar = { id: "c1", provider: "P", rentalCompany: "Rent", modelName: "Car", categoryLabel: "Compact", pickupLocation: "LA", returnLocation: "LA", pickupDate: "2026-08-01", pickupTime: "10:00", dropoffDate: "2026-08-03", dropoffTime: "10:00", sourcePrice: 90, sourceCurrency: "USD", resultReceivedAt: 100, detailsPath: "/cars/details/c1?pickupLocation=LA&dropoffLocation=LA&pickupDate=2026-08-01&pickupTime=10%3A00&dropoffDate=2026-08-03&dropoffTime=10%3A00&driverAge=30" };
const hotel: DealsTripPlanHotel = { id: "h1", provider: "H", name: "Stay", location: "LA", checkIn: "2026-08-01", checkOut: "2026-08-03", sourcePrice: 200, sourceCurrency: "USD", resultReceivedAt: 100 };
test("plan creation, replacement, clearing and opened semantics", () => { const empty = createDealsTripPlan({ mode: "hotel-flight", searchFingerprint: "x", resultsPath: "/deals/results?q=x" }, 100); assert.equal(empty.expiresAt - empty.createdAt, DEALS_TRIP_PLAN_TTL_MS); const selected = updateDealsTripPlan(empty, { flight, hotel }, 101); assert.equal(selected.flight?.id, "f1"); assert.equal(updateDealsTripPlan(selected, { flight: { ...flight, id: "f2" } }, 102).flight?.id, "f2"); assert.equal(markDealsProviderOpened(selected, "flight", 103).opened.flight, 103); assert.deepEqual(clearDealsTripPlan(selected, 104).opened, {}); assert.equal(clearDealsTripPlan(selected).flight, undefined); assert.equal(isDealsTripPlanExpired(empty, empty.expiresAt), true); assert.doesNotMatch(JSON.stringify(selected), /booked/i); });
test("readiness requires every included product", () => { assert.deepEqual(getDealsTripPlanReadiness("hotel-flight", {} as never).missing, ["flight", "hotel"]); assert.equal(getDealsTripPlanReadiness("hotel-flight", { flight, hotel }).ready, true); assert.deepEqual(getDealsTripPlanReadiness("hotel-flight-car", { flight, hotel }).missing, ["car"]); assert.equal(getDealsTripPlanReadiness("hotel-flight-car", { flight, hotel, car }).ready, true); assert.equal(getDealsTripPlanReadiness("flight-car", { flight }).ready, false); assert.equal(getDealsTripPlanReadiness("hotel-car", { hotel }).ready, false); assert.equal(getDealsTripPlanReadiness("hotel-flight-car", { flight, hotel, car }).missing.includes("car"), false); });
test("fingerprint is deterministic, ordered and mode-sensitive", () => { const a = createDefaultDealsSearch(); a.flightOriginCode = "LOS"; const b = { ...a }; assert.equal(buildDealsSearchFingerprint(a), buildDealsSearchFingerprint(b)); b.flightOriginCode = "ABV"; assert.notEqual(buildDealsSearchFingerprint(a), buildDealsSearchFingerprint(b)); b.flightOriginCode = "LOS"; b.mode = "flight-car"; assert.notEqual(buildDealsSearchFingerprint(a), buildDealsSearchFingerprint(b)); });
test("internal path allowlists reject open redirects and malformed encoding", () => { assert.equal(validateDealsInternalPath("/deals/results?q=x"), "/deals/results?q=x"); assert.equal(validateDealsInternalPath("/cars/results?q=x", "/cars/results"), "/cars/results?q=x"); for (const path of ["https://evil.test/deals/results", "//evil.test", "/other", "/deals/results?x=%ZZ", "/deals/results#evil"]) assert.equal(validateDealsInternalPath(path), null); });
test("next-provider logic advances one provider without claiming completion", () => { const plan = updateDealsTripPlan(createDealsTripPlan({ mode: "hotel-flight", searchFingerprint: "x", resultsPath: "/deals/results?q=x" }, 100), { flight, hotel }, 101); assert.equal(getNextDealsProviderStep(plan, 102).product, "flight"); const flightOpened = markDealsProviderOpened(plan, "flight", 103); assert.equal(getNextDealsProviderStep(flightOpened, 104).product, "hotel"); const both = markDealsProviderOpened(flightOpened, "hotel", 105); assert.deepEqual(getNextDealsProviderStep(both, 106), { product: null, href: null, allOpened: true }); assert.equal(getNextDealsProviderStep({ ...plan, flight: undefined }, 102).product, "hotel"); assert.equal(getNextDealsProviderStep(plan, DEALS_TRIP_PLAN_TTL_MS + 100).product, null); const withCar = updateDealsTripPlan(createDealsTripPlan({ mode: "flight-car", searchFingerprint: "x", resultsPath: "/deals/results?q=x" }, 100), { flight, car }, 101); assert.equal(getNextDealsProviderStep(markDealsProviderOpened(withCar, "flight", 103), 104).product, "car"); });

test("guided next expiry includes only products in the package mode without mutation", async () => {
  const { getDealsGuidedNextExpiryAt } = await import("./dealsTripPlan");
  const base = createDealsTripPlan({ mode: "hotel-flight", searchFingerprint: "x", resultsPath: "/deals/results" }, 100);
  const plan = { ...base, expiresAt: 9000, hotel: { id: "h", provider: "p", name: "h", location: "l", checkIn: "i", checkOut: "o", sourcePrice: 1, sourceCurrency: "USD", resultReceivedAt: 200 }, flight: { id: "f", provider: "p", airline: "a", origin: "o", destination: "d", departure: "d", arrival: "a", duration: "1h", sourcePrice: 1, sourceCurrency: "USD", resultReceivedAt: 300 }, car: { id: "c", provider: "p", rentalCompany: "r", modelName: "m", categoryLabel: "c", pickupLocation: "p", returnLocation: "r", pickupDate: "d", pickupTime: "t", dropoffDate: "d", dropoffTime: "t", sourcePrice: 1, sourceCurrency: "USD", resultReceivedAt: 0, detailsPath: "/cars/details/c?pickupLocation=p&dropoffLocation=r&pickupDate=d&pickupTime=t&dropoffDate=d&dropoffTime=t&driverAge=30" } };
  const before = structuredClone(plan); assert.equal(getDealsGuidedNextExpiryAt(plan), 9000); assert.deepEqual(plan, before);
});
