import assert from "node:assert/strict";
import test from "node:test";
import { getDealsGuidedEstimatedTotal, getDealsGuidedOpenedCount, getDealsGuidedProducts, prepareDealsGuidedActivation, validateDealsGuidedHandoffPlan } from "./dealsGuidedHandoff";
import { createDealsTripPlan, type DealsTripPlan } from "./dealsTripPlan";
import { parseDealsSearchParams, type DealsPackageMode } from "./dealsSearchParams";

const now = 100_000;
function plan(mode: DealsPackageMode): DealsTripPlan {
  const base = createDealsTripPlan({ mode, searchFingerprint: "fp", resultsPath: "/deals/results" }, now);
  const common = { provider: "Safe", sourcePrice: 100, sourceCurrency: "USD", resultReceivedAt: now };
  return { ...base, updatedAt: now, hotel: { ...common, id: "h", name: "Hotel", location: "Paris", checkIn: "2027-01-01", checkOut: "2027-01-03", detailsPath: "/hotels/details/h" }, flight: { ...common, id: "f", airline: "Air", origin: "JFK", destination: "CDG", departure: "2027-01-01T10:00", arrival: "2027-01-01T20:00", duration: "7h" }, car: { ...common, id: "c", rentalCompany: "Cars", modelName: "Model", categoryLabel: "compact", pickupLocation: "Paris", returnLocation: "Paris", pickupDate: "2027-01-01", pickupTime: "10:00", dropoffDate: "2027-01-03", dropoffTime: "10:00", detailsPath: "/cars/details/c?pickupLocation=Paris&dropoffLocation=Paris&pickupDate=2027-01-01&pickupTime=10%3A00&dropoffDate=2027-01-03&dropoffTime=10%3A00&driverAge=30" } };
}
const expected: Record<DealsPackageMode, string[]> = { "hotel-flight": ["hotel", "flight"], "hotel-car": ["hotel", "car"], "flight-car": ["flight", "car"], "hotel-flight-car": ["hotel", "flight", "car"] };
for (const mode of Object.keys(expected) as DealsPackageMode[]) test(`${mode} uses review order and omits excluded selections`, () => assert.deepEqual(getDealsGuidedProducts(plan(mode)), expected[mode]));
test("validation ignores excluded stale selection and opened timestamp", () => { const value = plan("hotel-flight"); value.car!.resultReceivedAt = 0; value.opened.car = now; const search = { ...parseDealsSearchParams({}), mode: value.mode }; assert.equal(validateDealsGuidedHandoffPlan(value, search, "fp", now + 1).ok, true); assert.equal(getDealsGuidedOpenedCount(value), 0); });
test("validation blocks mismatch, missing, and included expiry", () => { const value = plan("hotel-flight"); const search = { ...parseDealsSearchParams({}), mode: value.mode }; assert.equal(validateDealsGuidedHandoffPlan(value, search, "wrong", now).ok, false); const missing = { ...value, hotel: undefined }; assert.equal(validateDealsGuidedHandoffPlan(missing, search, "fp", now).ok, false); const stale = { ...value, hotel: { ...value.hotel!, resultReceivedAt: 0 } }; assert.equal(validateDealsGuidedHandoffPlan(stale, search, "fp", now + 1_500_000).ok, false); });
test("activation derives safe actions, blocks changed IDs, and preserves TTL and selections", () => { const value = plan("hotel-flight"); const search = { ...parseDealsSearchParams({}), mode: value.mode }; const flight = prepareDealsGuidedActivation(value, value, "flight", search, "fp", now + 1, "en"); assert.equal(flight.ok, true); if (!flight.ok) return; assert.equal(flight.href, "/redirect?id=f&type=flight"); assert.equal(flight.plan.expiresAt, value.expiresAt); assert.equal(flight.plan.flight!.resultReceivedAt, now); assert.equal(flight.plan.opened.flight, now + 1); assert.equal(value.opened.flight, undefined); const changed = { ...value, flight: { ...value.flight!, id: "other" } }; assert.deepEqual(prepareDealsGuidedActivation(changed, value, "flight", search, "fp", now + 1, "en"), { ok: false, reason: "selection-changed" }); });
test("included-only total ignores excluded missing rate", () => { const value = plan("hotel-flight"); value.car!.sourceCurrency = "XXX"; assert.equal(getDealsGuidedEstimatedTotal(value, "USD", { USD: 1 }), 200); value.hotel!.sourceCurrency = "XXX"; assert.equal(getDealsGuidedEstimatedTotal(value, "USD", { USD: 1 }), null); });
