import assert from "node:assert/strict";
import test from "node:test";
import { buildCarResultsUrl, buildDealsModifyUrl, buildDealsResultsUrl, buildFlightApiPayload, buildFlightResultsUrl, buildHotelResultsUrl, createDefaultDealsSearch, getIncludedProducts, parseDealsSearchParams, serializeDealsSearchParams, validateCarSearch, validateDealsSearch, validateFlightSearch, validateHotelSearch } from "./dealsSearchParams";

const valid = () => ({ ...createDefaultDealsSearch(), mode: "hotel-flight-car" as const, flightOriginText: "New York (JFK)", flightOriginCode: "JFK", flightDestinationText: "Los Angeles (LAX)", flightDestinationCode: "LAX", hotelDestination: "Los Angeles", carPickupLocation: "Los Angeles" });
test("package inclusion matrix", () => { assert.deepEqual(getIncludedProducts("hotel-flight"), { flight: true, hotel: true, car: false }); assert.deepEqual(getIncludedProducts("hotel-flight-car"), { flight: true, hotel: true, car: true }); assert.deepEqual(getIncludedProducts("flight-car"), { flight: true, hotel: false, car: true }); assert.deepEqual(getIncludedProducts("hotel-car"), { flight: false, hotel: true, car: true }); });
test("complete query round trips and builds deals links", () => { const search = valid(); const parsed = parseDealsSearchParams(serializeDealsSearchParams(search)); assert.deepEqual(parsed, search); assert.match(buildDealsResultsUrl(search), /^\/deals\/results\?/); assert.match(buildDealsModifyUrl(search), /^\/deals\?/); });
test("malformed and missing values normalize predictably", () => { const parsed = parseDealsSearchParams(new URLSearchParams("flightAdults=1.5&hotelRooms=nope&flightOriginCode=jfk&flightDepartureDate=2026-99-99")); assert.equal(parsed.flightAdults, 1); assert.equal(parsed.hotelRooms, 1); assert.equal(parsed.flightOriginCode, "JFK"); assert.notEqual(parsed.flightDepartureDate, "2026-99-99"); });
test("flight validates codes, passenger limits, infants, fractions, and dates", () => { const search = valid(); assert.deepEqual(validateFlightSearch(search, "2000-01-01"), {}); search.flightDestinationCode = "los angeles"; assert.ok(validateFlightSearch(search, "2000-01-01").flightDestinationCode); assert.equal(buildFlightApiPayload(search).destination, ""); search.flightDestinationCode = "lax"; search.flightAdults = 7; search.flightChildren = 1; search.flightInfants = 1; assert.deepEqual(validateFlightSearch(search, "2000-01-01"), {}); search.flightChildren = 2; assert.ok(validateFlightSearch(search, "2000-01-01").flightPassengers); search.flightChildren = 0; search.flightAdults = 1; search.flightInfants = 2; assert.ok(validateFlightSearch(search, "2000-01-01").flightInfants); search.flightInfants = 0; search.flightAdults = 1.5; assert.ok(validateFlightSearch(search, "2000-01-01").flightPassengers); search.flightAdults = 1; search.flightReturnDate = "2001-01-01"; search.flightDepartureDate = "2001-01-02"; assert.ok(validateFlightSearch(search, "2000-01-01").flightReturnDate); });
test("hotel validates destination, dates, guest and room maximums", () => { const search = valid(); assert.deepEqual(validateHotelSearch(search, "2000-01-01"), {}); search.hotelDestination = ""; assert.ok(validateHotelSearch(search, "2000-01-01").hotelDestination); search.hotelDestination = "LA"; search.hotelCheckOut = search.hotelCheckIn; assert.ok(validateHotelSearch(search, "2000-01-01").hotelDates); search.hotelCheckOut = "2099-01-02"; search.hotelCheckIn = "2099-01-01"; search.hotelAdults = 12; search.hotelChildren = 0; assert.equal(validateHotelSearch(search, "2000-01-01").hotelGuests, undefined); search.hotelChildren = 1; assert.ok(validateHotelSearch(search, "2000-01-01").hotelGuests); search.hotelChildren = 0; search.hotelRooms = 7; assert.ok(validateHotelSearch(search, "2000-01-01").hotelRooms); });
test("hidden products do not affect validation", () => { const search = valid(); search.mode = "flight-car"; search.hotelDestination = ""; assert.equal(validateDealsSearch(search, "2000-01-01").hotel, undefined); search.mode = "hotel-flight"; search.carPickupLocation = ""; assert.equal(validateDealsSearch(search, "2000-01-01").car, undefined); });
test("car reuses canonical validation and effective return location", () => { const search = valid(); assert.deepEqual(validateCarSearch(search, "2000-01-01"), {}); let url = new URL(buildCarResultsUrl(search), "https://example.test"); assert.equal(url.searchParams.get("dropoffLocation"), "Los Angeles"); search.carReturnToDifferentLocation = true; search.carReturnLocation = ""; assert.ok(validateCarSearch(search, "2000-01-01").dropoffLocation); search.carReturnLocation = "San Diego"; url = new URL(buildCarResultsUrl(search), "https://example.test"); assert.equal(url.searchParams.get("dropoffLocation"), "San Diego"); search.carReturnDate = "2000-01-01"; assert.ok(validateCarSearch(search, "2000-01-01").dateRange); });
test("product deep links preserve separate canonical values", () => { const search = valid(); search.flightDepartureDate = "2099-02-01"; search.flightReturnDate = "2099-02-10"; search.hotelCheckIn = "2099-02-03"; search.hotelCheckOut = "2099-02-07"; search.carPickupDate = "2099-02-04"; search.carReturnDate = "2099-02-06"; const flight = new URL(buildFlightResultsUrl(search), "https://x"); const hotel = new URL(buildHotelResultsUrl(search), "https://x"); const car = new URL(buildCarResultsUrl(search), "https://x"); assert.equal(flight.searchParams.get("destination"), "LAX"); assert.notEqual(flight.searchParams.get("destination"), search.flightDestinationText); assert.equal(hotel.searchParams.get("checkIn"), "2099-02-03"); assert.equal(car.searchParams.get("pickupDate"), "2099-02-04"); assert.equal(car.searchParams.get("pickupTime"), "10:00"); });
