import { getPrisma } from "@/lib/prisma";
import { consumePasskeyReauthToken } from "@/lib/passkey-reauth";
import { assertAllowedOrigin, getWebAuthnConfig, newChallenge, parseClientData, parseRegistrationAuthData, sha256, userHandle } from "@/lib/passkeys";
import { deliverSecurityEvent } from "@/services/securityEventService";

export type PasskeyPrincipal = { userId: string; email: string; name?: string | null; accountSessionId: string };
const label = (p: { deviceType: string | null; backedUp: boolean | null; transports: string | null }) => p.backedUp ? "Synced passkey" : p.transports?.includes("usb") || p.transports?.includes("nfc") ? "Security key" : p.deviceType === "platform" ? "This device" : "Device, password manager, or security key";
export async function listPasskeys(userId: string) { const rows = await getPrisma().userPasskey.findMany({where:{userId,revokedAt:null},orderBy:{createdAt:"desc"},select:{id:true,name:true,createdAt:true,lastUsedAt:true,deviceType:true,backedUp:true,transports:true}}); return rows.map(({transports,...p})=>({...p,label:label({...p,transports})})); }
export async function registrationOptions(p: PasskeyPrincipal, token: unknown) { const prisma=getPrisma(); const user=await prisma.user.findUnique({where:{id:p.userId},select:{status:true}}); if(user?.status!=="ACTIVE") throw new Error("inactive"); if(!await consumePasskeyReauthToken(p.userId,token,"setup")) throw new Error("reauth"); const challenge=newChallenge(); await prisma.webAuthnChallenge.create({data:{userId:p.userId,challenge,type:"registration",expiresAt:new Date(Date.now()+300000)}}); const existing=await prisma.userPasskey.findMany({where:{userId:p.userId,revokedAt:null},select:{credentialId:true,transports:true}}); const cfg=getWebAuthnConfig(); return {challenge,rp:{name:cfg.rpName,id:cfg.rpID},user:{id:userHandle(p.userId),name:p.email,displayName:p.name||p.email},pubKeyCredParams:[{type:"public-key" as const,alg:-7}],timeout:60000,attestation:"none",authenticatorSelection:{residentKey:"preferred",userVerification:"required"},excludeCredentials:existing.map(x=>({id:x.credentialId,type:"public-key" as const,transports:x.transports?.split(",")}))}; }
export async function verifyRegistration(p: PasskeyPrincipal, body: any) { const response=body?.response; const clientData=parseClientData(response.clientDataJSON); assertAllowedOrigin(clientData.origin, clientData.androidPackageName); if(clientData.type!=="webauthn.create") throw new Error("type"); const prisma=getPrisma(); const challenge=await prisma.webAuthnChallenge.findFirst({where:{userId:p.userId,challenge:clientData.challenge,type:"registration",consumedAt:null,expiresAt:{gt:new Date()}}}); if(!challenge) throw new Error("expired"); const auth=parseRegistrationAuthData(response.authenticatorData); if(!auth.rpIdHash.equals(sha256(getWebAuthnConfig().rpID))||!(auth.flags&1)||!(auth.flags&4)) throw new Error("verification"); const mutation=await prisma.$transaction(async tx=>{await tx.webAuthnChallenge.update({where:{id:challenge.id},data:{consumedAt:new Date()}}); const passkey=await tx.userPasskey.create({data:{userId:p.userId,credentialId:auth.credentialId,publicKey:auth.publicKey,counter:auth.counter,transports:Array.isArray(response.transports)?response.transports.join(","):null,deviceType:response.authenticatorAttachment||null,backedUp:Boolean(auth.flags&16),name:String(body.name||"Passkey").trim().slice(0,80)||"Passkey"},select:{id:true}}); const event=await tx.securityEvent.create({data:{userId:p.userId,accountSessionId:p.accountSessionId,type:"PASSKEY_ADDED",metadata:{passkeyId:passkey.id}}}); return {passkey,event};}); await deliverSecurityEvent({userId:p.userId,email:p.email,securityEventId:mutation.event.id,title:"Passkey added",body:"A passkey was added to your Kurioticket account. If this wasn’t you, remove it and secure your account immediately.",metadata:{passkeyId:mutation.passkey.id}}); }
export async function renamePasskey(userId:string,id:string,name:unknown){const clean=String(name||"").trim();if(!clean||clean.length>80)throw new Error("name");const r=await getPrisma().userPasskey.updateMany({where:{id,userId,revokedAt:null},data:{name:clean}});return r.count>0;}
export async function removePasskey(p:PasskeyPrincipal,id:string,token:unknown){if(!await consumePasskeyReauthToken(p.userId,token,"removal"))throw new Error("reauth");const event=await getPrisma().$transaction(async tx=>{const r=await tx.userPasskey.updateMany({where:{id,userId:p.userId,revokedAt:null},data:{revokedAt:new Date()}});if(!r.count)return null;return tx.securityEvent.create({data:{userId:p.userId,accountSessionId:p.accountSessionId,type:"PASSKEY_REMOVED",metadata:{passkeyId:id}}});});if(!event)return false;await deliverSecurityEvent({userId:p.userId,email:p.email,securityEventId:event.id,title:"Passkey removed",body:"A passkey was removed from your Kurioticket account. If this wasn’t you, secure your account immediately.",metadata:{passkeyId:id}});return true;}
