import { useState } from "react";
import { Pressable, Text, View } from "react-native";
import { CounterSheet, FormTextField, SearchSubmitButton } from "./SearchFormControls";
import { searchFormStyles as styles } from "./searchFormStyles";
import { addDays, isAfterDateTime, isIsoDate, sleep, todayIso } from "./searchUtils";
import { colors } from "../../theme/tokens";

type CarSearchValues = { pickupLocation: string; sameDropoffLocation: boolean; dropoffLocation: string; pickupDate: string; pickupTime: string; dropoffDate: string; dropoffTime: string; driverAge: number };
type CarErrors = Partial<Record<keyof CarSearchValues | "dateTime", string>>;
const timePattern = /^([01]\d|2[0-3]):[0-5]\d$/;

export function CarSearchForm() {
  const [values, setValues] = useState<CarSearchValues>({ pickupLocation: "", sameDropoffLocation: true, dropoffLocation: "", pickupDate: addDays(14), pickupTime: "10:00", dropoffDate: addDays(17), dropoffTime: "10:00", driverAge: 30 });
  const [errors, setErrors] = useState<CarErrors>({});
  const [showAge, setShowAge] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [message, setMessage] = useState("");
  const validate = () => { const next: CarErrors = {}; if (!values.pickupLocation.trim()) next.pickupLocation = "Enter a pick-up location."; if (!values.sameDropoffLocation && !values.dropoffLocation.trim()) next.dropoffLocation = "Enter a drop-off location."; if (!isIsoDate(values.pickupDate) || values.pickupDate < todayIso()) next.pickupDate = "Use a future YYYY-MM-DD date."; if (!timePattern.test(values.pickupTime)) next.pickupTime = "Use HH:MM time."; if (!isIsoDate(values.dropoffDate) || values.dropoffDate < todayIso()) next.dropoffDate = "Use a future YYYY-MM-DD date."; if (!timePattern.test(values.dropoffTime)) next.dropoffTime = "Use HH:MM time."; if (!Number.isInteger(values.driverAge) || values.driverAge < 18 || values.driverAge > 70) next.driverAge = "Driver age must be 18–70."; if (!next.pickupDate && !next.pickupTime && !next.dropoffDate && !next.dropoffTime && !isAfterDateTime(values.dropoffDate, values.dropoffTime, values.pickupDate, values.pickupTime)) next.dateTime = "Drop-off must be after pick-up."; setErrors(next); return Object.keys(next).length === 0; };
  const submit = async () => { if (submitting || !validate()) return; setSubmitting(true); setMessage(""); await sleep(300); setSubmitting(false); setMessage("Car rental results are not available yet."); };
  return <View style={styles.card}><FormTextField label="Pick-up location" value={values.pickupLocation} placeholder="Airport, city, or address" onChangeText={(pickupLocation) => setValues({ ...values, pickupLocation })} error={errors.pickupLocation} /><Pressable accessibilityRole="checkbox" accessibilityState={{ checked: values.sameDropoffLocation }} onPress={() => setValues({ ...values, sameDropoffLocation: !values.sameDropoffLocation })} style={({ pressed }) => [styles.field, { minHeight: 62, flexDirection: "row", alignItems: "center", gap: 12 }, pressed && styles.fieldPressed]}><View style={{ width: 24, height: 24, borderRadius: 8, borderWidth: 2, borderColor: colors.blue, backgroundColor: values.sameDropoffLocation ? colors.blue : colors.surface, alignItems: "center", justifyContent: "center" }}><Text style={{ color: "white", fontWeight: "900" }}>{values.sameDropoffLocation ? "✓" : ""}</Text></View><Text style={styles.fieldValue}>Same drop-off location</Text></Pressable>{values.sameDropoffLocation ? null : <FormTextField label="Drop-off location" value={values.dropoffLocation} placeholder="Airport, city, or address" onChangeText={(dropoffLocation) => setValues({ ...values, dropoffLocation })} error={errors.dropoffLocation} />}<View style={styles.row}><FormTextField compact label="Pick-up date" value={values.pickupDate} placeholder="YYYY-MM-DD" onChangeText={(pickupDate) => setValues({ ...values, pickupDate })} error={errors.pickupDate || errors.dateTime} /><FormTextField compact label="Time" value={values.pickupTime} placeholder="HH:MM" onChangeText={(pickupTime) => setValues({ ...values, pickupTime })} error={errors.pickupTime} /></View><View style={styles.row}><FormTextField compact label="Drop-off date" value={values.dropoffDate} placeholder="YYYY-MM-DD" onChangeText={(dropoffDate) => setValues({ ...values, dropoffDate })} error={errors.dropoffDate} /><FormTextField compact label="Time" value={values.dropoffTime} placeholder="HH:MM" onChangeText={(dropoffTime) => setValues({ ...values, dropoffTime })} error={errors.dropoffTime} /></View><Pressable onPress={() => setShowAge(true)} style={({ pressed }) => [styles.field, styles.compactField, pressed && styles.fieldPressed]}><Text style={styles.fieldLabel}>Driver age</Text><Text style={styles.fieldValue}>{values.driverAge}</Text>{errors.driverAge ? <Text style={styles.error}>{errors.driverAge}</Text> : null}</Pressable>{message ? <Text style={styles.notice}>{message}</Text> : null}<SearchSubmitButton label="Search Cars" submitting={submitting} onPress={submit} /><CounterSheet visible={showAge} title="Driver age" onClose={() => setShowAge(false)} counters={[{ label: "Age", value: values.driverAge, min: 18, max: 70, onChange: (driverAge) => setValues((current) => ({ ...current, driverAge })) }]} /></View>;
}
