import { StyleSheet } from "react-native";
import { colors, spacing } from "../../theme/tokens";

export const searchFormStyles = StyleSheet.create({
  card: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: spacing.radius, padding: spacing.card, gap: 14 },
  row: { flexDirection: "row", gap: 10 },
  field: { minHeight: 92, borderRadius: 18, borderColor: colors.border, borderWidth: 1, backgroundColor: colors.background, padding: 14, justifyContent: "center" },
  compactField: { flex: 1, minHeight: 74 },
  pressed: { opacity: 0.7 },
  fieldPressed: { borderColor: colors.blue, backgroundColor: colors.sky },
  fieldLabel: { color: colors.muted, fontSize: 12, fontWeight: "900", textTransform: "uppercase", letterSpacing: 0.7 },
  fieldValue: { color: colors.navy, fontSize: 17, lineHeight: 23, fontWeight: "900" },
  fieldMeta: { color: colors.slate, fontSize: 13, lineHeight: 18 },
  input: { color: colors.navy, fontSize: 17, lineHeight: 23, fontWeight: "900", padding: 0, marginTop: 4 },
  error: { color: colors.danger, fontSize: 12, lineHeight: 17, fontWeight: "800", marginTop: 6 },
  notice: { color: colors.slate, backgroundColor: colors.sky, borderColor: colors.border, borderWidth: 1, borderRadius: 14, padding: 12, fontSize: 13, lineHeight: 18, fontWeight: "700" },
  searchButton: { minHeight: 56, borderRadius: 18, backgroundColor: colors.blue, alignItems: "center", justifyContent: "center" },
  searchButtonDisabled: { opacity: 0.65 },
  searchButtonPressed: { backgroundColor: colors.navy },
  searchButtonText: { color: "white", fontSize: 17, fontWeight: "900" },
  segment: { flexDirection: "row", padding: 4, borderRadius: 18, backgroundColor: colors.background },
  segmentItem: { flex: 1, minHeight: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" },
  segmentItemActive: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1 },
  segmentText: { color: colors.muted, fontWeight: "800", fontSize: 13 },
  segmentTextActive: { color: colors.navy },
  modalOverlay: { flex: 1, backgroundColor: "rgba(2,28,43,0.28)", justifyContent: "flex-end" },
  sheet: { backgroundColor: colors.surface, padding: spacing.screen, borderTopLeftRadius: spacing.radius, borderTopRightRadius: spacing.radius, gap: 14 },
  sheetTitle: { color: colors.navy, fontSize: 20, lineHeight: 26, fontWeight: "900" },
  counterRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  counterLabel: { color: colors.navy, fontSize: 16, fontWeight: "900" },
  counterControls: { flexDirection: "row", alignItems: "center", gap: 12 },
  counterButton: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.background, borderColor: colors.border, borderWidth: 1, alignItems: "center", justifyContent: "center" },
  counterButtonText: { color: colors.blue, fontSize: 22, fontWeight: "900" },
});
