export type SupportedRegion = {
  code: string;
  country: string;
  currency: string;
};

export type SupportedCurrency = {
  code: string;
  name: string;
};

// Public country/territory selector catalog for display-market preferences.
// Includes ISO 3166-1 countries and territories plus the existing EU market option.
// Currency values are display defaults constrained to currencies Kurioticket can safely format today.
export const supportedRegions: SupportedRegion[] = [
  { code: "AF", country: "Afghanistan", currency: "USD" },
  { code: "AL", country: "Albania", currency: "USD" },
  { code: "DZ", country: "Algeria", currency: "USD" },
  { code: "AS", country: "American Samoa", currency: "USD" },
  { code: "AD", country: "Andorra", currency: "EUR" },
  { code: "AO", country: "Angola", currency: "USD" },
  { code: "AI", country: "Anguilla", currency: "USD" },
  { code: "AQ", country: "Antarctica", currency: "USD" },
  { code: "AG", country: "Antigua and Barbuda", currency: "USD" },
  { code: "AR", country: "Argentina", currency: "ARS" },
  { code: "AM", country: "Armenia", currency: "USD" },
  { code: "AW", country: "Aruba", currency: "USD" },
  { code: "AU", country: "Australia", currency: "AUD" },
  { code: "AT", country: "Austria", currency: "EUR" },
  { code: "AZ", country: "Azerbaijan", currency: "USD" },
  { code: "BS", country: "Bahamas", currency: "USD" },
  { code: "BH", country: "Bahrain", currency: "USD" },
  { code: "BD", country: "Bangladesh", currency: "USD" },
  { code: "BB", country: "Barbados", currency: "USD" },
  { code: "BY", country: "Belarus", currency: "USD" },
  { code: "BE", country: "Belgium", currency: "EUR" },
  { code: "BZ", country: "Belize", currency: "USD" },
  { code: "BJ", country: "Benin", currency: "USD" },
  { code: "BM", country: "Bermuda", currency: "USD" },
  { code: "BT", country: "Bhutan", currency: "USD" },
  { code: "BO", country: "Bolivia, Plurinational State of", currency: "USD" },
  { code: "BQ", country: "Bonaire, Sint Eustatius and Saba", currency: "USD" },
  { code: "BA", country: "Bosnia and Herzegovina", currency: "USD" },
  { code: "BW", country: "Botswana", currency: "USD" },
  { code: "BV", country: "Bouvet Island", currency: "NOK" },
  { code: "BR", country: "Brazil", currency: "BRL" },
  { code: "IO", country: "British Indian Ocean Territory", currency: "USD" },
  { code: "BN", country: "Brunei Darussalam", currency: "USD" },
  { code: "BG", country: "Bulgaria", currency: "USD" },
  { code: "BF", country: "Burkina Faso", currency: "USD" },
  { code: "BI", country: "Burundi", currency: "USD" },
  { code: "CV", country: "Cabo Verde", currency: "USD" },
  { code: "KH", country: "Cambodia", currency: "USD" },
  { code: "CM", country: "Cameroon", currency: "USD" },
  { code: "CA", country: "Canada", currency: "CAD" },
  { code: "KY", country: "Cayman Islands", currency: "USD" },
  { code: "CF", country: "Central African Republic", currency: "USD" },
  { code: "TD", country: "Chad", currency: "USD" },
  { code: "CL", country: "Chile", currency: "CLP" },
  { code: "CN", country: "China", currency: "CNY" },
  { code: "CX", country: "Christmas Island", currency: "AUD" },
  { code: "CC", country: "Cocos (Keeling) Islands", currency: "AUD" },
  { code: "CO", country: "Colombia", currency: "COP" },
  { code: "KM", country: "Comoros", currency: "USD" },
  { code: "CG", country: "Congo", currency: "USD" },
  { code: "CD", country: "Congo, The Democratic Republic of the", currency: "USD" },
  { code: "CK", country: "Cook Islands", currency: "USD" },
  { code: "CR", country: "Costa Rica", currency: "USD" },
  { code: "HR", country: "Croatia", currency: "EUR" },
  { code: "CU", country: "Cuba", currency: "USD" },
  { code: "CW", country: "Curaçao", currency: "USD" },
  { code: "CY", country: "Cyprus", currency: "EUR" },
  { code: "CZ", country: "Czechia", currency: "CZK" },
  { code: "CI", country: "Côte d'Ivoire", currency: "USD" },
  { code: "DK", country: "Denmark", currency: "DKK" },
  { code: "DJ", country: "Djibouti", currency: "USD" },
  { code: "DM", country: "Dominica", currency: "USD" },
  { code: "DO", country: "Dominican Republic", currency: "USD" },
  { code: "EC", country: "Ecuador", currency: "USD" },
  { code: "EG", country: "Egypt", currency: "EGP" },
  { code: "SV", country: "El Salvador", currency: "USD" },
  { code: "GQ", country: "Equatorial Guinea", currency: "USD" },
  { code: "ER", country: "Eritrea", currency: "USD" },
  { code: "EE", country: "Estonia", currency: "EUR" },
  { code: "SZ", country: "Eswatini", currency: "USD" },
  { code: "ET", country: "Ethiopia", currency: "USD" },
  { code: "EU", country: "European Union", currency: "EUR" },
  { code: "FK", country: "Falkland Islands (Malvinas)", currency: "USD" },
  { code: "FO", country: "Faroe Islands", currency: "DKK" },
  { code: "FJ", country: "Fiji", currency: "USD" },
  { code: "FI", country: "Finland", currency: "EUR" },
  { code: "FR", country: "France", currency: "EUR" },
  { code: "GF", country: "French Guiana", currency: "EUR" },
  { code: "PF", country: "French Polynesia", currency: "USD" },
  { code: "TF", country: "French Southern Territories", currency: "EUR" },
  { code: "GA", country: "Gabon", currency: "USD" },
  { code: "GM", country: "Gambia", currency: "USD" },
  { code: "GE", country: "Georgia", currency: "USD" },
  { code: "DE", country: "Germany", currency: "EUR" },
  { code: "GH", country: "Ghana", currency: "GHS" },
  { code: "GI", country: "Gibraltar", currency: "USD" },
  { code: "GR", country: "Greece", currency: "EUR" },
  { code: "GL", country: "Greenland", currency: "DKK" },
  { code: "GD", country: "Grenada", currency: "USD" },
  { code: "GP", country: "Guadeloupe", currency: "EUR" },
  { code: "GU", country: "Guam", currency: "USD" },
  { code: "GT", country: "Guatemala", currency: "USD" },
  { code: "GG", country: "Guernsey", currency: "USD" },
  { code: "GN", country: "Guinea", currency: "USD" },
  { code: "GW", country: "Guinea-Bissau", currency: "USD" },
  { code: "GY", country: "Guyana", currency: "USD" },
  { code: "HT", country: "Haiti", currency: "USD" },
  { code: "HM", country: "Heard Island and McDonald Islands", currency: "AUD" },
  { code: "VA", country: "Holy See (Vatican City State)", currency: "EUR" },
  { code: "HN", country: "Honduras", currency: "USD" },
  { code: "HK", country: "Hong Kong", currency: "HKD" },
  { code: "HU", country: "Hungary", currency: "HUF" },
  { code: "IS", country: "Iceland", currency: "USD" },
  { code: "IN", country: "India", currency: "INR" },
  { code: "ID", country: "Indonesia", currency: "IDR" },
  { code: "IR", country: "Iran, Islamic Republic of", currency: "USD" },
  { code: "IQ", country: "Iraq", currency: "USD" },
  { code: "IE", country: "Ireland", currency: "EUR" },
  { code: "IM", country: "Isle of Man", currency: "USD" },
  { code: "IL", country: "Israel", currency: "USD" },
  { code: "IT", country: "Italy", currency: "EUR" },
  { code: "JM", country: "Jamaica", currency: "USD" },
  { code: "JP", country: "Japan", currency: "JPY" },
  { code: "JE", country: "Jersey", currency: "USD" },
  { code: "JO", country: "Jordan", currency: "USD" },
  { code: "KZ", country: "Kazakhstan", currency: "USD" },
  { code: "KE", country: "Kenya", currency: "KES" },
  { code: "KI", country: "Kiribati", currency: "USD" },
  { code: "KP", country: "Korea, Democratic People's Republic of", currency: "USD" },
  { code: "KR", country: "Korea, Republic of", currency: "KRW" },
  { code: "KW", country: "Kuwait", currency: "USD" },
  { code: "KG", country: "Kyrgyzstan", currency: "USD" },
  { code: "LA", country: "Lao People's Democratic Republic", currency: "USD" },
  { code: "LV", country: "Latvia", currency: "EUR" },
  { code: "LB", country: "Lebanon", currency: "USD" },
  { code: "LS", country: "Lesotho", currency: "USD" },
  { code: "LR", country: "Liberia", currency: "USD" },
  { code: "LY", country: "Libya", currency: "USD" },
  { code: "LI", country: "Liechtenstein", currency: "USD" },
  { code: "LT", country: "Lithuania", currency: "EUR" },
  { code: "LU", country: "Luxembourg", currency: "EUR" },
  { code: "MO", country: "Macao", currency: "USD" },
  { code: "MG", country: "Madagascar", currency: "USD" },
  { code: "MW", country: "Malawi", currency: "USD" },
  { code: "MY", country: "Malaysia", currency: "MYR" },
  { code: "MV", country: "Maldives", currency: "USD" },
  { code: "ML", country: "Mali", currency: "USD" },
  { code: "MT", country: "Malta", currency: "EUR" },
  { code: "MH", country: "Marshall Islands", currency: "USD" },
  { code: "MQ", country: "Martinique", currency: "EUR" },
  { code: "MR", country: "Mauritania", currency: "USD" },
  { code: "MU", country: "Mauritius", currency: "USD" },
  { code: "YT", country: "Mayotte", currency: "EUR" },
  { code: "MX", country: "Mexico", currency: "MXN" },
  { code: "FM", country: "Micronesia, Federated States of", currency: "USD" },
  { code: "MD", country: "Moldova, Republic of", currency: "USD" },
  { code: "MC", country: "Monaco", currency: "EUR" },
  { code: "MN", country: "Mongolia", currency: "USD" },
  { code: "ME", country: "Montenegro", currency: "EUR" },
  { code: "MS", country: "Montserrat", currency: "USD" },
  { code: "MA", country: "Morocco", currency: "USD" },
  { code: "MZ", country: "Mozambique", currency: "USD" },
  { code: "MM", country: "Myanmar", currency: "USD" },
  { code: "NA", country: "Namibia", currency: "USD" },
  { code: "NR", country: "Nauru", currency: "USD" },
  { code: "NP", country: "Nepal", currency: "USD" },
  { code: "NL", country: "Netherlands", currency: "EUR" },
  { code: "NC", country: "New Caledonia", currency: "USD" },
  { code: "NZ", country: "New Zealand", currency: "USD" },
  { code: "NI", country: "Nicaragua", currency: "USD" },
  { code: "NE", country: "Niger", currency: "USD" },
  { code: "NG", country: "Nigeria", currency: "NGN" },
  { code: "NU", country: "Niue", currency: "USD" },
  { code: "NF", country: "Norfolk Island", currency: "AUD" },
  { code: "MK", country: "North Macedonia", currency: "USD" },
  { code: "MP", country: "Northern Mariana Islands", currency: "USD" },
  { code: "NO", country: "Norway", currency: "NOK" },
  { code: "OM", country: "Oman", currency: "USD" },
  { code: "PK", country: "Pakistan", currency: "USD" },
  { code: "PW", country: "Palau", currency: "USD" },
  { code: "PS", country: "Palestine, State of", currency: "USD" },
  { code: "PA", country: "Panama", currency: "USD" },
  { code: "PG", country: "Papua New Guinea", currency: "USD" },
  { code: "PY", country: "Paraguay", currency: "USD" },
  { code: "PE", country: "Peru", currency: "PEN" },
  { code: "PH", country: "Philippines", currency: "PHP" },
  { code: "PN", country: "Pitcairn", currency: "USD" },
  { code: "PL", country: "Poland", currency: "PLN" },
  { code: "PT", country: "Portugal", currency: "EUR" },
  { code: "PR", country: "Puerto Rico", currency: "USD" },
  { code: "QA", country: "Qatar", currency: "USD" },
  { code: "RO", country: "Romania", currency: "USD" },
  { code: "RU", country: "Russian Federation", currency: "USD" },
  { code: "RW", country: "Rwanda", currency: "USD" },
  { code: "RE", country: "Réunion", currency: "EUR" },
  { code: "BL", country: "Saint Barthélemy", currency: "EUR" },
  { code: "SH", country: "Saint Helena, Ascension and Tristan da Cunha", currency: "USD" },
  { code: "KN", country: "Saint Kitts and Nevis", currency: "USD" },
  { code: "LC", country: "Saint Lucia", currency: "USD" },
  { code: "MF", country: "Saint Martin (French part)", currency: "EUR" },
  { code: "PM", country: "Saint Pierre and Miquelon", currency: "EUR" },
  { code: "VC", country: "Saint Vincent and the Grenadines", currency: "USD" },
  { code: "WS", country: "Samoa", currency: "USD" },
  { code: "SM", country: "San Marino", currency: "EUR" },
  { code: "ST", country: "Sao Tome and Principe", currency: "USD" },
  { code: "SA", country: "Saudi Arabia", currency: "SAR" },
  { code: "SN", country: "Senegal", currency: "USD" },
  { code: "RS", country: "Serbia", currency: "USD" },
  { code: "SC", country: "Seychelles", currency: "USD" },
  { code: "SL", country: "Sierra Leone", currency: "USD" },
  { code: "SG", country: "Singapore", currency: "SGD" },
  { code: "SX", country: "Sint Maarten (Dutch part)", currency: "USD" },
  { code: "SK", country: "Slovakia", currency: "EUR" },
  { code: "SI", country: "Slovenia", currency: "EUR" },
  { code: "SB", country: "Solomon Islands", currency: "USD" },
  { code: "SO", country: "Somalia", currency: "USD" },
  { code: "ZA", country: "South Africa", currency: "ZAR" },
  { code: "GS", country: "South Georgia and the South Sandwich Islands", currency: "USD" },
  { code: "SS", country: "South Sudan", currency: "USD" },
  { code: "ES", country: "Spain", currency: "EUR" },
  { code: "LK", country: "Sri Lanka", currency: "USD" },
  { code: "SD", country: "Sudan", currency: "USD" },
  { code: "SR", country: "Suriname", currency: "USD" },
  { code: "SJ", country: "Svalbard and Jan Mayen", currency: "NOK" },
  { code: "SE", country: "Sweden", currency: "SEK" },
  { code: "CH", country: "Switzerland", currency: "CHF" },
  { code: "SY", country: "Syrian Arab Republic", currency: "USD" },
  { code: "TW", country: "Taiwan, Province of China", currency: "USD" },
  { code: "TJ", country: "Tajikistan", currency: "USD" },
  { code: "TZ", country: "Tanzania, United Republic of", currency: "USD" },
  { code: "TH", country: "Thailand", currency: "THB" },
  { code: "TL", country: "Timor-Leste", currency: "USD" },
  { code: "TG", country: "Togo", currency: "USD" },
  { code: "TK", country: "Tokelau", currency: "USD" },
  { code: "TO", country: "Tonga", currency: "USD" },
  { code: "TT", country: "Trinidad and Tobago", currency: "USD" },
  { code: "TN", country: "Tunisia", currency: "USD" },
  { code: "TM", country: "Turkmenistan", currency: "USD" },
  { code: "TC", country: "Turks and Caicos Islands", currency: "USD" },
  { code: "TV", country: "Tuvalu", currency: "USD" },
  { code: "TR", country: "Türkiye", currency: "TRY" },
  { code: "UG", country: "Uganda", currency: "USD" },
  { code: "UA", country: "Ukraine", currency: "USD" },
  { code: "AE", country: "United Arab Emirates", currency: "AED" },
  { code: "GB", country: "United Kingdom", currency: "GBP" },
  { code: "US", country: "United States", currency: "USD" },
  { code: "UM", country: "United States Minor Outlying Islands", currency: "USD" },
  { code: "UY", country: "Uruguay", currency: "USD" },
  { code: "UZ", country: "Uzbekistan", currency: "USD" },
  { code: "VU", country: "Vanuatu", currency: "USD" },
  { code: "VE", country: "Venezuela, Bolivarian Republic of", currency: "USD" },
  { code: "VN", country: "Viet Nam", currency: "USD" },
  { code: "VG", country: "Virgin Islands, British", currency: "USD" },
  { code: "VI", country: "Virgin Islands, U.S.", currency: "USD" },
  { code: "WF", country: "Wallis and Futuna", currency: "USD" },
  { code: "EH", country: "Western Sahara", currency: "USD" },
  { code: "YE", country: "Yemen", currency: "USD" },
  { code: "ZM", country: "Zambia", currency: "USD" },
  { code: "ZW", country: "Zimbabwe", currency: "USD" },
  { code: "AX", country: "Åland Islands", currency: "EUR" },
];

export const supportedCurrencies: SupportedCurrency[] = [
  { code: "AED", name: "United Arab Emirates dirham" },
  { code: "ARS", name: "Argentine peso" },
  { code: "AUD", name: "Australian dollar" },
  { code: "BRL", name: "Brazilian real" },
  { code: "CAD", name: "Canadian dollar" },
  { code: "CHF", name: "Swiss franc" },
  { code: "CLP", name: "Chilean peso" },
  { code: "CNY", name: "Chinese yuan" },
  { code: "COP", name: "Colombian peso" },
  { code: "CZK", name: "Czech koruna" },
  { code: "DKK", name: "Danish krone" },
  { code: "EGP", name: "Egyptian pound" },
  { code: "EUR", name: "Euro" },
  { code: "GBP", name: "British pound" },
  { code: "GHS", name: "Ghanaian cedi" },
  { code: "HKD", name: "Hong Kong dollar" },
  { code: "HUF", name: "Hungarian forint" },
  { code: "IDR", name: "Indonesian rupiah" },
  { code: "INR", name: "Indian rupee" },
  { code: "JPY", name: "Japanese yen" },
  { code: "KES", name: "Kenyan shilling" },
  { code: "KRW", name: "South Korean won" },
  { code: "MXN", name: "Mexican peso" },
  { code: "MYR", name: "Malaysian ringgit" },
  { code: "NGN", name: "Nigerian naira" },
  { code: "NOK", name: "Norwegian krone" },
  { code: "PEN", name: "Peruvian sol" },
  { code: "PHP", name: "Philippine peso" },
  { code: "PLN", name: "Polish zloty" },
  { code: "SAR", name: "Saudi riyal" },
  { code: "SEK", name: "Swedish krona" },
  { code: "SGD", name: "Singapore dollar" },
  { code: "THB", name: "Thai baht" },
  { code: "TRY", name: "Turkish lira" },
  { code: "USD", name: "United States dollar" },
  { code: "ZAR", name: "South African rand" },
];
