export type SupportedRegion = {
  code: string;
  country: string;
  currency: string;
};

export type SupportedCurrency = {
  code: string;
  name: string;
};

// Public country/territory selector catalog for display-market preferences.
// Includes ISO 3166-1 countries and territories plus the existing EU market option.
// Currency values are local/default display currencies for each visible market where reasonably possible.
export const supportedRegions: SupportedRegion[] = [
  { code: "AF", country: "Afghanistan", currency: "AFN" },
  { code: "AL", country: "Albania", currency: "ALL" },
  { code: "DZ", country: "Algeria", currency: "DZD" },
  { code: "AS", country: "American Samoa", currency: "USD" },
  { code: "AD", country: "Andorra", currency: "EUR" },
  { code: "AO", country: "Angola", currency: "AOA" },
  { code: "AI", country: "Anguilla", currency: "XCD" },
  { code: "AQ", country: "Antarctica", currency: "USD" },
  { code: "AG", country: "Antigua and Barbuda", currency: "XCD" },
  { code: "AR", country: "Argentina", currency: "ARS" },
  { code: "AM", country: "Armenia", currency: "AMD" },
  { code: "AW", country: "Aruba", currency: "AWG" },
  { code: "AU", country: "Australia", currency: "AUD" },
  { code: "AT", country: "Austria", currency: "EUR" },
  { code: "AZ", country: "Azerbaijan", currency: "AZN" },
  { code: "BS", country: "Bahamas", currency: "BSD" },
  { code: "BH", country: "Bahrain", currency: "BHD" },
  { code: "BD", country: "Bangladesh", currency: "BDT" },
  { code: "BB", country: "Barbados", currency: "BBD" },
  { code: "BY", country: "Belarus", currency: "BYN" },
  { code: "BE", country: "Belgium", currency: "EUR" },
  { code: "BZ", country: "Belize", currency: "BZD" },
  { code: "BJ", country: "Benin", currency: "XOF" },
  { code: "BM", country: "Bermuda", currency: "BMD" },
  { code: "BT", country: "Bhutan", currency: "BTN" },
  { code: "BO", country: "Bolivia, Plurinational State of", currency: "BOB" },
  { code: "BQ", country: "Bonaire, Sint Eustatius and Saba", currency: "USD" },
  { code: "BA", country: "Bosnia and Herzegovina", currency: "BAM" },
  { code: "BW", country: "Botswana", currency: "BWP" },
  { code: "BV", country: "Bouvet Island", currency: "NOK" },
  { code: "BR", country: "Brazil", currency: "BRL" },
  { code: "IO", country: "British Indian Ocean Territory", currency: "USD" },
  { code: "BN", country: "Brunei Darussalam", currency: "BND" },
  { code: "BG", country: "Bulgaria", currency: "EUR" },
  { code: "BF", country: "Burkina Faso", currency: "XOF" },
  { code: "BI", country: "Burundi", currency: "BIF" },
  { code: "CV", country: "Cabo Verde", currency: "CVE" },
  { code: "KH", country: "Cambodia", currency: "KHR" },
  { code: "CM", country: "Cameroon", currency: "XAF" },
  { code: "CA", country: "Canada", currency: "CAD" },
  { code: "KY", country: "Cayman Islands", currency: "KYD" },
  { code: "CF", country: "Central African Republic", currency: "XAF" },
  { code: "TD", country: "Chad", currency: "XAF" },
  { code: "CL", country: "Chile", currency: "CLP" },
  { code: "CN", country: "China", currency: "CNY" },
  { code: "CX", country: "Christmas Island", currency: "AUD" },
  { code: "CC", country: "Cocos (Keeling) Islands", currency: "AUD" },
  { code: "CO", country: "Colombia", currency: "COP" },
  { code: "KM", country: "Comoros", currency: "KMF" },
  { code: "CG", country: "Congo", currency: "XAF" },
  { code: "CD", country: "Congo, The Democratic Republic of the", currency: "CDF" },
  { code: "CK", country: "Cook Islands", currency: "NZD" },
  { code: "CR", country: "Costa Rica", currency: "CRC" },
  { code: "HR", country: "Croatia", currency: "EUR" },
  { code: "CU", country: "Cuba", currency: "CUP" },
  { code: "CW", country: "Curaçao", currency: "XCG" },
  { code: "CY", country: "Cyprus", currency: "EUR" },
  { code: "CZ", country: "Czechia", currency: "CZK" },
  { code: "CI", country: "Côte d'Ivoire", currency: "XOF" },
  { code: "DK", country: "Denmark", currency: "DKK" },
  { code: "DJ", country: "Djibouti", currency: "DJF" },
  { code: "DM", country: "Dominica", currency: "XCD" },
  { code: "DO", country: "Dominican Republic", currency: "DOP" },
  { code: "EC", country: "Ecuador", currency: "USD" },
  { code: "EG", country: "Egypt", currency: "EGP" },
  { code: "SV", country: "El Salvador", currency: "USD" },
  { code: "GQ", country: "Equatorial Guinea", currency: "XAF" },
  { code: "ER", country: "Eritrea", currency: "ERN" },
  { code: "EE", country: "Estonia", currency: "EUR" },
  { code: "SZ", country: "Eswatini", currency: "SZL" },
  { code: "ET", country: "Ethiopia", currency: "ETB" },
  { code: "EU", country: "European Union", currency: "EUR" },
  { code: "FK", country: "Falkland Islands (Malvinas)", currency: "FKP" },
  { code: "FO", country: "Faroe Islands", currency: "DKK" },
  { code: "FJ", country: "Fiji", currency: "FJD" },
  { code: "FI", country: "Finland", currency: "EUR" },
  { code: "FR", country: "France", currency: "EUR" },
  { code: "GF", country: "French Guiana", currency: "EUR" },
  { code: "PF", country: "French Polynesia", currency: "XPF" },
  { code: "TF", country: "French Southern Territories", currency: "EUR" },
  { code: "GA", country: "Gabon", currency: "XAF" },
  { code: "GM", country: "Gambia", currency: "GMD" },
  { code: "GE", country: "Georgia", currency: "GEL" },
  { code: "DE", country: "Germany", currency: "EUR" },
  { code: "GH", country: "Ghana", currency: "GHS" },
  { code: "GI", country: "Gibraltar", currency: "GIP" },
  { code: "GR", country: "Greece", currency: "EUR" },
  { code: "GL", country: "Greenland", currency: "DKK" },
  { code: "GD", country: "Grenada", currency: "XCD" },
  { code: "GP", country: "Guadeloupe", currency: "EUR" },
  { code: "GU", country: "Guam", currency: "USD" },
  { code: "GT", country: "Guatemala", currency: "GTQ" },
  { code: "GG", country: "Guernsey", currency: "GBP" },
  { code: "GN", country: "Guinea", currency: "GNF" },
  { code: "GW", country: "Guinea-Bissau", currency: "XOF" },
  { code: "GY", country: "Guyana", currency: "GYD" },
  { code: "HT", country: "Haiti", currency: "HTG" },
  { code: "HM", country: "Heard Island and McDonald Islands", currency: "AUD" },
  { code: "VA", country: "Holy See (Vatican City State)", currency: "EUR" },
  { code: "HN", country: "Honduras", currency: "HNL" },
  { code: "HK", country: "Hong Kong", currency: "HKD" },
  { code: "HU", country: "Hungary", currency: "HUF" },
  { code: "IS", country: "Iceland", currency: "ISK" },
  { code: "IN", country: "India", currency: "INR" },
  { code: "ID", country: "Indonesia", currency: "IDR" },
  { code: "IR", country: "Iran, Islamic Republic of", currency: "IRR" },
  { code: "IQ", country: "Iraq", currency: "IQD" },
  { code: "IE", country: "Ireland", currency: "EUR" },
  { code: "IM", country: "Isle of Man", currency: "GBP" },
  { code: "IL", country: "Israel", currency: "ILS" },
  { code: "IT", country: "Italy", currency: "EUR" },
  { code: "JM", country: "Jamaica", currency: "JMD" },
  { code: "JP", country: "Japan", currency: "JPY" },
  { code: "JE", country: "Jersey", currency: "GBP" },
  { code: "JO", country: "Jordan", currency: "JOD" },
  { code: "KZ", country: "Kazakhstan", currency: "KZT" },
  { code: "KE", country: "Kenya", currency: "KES" },
  { code: "KI", country: "Kiribati", currency: "AUD" },
  { code: "KP", country: "Korea, Democratic People's Republic of", currency: "KPW" },
  { code: "KR", country: "Korea, Republic of", currency: "KRW" },
  { code: "KW", country: "Kuwait", currency: "KWD" },
  { code: "KG", country: "Kyrgyzstan", currency: "KGS" },
  { code: "LA", country: "Lao People's Democratic Republic", currency: "LAK" },
  { code: "LV", country: "Latvia", currency: "EUR" },
  { code: "LB", country: "Lebanon", currency: "LBP" },
  { code: "LS", country: "Lesotho", currency: "LSL" },
  { code: "LR", country: "Liberia", currency: "LRD" },
  { code: "LY", country: "Libya", currency: "LYD" },
  { code: "LI", country: "Liechtenstein", currency: "CHF" },
  { code: "LT", country: "Lithuania", currency: "EUR" },
  { code: "LU", country: "Luxembourg", currency: "EUR" },
  { code: "MO", country: "Macao", currency: "MOP" },
  { code: "MG", country: "Madagascar", currency: "MGA" },
  { code: "MW", country: "Malawi", currency: "MWK" },
  { code: "MY", country: "Malaysia", currency: "MYR" },
  { code: "MV", country: "Maldives", currency: "MVR" },
  { code: "ML", country: "Mali", currency: "XOF" },
  { code: "MT", country: "Malta", currency: "EUR" },
  { code: "MH", country: "Marshall Islands", currency: "USD" },
  { code: "MQ", country: "Martinique", currency: "EUR" },
  { code: "MR", country: "Mauritania", currency: "MRU" },
  { code: "MU", country: "Mauritius", currency: "MUR" },
  { code: "YT", country: "Mayotte", currency: "EUR" },
  { code: "MX", country: "Mexico", currency: "MXN" },
  { code: "FM", country: "Micronesia, Federated States of", currency: "USD" },
  { code: "MD", country: "Moldova, Republic of", currency: "MDL" },
  { code: "MC", country: "Monaco", currency: "EUR" },
  { code: "MN", country: "Mongolia", currency: "MNT" },
  { code: "ME", country: "Montenegro", currency: "EUR" },
  { code: "MS", country: "Montserrat", currency: "XCD" },
  { code: "MA", country: "Morocco", currency: "MAD" },
  { code: "MZ", country: "Mozambique", currency: "MZN" },
  { code: "MM", country: "Myanmar", currency: "MMK" },
  { code: "NA", country: "Namibia", currency: "NAD" },
  { code: "NR", country: "Nauru", currency: "AUD" },
  { code: "NP", country: "Nepal", currency: "NPR" },
  { code: "NL", country: "Netherlands", currency: "EUR" },
  { code: "NC", country: "New Caledonia", currency: "XPF" },
  { code: "NZ", country: "New Zealand", currency: "NZD" },
  { code: "NI", country: "Nicaragua", currency: "NIO" },
  { code: "NE", country: "Niger", currency: "XOF" },
  { code: "NG", country: "Nigeria", currency: "NGN" },
  { code: "NU", country: "Niue", currency: "NZD" },
  { code: "NF", country: "Norfolk Island", currency: "AUD" },
  { code: "MK", country: "North Macedonia", currency: "MKD" },
  { code: "MP", country: "Northern Mariana Islands", currency: "USD" },
  { code: "NO", country: "Norway", currency: "NOK" },
  { code: "OM", country: "Oman", currency: "OMR" },
  { code: "PK", country: "Pakistan", currency: "PKR" },
  { code: "PW", country: "Palau", currency: "USD" },
  { code: "PS", country: "Palestine, State of", currency: "ILS" },
  { code: "PA", country: "Panama", currency: "PAB" },
  { code: "PG", country: "Papua New Guinea", currency: "PGK" },
  { code: "PY", country: "Paraguay", currency: "PYG" },
  { code: "PE", country: "Peru", currency: "PEN" },
  { code: "PH", country: "Philippines", currency: "PHP" },
  { code: "PN", country: "Pitcairn", currency: "NZD" },
  { code: "PL", country: "Poland", currency: "PLN" },
  { code: "PT", country: "Portugal", currency: "EUR" },
  { code: "PR", country: "Puerto Rico", currency: "USD" },
  { code: "QA", country: "Qatar", currency: "QAR" },
  { code: "RO", country: "Romania", currency: "RON" },
  { code: "RU", country: "Russian Federation", currency: "RUB" },
  { code: "RW", country: "Rwanda", currency: "RWF" },
  { code: "RE", country: "Réunion", currency: "EUR" },
  { code: "BL", country: "Saint Barthélemy", currency: "EUR" },
  { code: "SH", country: "Saint Helena, Ascension and Tristan da Cunha", currency: "SHP" },
  { code: "KN", country: "Saint Kitts and Nevis", currency: "XCD" },
  { code: "LC", country: "Saint Lucia", currency: "XCD" },
  { code: "MF", country: "Saint Martin (French part)", currency: "EUR" },
  { code: "PM", country: "Saint Pierre and Miquelon", currency: "EUR" },
  { code: "VC", country: "Saint Vincent and the Grenadines", currency: "XCD" },
  { code: "WS", country: "Samoa", currency: "WST" },
  { code: "SM", country: "San Marino", currency: "EUR" },
  { code: "ST", country: "Sao Tome and Principe", currency: "STN" },
  { code: "SA", country: "Saudi Arabia", currency: "SAR" },
  { code: "SN", country: "Senegal", currency: "XOF" },
  { code: "RS", country: "Serbia", currency: "RSD" },
  { code: "SC", country: "Seychelles", currency: "SCR" },
  { code: "SL", country: "Sierra Leone", currency: "SLE" },
  { code: "SG", country: "Singapore", currency: "SGD" },
  { code: "SX", country: "Sint Maarten (Dutch part)", currency: "XCG" },
  { code: "SK", country: "Slovakia", currency: "EUR" },
  { code: "SI", country: "Slovenia", currency: "EUR" },
  { code: "SB", country: "Solomon Islands", currency: "SBD" },
  { code: "SO", country: "Somalia", currency: "SOS" },
  { code: "ZA", country: "South Africa", currency: "ZAR" },
  { code: "GS", country: "South Georgia and the South Sandwich Islands", currency: "GBP" },
  { code: "SS", country: "South Sudan", currency: "SSP" },
  { code: "ES", country: "Spain", currency: "EUR" },
  { code: "LK", country: "Sri Lanka", currency: "LKR" },
  { code: "SD", country: "Sudan", currency: "SDG" },
  { code: "SR", country: "Suriname", currency: "SRD" },
  { code: "SJ", country: "Svalbard and Jan Mayen", currency: "NOK" },
  { code: "SE", country: "Sweden", currency: "SEK" },
  { code: "CH", country: "Switzerland", currency: "CHF" },
  { code: "SY", country: "Syrian Arab Republic", currency: "SYP" },
  { code: "TW", country: "Taiwan, Province of China", currency: "TWD" },
  { code: "TJ", country: "Tajikistan", currency: "TJS" },
  { code: "TZ", country: "Tanzania, United Republic of", currency: "TZS" },
  { code: "TH", country: "Thailand", currency: "THB" },
  { code: "TL", country: "Timor-Leste", currency: "USD" },
  { code: "TG", country: "Togo", currency: "XOF" },
  { code: "TK", country: "Tokelau", currency: "NZD" },
  { code: "TO", country: "Tonga", currency: "TOP" },
  { code: "TT", country: "Trinidad and Tobago", currency: "TTD" },
  { code: "TN", country: "Tunisia", currency: "TND" },
  { code: "TM", country: "Turkmenistan", currency: "TMT" },
  { code: "TC", country: "Turks and Caicos Islands", currency: "USD" },
  { code: "TV", country: "Tuvalu", currency: "AUD" },
  { code: "TR", country: "Türkiye", currency: "TRY" },
  { code: "UG", country: "Uganda", currency: "UGX" },
  { code: "UA", country: "Ukraine", currency: "UAH" },
  { code: "AE", country: "United Arab Emirates", currency: "AED" },
  { code: "GB", country: "United Kingdom", currency: "GBP" },
  { code: "US", country: "United States", currency: "USD" },
  { code: "UM", country: "United States Minor Outlying Islands", currency: "USD" },
  { code: "UY", country: "Uruguay", currency: "UYU" },
  { code: "UZ", country: "Uzbekistan", currency: "UZS" },
  { code: "VU", country: "Vanuatu", currency: "VUV" },
  { code: "VE", country: "Venezuela, Bolivarian Republic of", currency: "VES" },
  { code: "VN", country: "Viet Nam", currency: "VND" },
  { code: "VG", country: "Virgin Islands, British", currency: "USD" },
  { code: "VI", country: "Virgin Islands, U.S.", currency: "USD" },
  { code: "WF", country: "Wallis and Futuna", currency: "XPF" },
  { code: "EH", country: "Western Sahara", currency: "MAD" },
  { code: "YE", country: "Yemen", currency: "YER" },
  { code: "ZM", country: "Zambia", currency: "ZMW" },
  { code: "ZW", country: "Zimbabwe", currency: "ZWG" },
  { code: "AX", country: "Åland Islands", currency: "EUR" },
];

export const supportedCurrencies: SupportedCurrency[] = [
  { code: "AED", name: "United Arab Emirates Dirham" },
  { code: "AFN", name: "Afghan Afghani" },
  { code: "ALL", name: "Albanian Lek" },
  { code: "AMD", name: "Armenian Dram" },
  { code: "AOA", name: "Angolan Kwanza" },
  { code: "ARS", name: "Argentine Peso" },
  { code: "AUD", name: "Australian Dollar" },
  { code: "AWG", name: "Aruban Florin" },
  { code: "AZN", name: "Azerbaijani Manat" },
  { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark" },
  { code: "BBD", name: "Barbadian Dollar" },
  { code: "BDT", name: "Bangladeshi Taka" },
  { code: "BHD", name: "Bahraini Dinar" },
  { code: "BIF", name: "Burundian Franc" },
  { code: "BMD", name: "Bermudan Dollar" },
  { code: "BND", name: "Brunei Dollar" },
  { code: "BOB", name: "Bolivian Boliviano" },
  { code: "BRL", name: "Brazilian Real" },
  { code: "BSD", name: "Bahamian Dollar" },
  { code: "BTN", name: "Bhutanese Ngultrum" },
  { code: "BWP", name: "Botswanan Pula" },
  { code: "BYN", name: "Belarusian Ruble" },
  { code: "BZD", name: "Belize Dollar" },
  { code: "CAD", name: "Canadian Dollar" },
  { code: "CDF", name: "Congolese Franc" },
  { code: "CHF", name: "Swiss Franc" },
  { code: "CLP", name: "Chilean Peso" },
  { code: "CNY", name: "Chinese Yuan" },
  { code: "COP", name: "Colombian Peso" },
  { code: "CRC", name: "Costa Rican Colón" },
  { code: "CUP", name: "Cuban Peso" },
  { code: "CVE", name: "Cape Verdean Escudo" },
  { code: "CZK", name: "Czech Koruna" },
  { code: "DJF", name: "Djiboutian Franc" },
  { code: "DKK", name: "Danish Krone" },
  { code: "DOP", name: "Dominican Peso" },
  { code: "DZD", name: "Algerian Dinar" },
  { code: "EGP", name: "Egyptian Pound" },
  { code: "ERN", name: "Eritrean Nakfa" },
  { code: "ETB", name: "Ethiopian Birr" },
  { code: "EUR", name: "Euro" },
  { code: "FJD", name: "Fijian Dollar" },
  { code: "FKP", name: "Falkland Islands Pound" },
  { code: "GBP", name: "British Pound" },
  { code: "GEL", name: "Georgian Lari" },
  { code: "GHS", name: "Ghanaian Cedi" },
  { code: "GIP", name: "Gibraltar Pound" },
  { code: "GMD", name: "Gambian Dalasi" },
  { code: "GNF", name: "Guinean Franc" },
  { code: "GTQ", name: "Guatemalan Quetzal" },
  { code: "GYD", name: "Guyanaese Dollar" },
  { code: "HKD", name: "Hong Kong Dollar" },
  { code: "HNL", name: "Honduran Lempira" },
  { code: "HTG", name: "Haitian Gourde" },
  { code: "HUF", name: "Hungarian Forint" },
  { code: "IDR", name: "Indonesian Rupiah" },
  { code: "ILS", name: "Israeli New Shekel" },
  { code: "INR", name: "Indian Rupee" },
  { code: "IQD", name: "Iraqi Dinar" },
  { code: "IRR", name: "Iranian Rial" },
  { code: "ISK", name: "Icelandic Króna" },
  { code: "JMD", name: "Jamaican Dollar" },
  { code: "JOD", name: "Jordanian Dinar" },
  { code: "JPY", name: "Japanese Yen" },
  { code: "KES", name: "Kenyan Shilling" },
  { code: "KGS", name: "Kyrgyz Som" },
  { code: "KHR", name: "Cambodian Riel" },
  { code: "KMF", name: "Comorian Franc" },
  { code: "KPW", name: "North Korean Won" },
  { code: "KRW", name: "South Korean Won" },
  { code: "KWD", name: "Kuwaiti Dinar" },
  { code: "KYD", name: "Cayman Islands Dollar" },
  { code: "KZT", name: "Kazakhstani Tenge" },
  { code: "LAK", name: "Laotian Kip" },
  { code: "LBP", name: "Lebanese Pound" },
  { code: "LKR", name: "Sri Lankan Rupee" },
  { code: "LRD", name: "Liberian Dollar" },
  { code: "LSL", name: "Lesotho Loti" },
  { code: "LYD", name: "Libyan Dinar" },
  { code: "MAD", name: "Moroccan Dirham" },
  { code: "MDL", name: "Moldovan Leu" },
  { code: "MGA", name: "Malagasy Ariary" },
  { code: "MKD", name: "Macedonian Denar" },
  { code: "MMK", name: "Myanmar Kyat" },
  { code: "MNT", name: "Mongolian Tugrik" },
  { code: "MOP", name: "Macanese Pataca" },
  { code: "MRU", name: "Mauritanian Ouguiya" },
  { code: "MUR", name: "Mauritian Rupee" },
  { code: "MVR", name: "Maldivian Rufiyaa" },
  { code: "MWK", name: "Malawian Kwacha" },
  { code: "MXN", name: "Mexican Peso" },
  { code: "MYR", name: "Malaysian Ringgit" },
  { code: "MZN", name: "Mozambican Metical" },
  { code: "NAD", name: "Namibian Dollar" },
  { code: "NGN", name: "Nigerian Naira" },
  { code: "NIO", name: "Nicaraguan Córdoba" },
  { code: "NOK", name: "Norwegian Krone" },
  { code: "NPR", name: "Nepalese Rupee" },
  { code: "NZD", name: "New Zealand Dollar" },
  { code: "OMR", name: "Omani Rial" },
  { code: "PAB", name: "Panamanian Balboa" },
  { code: "PEN", name: "Peruvian Sol" },
  { code: "PGK", name: "Papua New Guinean Kina" },
  { code: "PHP", name: "Philippine Peso" },
  { code: "PKR", name: "Pakistani Rupee" },
  { code: "PLN", name: "Polish Zloty" },
  { code: "PYG", name: "Paraguayan Guarani" },
  { code: "QAR", name: "Qatari Riyal" },
  { code: "RON", name: "Romanian Leu" },
  { code: "RSD", name: "Serbian Dinar" },
  { code: "RUB", name: "Russian Ruble" },
  { code: "RWF", name: "Rwandan Franc" },
  { code: "SAR", name: "Saudi Riyal" },
  { code: "SBD", name: "Solomon Islands Dollar" },
  { code: "SCR", name: "Seychellois Rupee" },
  { code: "SDG", name: "Sudanese Pound" },
  { code: "SEK", name: "Swedish Krona" },
  { code: "SGD", name: "Singapore Dollar" },
  { code: "SHP", name: "St. Helena Pound" },
  { code: "SLE", name: "Sierra Leonean Leone" },
  { code: "SOS", name: "Somali Shilling" },
  { code: "SRD", name: "Surinamese Dollar" },
  { code: "SSP", name: "South Sudanese Pound" },
  { code: "STN", name: "São Tomé & Príncipe Dobra" },
  { code: "SYP", name: "Syrian Pound" },
  { code: "SZL", name: "Swazi Lilangeni" },
  { code: "THB", name: "Thai Baht" },
  { code: "TJS", name: "Tajikistani Somoni" },
  { code: "TMT", name: "Turkmenistani Manat" },
  { code: "TND", name: "Tunisian Dinar" },
  { code: "TOP", name: "Tongan Paʻanga" },
  { code: "TRY", name: "Turkish Lira" },
  { code: "TTD", name: "Trinidad & Tobago Dollar" },
  { code: "TWD", name: "New Taiwan Dollar" },
  { code: "TZS", name: "Tanzanian Shilling" },
  { code: "UAH", name: "Ukrainian Hryvnia" },
  { code: "UGX", name: "Ugandan Shilling" },
  { code: "USD", name: "US Dollar" },
  { code: "UYU", name: "Uruguayan Peso" },
  { code: "UZS", name: "Uzbekistani Som" },
  { code: "VES", name: "Venezuelan Bolívar" },
  { code: "VND", name: "Vietnamese Dong" },
  { code: "VUV", name: "Vanuatu Vatu" },
  { code: "WST", name: "Samoan Tala" },
  { code: "XAF", name: "Central African CFA Franc" },
  { code: "XCD", name: "East Caribbean Dollar" },
  { code: "XCG", name: "Caribbean Guilder" },
  { code: "XOF", name: "West African CFA Franc" },
  { code: "XPF", name: "CFP Franc" },
  { code: "YER", name: "Yemeni Rial" },
  { code: "ZAR", name: "South African Rand" },
  { code: "ZMW", name: "Zambian Kwacha" },
  { code: "ZWG", name: "Zimbabwean Gold" },
];
