import assert from "node:assert/strict";import test from "node:test";import { DuplicateSavedItemError,SavedItemNotFoundError } from "@/services/savedRecentService";import { createSavedHandlers } from "./route";

import { Prisma } from "@/generated/prisma/client";
import type { createUserSavedItem } from "@/services/savedRecentService";
const createFixture: typeof createUserSavedItem = async (userId, input) => {
  const base = { id: "1", userId, createdAt: new Date("2026-09-12T00:00:00Z") };
  if (input.type === "flight") return { ...base, ...input, payload: {}, flightNumber: input.flightNumber ?? null, departureTime: new Date(input.departureTime), arrivalTime: new Date(input.arrivalTime), price: new Prisma.Decimal(input.price) };
  if (input.type === "hotel") return { ...base, ...input, payload: {}, checkIn: new Date(input.checkIn), checkOut: new Date(input.checkOut), totalPrice: new Prisma.Decimal(input.totalPrice) };
  if (input.type === "search") return { ...base, type: "FLIGHT", label: null, origin: null, destination: input.destination ?? null, checkIn: null, checkOut: null, query: {} };
  return assert.fail("Unexpected car fixture");
};

const active=async()=>({user:{id:"u1",status:"ACTIVE"}});const req=(method="GET",body?:unknown,url="https://x/api/mobile/v1/saved")=>new Request(url,{method,body:body===undefined?undefined:JSON.stringify(body),headers:{"content-type":"application/json"}});const flight={type:"flight",provider:"p",airlineName:"A",originAirport:"LOS",destinationAirport:"LHR",departureTime:"2027-01-01T00:00:00Z",arrivalTime:"2027-01-01T06:00:00Z",price:10,currency:"USD",payload:{}};const hotel={type:"hotel",provider:"p",hotelName:"H",destination:"Paris",checkIn:"2027-01-01T00:00:00Z",checkOut:"2027-01-02T00:00:00Z",totalPrice:10,currency:"USD",payload:{}};const search={type:"search",searchType:"flight",destination:"Paris",query:{destination:"Paris"}};
test("saved rejects missing and inactive sessions",async()=>{for(const session of [async()=>null,async()=>({user:{id:"u",status:"DISABLED"}})])assert.equal((await createSavedHandlers({session,list:async()=>({items:[],summary:{flights:0,hotels:0,cars:0,searches:0,total:0}}),create:async()=>assert.fail("Unexpected creation"),remove:async()=>{}}).GET(req())).status,401);});test("saved validates filter and lists scoped user",async()=>{let user="";const h=createSavedHandlers({session:active,list:async u=>(user=u,{items:[],summary:{flights:0,hotels:0,cars:0,searches:0,total:0}}),create:async()=>assert.fail("Unexpected creation"),remove:async()=>{}});assert.equal((await h.GET(req("GET",undefined,"https://x/api/mobile/v1/saved?type=nope"))).status,400);assert.equal((await h.GET(req())).status,200);assert.equal(user,"u1");});for(const payload of [flight,hotel,search])test(`creates ${payload.type}`,async()=>assert.equal((await createSavedHandlers({session:active,list:async()=>({items:[],summary:{flights:0,hotels:0,cars:0,searches:0,total:0}}),create:createFixture,remove:async()=>{}}).POST(req("POST",payload))).status,201));test("saved rejects invalid and duplicates",async()=>{const h=createSavedHandlers({session:active,list:async()=>({items:[],summary:{flights:0,hotels:0,cars:0,searches:0,total:0}}),create:async()=>{throw new DuplicateSavedItemError("duplicate")},remove:async()=>{}});assert.equal((await h.POST(req("POST",{}))).status,400);assert.equal((await h.POST(req("POST",flight))).status,409);});test("delete is user scoped and missing is 404",async()=>{let user="";const ok=createSavedHandlers({session:active,list:async()=>({items:[],summary:{flights:0,hotels:0,cars:0,searches:0,total:0}}),create:async()=>assert.fail("Unexpected creation"),remove:async(u)=>{user=u}});assert.equal((await ok.DELETE(req("DELETE",{type:"flight",id:"other"}))).status,200);assert.equal(user,"u1");const missing=createSavedHandlers({session:active,list:async()=>({items:[],summary:{flights:0,hotels:0,cars:0,searches:0,total:0}}),create:async()=>assert.fail("Unexpected creation"),remove:async()=>{throw new SavedItemNotFoundError("missing")}});assert.equal((await missing.DELETE(req("DELETE",{type:"flight",id:"x"}))).status,404);});
