import assert from "node:assert/strict";import test from "node:test";
import { AuthRateLimitError } from "@/lib/auth-rate-limit";
import { createSetupHandler } from "./setup/route";import { createConfirmHandler } from "./confirm/route";import { createDisableHandler } from "./disable/route";
const req=(body:unknown={})=>new Request("https://test/api",{method:"POST",headers:{authorization:"Bearer mobile"},body:JSON.stringify(body)});
const auth={id:"mobile-session",reauthenticatedAt:null,assuranceLevel:"MFA",user:{id:"authoritative-user",email:"owner@example.com"}};
test("setup requires mobile bearer auth and uses only authoritative identity",async()=>{assert.equal((await createSetupHandler({authenticate:async()=>null,rateLimit:()=>{},setup:async()=>assert.fail()})(req({userId:"attacker"}))).status,401);let input:unknown;const response=await createSetupHandler({authenticate:async()=>auth,rateLimit:()=>{},setup:async value=>(input=value,{otpauthUri:"otpauth://real",manualSetupKey:"SECRET",expiresAt:"soon"})})(req({userId:"attacker",email:"evil@example.com"}));assert.equal(response.status,200);assert.deepEqual(input,{userId:"authoritative-user",email:"owner@example.com"});});
test("all 2FA handlers return Retry-After for canonical rate limits",async()=>{const rateLimit=()=>{throw new AuthRateLimitError(31)};const setup=await createSetupHandler({authenticate:async()=>auth,rateLimit,setup:async()=>assert.fail()})(req());const confirm=await createConfirmHandler({authenticate:async()=>auth,rateLimit,confirm:async()=>assert.fail(),status:async()=>assert.fail(),notify:async()=>undefined})(req({code:"123456"}));const disable=await createDisableHandler({authenticate:async()=>auth,rateLimit,verify:async()=>false,passwordHash:async()=>null,compare:async()=>false,disable:async()=>assert.fail(),status:async()=>assert.fail(),notify:async()=>undefined})(req({code:"123456"}));for(const response of [setup,confirm,disable]){assert.equal(response.status,429);assert.equal(response.headers.get("retry-after"),"31");}});
test("confirmation rejects malformed and invalid codes then enables against the mobile session",async()=>{const base={authenticate:async()=>auth,rateLimit:()=>{},status:async()=>({enabled:true,method:"TOTP",enabledAt:null,disabledAt:null,recoveryCodesRemaining:10}),notify:async()=>undefined};assert.equal((await createConfirmHandler({...base,confirm:async()=>assert.fail()})(req({code:"12x"}))).status,400);assert.equal((await createConfirmHandler({...base,confirm:async()=>null})(req({code:"123456"}))).status,400);let input:unknown;const response=await createConfirmHandler({...base,confirm:async value=>(input=value,{recoveryCodes:["one"],securityEvent:{id:"event"}} as never)})(req({code:"123456",userId:"attacker"}));assert.equal(response.status,200);assert.deepEqual(input,{userId:"authoritative-user",accountSessionId:"mobile-session",code:"123456"});assert.deepEqual((await response.json()).recoveryCodes,["one"]);});
test("disable requires verification and preserves the current mobile account-session id",async()=>{const base={authenticate:async()=>auth,rateLimit:()=>{},passwordHash:async()=>null,compare:async()=>false,status:async()=>({enabled:false,method:null,enabledAt:null,disabledAt:null,recoveryCodesRemaining:0}),notify:async()=>undefined};assert.equal((await createDisableHandler({...base,verify:async()=>false,disable:async()=>assert.fail()})(req({code:"BAD-CODE"}))).status,403);let input:unknown;const response=await createDisableHandler({...base,verify:async()=>true,disable:async value=>(input=value,{id:"event"} as never)})(req({code:"RECOVERY-CODE",userId:"attacker"}));assert.equal(response.status,200);assert.deepEqual(input,{userId:"authoritative-user",accountSessionId:"mobile-session",assuranceLevel:"MFA"});});
