import { useCallback, useState } from "react";
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { router, useFocusEffect } from "expo-router";
import { travelApi, TravelApiError, type MobileNotification } from "../../api/travelApi";
import { readSession } from "../../storage/sessionStorage";
import { FlowIcon } from "../flow/FlowIcon";
import { flowColors, flowStyles } from "../flow/flowStyles";

export function NotificationsScreen() {
  const [items, setItems] = useState<MobileNotification[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState(""); const [pendingAll, setPendingAll] = useState(false);
  const load = useCallback(async (refresh = false) => { refresh ? setRefreshing(true) : setLoading(true); setError(""); try { setItems((await travelApi.notifications()).items); } catch (cause) { if (cause instanceof TravelApiError && cause.status === 401 || !await readSession().catch(() => null)) { router.replace("/email-auth"); return; } setError(cause instanceof TravelApiError ? cause.message : "Unable to load notifications."); } finally { setLoading(false); setRefreshing(false); } }, []);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  const open = async (item: MobileNotification) => { if (!item.readAt) { setItems((current) => current.map((value) => value.id === item.id ? { ...value, readAt: new Date().toISOString() } : value)); await travelApi.markNotificationRead(item.id).catch(() => setError("Unable to mark notification as read.")); } if (item.actionPath) router.push(item.actionPath); };
  const markAll = async () => { if (pendingAll) return; setPendingAll(true); try { await travelApi.markAllNotificationsRead(); const now = new Date().toISOString(); setItems((current) => current.map((item) => ({ ...item, readAt: item.readAt ?? now }))); } catch { setError("Unable to mark all notifications as read."); } finally { setPendingAll(false); } };
  const unread = items.some((item) => !item.readAt);
  return <SafeAreaView style={flowStyles.safe} edges={["top"]}><View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={() => router.back()} style={flowStyles.iconButton}><FlowIcon name="back" /></Pressable><Text accessibilityRole="header" style={flowStyles.title}>Notifications</Text>{unread ? <Pressable accessibilityRole="button" accessibilityLabel="Mark all notifications as read" disabled={pendingAll} onPress={() => void markAll()} style={styles.markAll}><Text style={styles.link}>Mark all read</Text></Pressable> : <View style={styles.markAll} />}</View>{loading && !items.length ? <View style={styles.center}><ActivityIndicator color={flowColors.blue} /><Text style={flowStyles.meta}>Loading notifications…</Text></View> : null}{error ? <View style={styles.feedback}><Text accessibilityRole="alert" style={styles.error}>{error}</Text><Pressable accessibilityRole="button" accessibilityLabel="Retry loading notifications" onPress={() => void load()}><Text style={styles.link}>Try again</Text></Pressable></View> : null}{!loading || items.length ? <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} />} contentContainerStyle={styles.list}>{items.length ? items.map((item) => <Pressable key={item.id} accessibilityRole="button" accessibilityLabel={`${item.readAt ? "Read" : "Unread"} ${item.title}. ${item.body}`} onPress={() => void open(item)} style={[styles.card, !item.readAt && styles.unread]}><View style={styles.icon}><FlowIcon name="bell" color={item.readAt ? flowColors.muted : flowColors.blue} size={20} /></View><View style={styles.copy}><Text style={[styles.title, !item.readAt && styles.unreadTitle]}>{item.title}</Text><Text style={flowStyles.meta}>{item.body}</Text><Text style={styles.time}>{formatTime(item.createdAt)}</Text></View>{!item.readAt ? <View accessibilityLabel="Unread" style={styles.dot} /> : null}</Pressable>) : <View style={styles.center}><FlowIcon name="bell" color={flowColors.blue} size={42} /><Text style={flowStyles.value}>You’re all caught up</Text><Text style={[flowStyles.meta, styles.emptyCopy]}>Important account and travel updates will appear here.</Text></View>}</ScrollView> : null}</SafeAreaView>;
}
function formatTime(value: string) { const date = new Date(value); const elapsed = Date.now() - date.getTime(); if (elapsed < 60_000) return "Just now"; if (elapsed < 3_600_000) return `${Math.floor(elapsed / 60_000)}m ago`; if (elapsed < 86_400_000) return `${Math.floor(elapsed / 3_600_000)}h ago`; return date.toLocaleDateString(); }
const styles = StyleSheet.create({ header: { minHeight: 62, flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 8, borderBottomColor: flowColors.border, borderBottomWidth: 1 }, markAll: { minWidth: 92, minHeight: 44, alignItems: "center", justifyContent: "center", marginLeft: "auto" }, link: { color: flowColors.blue, fontWeight: "800" }, list: { padding: 14, gap: 10, flexGrow: 1 }, card: { minHeight: 92, flexDirection: "row", gap: 12, padding: 14, borderRadius: 14, borderWidth: 1, borderColor: flowColors.border, backgroundColor: "white" }, unread: { backgroundColor: "#F3F7FF", borderColor: "#BED2FA" }, icon: { width: 34, height: 34, borderRadius: 17, alignItems: "center", justifyContent: "center", backgroundColor: "#EEF4FF" }, copy: { flex: 1, gap: 4 }, title: { color: flowColors.navy, fontWeight: "600", fontSize: 16 }, unreadTitle: { fontWeight: "800" }, time: { color: flowColors.muted, fontSize: 12, marginTop: 3 }, dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: flowColors.blue, marginTop: 7 }, center: { flex: 1, minHeight: 300, alignItems: "center", justifyContent: "center", gap: 12, padding: 24 }, emptyCopy: { textAlign: "center" }, feedback: { padding: 14, flexDirection: "row", gap: 12 }, error: { color: "#A4262C", flex: 1 } });
