/**
 * Canonical, platform-neutral airport records.
 *
 * Update this literal list when airport coverage changes; web and mobile adapters both
 * consume it directly. Keep this module free of runtime imports and generated-at-runtime
 * values so it remains safe for browsers and test runners.
 */
export type SharedAirport = {
  code: string;
  city: string;
  airport: string;
  country: string;
  countryCode: string;
  latitude: number;
  longitude: number;
  priority: number;
};

export const SHARED_AIRPORTS: readonly SharedAirport[] = [
  {"code": "ATL", "city": "Atlanta", "airport": "Hartsfield-Jackson Atlanta International Airport", "country": "United States", "countryCode": "US", "latitude": 33.6407, "longitude": -84.4277, "priority": 90},
  {"code": "JFK", "city": "New York", "airport": "John F. Kennedy International Airport", "country": "United States", "countryCode": "US", "latitude": 40.6413, "longitude": -73.7781, "priority": 90},
  {"code": "LAX", "city": "Los Angeles", "airport": "Los Angeles International Airport", "country": "United States", "countryCode": "US", "latitude": 33.9416, "longitude": -118.4085, "priority": 90},
  {"code": "ORD", "city": "Chicago", "airport": "O'Hare International Airport", "country": "United States", "countryCode": "US", "latitude": 41.9742, "longitude": -87.9073, "priority": 89},
  {"code": "DFW", "city": "Dallas-Fort Worth", "airport": "Dallas/Fort Worth International Airport", "country": "United States", "countryCode": "US", "latitude": 32.8998, "longitude": -97.0403, "priority": 89},
  {"code": "DEN", "city": "Denver", "airport": "Denver International Airport", "country": "United States", "countryCode": "US", "latitude": 39.8561, "longitude": -104.6737, "priority": 89},
  {"code": "SFO", "city": "San Francisco", "airport": "San Francisco International Airport", "country": "United States", "countryCode": "US", "latitude": 37.6213, "longitude": -122.379, "priority": 88},
  {"code": "MIA", "city": "Miami", "airport": "Miami International Airport", "country": "United States", "countryCode": "US", "latitude": 25.7959, "longitude": -80.287, "priority": 88},
  {"code": "SEA", "city": "Seattle", "airport": "Seattle-Tacoma International Airport", "country": "United States", "countryCode": "US", "latitude": 47.4502, "longitude": -122.3088, "priority": 88},
  {"code": "IAH", "city": "Houston", "airport": "George Bush Intercontinental Airport", "country": "United States", "countryCode": "US", "latitude": 29.9902, "longitude": -95.3368, "priority": 98},
  {"code": "HOU", "city": "Houston", "airport": "William P. Hobby Airport", "country": "United States", "countryCode": "US", "latitude": 29.6454, "longitude": -95.2789, "priority": 86},
  {"code": "YYZ", "city": "Toronto", "airport": "Toronto Pearson International Airport", "country": "Canada", "countryCode": "CA", "latitude": 43.6777, "longitude": -79.6248, "priority": 98},
  {"code": "YTZ", "city": "Toronto", "airport": "Billy Bishop Toronto City Airport", "country": "Canada", "countryCode": "CA", "latitude": 43.6275, "longitude": -79.3962, "priority": 72},
  {"code": "YVR", "city": "Vancouver", "airport": "Vancouver International Airport", "country": "Canada", "countryCode": "CA", "latitude": 49.1951, "longitude": -123.1779, "priority": 86},
  {"code": "YUL", "city": "Montreal", "airport": "Montréal-Trudeau International Airport", "country": "Canada", "countryCode": "CA", "latitude": 45.47, "longitude": -73.7408, "priority": 86},
  {"code": "MEX", "city": "Mexico City", "airport": "Mexico City International Airport", "country": "Mexico", "countryCode": "MX", "latitude": 19.4363, "longitude": -99.0721, "priority": 85},
  {"code": "CUN", "city": "Cancún", "airport": "Cancún International Airport", "country": "Mexico", "countryCode": "MX", "latitude": 21.0365, "longitude": -86.8771, "priority": 85},
  {"code": "GDL", "city": "Guadalajara", "airport": "Miguel Hidalgo y Costilla Guadalajara International Airport", "country": "Mexico", "countryCode": "MX", "latitude": 20.5218, "longitude": -103.3112, "priority": 85},
  {"code": "GUA", "city": "Guatemala City", "airport": "La Aurora International Airport", "country": "Guatemala", "countryCode": "GT", "latitude": 14.5833, "longitude": -90.5275, "priority": 84},
  {"code": "SAL", "city": "San Salvador", "airport": "Monseñor Óscar Arnulfo Romero International Airport", "country": "El Salvador", "countryCode": "SV", "latitude": 13.4409, "longitude": -89.0557, "priority": 84},
  {"code": "SAP", "city": "San Pedro Sula", "airport": "Ramón Villeda Morales International Airport", "country": "Honduras", "countryCode": "HN", "latitude": 15.4526, "longitude": -87.9236, "priority": 84},
  {"code": "MGA", "city": "Managua", "airport": "Augusto C. Sandino International Airport", "country": "Nicaragua", "countryCode": "NI", "latitude": 12.1415, "longitude": -86.1682, "priority": 83},
  {"code": "SJO", "city": "San José", "airport": "Juan Santamaría International Airport", "country": "Costa Rica", "countryCode": "CR", "latitude": 9.9939, "longitude": -84.2088, "priority": 83},
  {"code": "PTY", "city": "Panama City", "airport": "Tocumen International Airport", "country": "Panama", "countryCode": "PA", "latitude": 9.0714, "longitude": -79.3835, "priority": 83},
  {"code": "HAV", "city": "Havana", "airport": "José Martí International Airport", "country": "Cuba", "countryCode": "CU", "latitude": 22.9892, "longitude": -82.4091, "priority": 82},
  {"code": "SDQ", "city": "Santo Domingo", "airport": "Las Américas International Airport", "country": "Dominican Republic", "countryCode": "DO", "latitude": 18.4297, "longitude": -69.6689, "priority": 82},
  {"code": "PUJ", "city": "Punta Cana", "airport": "Punta Cana International Airport", "country": "Dominican Republic", "countryCode": "DO", "latitude": 18.5674, "longitude": -68.3634, "priority": 82},
  {"code": "KIN", "city": "Kingston", "airport": "Norman Manley International Airport", "country": "Jamaica", "countryCode": "JM", "latitude": 17.9357, "longitude": -76.7875, "priority": 81},
  {"code": "MBJ", "city": "Montego Bay", "airport": "Sangster International Airport", "country": "Jamaica", "countryCode": "JM", "latitude": 18.5037, "longitude": -77.9134, "priority": 81},
  {"code": "POS", "city": "Port of Spain", "airport": "Piarco International Airport", "country": "Trinidad & Tobago", "countryCode": "TT", "latitude": 10.5954, "longitude": -61.3372, "priority": 81},
  {"code": "BGI", "city": "Bridgetown", "airport": "Grantley Adams International Airport", "country": "Barbados", "countryCode": "BB", "latitude": 13.0746, "longitude": -59.4925, "priority": 80},
  {"code": "NAS", "city": "Nassau", "airport": "Lynden Pindling International Airport", "country": "Bahamas", "countryCode": "BS", "latitude": 25.039, "longitude": -77.4662, "priority": 80},
  {"code": "ANU", "city": "St. John's", "airport": "V. C. Bird International Airport", "country": "Antigua & Barbuda", "countryCode": "AG", "latitude": 17.1367, "longitude": -61.7927, "priority": 80},
  {"code": "AUA", "city": "Oranjestad", "airport": "Queen Beatrix International Airport", "country": "Aruba", "countryCode": "AW", "latitude": 12.5014, "longitude": -70.0152, "priority": 79},
  {"code": "BOG", "city": "Bogotá", "airport": "El Dorado International Airport", "country": "Colombia", "countryCode": "CO", "latitude": 4.7016, "longitude": -74.1469, "priority": 79},
  {"code": "MDE", "city": "Medellín", "airport": "José María Córdova International Airport", "country": "Colombia", "countryCode": "CO", "latitude": 6.1645, "longitude": -75.4231, "priority": 79},
  {"code": "UIO", "city": "Quito", "airport": "Mariscal Sucre International Airport", "country": "Ecuador", "countryCode": "EC", "latitude": -0.1292, "longitude": -78.3575, "priority": 78},
  {"code": "GYE", "city": "Guayaquil", "airport": "José Joaquín de Olmedo International Airport", "country": "Ecuador", "countryCode": "EC", "latitude": -2.1574, "longitude": -79.8836, "priority": 78},
  {"code": "LIM", "city": "Lima", "airport": "Jorge Chávez International Airport", "country": "Peru", "countryCode": "PE", "latitude": -12.0219, "longitude": -77.1143, "priority": 78},
  {"code": "LPB", "city": "La Paz", "airport": "El Alto International Airport", "country": "Bolivia", "countryCode": "BO", "latitude": -16.5133, "longitude": -68.1923, "priority": 77},
  {"code": "VVI", "city": "Santa Cruz", "airport": "Viru Viru International Airport", "country": "Bolivia", "countryCode": "BO", "latitude": -17.6448, "longitude": -63.1354, "priority": 77},
  {"code": "SCL", "city": "Santiago", "airport": "Arturo Merino Benítez International Airport", "country": "Chile", "countryCode": "CL", "latitude": -33.3928, "longitude": -70.7858, "priority": 77},
  {"code": "EZE", "city": "Buenos Aires", "airport": "Ministro Pistarini International Airport", "country": "Argentina", "countryCode": "AR", "latitude": -34.8222, "longitude": -58.5358, "priority": 76},
  {"code": "AEP", "city": "Buenos Aires", "airport": "Jorge Newbery Airfield", "country": "Argentina", "countryCode": "AR", "latitude": -34.5592, "longitude": -58.4156, "priority": 76},
  {"code": "MVD", "city": "Montevideo", "airport": "Carrasco International Airport", "country": "Uruguay", "countryCode": "UY", "latitude": -34.8384, "longitude": -56.0308, "priority": 76},
  {"code": "ASU", "city": "Asunción", "airport": "Silvio Pettirossi International Airport", "country": "Paraguay", "countryCode": "PY", "latitude": -25.2399, "longitude": -57.5191, "priority": 75},
  {"code": "GRU", "city": "São Paulo", "airport": "São Paulo/Guarulhos International Airport", "country": "Brazil", "countryCode": "BR", "latitude": -23.4356, "longitude": -46.4731, "priority": 75},
  {"code": "GIG", "city": "Rio de Janeiro", "airport": "Rio de Janeiro/Galeão International Airport", "country": "Brazil", "countryCode": "BR", "latitude": -22.809999, "longitude": -43.2506, "priority": 75},
  {"code": "BSB", "city": "Brasília", "airport": "Brasília International Airport", "country": "Brazil", "countryCode": "BR", "latitude": -15.8697, "longitude": -47.9208, "priority": 74},
  {"code": "MAO", "city": "Manaus", "airport": "Eduardo Gomes International Airport", "country": "Brazil", "countryCode": "BR", "latitude": -3.0386, "longitude": -60.0497, "priority": 74},
  {"code": "LHR", "city": "London", "airport": "Heathrow Airport", "country": "United Kingdom", "countryCode": "GB", "latitude": 51.47, "longitude": -0.4543, "priority": 100},
  {"code": "LGW", "city": "London", "airport": "Gatwick Airport", "country": "United Kingdom", "countryCode": "GB", "latitude": 51.1537, "longitude": -0.1821, "priority": 88},
  {"code": "LCY", "city": "London", "airport": "London City Airport", "country": "United Kingdom", "countryCode": "GB", "latitude": 51.5053, "longitude": 0.0553, "priority": 74},
  {"code": "STN", "city": "London", "airport": "London Stansted Airport", "country": "United Kingdom", "countryCode": "GB", "latitude": 51.885, "longitude": 0.235, "priority": 72},
  {"code": "LTN", "city": "London", "airport": "London Luton Airport", "country": "United Kingdom", "countryCode": "GB", "latitude": 51.8747, "longitude": -0.3683, "priority": 70},
  {"code": "MAN", "city": "Manchester", "airport": "Manchester Airport", "country": "United Kingdom", "countryCode": "GB", "latitude": 53.3537, "longitude": -2.2749, "priority": 72},
  {"code": "DUB", "city": "Dublin", "airport": "Dublin Airport", "country": "Ireland", "countryCode": "IE", "latitude": 53.4213, "longitude": -6.2701, "priority": 72},
  {"code": "KEF", "city": "Reykjavík", "airport": "Keflavík International Airport", "country": "Iceland", "countryCode": "IS", "latitude": 63.985, "longitude": -22.6056, "priority": 71},
  {"code": "CDG", "city": "Paris", "airport": "Charles de Gaulle Airport", "country": "France", "countryCode": "FR", "latitude": 49.0097, "longitude": 2.5479, "priority": 71},
  {"code": "ORY", "city": "Paris", "airport": "Paris Orly Airport", "country": "France", "countryCode": "FR", "latitude": 48.7233, "longitude": 2.3794, "priority": 71},
  {"code": "NCE", "city": "Nice", "airport": "Nice Côte d'Azur Airport", "country": "France", "countryCode": "FR", "latitude": 43.6584, "longitude": 7.2159, "priority": 70},
  {"code": "AMS", "city": "Amsterdam", "airport": "Amsterdam Airport Schiphol", "country": "Netherlands", "countryCode": "NL", "latitude": 52.3105, "longitude": 4.7683, "priority": 70},
  {"code": "BRU", "city": "Brussels", "airport": "Brussels Airport", "country": "Belgium", "countryCode": "BE", "latitude": 50.9014, "longitude": 4.4844, "priority": 70},
  {"code": "LUX", "city": "Luxembourg", "airport": "Luxembourg Airport", "country": "Luxembourg", "countryCode": "LU", "latitude": 49.6233, "longitude": 6.2044, "priority": 69},
  {"code": "FRA", "city": "Frankfurt", "airport": "Frankfurt Airport", "country": "Germany", "countryCode": "DE", "latitude": 50.0379, "longitude": 8.5622, "priority": 69},
  {"code": "MUC", "city": "Munich", "airport": "Munich Airport", "country": "Germany", "countryCode": "DE", "latitude": 48.3538, "longitude": 11.7861, "priority": 69},
  {"code": "BER", "city": "Berlin", "airport": "Berlin Brandenburg Airport", "country": "Germany", "countryCode": "DE", "latitude": 52.3667, "longitude": 13.5033, "priority": 68},
  {"code": "DUS", "city": "Düsseldorf", "airport": "Düsseldorf Airport", "country": "Germany", "countryCode": "DE", "latitude": 51.2895, "longitude": 6.7668, "priority": 68},
  {"code": "HAM", "city": "Hamburg", "airport": "Hamburg Airport", "country": "Germany", "countryCode": "DE", "latitude": 53.6304, "longitude": 9.9882, "priority": 68},
  {"code": "CGN", "city": "Cologne", "airport": "Cologne Bonn Airport", "country": "Germany", "countryCode": "DE", "latitude": 50.8659, "longitude": 7.1427, "priority": 67},
  {"code": "STR", "city": "Stuttgart", "airport": "Stuttgart Airport", "country": "Germany", "countryCode": "DE", "latitude": 48.6899, "longitude": 9.2219, "priority": 67},
  {"code": "ZRH", "city": "Zurich", "airport": "Zurich Airport", "country": "Switzerland", "countryCode": "CH", "latitude": 47.4581, "longitude": 8.5555, "priority": 67},
  {"code": "GVA", "city": "Geneva", "airport": "Geneva Airport", "country": "Switzerland", "countryCode": "CH", "latitude": 46.2381, "longitude": 6.109, "priority": 66},
  {"code": "VIE", "city": "Vienna", "airport": "Vienna International Airport", "country": "Austria", "countryCode": "AT", "latitude": 48.1103, "longitude": 16.5697, "priority": 66},
  {"code": "MAD", "city": "Madrid", "airport": "Adolfo Suárez Madrid-Barajas Airport", "country": "Spain", "countryCode": "ES", "latitude": 40.4983, "longitude": -3.5676, "priority": 66},
  {"code": "BCN", "city": "Barcelona", "airport": "Josep Tarradellas Barcelona-El Prat Airport", "country": "Spain", "countryCode": "ES", "latitude": 41.2974, "longitude": 2.0833, "priority": 65},
  {"code": "LIS", "city": "Lisbon", "airport": "Humberto Delgado Airport", "country": "Portugal", "countryCode": "PT", "latitude": 38.7813, "longitude": -9.1359, "priority": 65},
  {"code": "OPO", "city": "Porto", "airport": "Francisco Sá Carneiro Airport", "country": "Portugal", "countryCode": "PT", "latitude": 41.2481, "longitude": -8.6814, "priority": 65},
  {"code": "FCO", "city": "Rome", "airport": "Leonardo da Vinci-Fiumicino Airport", "country": "Italy", "countryCode": "IT", "latitude": 41.8003, "longitude": 12.2389, "priority": 64},
  {"code": "MXP", "city": "Milan", "airport": "Milan Malpensa Airport", "country": "Italy", "countryCode": "IT", "latitude": 45.6306, "longitude": 8.7281, "priority": 64},
  {"code": "ATH", "city": "Athens", "airport": "Athens International Airport", "country": "Greece", "countryCode": "GR", "latitude": 37.9364, "longitude": 23.9445, "priority": 64},
  {"code": "SKG", "city": "Thessaloniki", "airport": "Thessaloniki Airport", "country": "Greece", "countryCode": "GR", "latitude": 40.5197, "longitude": 22.9709, "priority": 63},
  {"code": "LCA", "city": "Larnaca", "airport": "Larnaca International Airport", "country": "Cyprus", "countryCode": "CY", "latitude": 34.8751, "longitude": 33.6249, "priority": 63},
  {"code": "PFO", "city": "Paphos", "airport": "Paphos International Airport", "country": "Cyprus", "countryCode": "CY", "latitude": 34.718, "longitude": 32.4857, "priority": 63},
  {"code": "CPH", "city": "Copenhagen", "airport": "Copenhagen Airport", "country": "Denmark", "countryCode": "DK", "latitude": 55.618, "longitude": 12.656, "priority": 62},
  {"code": "OSL", "city": "Oslo", "airport": "Oslo Airport", "country": "Norway", "countryCode": "NO", "latitude": 60.1939, "longitude": 11.1004, "priority": 62},
  {"code": "ARN", "city": "Stockholm", "airport": "Stockholm Arlanda Airport", "country": "Sweden", "countryCode": "SE", "latitude": 59.6519, "longitude": 17.9186, "priority": 62},
  {"code": "HEL", "city": "Helsinki", "airport": "Helsinki Airport", "country": "Finland", "countryCode": "FI", "latitude": 60.3172, "longitude": 24.9633, "priority": 61},
  {"code": "WAW", "city": "Warsaw", "airport": "Warsaw Chopin Airport", "country": "Poland", "countryCode": "PL", "latitude": 52.1657, "longitude": 20.9671, "priority": 61},
  {"code": "PRG", "city": "Prague", "airport": "Václav Havel Airport Prague", "country": "Czechia", "countryCode": "CZ", "latitude": 50.1008, "longitude": 14.26, "priority": 61},
  {"code": "BUD", "city": "Budapest", "airport": "Budapest Ferenc Liszt International Airport", "country": "Hungary", "countryCode": "HU", "latitude": 47.4298, "longitude": 19.2611, "priority": 60},
  {"code": "OTP", "city": "Bucharest", "airport": "Henri Coandă International Airport", "country": "Romania", "countryCode": "RO", "latitude": 44.5711, "longitude": 26.085, "priority": 60},
  {"code": "SOF", "city": "Sofia", "airport": "Sofia Airport", "country": "Bulgaria", "countryCode": "BG", "latitude": 42.6967, "longitude": 23.4114, "priority": 60},
  {"code": "BEG", "city": "Belgrade", "airport": "Belgrade Nikola Tesla Airport", "country": "Serbia", "countryCode": "RS", "latitude": 44.8184, "longitude": 20.3091, "priority": 59},
  {"code": "ZAG", "city": "Zagreb", "airport": "Zagreb Airport", "country": "Croatia", "countryCode": "HR", "latitude": 45.7429, "longitude": 16.0688, "priority": 59},
  {"code": "LJU", "city": "Ljubljana", "airport": "Ljubljana Jože Pučnik Airport", "country": "Slovenia", "countryCode": "SI", "latitude": 46.2237, "longitude": 14.4576, "priority": 59},
  {"code": "TIA", "city": "Tirana", "airport": "Tirana International Airport", "country": "Albania", "countryCode": "AL", "latitude": 41.4147, "longitude": 19.7206, "priority": 58},
  {"code": "SKP", "city": "Skopje", "airport": "Skopje International Airport", "country": "North Macedonia", "countryCode": "MK", "latitude": 41.9616, "longitude": 21.6214, "priority": 58},
  {"code": "SJJ", "city": "Sarajevo", "airport": "Sarajevo International Airport", "country": "Bosnia & Herzegovina", "countryCode": "BA", "latitude": 43.8246, "longitude": 18.3315, "priority": 58},
  {"code": "TGD", "city": "Podgorica", "airport": "Podgorica Airport", "country": "Montenegro", "countryCode": "ME", "latitude": 42.3594, "longitude": 19.2519, "priority": 57},
  {"code": "RIX", "city": "Riga", "airport": "Riga International Airport", "country": "Latvia", "countryCode": "LV", "latitude": 56.9236, "longitude": 23.9711, "priority": 57},
  {"code": "TLL", "city": "Tallinn", "airport": "Tallinn Airport", "country": "Estonia", "countryCode": "EE", "latitude": 59.4133, "longitude": 24.8328, "priority": 57},
  {"code": "VNO", "city": "Vilnius", "airport": "Vilnius Airport", "country": "Lithuania", "countryCode": "LT", "latitude": 54.6341, "longitude": 25.2858, "priority": 56},
  {"code": "IST", "city": "Istanbul", "airport": "Istanbul Airport", "country": "Türkiye", "countryCode": "TR", "latitude": 41.2753, "longitude": 28.7519, "priority": 56},
  {"code": "SAW", "city": "Istanbul", "airport": "Sabiha Gökçen International Airport", "country": "Türkiye", "countryCode": "TR", "latitude": 40.8986, "longitude": 29.3092, "priority": 56},
  {"code": "KBP", "city": "Kyiv", "airport": "Boryspil International Airport", "country": "Ukraine", "countryCode": "UA", "latitude": 50.345, "longitude": 30.8947, "priority": 55},
  {"code": "EVN", "city": "Yerevan", "airport": "Zvartnots International Airport", "country": "Armenia", "countryCode": "AM", "latitude": 40.1473, "longitude": 44.3959, "priority": 55},
  {"code": "TBS", "city": "Tbilisi", "airport": "Tbilisi International Airport", "country": "Georgia", "countryCode": "GE", "latitude": 41.6692, "longitude": 44.9547, "priority": 55},
  {"code": "GYD", "city": "Baku", "airport": "Heydar Aliyev International Airport", "country": "Azerbaijan", "countryCode": "AZ", "latitude": 40.4675, "longitude": 50.0467, "priority": 54},
  {"code": "SVO", "city": "Moscow", "airport": "Sheremetyevo International Airport", "country": "Russia", "countryCode": "RU", "latitude": 55.9726, "longitude": 37.4146, "priority": 54},
  {"code": "LED", "city": "St. Petersburg", "airport": "Pulkovo Airport", "country": "Russia", "countryCode": "RU", "latitude": 59.8003, "longitude": 30.2625, "priority": 54},
  {"code": "CMN", "city": "Casablanca", "airport": "Mohammed V International Airport", "country": "Morocco", "countryCode": "MA", "latitude": 33.3675, "longitude": -7.5899, "priority": 53},
  {"code": "RAK", "city": "Marrakesh", "airport": "Marrakesh Menara Airport", "country": "Morocco", "countryCode": "MA", "latitude": 31.6069, "longitude": -8.0363, "priority": 53},
  {"code": "ALG", "city": "Algiers", "airport": "Houari Boumediene Airport", "country": "Algeria", "countryCode": "DZ", "latitude": 36.691, "longitude": 3.2154, "priority": 53},
  {"code": "TUN", "city": "Tunis", "airport": "Tunis-Carthage International Airport", "country": "Tunisia", "countryCode": "TN", "latitude": 36.851, "longitude": 10.2272, "priority": 52},
  {"code": "CAI", "city": "Cairo", "airport": "Cairo International Airport", "country": "Egypt", "countryCode": "EG", "latitude": 30.1219, "longitude": 31.4056, "priority": 52},
  {"code": "SSH", "city": "Sharm El Sheikh", "airport": "Sharm El Sheikh International Airport", "country": "Egypt", "countryCode": "EG", "latitude": 27.9773, "longitude": 34.3949, "priority": 52},
  {"code": "TIP", "city": "Tripoli", "airport": "Mitiga International Airport", "country": "Libya", "countryCode": "LY", "latitude": 32.8941, "longitude": 13.276, "priority": 51},
  {"code": "LOS", "city": "Lagos", "airport": "Murtala Muhammed International Airport", "country": "Nigeria", "countryCode": "NG", "latitude": 6.5774, "longitude": 3.3212, "priority": 51},
  {"code": "ABV", "city": "Abuja", "airport": "Nnamdi Azikiwe International Airport", "country": "Nigeria", "countryCode": "NG", "latitude": 9.0068, "longitude": 7.2632, "priority": 51},
  {"code": "PHC", "city": "Port Harcourt", "airport": "Port Harcourt International Airport", "country": "Nigeria", "countryCode": "NG", "latitude": 5.0155, "longitude": 6.9496, "priority": 50},
  {"code": "KAN", "city": "Kano", "airport": "Mallam Aminu Kano International Airport", "country": "Nigeria", "countryCode": "NG", "latitude": 12.0476, "longitude": 8.5246, "priority": 50},
  {"code": "ACC", "city": "Accra", "airport": "Kotoka International Airport", "country": "Ghana", "countryCode": "GH", "latitude": 5.6052, "longitude": -0.1668, "priority": 50},
  {"code": "ABJ", "city": "Abidjan", "airport": "Félix-Houphouët-Boigny International Airport", "country": "Côte d’Ivoire", "countryCode": "CI", "latitude": 5.2614, "longitude": -3.9263, "priority": 49},
  {"code": "DKR", "city": "Dakar", "airport": "Blaise Diagne International Airport", "country": "Senegal", "countryCode": "SN", "latitude": 14.67, "longitude": -17.0733, "priority": 49},
  {"code": "BJL", "city": "Banjul", "airport": "Banjul International Airport", "country": "Gambia", "countryCode": "GM", "latitude": 13.3379, "longitude": -16.6522, "priority": 49},
  {"code": "CKY", "city": "Conakry", "airport": "Ahmed Sékou Touré International Airport", "country": "Guinea", "countryCode": "GN", "latitude": 9.5769, "longitude": -13.612, "priority": 48},
  {"code": "FNA", "city": "Freetown", "airport": "Freetown International Airport", "country": "Sierra Leone", "countryCode": "SL", "latitude": 8.6164, "longitude": -13.1955, "priority": 48},
  {"code": "ROB", "city": "Monrovia", "airport": "Roberts International Airport", "country": "Liberia", "countryCode": "LR", "latitude": 6.2338, "longitude": -10.3623, "priority": 48},
  {"code": "OUA", "city": "Ouagadougou", "airport": "Ouagadougou Airport", "country": "Burkina Faso", "countryCode": "BF", "latitude": 12.3532, "longitude": -1.5124, "priority": 47},
  {"code": "BKO", "city": "Bamako", "airport": "Modibo Keita International Airport", "country": "Mali", "countryCode": "ML", "latitude": 12.5335, "longitude": -7.9499, "priority": 47},
  {"code": "NIM", "city": "Niamey", "airport": "Diori Hamani International Airport", "country": "Niger", "countryCode": "NE", "latitude": 13.4815, "longitude": 2.1836, "priority": 47},
  {"code": "LFW", "city": "Lomé", "airport": "Lomé-Tokoin International Airport", "country": "Togo", "countryCode": "TG", "latitude": 6.1656, "longitude": 1.2545, "priority": 46},
  {"code": "COO", "city": "Cotonou", "airport": "Cadjehoun Airport", "country": "Benin", "countryCode": "BJ", "latitude": 6.3572, "longitude": 2.3844, "priority": 46},
  {"code": "NSI", "city": "Yaoundé", "airport": "Yaoundé Nsimalen International Airport", "country": "Cameroon", "countryCode": "CM", "latitude": 3.7226, "longitude": 11.5533, "priority": 46},
  {"code": "DLA", "city": "Douala", "airport": "Douala International Airport", "country": "Cameroon", "countryCode": "CM", "latitude": 4.0061, "longitude": 9.7195, "priority": 45},
  {"code": "LBV", "city": "Libreville", "airport": "Léon-Mba International Airport", "country": "Gabon", "countryCode": "GA", "latitude": 0.4586, "longitude": 9.4123, "priority": 45},
  {"code": "BZV", "city": "Brazzaville", "airport": "Maya-Maya Airport", "country": "Congo - Brazzaville", "countryCode": "CG", "latitude": -4.2517, "longitude": 15.253, "priority": 45},
  {"code": "FIH", "city": "Kinshasa", "airport": "N'djili Airport", "country": "Congo - Kinshasa", "countryCode": "CD", "latitude": -4.3858, "longitude": 15.4446, "priority": 44},
  {"code": "LAD", "city": "Luanda", "airport": "Quatro de Fevereiro Airport", "country": "Angola", "countryCode": "AO", "latitude": -8.8584, "longitude": 13.2312, "priority": 44},
  {"code": "ADD", "city": "Addis Ababa", "airport": "Addis Ababa Bole International Airport", "country": "Ethiopia", "countryCode": "ET", "latitude": 8.9779, "longitude": 38.7993, "priority": 44},
  {"code": "NBO", "city": "Nairobi", "airport": "Jomo Kenyatta International Airport", "country": "Kenya", "countryCode": "KE", "latitude": -1.3192, "longitude": 36.9278, "priority": 43},
  {"code": "MBA", "city": "Mombasa", "airport": "Moi International Airport", "country": "Kenya", "countryCode": "KE", "latitude": -4.0348, "longitude": 39.5942, "priority": 43},
  {"code": "DAR", "city": "Dar es Salaam", "airport": "Julius Nyerere International Airport", "country": "Tanzania", "countryCode": "TZ", "latitude": -6.8781, "longitude": 39.2026, "priority": 43},
  {"code": "ZNZ", "city": "Zanzibar", "airport": "Abeid Amani Karume International Airport", "country": "Tanzania", "countryCode": "TZ", "latitude": -6.222, "longitude": 39.2249, "priority": 42},
  {"code": "EBB", "city": "Entebbe", "airport": "Entebbe International Airport", "country": "Uganda", "countryCode": "UG", "latitude": 0.0424, "longitude": 32.4435, "priority": 42},
  {"code": "KGL", "city": "Kigali", "airport": "Kigali International Airport", "country": "Rwanda", "countryCode": "RW", "latitude": -1.9686, "longitude": 30.1395, "priority": 42},
  {"code": "BJM", "city": "Bujumbura", "airport": "Bujumbura International Airport", "country": "Burundi", "countryCode": "BI", "latitude": -3.324, "longitude": 29.3185, "priority": 41},
  {"code": "JIB", "city": "Djibouti", "airport": "Djibouti-Ambouli International Airport", "country": "Djibouti", "countryCode": "DJ", "latitude": 11.5473, "longitude": 43.1595, "priority": 41},
  {"code": "HGA", "city": "Hargeisa", "airport": "Hargeisa Egal International Airport", "country": "Somalia", "countryCode": "SO", "latitude": 9.5182, "longitude": 44.0888, "priority": 41},
  {"code": "KRT", "city": "Khartoum", "airport": "Khartoum International Airport", "country": "Sudan", "countryCode": "SD", "latitude": 15.5895, "longitude": 32.5532, "priority": 40},
  {"code": "JUB", "city": "Juba", "airport": "Juba International Airport", "country": "South Sudan", "countryCode": "SS", "latitude": 4.872, "longitude": 31.6011, "priority": 40},
  {"code": "CPT", "city": "Cape Town", "airport": "Cape Town International Airport", "country": "South Africa", "countryCode": "ZA", "latitude": -33.9715, "longitude": 18.6021, "priority": 40},
  {"code": "JNB", "city": "Johannesburg", "airport": "O. R. Tambo International Airport", "country": "South Africa", "countryCode": "ZA", "latitude": -26.1392, "longitude": 28.246, "priority": 39},
  {"code": "DUR", "city": "Durban", "airport": "King Shaka International Airport", "country": "South Africa", "countryCode": "ZA", "latitude": -29.6144, "longitude": 31.1197, "priority": 39},
  {"code": "LUN", "city": "Lusaka", "airport": "Kenneth Kaunda International Airport", "country": "Zambia", "countryCode": "ZM", "latitude": -15.3308, "longitude": 28.4526, "priority": 39},
  {"code": "HRE", "city": "Harare", "airport": "Robert Gabriel Mugabe International Airport", "country": "Zimbabwe", "countryCode": "ZW", "latitude": -17.9318, "longitude": 31.0928, "priority": 38},
  {"code": "MPM", "city": "Maputo", "airport": "Maputo International Airport", "country": "Mozambique", "countryCode": "MZ", "latitude": -25.9208, "longitude": 32.5726, "priority": 38},
  {"code": "GBE", "city": "Gaborone", "airport": "Sir Seretse Khama International Airport", "country": "Botswana", "countryCode": "BW", "latitude": -24.5552, "longitude": 25.9182, "priority": 38},
  {"code": "WDH", "city": "Windhoek", "airport": "Hosea Kutako International Airport", "country": "Namibia", "countryCode": "NA", "latitude": -22.4799, "longitude": 17.4709, "priority": 37},
  {"code": "MRU", "city": "Mauritius", "airport": "Sir Seewoosagur Ramgoolam International Airport", "country": "Mauritius", "countryCode": "MU", "latitude": -20.4302, "longitude": 57.6836, "priority": 37},
  {"code": "SEZ", "city": "Mahé", "airport": "Seychelles International Airport", "country": "Seychelles", "countryCode": "SC", "latitude": -4.6743, "longitude": 55.5218, "priority": 37},
  {"code": "TNR", "city": "Antananarivo", "airport": "Ivato International Airport", "country": "Madagascar", "countryCode": "MG", "latitude": -18.7969, "longitude": 47.4788, "priority": 36},
  {"code": "RUN", "city": "Saint-Denis", "airport": "Roland Garros Airport", "country": "Réunion", "countryCode": "RE", "latitude": -20.8901, "longitude": 55.5164, "priority": 36},
  {"code": "DXB", "city": "Dubai", "airport": "Dubai International Airport", "country": "United Arab Emirates", "countryCode": "AE", "latitude": 25.2532, "longitude": 55.3657, "priority": 100},
  {"code": "DWC", "city": "Dubai", "airport": "Al Maktoum International Airport", "country": "United Arab Emirates", "countryCode": "AE", "latitude": 24.8964, "longitude": 55.1614, "priority": 68},
  {"code": "AUH", "city": "Abu Dhabi", "airport": "Zayed International Airport", "country": "United Arab Emirates", "countryCode": "AE", "latitude": 24.4329, "longitude": 54.6511, "priority": 35},
  {"code": "DOH", "city": "Doha", "airport": "Hamad International Airport", "country": "Qatar", "countryCode": "QA", "latitude": 25.2731, "longitude": 51.6081, "priority": 35},
  {"code": "BAH", "city": "Manama", "airport": "Bahrain International Airport", "country": "Bahrain", "countryCode": "BH", "latitude": 26.2708, "longitude": 50.6336, "priority": 34},
  {"code": "KWI", "city": "Kuwait City", "airport": "Kuwait International Airport", "country": "Kuwait", "countryCode": "KW", "latitude": 29.2266, "longitude": 47.9689, "priority": 34},
  {"code": "RUH", "city": "Riyadh", "airport": "King Khalid International Airport", "country": "Saudi Arabia", "countryCode": "SA", "latitude": 24.9576, "longitude": 46.6988, "priority": 34},
  {"code": "JED", "city": "Jeddah", "airport": "King Abdulaziz International Airport", "country": "Saudi Arabia", "countryCode": "SA", "latitude": 21.6796, "longitude": 39.1565, "priority": 33},
  {"code": "MCT", "city": "Muscat", "airport": "Muscat International Airport", "country": "Oman", "countryCode": "OM", "latitude": 23.5933, "longitude": 58.2844, "priority": 33},
  {"code": "AMM", "city": "Amman", "airport": "Queen Alia International Airport", "country": "Jordan", "countryCode": "JO", "latitude": 31.7226, "longitude": 35.9932, "priority": 33},
  {"code": "BEY", "city": "Beirut", "airport": "Beirut-Rafic Hariri International Airport", "country": "Lebanon", "countryCode": "LB", "latitude": 33.8209, "longitude": 35.4884, "priority": 32},
  {"code": "TLV", "city": "Tel Aviv", "airport": "Ben Gurion Airport", "country": "Israel", "countryCode": "IL", "latitude": 32.0114, "longitude": 34.8867, "priority": 32},
  {"code": "IKA", "city": "Tehran", "airport": "Imam Khomeini International Airport", "country": "Iran", "countryCode": "IR", "latitude": 35.4161, "longitude": 51.1522, "priority": 32},
  {"code": "BGW", "city": "Baghdad", "airport": "Baghdad International Airport", "country": "Iraq", "countryCode": "IQ", "latitude": 33.2625, "longitude": 44.2346, "priority": 31},
  {"code": "DEL", "city": "New Delhi", "airport": "Indira Gandhi International Airport", "country": "India", "countryCode": "IN", "latitude": 28.5562, "longitude": 77.1, "priority": 31},
  {"code": "BOM", "city": "Mumbai", "airport": "Chhatrapati Shivaji Maharaj International Airport", "country": "India", "countryCode": "IN", "latitude": 19.09, "longitude": 72.8679, "priority": 31},
  {"code": "BLR", "city": "Bengaluru", "airport": "Kempegowda International Airport", "country": "India", "countryCode": "IN", "latitude": 13.1986, "longitude": 77.7066, "priority": 30},
  {"code": "MAA", "city": "Chennai", "airport": "Chennai International Airport", "country": "India", "countryCode": "IN", "latitude": 12.9941, "longitude": 80.1709, "priority": 30},
  {"code": "HYD", "city": "Hyderabad", "airport": "Rajiv Gandhi International Airport", "country": "India", "countryCode": "IN", "latitude": 17.2403, "longitude": 78.4294, "priority": 30},
  {"code": "CCU", "city": "Kolkata", "airport": "Netaji Subhas Chandra Bose International Airport", "country": "India", "countryCode": "IN", "latitude": 22.6547, "longitude": 88.4467, "priority": 29},
  {"code": "COK", "city": "Kochi", "airport": "Cochin International Airport", "country": "India", "countryCode": "IN", "latitude": 10.152, "longitude": 76.4019, "priority": 29},
  {"code": "ISB", "city": "Islamabad", "airport": "Islamabad International Airport", "country": "Pakistan", "countryCode": "PK", "latitude": 33.5607, "longitude": 72.8516, "priority": 29},
  {"code": "KHI", "city": "Karachi", "airport": "Jinnah International Airport", "country": "Pakistan", "countryCode": "PK", "latitude": 24.9065, "longitude": 67.1608, "priority": 28},
  {"code": "LHE", "city": "Lahore", "airport": "Allama Iqbal International Airport", "country": "Pakistan", "countryCode": "PK", "latitude": 31.5216, "longitude": 74.4036, "priority": 28},
  {"code": "DAC", "city": "Dhaka", "airport": "Hazrat Shahjalal International Airport", "country": "Bangladesh", "countryCode": "BD", "latitude": 23.8433, "longitude": 90.3978, "priority": 28},
  {"code": "CMB", "city": "Colombo", "airport": "Bandaranaike International Airport", "country": "Sri Lanka", "countryCode": "LK", "latitude": 7.1808, "longitude": 79.8841, "priority": 27},
  {"code": "MLE", "city": "Malé", "airport": "Velana International Airport", "country": "Maldives", "countryCode": "MV", "latitude": 4.1918, "longitude": 73.5291, "priority": 27},
  {"code": "KTM", "city": "Kathmandu", "airport": "Tribhuvan International Airport", "country": "Nepal", "countryCode": "NP", "latitude": 27.6966, "longitude": 85.3591, "priority": 27},
  {"code": "PBH", "city": "Paro", "airport": "Paro International Airport", "country": "Bhutan", "countryCode": "BT", "latitude": 27.4032, "longitude": 89.4246, "priority": 26},
  {"code": "TAS", "city": "Tashkent", "airport": "Tashkent International Airport", "country": "Uzbekistan", "countryCode": "UZ", "latitude": 41.2579, "longitude": 69.2812, "priority": 26},
  {"code": "ALA", "city": "Almaty", "airport": "Almaty International Airport", "country": "Kazakhstan", "countryCode": "KZ", "latitude": 43.3521, "longitude": 77.0405, "priority": 26},
  {"code": "FRU", "city": "Bishkek", "airport": "Manas International Airport", "country": "Kyrgyzstan", "countryCode": "KG", "latitude": 43.0613, "longitude": 74.4776, "priority": 25},
  {"code": "DYU", "city": "Dushanbe", "airport": "Dushanbe International Airport", "country": "Tajikistan", "countryCode": "TJ", "latitude": 38.5433, "longitude": 68.825, "priority": 25},
  {"code": "ASB", "city": "Ashgabat", "airport": "Ashgabat International Airport", "country": "Turkmenistan", "countryCode": "TM", "latitude": 37.9868, "longitude": 58.361, "priority": 25},
  {"code": "PEK", "city": "Beijing", "airport": "Beijing Capital International Airport", "country": "China", "countryCode": "CN", "latitude": 40.0799, "longitude": 116.6031, "priority": 24},
  {"code": "PKX", "city": "Beijing", "airport": "Beijing Daxing International Airport", "country": "China", "countryCode": "CN", "latitude": 39.5098, "longitude": 116.4105, "priority": 24},
  {"code": "PVG", "city": "Shanghai", "airport": "Shanghai Pudong International Airport", "country": "China", "countryCode": "CN", "latitude": 31.1443, "longitude": 121.8083, "priority": 24},
  {"code": "CAN", "city": "Guangzhou", "airport": "Guangzhou Baiyun International Airport", "country": "China", "countryCode": "CN", "latitude": 23.3924, "longitude": 113.2988, "priority": 23},
  {"code": "SZX", "city": "Shenzhen", "airport": "Shenzhen Bao'an International Airport", "country": "China", "countryCode": "CN", "latitude": 22.6393, "longitude": 113.8107, "priority": 23},
  {"code": "HKG", "city": "Hong Kong", "airport": "Hong Kong International Airport", "country": "Hong Kong SAR China", "countryCode": "HK", "latitude": 22.308, "longitude": 113.9185, "priority": 23},
  {"code": "MFM", "city": "Macau", "airport": "Macau International Airport", "country": "Macao SAR China", "countryCode": "MO", "latitude": 22.1496, "longitude": 113.591, "priority": 22},
  {"code": "TPE", "city": "Taipei", "airport": "Taiwan Taoyuan International Airport", "country": "Taiwan", "countryCode": "TW", "latitude": 25.0777, "longitude": 121.2328, "priority": 22},
  {"code": "HND", "city": "Tokyo", "airport": "Haneda Airport", "country": "Japan", "countryCode": "JP", "latitude": 35.5494, "longitude": 139.7798, "priority": 22},
  {"code": "NRT", "city": "Tokyo", "airport": "Narita International Airport", "country": "Japan", "countryCode": "JP", "latitude": 35.7719, "longitude": 140.3929, "priority": 21},
  {"code": "KIX", "city": "Osaka", "airport": "Kansai International Airport", "country": "Japan", "countryCode": "JP", "latitude": 34.4347, "longitude": 135.244, "priority": 21},
  {"code": "ICN", "city": "Seoul", "airport": "Incheon International Airport", "country": "South Korea", "countryCode": "KR", "latitude": 37.4602, "longitude": 126.4407, "priority": 21},
  {"code": "GMP", "city": "Seoul", "airport": "Gimpo International Airport", "country": "South Korea", "countryCode": "KR", "latitude": 37.5583, "longitude": 126.7906, "priority": 20},
  {"code": "ULN", "city": "Ulaanbaatar", "airport": "Chinggis Khaan International Airport", "country": "Mongolia", "countryCode": "MN", "latitude": 47.6469, "longitude": 106.8198, "priority": 20},
  {"code": "BKK", "city": "Bangkok", "airport": "Suvarnabhumi Airport", "country": "Thailand", "countryCode": "TH", "latitude": 13.69, "longitude": 100.7501, "priority": 20},
  {"code": "DMK", "city": "Bangkok", "airport": "Don Mueang International Airport", "country": "Thailand", "countryCode": "TH", "latitude": 13.9126, "longitude": 100.6067, "priority": 20},
  {"code": "HKT", "city": "Phuket", "airport": "Phuket International Airport", "country": "Thailand", "countryCode": "TH", "latitude": 8.1132, "longitude": 98.3169, "priority": 20},
  {"code": "SIN", "city": "Singapore", "airport": "Singapore Changi Airport", "country": "Singapore", "countryCode": "SG", "latitude": 1.3644, "longitude": 103.9915, "priority": 20},
  {"code": "KUL", "city": "Kuala Lumpur", "airport": "Kuala Lumpur International Airport", "country": "Malaysia", "countryCode": "MY", "latitude": 2.7456, "longitude": 101.7072, "priority": 20},
  {"code": "PEN", "city": "Penang", "airport": "Penang International Airport", "country": "Malaysia", "countryCode": "MY", "latitude": 5.2971, "longitude": 100.2769, "priority": 20},
  {"code": "CGK", "city": "Jakarta", "airport": "Soekarno-Hatta International Airport", "country": "Indonesia", "countryCode": "ID", "latitude": -6.1256, "longitude": 106.6559, "priority": 20},
  {"code": "DPS", "city": "Denpasar", "airport": "Ngurah Rai International Airport", "country": "Indonesia", "countryCode": "ID", "latitude": -8.7482, "longitude": 115.167, "priority": 20},
  {"code": "MNL", "city": "Manila", "airport": "Ninoy Aquino International Airport", "country": "Philippines", "countryCode": "PH", "latitude": 14.5086, "longitude": 121.0198, "priority": 20},
  {"code": "CEB", "city": "Cebu", "airport": "Mactan-Cebu International Airport", "country": "Philippines", "countryCode": "PH", "latitude": 10.3075, "longitude": 123.9794, "priority": 20},
  {"code": "HAN", "city": "Hanoi", "airport": "Noi Bai International Airport", "country": "Vietnam", "countryCode": "VN", "latitude": 21.2212, "longitude": 105.8072, "priority": 20},
  {"code": "SGN", "city": "Ho Chi Minh City", "airport": "Tan Son Nhat International Airport", "country": "Vietnam", "countryCode": "VN", "latitude": 10.8188, "longitude": 106.6519, "priority": 20},
  {"code": "PNH", "city": "Phnom Penh", "airport": "Phnom Penh International Airport", "country": "Cambodia", "countryCode": "KH", "latitude": 11.5466, "longitude": 104.8441, "priority": 20},
  {"code": "REP", "city": "Siem Reap", "airport": "Siem Reap-Angkor International Airport", "country": "Cambodia", "countryCode": "KH", "latitude": 13.3692, "longitude": 104.2231, "priority": 20},
  {"code": "VTE", "city": "Vientiane", "airport": "Wattay International Airport", "country": "Laos", "countryCode": "LA", "latitude": 17.9883, "longitude": 102.5633, "priority": 20},
  {"code": "RGN", "city": "Yangon", "airport": "Yangon International Airport", "country": "Myanmar (Burma)", "countryCode": "MM", "latitude": 16.9073, "longitude": 96.1332, "priority": 20},
  {"code": "BWN", "city": "Bandar Seri Begawan", "airport": "Brunei International Airport", "country": "Brunei", "countryCode": "BN", "latitude": 4.9442, "longitude": 114.9284, "priority": 20},
  {"code": "DIL", "city": "Dili", "airport": "Presidente Nicolau Lobato International Airport", "country": "Timor-Leste", "countryCode": "TL", "latitude": -8.5464, "longitude": 125.5247, "priority": 20},
  {"code": "SYD", "city": "Sydney", "airport": "Sydney Kingsford Smith Airport", "country": "Australia", "countryCode": "AU", "latitude": -33.9399, "longitude": 151.1753, "priority": 20},
  {"code": "MEL", "city": "Melbourne", "airport": "Melbourne Airport", "country": "Australia", "countryCode": "AU", "latitude": -37.669, "longitude": 144.841, "priority": 20},
  {"code": "BNE", "city": "Brisbane", "airport": "Brisbane Airport", "country": "Australia", "countryCode": "AU", "latitude": -27.3842, "longitude": 153.1175, "priority": 20},
  {"code": "PER", "city": "Perth", "airport": "Perth Airport", "country": "Australia", "countryCode": "AU", "latitude": -31.9403, "longitude": 115.9669, "priority": 20},
  {"code": "ADL", "city": "Adelaide", "airport": "Adelaide Airport", "country": "Australia", "countryCode": "AU", "latitude": -34.945, "longitude": 138.5306, "priority": 20},
  {"code": "AKL", "city": "Auckland", "airport": "Auckland Airport", "country": "New Zealand", "countryCode": "NZ", "latitude": -37.0082, "longitude": 174.785, "priority": 20},
  {"code": "WLG", "city": "Wellington", "airport": "Wellington International Airport", "country": "New Zealand", "countryCode": "NZ", "latitude": -41.3272, "longitude": 174.8053, "priority": 20},
  {"code": "CHC", "city": "Christchurch", "airport": "Christchurch Airport", "country": "New Zealand", "countryCode": "NZ", "latitude": -43.4894, "longitude": 172.5322, "priority": 20},
  {"code": "NAN", "city": "Nadi", "airport": "Nadi International Airport", "country": "Fiji", "countryCode": "FJ", "latitude": -17.7554, "longitude": 177.4434, "priority": 20},
  {"code": "PPT", "city": "Papeete", "airport": "Faa'a International Airport", "country": "French Polynesia", "countryCode": "PF", "latitude": -17.5537, "longitude": -149.606, "priority": 20},
  {"code": "POM", "city": "Port Moresby", "airport": "Jacksons International Airport", "country": "Papua New Guinea", "countryCode": "PG", "latitude": -9.4434, "longitude": 147.22, "priority": 20},
  {"code": "HIR", "city": "Honiara", "airport": "Honiara International Airport", "country": "Solomon Islands", "countryCode": "SB", "latitude": -9.428, "longitude": 160.0548, "priority": 20},
  {"code": "VLI", "city": "Port Vila", "airport": "Bauerfield International Airport", "country": "Vanuatu", "countryCode": "VU", "latitude": -17.6993, "longitude": 168.3198, "priority": 20},
  {"code": "APW", "city": "Apia", "airport": "Faleolo International Airport", "country": "Samoa", "countryCode": "WS", "latitude": -13.82997, "longitude": -172.0083, "priority": 20},
  {"code": "TBU", "city": "Nukuʻalofa", "airport": "Fuaʻamotu International Airport", "country": "Tonga", "countryCode": "TO", "latitude": -21.2412, "longitude": -175.1496, "priority": 20},
  {"code": "RAR", "city": "Rarotonga", "airport": "Rarotonga International Airport", "country": "Cook Islands", "countryCode": "CK", "latitude": -21.2027, "longitude": -159.8056, "priority": 20},
  {"code": "GUM", "city": "Guam", "airport": "Antonio B. Won Pat International Airport", "country": "Guam", "countryCode": "GU", "latitude": 13.4839, "longitude": 144.797, "priority": 20},
  {"code": "SPN", "city": "Saipan", "airport": "Saipan International Airport", "country": "Northern Mariana Islands", "countryCode": "MP", "latitude": 15.119, "longitude": 145.729, "priority": 20},
];
