import type { MobileLocale } from "../../localization/mobileLocalizationCatalog";

const english = {
  unsupported: "Passkeys are not available in this app build or on this device. Install the latest Kurioticket Preview build and make sure a screen lock is enabled.",
  checkingSupport: "Checking passkey support…",
  noPasskeys: "No passkeys have been added yet.",
  lastUsed: "Last used",
  neverUsed: "Not used yet",
  rename: "Rename",
  remove: "Remove",
  renameTitle: "Rename passkey",
  passkeyName: "Passkey name",
  saveName: "Save name",
  invalidName: "Enter a name of no more than 80 characters.",
  renamed: "Passkey renamed.",
  removeTitle: "Remove this passkey?",
  removeBody: "You will no longer be able to use this passkey with Kurioticket.",
  removed: "Passkey removed.",
  added: "Passkey added.",
  verifyTitle: "Verify your account",
  verifyTotp: "Enter an authenticator code or recovery code before continuing.",
  verifyPassword: "Enter your current password before continuing.",
  verifyEmail: "We will send a six-digit verification code to your account email.",
  verificationCode: "Verification code",
  currentPassword: "Current password",
  sendEmailCode: "Send verification code",
  emailCodeSent: "A verification code was sent to your account email.",
  continue: "Continue",
  backToPasskeys: "Back to passkeys",
  operationFailed: "Unable to update passkeys. Try again.",
  registrationFailed: "Unable to create this passkey. Try again.",
  verificationRequired: "Enter the requested verification before continuing.",
  iosDefaultName: "iPhone passkey",
  androidDefaultName: "Android passkey",
} as const;

export type PasskeyCopy = { [K in keyof typeof english]: string };

const spanish: PasskeyCopy = {
  unsupported: "Las llaves de acceso no están disponibles en esta versión de la aplicación o en este dispositivo. Instala la última versión Preview de Kurioticket y asegúrate de tener un bloqueo de pantalla.",
  checkingSupport: "Comprobando la compatibilidad con llaves de acceso…",
  noPasskeys: "Todavía no se ha añadido ninguna llave de acceso.",
  lastUsed: "Último uso",
  neverUsed: "Aún no se ha usado",
  rename: "Cambiar nombre",
  remove: "Eliminar",
  renameTitle: "Cambiar el nombre de la llave",
  passkeyName: "Nombre de la llave de acceso",
  saveName: "Guardar nombre",
  invalidName: "Introduce un nombre de no más de 80 caracteres.",
  renamed: "Se cambió el nombre de la llave de acceso.",
  removeTitle: "¿Eliminar esta llave de acceso?",
  removeBody: "Ya no podrás usar esta llave de acceso con Kurioticket.",
  removed: "Llave de acceso eliminada.",
  added: "Llave de acceso añadida.",
  verifyTitle: "Verifica tu cuenta",
  verifyTotp: "Introduce un código del autenticador o un código de recuperación antes de continuar.",
  verifyPassword: "Introduce tu contraseña actual antes de continuar.",
  verifyEmail: "Enviaremos un código de verificación de seis dígitos al correo de tu cuenta.",
  verificationCode: "Código de verificación",
  currentPassword: "Contraseña actual",
  sendEmailCode: "Enviar código de verificación",
  emailCodeSent: "Se envió un código de verificación al correo de tu cuenta.",
  continue: "Continuar",
  backToPasskeys: "Volver a llaves de acceso",
  operationFailed: "No se pudieron actualizar las llaves de acceso. Inténtalo de nuevo.",
  registrationFailed: "No se pudo crear esta llave de acceso. Inténtalo de nuevo.",
  verificationRequired: "Introduce la verificación solicitada antes de continuar.",
  iosDefaultName: "Llave de acceso del iPhone",
  androidDefaultName: "Llave de acceso de Android",
};

export function passkeyCopyForLocale(locale: MobileLocale): PasskeyCopy {
  return locale === "es-es" ? spanish : english;
}
