import type { MobileLocale } from "../../localization/mobileLocalizationCatalog";

export type PasswordFlowCopy = {
  verifyTitle: string;
  verifyBody: (maskedEmail: string) => string;
  codeLabel: string;
  verifyChangeAction: string;
  continueAction: string;
  resend: string;
  resendIn: (seconds: number) => string;
  codeSent: string;
  expiryHint: string;
  tryAnotherWay: string;
  createTitle: string;
  currentRequired: string;
  currentIncorrect: string;
  newTooShort: string;
  newSame: string;
  confirmRequired: string;
  confirmMismatch: string;
};

export const mmss = (seconds: number) => `00:${String(Math.max(0, seconds)).padStart(2, "0")}`;

export const passwordFlowCopy: Record<MobileLocale, PasswordFlowCopy> = {
  "en-us": { verifyTitle: "Verify it’s you", verifyBody: (email) => `Enter the 6-digit code we sent to ${email}.`, codeLabel: "Verification code", verifyChangeAction: "Verify and change password", continueAction: "Continue", resend: "Request new code", resendIn: (s) => `Request new code in ${mmss(s)}`, codeSent: "New code sent.", expiryHint: "The code expires in 5 minutes.", tryAnotherWay: "Try another way", createTitle: "Create a new password", currentRequired: "Enter your current password.", currentIncorrect: "Current password is incorrect.", newTooShort: "Use at least 8 characters.", newSame: "Choose a password different from your current password.", confirmRequired: "Confirm your new password.", confirmMismatch: "Passwords do not match." },
  "es-es": { verifyTitle: "Verifica que eres tú", verifyBody: (email) => `Introduce el código de 6 dígitos que enviamos a ${email}.`, codeLabel: "Código de verificación", verifyChangeAction: "Verificar y cambiar contraseña", continueAction: "Continuar", resend: "Solicitar un código nuevo", resendIn: (s) => `Solicitar un código nuevo en ${mmss(s)}`, codeSent: "Se envió un código nuevo.", expiryHint: "El código caduca en 5 minutos.", tryAnotherWay: "Probar otra forma", createTitle: "Crear una contraseña nueva", currentRequired: "Introduce tu contraseña actual.", currentIncorrect: "La contraseña actual es incorrecta.", newTooShort: "Usa al menos 8 caracteres.", newSame: "Elige una contraseña distinta de la actual.", confirmRequired: "Confirma tu contraseña nueva.", confirmMismatch: "Las contraseñas no coinciden." },
  fr: { verifyTitle: "Vérifiez votre identité", verifyBody: (email) => `Saisissez le code à 6 chiffres envoyé à ${email}.`, codeLabel: "Code de vérification", verifyChangeAction: "Vérifier et changer le mot de passe", continueAction: "Continuer", resend: "Demander un nouveau code", resendIn: (s) => `Nouveau code dans ${mmss(s)}`, codeSent: "Nouveau code envoyé.", expiryHint: "Le code expire dans 5 minutes.", tryAnotherWay: "Essayer une autre méthode", createTitle: "Créer un nouveau mot de passe", currentRequired: "Saisissez votre mot de passe actuel.", currentIncorrect: "Le mot de passe actuel est incorrect.", newTooShort: "Utilisez au moins 8 caractères.", newSame: "Choisissez un mot de passe différent de l’actuel.", confirmRequired: "Confirmez votre nouveau mot de passe.", confirmMismatch: "Les mots de passe ne correspondent pas." },
  "de-de": { verifyTitle: "Bestätigen Sie Ihre Identität", verifyBody: (email) => `Geben Sie den 6-stelligen Code ein, den wir an ${email} gesendet haben.`, codeLabel: "Bestätigungscode", verifyChangeAction: "Bestätigen und Passwort ändern", continueAction: "Weiter", resend: "Neuen Code anfordern", resendIn: (s) => `Neuen Code anfordern in ${mmss(s)}`, codeSent: "Neuer Code gesendet.", expiryHint: "Der Code läuft in 5 Minuten ab.", tryAnotherWay: "Andere Methode versuchen", createTitle: "Neues Passwort erstellen", currentRequired: "Geben Sie Ihr aktuelles Passwort ein.", currentIncorrect: "Das aktuelle Passwort ist falsch.", newTooShort: "Verwenden Sie mindestens 8 Zeichen.", newSame: "Wählen Sie ein anderes Passwort als Ihr aktuelles.", confirmRequired: "Bestätigen Sie Ihr neues Passwort.", confirmMismatch: "Die Passwörter stimmen nicht überein." },
  "it-it": { verifyTitle: "Verifica la tua identità", verifyBody: (email) => `Inserisci il codice di 6 cifre inviato a ${email}.`, codeLabel: "Codice di verifica", verifyChangeAction: "Verifica e cambia password", continueAction: "Continua", resend: "Richiedi un nuovo codice", resendIn: (s) => `Richiedi un nuovo codice tra ${mmss(s)}`, codeSent: "Nuovo codice inviato.", expiryHint: "Il codice scade tra 5 minuti.", tryAnotherWay: "Prova un altro metodo", createTitle: "Crea una nuova password", currentRequired: "Inserisci la password attuale.", currentIncorrect: "La password attuale non è corretta.", newTooShort: "Usa almeno 8 caratteri.", newSame: "Scegli una password diversa da quella attuale.", confirmRequired: "Conferma la nuova password.", confirmMismatch: "Le password non corrispondono." },
  "pt-br": { verifyTitle: "Verifique sua identidade", verifyBody: (email) => `Digite o código de 6 dígitos enviado para ${email}.`, codeLabel: "Código de verificação", verifyChangeAction: "Verificar e alterar senha", continueAction: "Continuar", resend: "Solicitar novo código", resendIn: (s) => `Solicitar novo código em ${mmss(s)}`, codeSent: "Novo código enviado.", expiryHint: "O código expira em 5 minutos.", tryAnotherWay: "Tentar de outra forma", createTitle: "Criar uma nova senha", currentRequired: "Digite sua senha atual.", currentIncorrect: "A senha atual está incorreta.", newTooShort: "Use pelo menos 8 caracteres.", newSame: "Escolha uma senha diferente da atual.", confirmRequired: "Confirme sua nova senha.", confirmMismatch: "As senhas não coincidem." },
  nl: { verifyTitle: "Controleer dat u het bent", verifyBody: (email) => `Voer de 6-cijferige code in die we naar ${email} hebben gestuurd.`, codeLabel: "Verificatiecode", verifyChangeAction: "Verifiëren en wachtwoord wijzigen", continueAction: "Doorgaan", resend: "Nieuwe code aanvragen", resendIn: (s) => `Nieuwe code aanvragen over ${mmss(s)}`, codeSent: "Nieuwe code verzonden.", expiryHint: "De code verloopt over 5 minuten.", tryAnotherWay: "Andere manier proberen", createTitle: "Nieuw wachtwoord maken", currentRequired: "Voer uw huidige wachtwoord in.", currentIncorrect: "Het huidige wachtwoord is onjuist.", newTooShort: "Gebruik minimaal 8 tekens.", newSame: "Kies een ander wachtwoord dan uw huidige wachtwoord.", confirmRequired: "Bevestig uw nieuwe wachtwoord.", confirmMismatch: "De wachtwoorden komen niet overeen." },
  ar: { verifyTitle: "تحقق من هويتك", verifyBody: (email) => `أدخل الرمز المكوّن من 6 أرقام الذي أرسلناه إلى ${email}.`, codeLabel: "رمز التحقق", verifyChangeAction: "تحقق وغيّر كلمة المرور", continueAction: "متابعة", resend: "طلب رمز جديد", resendIn: (s) => `طلب رمز جديد خلال ${mmss(s)}`, codeSent: "تم إرسال رمز جديد.", expiryHint: "تنتهي صلاحية الرمز خلال 5 دقائق.", tryAnotherWay: "جرّب طريقة أخرى", createTitle: "إنشاء كلمة مرور جديدة", currentRequired: "أدخل كلمة المرور الحالية.", currentIncorrect: "كلمة المرور الحالية غير صحيحة.", newTooShort: "استخدم 8 أحرف على الأقل.", newSame: "اختر كلمة مرور مختلفة عن الحالية.", confirmRequired: "أكد كلمة المرور الجديدة.", confirmMismatch: "كلمتا المرور غير متطابقتين." },
  "zh-cn": { verifyTitle: "验证是您本人", verifyBody: (email) => `请输入我们发送到 ${email} 的 6 位验证码。`, codeLabel: "验证码", verifyChangeAction: "验证并更改密码", continueAction: "继续", resend: "获取新验证码", resendIn: (s) => `${mmss(s)} 后可获取新验证码`, codeSent: "新验证码已发送。", expiryHint: "验证码将在 5 分钟后过期。", tryAnotherWay: "尝试其他方式", createTitle: "创建新密码", currentRequired: "请输入当前密码。", currentIncorrect: "当前密码不正确。", newTooShort: "请至少使用 8 个字符。", newSame: "请选择与当前密码不同的密码。", confirmRequired: "请确认新密码。", confirmMismatch: "两次输入的密码不一致。" },
  ja: { verifyTitle: "本人確認", verifyBody: (email) => `${email} に送信した6桁のコードを入力してください。`, codeLabel: "確認コード", verifyChangeAction: "確認してパスワードを変更", continueAction: "続ける", resend: "新しいコードをリクエスト", resendIn: (s) => `${mmss(s)} 後に新しいコードをリクエスト`, codeSent: "新しいコードを送信しました。", expiryHint: "コードは5分で期限切れになります。", tryAnotherWay: "別の方法を試す", createTitle: "新しいパスワードを作成", currentRequired: "現在のパスワードを入力してください。", currentIncorrect: "現在のパスワードが正しくありません。", newTooShort: "8文字以上を使用してください。", newSame: "現在のパスワードとは異なるものを選んでください。", confirmRequired: "新しいパスワードを確認してください。", confirmMismatch: "パスワードが一致しません。" },
  ko: { verifyTitle: "본인 확인", verifyBody: (email) => `${email}로 보낸 6자리 코드를 입력하세요.`, codeLabel: "인증 코드", verifyChangeAction: "인증하고 비밀번호 변경", continueAction: "계속", resend: "새 코드 요청", resendIn: (s) => `${mmss(s)} 후 새 코드 요청`, codeSent: "새 코드를 보냈습니다.", expiryHint: "코드는 5분 후 만료됩니다.", tryAnotherWay: "다른 방법 시도", createTitle: "새 비밀번호 만들기", currentRequired: "현재 비밀번호를 입력하세요.", currentIncorrect: "현재 비밀번호가 올바르지 않습니다.", newTooShort: "8자 이상 사용하세요.", newSame: "현재 비밀번호와 다른 비밀번호를 선택하세요.", confirmRequired: "새 비밀번호를 확인하세요.", confirmMismatch: "비밀번호가 일치하지 않습니다." },
  hi: { verifyTitle: "पुष्टि करें कि यह आप हैं", verifyBody: (email) => `${email} पर भेजा गया 6 अंकों का कोड दर्ज करें।`, codeLabel: "सत्यापन कोड", verifyChangeAction: "सत्यापित करें और पासवर्ड बदलें", continueAction: "जारी रखें", resend: "नया कोड मांगें", resendIn: (s) => `${mmss(s)} में नया कोड मांगें`, codeSent: "नया कोड भेज दिया गया।", expiryHint: "कोड 5 मिनट में समाप्त हो जाएगा।", tryAnotherWay: "दूसरा तरीका आज़माएँ", createTitle: "नया पासवर्ड बनाएँ", currentRequired: "अपना मौजूदा पासवर्ड दर्ज करें।", currentIncorrect: "मौजूदा पासवर्ड गलत है।", newTooShort: "कम से कम 8 अक्षर इस्तेमाल करें।", newSame: "मौजूदा पासवर्ड से अलग पासवर्ड चुनें।", confirmRequired: "अपने नए पासवर्ड की पुष्टि करें।", confirmMismatch: "पासवर्ड मेल नहीं खाते।" },
  tr: { verifyTitle: "Siz olduğunuzu doğrulayın", verifyBody: (email) => `${email} adresine gönderdiğimiz 6 haneli kodu girin.`, codeLabel: "Doğrulama kodu", verifyChangeAction: "Doğrula ve şifreyi değiştir", continueAction: "Devam et", resend: "Yeni kod iste", resendIn: (s) => `${mmss(s)} sonra yeni kod iste`, codeSent: "Yeni kod gönderildi.", expiryHint: "Kod 5 dakika içinde sona erer.", tryAnotherWay: "Başka bir yol dene", createTitle: "Yeni bir parola oluştur", currentRequired: "Mevcut parolanızı girin.", currentIncorrect: "Mevcut parola yanlış.", newTooShort: "En az 8 karakter kullanın.", newSame: "Mevcut parolanızdan farklı bir parola seçin.", confirmRequired: "Yeni parolanızı doğrulayın.", confirmMismatch: "Parolalar eşleşmiyor." },
  pl: { verifyTitle: "Potwierdź, że to Ty", verifyBody: (email) => `Wpisz 6-cyfrowy kod wysłany na ${email}.`, codeLabel: "Kod weryfikacyjny", verifyChangeAction: "Zweryfikuj i zmień hasło", continueAction: "Dalej", resend: "Poproś o nowy kod", resendIn: (s) => `Nowy kod za ${mmss(s)}`, codeSent: "Wysłano nowy kod.", expiryHint: "Kod wygaśnie za 5 minut.", tryAnotherWay: "Wypróbuj inną metodę", createTitle: "Utwórz nowe hasło", currentRequired: "Wpisz obecne hasło.", currentIncorrect: "Obecne hasło jest nieprawidłowe.", newTooShort: "Użyj co najmniej 8 znaków.", newSame: "Wybierz hasło inne niż obecne.", confirmRequired: "Potwierdź nowe hasło.", confirmMismatch: "Hasła nie są zgodne." },
  sv: { verifyTitle: "Verifiera att det är du", verifyBody: (email) => `Ange den 6-siffriga koden vi skickade till ${email}.`, codeLabel: "Verifieringskod", verifyChangeAction: "Verifiera och byt lösenord", continueAction: "Fortsätt", resend: "Begär ny kod", resendIn: (s) => `Begär ny kod om ${mmss(s)}`, codeSent: "Ny kod skickad.", expiryHint: "Koden går ut om 5 minuter.", tryAnotherWay: "Prova ett annat sätt", createTitle: "Skapa ett nytt lösenord", currentRequired: "Ange ditt nuvarande lösenord.", currentIncorrect: "Det nuvarande lösenordet är fel.", newTooShort: "Använd minst 8 tecken.", newSame: "Välj ett annat lösenord än ditt nuvarande.", confirmRequired: "Bekräfta ditt nya lösenord.", confirmMismatch: "Lösenorden matchar inte." },
  id: { verifyTitle: "Verifikasi bahwa ini Anda", verifyBody: (email) => `Masukkan kode 6 digit yang kami kirim ke ${email}.`, codeLabel: "Kode verifikasi", verifyChangeAction: "Verifikasi dan ubah kata sandi", continueAction: "Lanjutkan", resend: "Minta kode baru", resendIn: (s) => `Minta kode baru dalam ${mmss(s)}`, codeSent: "Kode baru telah dikirim.", expiryHint: "Kode akan kedaluwarsa dalam 5 menit.", tryAnotherWay: "Coba cara lain", createTitle: "Buat kata sandi baru", currentRequired: "Masukkan kata sandi saat ini.", currentIncorrect: "Kata sandi saat ini salah.", newTooShort: "Gunakan setidaknya 8 karakter.", newSame: "Pilih kata sandi yang berbeda dari kata sandi saat ini.", confirmRequired: "Konfirmasi kata sandi baru Anda.", confirmMismatch: "Kata sandi tidak cocok." },
  th: { verifyTitle: "ยืนยันว่าเป็นคุณ", verifyBody: (email) => `กรอกรหัส 6 หลักที่เราส่งไปยัง ${email}`, codeLabel: "รหัสยืนยัน", verifyChangeAction: "ยืนยันและเปลี่ยนรหัสผ่าน", continueAction: "ดำเนินการต่อ", resend: "ขอรหัสใหม่", resendIn: (s) => `ขอรหัสใหม่ได้ใน ${mmss(s)}`, codeSent: "ส่งรหัสใหม่แล้ว", expiryHint: "รหัสจะหมดอายุใน 5 นาที", tryAnotherWay: "ลองวิธีอื่น", createTitle: "สร้างรหัสผ่านใหม่", currentRequired: "กรอกรหัสผ่านปัจจุบันของคุณ", currentIncorrect: "รหัสผ่านปัจจุบันไม่ถูกต้อง", newTooShort: "ใช้อย่างน้อย 8 ตัวอักษร", newSame: "เลือกรหัสผ่านที่ต่างจากรหัสผ่านปัจจุบัน", confirmRequired: "ยืนยันรหัสผ่านใหม่ของคุณ", confirmMismatch: "รหัสผ่านไม่ตรงกัน" },
  vi: { verifyTitle: "Xác minh đó là bạn", verifyBody: (email) => `Nhập mã 6 chữ số chúng tôi đã gửi đến ${email}.`, codeLabel: "Mã xác minh", verifyChangeAction: "Xác minh và đổi mật khẩu", continueAction: "Tiếp tục", resend: "Yêu cầu mã mới", resendIn: (s) => `Yêu cầu mã mới sau ${mmss(s)}`, codeSent: "Đã gửi mã mới.", expiryHint: "Mã sẽ hết hạn sau 5 phút.", tryAnotherWay: "Thử cách khác", createTitle: "Tạo mật khẩu mới", currentRequired: "Nhập mật khẩu hiện tại của bạn.", currentIncorrect: "Mật khẩu hiện tại không đúng.", newTooShort: "Sử dụng ít nhất 8 ký tự.", newSame: "Chọn mật khẩu khác với mật khẩu hiện tại.", confirmRequired: "Xác nhận mật khẩu mới của bạn.", confirmMismatch: "Mật khẩu không khớp." },
};
