import { forwardRef, useCallback, useEffect, useImperativeHandle, useRef, useState, type ReactNode } from "react";
import { AccessibilityInfo, ActivityIndicator, Keyboard, Modal, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { Eye, EyeOff, KeyRound, MoreHorizontal } from "lucide-react-native";
import { travelApi, TravelApiError, type MobilePasskey } from "../../api/travelApi";
import { useMobileLocalization } from "../../localization/MobileLocalizationProvider";
import { useAppTheme } from "../../theme/AppTheme";
import { flowColors } from "../flow/flowStyles";
import { formatSecurityDate } from "./securityLocalization";
import { passkeyCopyForLocale } from "./passkeyLocalization";
import { createNativePasskey, defaultPasskeyName, isNativePasskeySupported, isPasskeyCancellation } from "../passkeys/nativePasskeys";
import { normalizeNativePasskeyCreationError, type NativePasskeyCreationDiagnostic } from "../passkeys/nativePasskeyDiagnostics";

type Purpose = "setup" | "removal";
type Stage = "list" | "verify" | "rename";
type Success = "added" | "renamed" | "removed" | null;
export type PasskeysManagerHandle = { cancelInternal: () => boolean };
type Props = { active:boolean; passkeys:MobilePasskey[]; loadError:string; hasPassword:boolean; twoFactorEnabled:boolean; onReload:()=>Promise<void>; onUnauthorized:(error:unknown)=>Promise<boolean>; onClearLoadError:()=>void };

const SUCCESS_DELAY_MS = 1000;
export const PASSKEY_FEEDBACK_DURATION_MS = 1000;
type FeedbackState = { text:string; tone:"error"|"message" } | null;

class AndroidPasskeyCreationError extends Error {
  constructor(readonly diagnostic:NativePasskeyCreationDiagnostic) { super("Android passkey creation failed"); }
}

export const PasskeysManager = forwardRef<PasskeysManagerHandle, Props>(function PasskeysManager({ active, passkeys, loadError, hasPassword, twoFactorEnabled, onReload, onUnauthorized, onClearLoadError }, ref) {
  const { theme } = useAppTheme();
  const { locale } = useMobileLocalization();
  const copy = passkeyCopyForLocale(locale);
  const [supported,setSupported]=useState<boolean|null>(null);
  const [stage,setStage]=useState<Stage>("list");
  const [purpose,setPurpose]=useState<Purpose>("setup");
  const [target,setTarget]=useState<MobilePasskey|null>(null);
  const [managed,setManaged]=useState<MobilePasskey|null>(null);
  const [confirming,setConfirming]=useState<MobilePasskey|null>(null);
  const [verification,setVerification]=useState("");
  const [passwordVisible,setPasswordVisible]=useState(false);
  const [emailCodeSent,setEmailCodeSent]=useState(false);
  const [renameValue,setRenameValue]=useState("");
  const [busy,setBusy]=useState(false);
  const [success,setSuccess]=useState<Success>(null);
  const [feedback,setFeedback]=useState<FeedbackState>(null);
  const request=useRef(0); const nativeAbort=useRef<AbortController|null>(null); const successTimer=useRef<ReturnType<typeof setTimeout>|null>(null); const feedbackTimer=useRef<ReturnType<typeof setTimeout>|null>(null); const feedbackGeneration=useRef(0);

  const clearTimer=useCallback(()=>{ if(successTimer.current){clearTimeout(successTimer.current);successTimer.current=null;} },[]);
  const clearFeedback=useCallback(()=>{ feedbackGeneration.current+=1;if(feedbackTimer.current){clearTimeout(feedbackTimer.current);feedbackTimer.current=null;}setFeedback(null); },[]);
  const showFeedback=useCallback((text:string,tone:"error"|"message"="error")=>{feedbackGeneration.current+=1;const generation=feedbackGeneration.current;if(feedbackTimer.current)clearTimeout(feedbackTimer.current);setFeedback({text,tone});feedbackTimer.current=setTimeout(()=>{if(generation!==feedbackGeneration.current)return;feedbackTimer.current=null;setFeedback(null);},PASSKEY_FEEDBACK_DURATION_MS);},[]);
  const clearSensitive=useCallback(()=>{ clearTimer(); clearFeedback(); nativeAbort.current?.abort(); nativeAbort.current=null; Keyboard.dismiss(); setVerification(""); setPasswordVisible(false); setEmailCodeSent(false); setRenameValue(""); setTarget(null); setManaged(null); setConfirming(null); setPurpose("setup"); setBusy(false); setSuccess(null); },[clearFeedback,clearTimer]);
  const cancelFlow=useCallback(()=>{ request.current+=1; clearSensitive(); onClearLoadError(); setStage("list"); },[clearSensitive,onClearLoadError]);
  useImperativeHandle(ref,()=>({cancelInternal:()=>{ if(stage==="list"&&!managed&&!confirming)return false; cancelFlow(); return true; }}),[stage,managed,confirming,cancelFlow]);

  useEffect(()=>{ const current=++request.current; if(!active){clearSensitive();setSupported(null);setStage("list");return;} onClearLoadError();void isNativePasskeySupported().then(value=>{if(current===request.current)setSupported(value);}); return()=>{request.current+=1;clearSensitive();}; },[active,clearSensitive,onClearLoadError]);
  useEffect(()=>{if(!loadError)return;showFeedback(loadError);onClearLoadError();},[loadError,onClearLoadError,showFeedback]);
  const beginVerification=(nextPurpose:Purpose,item:MobilePasskey|null=null)=>{request.current+=1;clearSensitive();onClearLoadError();setPurpose(nextPurpose);setTarget(item);setStage("verify");};
  const passkeyErrorMessage=(error:unknown,fallback:string)=>error instanceof TravelApiError&&error.status>0&&error.status<500&&error.code!=="invalid-response"?error.message:fallback;
  const fail=async(error:unknown,fallback:string,current:number)=>{if(current!==request.current)return;if(await onUnauthorized(error))return;if(current===request.current)showFeedback(passkeyErrorMessage(error,fallback));};
  const showSuccess=(kind:Exclude<Success,null>,current:number)=>{if(current!==request.current)return;Keyboard.dismiss();setBusy(false);setSuccess(kind);const message=kind==="added"?copy.added:kind==="renamed"?copy.renamed:copy.removed;AccessibilityInfo.announceForAccessibility(message);void onReload();successTimer.current=setTimeout(()=>{successTimer.current=null;if(current!==request.current)return;clearSensitive();setStage("list");},SUCCESS_DELAY_MS);};
  const registerPasskey=async(reauthToken:string,current:number)=>{const result=await travelApi.passkeyRegistrationOptions(reauthToken);if(current!==request.current)return;const controller=new AbortController();nativeAbort.current=controller;let response;try{response=await createNativePasskey(result.options,controller.signal);}catch(error){if(Platform.OS!=="android"||isPasskeyCancellation(error))throw error;const diagnostic=normalizeNativePasskeyCreationError(error);if(__DEV__)console.warn("Android passkey creation diagnostic",{platform:Platform.OS,category:diagnostic.category,code:diagnostic.safeNativeCode});throw new AndroidPasskeyCreationError(diagnostic);}finally{nativeAbort.current=null;}if(current!==request.current)return;if(!response){cancelFlow();return;}await travelApi.verifyPasskeyRegistration({name:defaultPasskeyName({ios:copy.iosDefaultName,android:copy.androidDefaultName}),response});if(current!==request.current)return;setStage("list");setVerification("");showSuccess("added",current);};
  const removePasskey=async(reauthToken:string,current:number)=>{if(!target)throw new Error(copy.operationFailed);await travelApi.removePasskey(target.id,reauthToken);showSuccess("removed",current);};
  const submitVerification=async()=>{if(busy)return;const value=twoFactorEnabled||!hasPassword?verification.trim():verification;if(!value){showFeedback(copy.verificationRequired);return;}const current=++request.current;setBusy(true);clearFeedback();try{const result=await travelApi.passkeyReauth({action:"verify",purpose,...(twoFactorEnabled||!hasPassword?{code:value}:{password:value})});if(current!==request.current)return;if(!result.reauthToken)throw new Error(copy.verificationRequired);if(purpose==="setup")await registerPasskey(result.reauthToken,current);else await removePasskey(result.reauthToken,current);}catch(error){if(isPasskeyCancellation(error)){if(current===request.current)cancelFlow();}else{const fallback=purpose==="setup"?copy.registrationFailed:copy.operationFailed;const diagnostic=error instanceof AndroidPasskeyCreationError?error.diagnostic:null;const suffix=diagnostic?` (${diagnostic.category}${diagnostic.category==="UNKNOWN_NATIVE"&&diagnostic.safeNativeCode?`: ${diagnostic.safeNativeCode}`:""})`:"";await fail(error,`${fallback}${suffix}`,current);}}finally{if(current===request.current&&!success)setBusy(false);}};
  const sendEmailCode=async()=>{if(busy)return;const current=++request.current;setBusy(true);clearFeedback();try{await travelApi.passkeyReauth({action:"send-email-code",purpose});if(current!==request.current)return;setEmailCodeSent(true);showFeedback(copy.emailCodeSent,"message");AccessibilityInfo.announceForAccessibility(copy.emailCodeSent);}catch(error){await fail(error,copy.operationFailed,current);}finally{if(current===request.current)setBusy(false);}};
  const beginRename=(item:MobilePasskey)=>{request.current+=1;clearSensitive();onClearLoadError();setTarget(item);setRenameValue(item.name);setStage("rename");};
  const saveRename=async()=>{if(busy||!target)return;const name=renameValue.trim();if(!name||name.length>80){showFeedback(copy.invalidName);return;}const current=++request.current;setBusy(true);clearFeedback();try{await travelApi.renamePasskey(target.id,name);showSuccess("renamed",current);}catch(error){await fail(error,copy.operationFailed,current);}finally{if(current===request.current&&!success)setBusy(false);}};

  if(stage==="rename")return <View style={styles.form}><Text style={[styles.heading,{color:theme.text}]}>{copy.renameTitle}</Text><Text style={[styles.detail,{color:theme.muted}]}>{copy.renameHelp}</Text><Text style={[styles.label,{color:theme.text}]}>{copy.passkeyName}</Text><TextInput accessibilityLabel={copy.passkeyName} autoCapitalize="sentences" maxLength={80} value={renameValue} onChangeText={value=>{setRenameValue(value);clearFeedback();}} style={[styles.input,{color:theme.text,borderColor:theme.border,backgroundColor:theme.surface}]}/><LocalFeedback feedback={feedback}/><ActionButton label={success==="renamed"?copy.renamed:copy.saveName} loading={busy&&success!=="renamed"} disabled={busy||success!==null} onPress={()=>void saveRename()}/></View>;
  if(stage==="verify"){
    const usesEmail=!twoFactorEnabled&&!hasPassword;const passwordMode=hasPassword&&!twoFactorEnabled;const help=twoFactorEnabled?copy.verifyTotp:hasPassword?copy.verifyPassword:copy.verifyEmail;const verificationLabel=usesEmail||twoFactorEnabled?copy.verificationCode:copy.currentPassword;
    return <View style={styles.form}><Text style={[styles.heading,{color:theme.text}]}>{copy.verifyTitle}</Text><Text style={[styles.detail,{color:theme.muted}]}>{help}</Text>{passwordMode?<Text style={[styles.detail,{color:theme.muted}]}>{copy.verifyExtra}</Text>:null}{usesEmail&&!emailCodeSent?<><ActionButton label={copy.sendEmailCode} loading={busy} disabled={busy} onPress={()=>void sendEmailCode()}/><LocalFeedback feedback={feedback}/></>:<><Text style={[styles.label,{color:theme.text}]}>{verificationLabel}</Text><View style={[styles.inputRow,{borderColor:theme.border,backgroundColor:theme.surface}]}><TextInput accessibilityLabel={verificationLabel} keyboardType={usesEmail?"number-pad":"default"} maxLength={usesEmail?6:undefined} secureTextEntry={passwordMode&&!passwordVisible} autoCapitalize="none" value={verification} onChangeText={value=>{setVerification(value);clearFeedback();}} style={[styles.inputInner,{color:theme.text}]}/>{passwordMode?<Pressable accessibilityRole="button" accessibilityLabel={passwordVisible?copy.hidePassword:copy.showPassword} onPress={()=>setPasswordVisible(value=>!value)} style={styles.eye}>{passwordVisible?<EyeOff size={20} color={theme.muted}/>:<Eye size={20} color={theme.muted}/>}</Pressable>:null}</View><LocalFeedback feedback={feedback}/><ActionButton destructive={purpose==="removal"} label={success==="removed"?copy.removed:purpose==="removal"?copy.removePasskey:copy.continue} loading={busy&&success!=="removed"} disabled={busy||success!==null} onPress={()=>void submitVerification()}/></>}</View>;
  }
  return <View style={styles.form}><Text style={[styles.sectionHeading,{color:theme.text}]}>{copy.yourPasskeys}</Text><LocalFeedback feedback={feedback}/>{passkeys.length===0?<View style={[styles.empty,{borderColor:theme.border,backgroundColor:theme.surface}]}><KeyRound size={22} color={theme.muted}/><Text style={[styles.heading,{color:theme.text}]}>{copy.noPasskeys}</Text><Text style={[styles.detail,{color:theme.muted,textAlign:"center"}]}>{copy.emptyHelp}</Text></View>:passkeys.map(item=><View key={item.id} style={[styles.passkey,{borderColor:theme.border,backgroundColor:theme.surface}]}><KeyRound size={20} color={theme.icon}/><View style={styles.rowCopy}><View style={styles.nameRow}><Text numberOfLines={1} style={[styles.rowName,{color:theme.text}]}>{item.name}</Text>{item.backedUp?<Text style={styles.badge}>{copy.synced}</Text>:null}</View><Text numberOfLines={1} style={[styles.detail,{color:theme.muted}]}>{item.label}</Text><Text style={[styles.meta,{color:theme.muted}]}>{copy.lastUsed}: {item.lastUsedAt?formatSecurityDate(item.lastUsedAt,locale):copy.neverUsed}</Text></View><Pressable accessibilityRole="button" accessibilityLabel={`${copy.managePasskey}: ${item.name}`} onPress={()=>setManaged(item)} style={styles.manage}><MoreHorizontal size={22} color={theme.icon}/></Pressable></View>)}<ActionButton label={success==="added"?copy.added:copy.addPasskey} loading={supported===null} disabled={supported!==true||busy||success!==null} onPress={()=>beginVerification("setup")}/>{supported===null?<Text style={[styles.detail,{color:theme.muted}]}>{copy.checkingSupport}</Text>:null}{supported===false?<Text accessibilityRole="alert" style={[styles.detail,{color:theme.muted}]}>{copy.unsupported}</Text>:null}<BottomSheet dismissLabel={copy.dismiss} visible={Boolean(managed)} onDismiss={()=>setManaged(null)}><Text style={[styles.heading,{color:theme.text}]}>{managed?.name}</Text><Text style={[styles.detail,{color:theme.muted}]}>{copy.managePasskey}</Text><TextAction label={copy.rename} onPress={()=>{const item=managed;setManaged(null);if(item)beginRename(item);}}/><TextAction label={copy.remove} destructive onPress={()=>{const item=managed;setManaged(null);if(item)setConfirming(item);}}/></BottomSheet><BottomSheet dismissLabel={copy.dismiss} visible={Boolean(confirming)} onDismiss={()=>setConfirming(null)}><Text style={[styles.heading,{color:theme.text}]}>{copy.removeTitle}</Text><Text style={[styles.detail,{color:theme.muted}]}>{copy.removeBody}</Text><TextAction label={copy.cancel} onPress={()=>setConfirming(null)}/><TextAction label={copy.removePasskey} destructive onPress={()=>{const item=confirming;setConfirming(null);if(item)beginVerification("removal",item);}}/></BottomSheet></View>;
});

function LocalFeedback({feedback}:{feedback:FeedbackState}){if(!feedback)return null;return <Text accessibilityRole="alert" style={feedback.tone==="error"?styles.localError:styles.localMessage}>{feedback.text}</Text>;}

function BottomSheet({visible,onDismiss,dismissLabel,children}:{visible:boolean;onDismiss:()=>void;dismissLabel:string;children:ReactNode}){const{theme}=useAppTheme();return <Modal transparent animationType="slide" visible={visible} onRequestClose={onDismiss}><Pressable accessibilityRole="button" accessibilityLabel={dismissLabel} style={styles.scrim} onPress={onDismiss}><Pressable accessibilityViewIsModal style={[styles.sheet,{backgroundColor:theme.surface}]} onPress={event=>event.stopPropagation()}>{children}</Pressable></Pressable></Modal>;}
function ActionButton({label,onPress,disabled=false,loading=false,destructive=false}:{label:string;onPress:()=>void;disabled?:boolean;loading?:boolean;destructive?:boolean}){const inactive=disabled||loading;return <Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{disabled:inactive,busy:loading}} disabled={inactive} onPress={onPress} style={({pressed})=>[styles.button,destructive&&styles.destructiveButton,inactive&&styles.disabled,pressed&&styles.pressed]}><View style={styles.buttonContent}><Text style={styles.buttonText}>{label}</Text>{loading?<ActivityIndicator size="small" color="white"/>:null}</View></Pressable>;}
function TextAction({label,onPress,destructive=false}:{label:string;onPress:()=>void;destructive?:boolean}){return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={({pressed})=>[styles.textAction,pressed&&styles.pressed]}><Text style={[styles.actionText,destructive&&styles.destructive]}>{label}</Text></Pressable>;}
const styles=StyleSheet.create({form:{gap:12},heading:{fontSize:16,lineHeight:22,fontWeight:"700"},sectionHeading:{fontSize:17,lineHeight:23,fontWeight:"800",marginTop:2},detail:{fontSize:14,lineHeight:20},label:{fontSize:14,fontWeight:"700",marginBottom:-6},input:{minHeight:50,borderWidth:1,borderRadius:10,paddingHorizontal:12,fontSize:15},inputRow:{minHeight:50,borderWidth:1,borderRadius:10,flexDirection:"row",alignItems:"center"},inputInner:{flex:1,minHeight:48,paddingHorizontal:12,fontSize:15},eye:{width:48,minHeight:48,alignItems:"center",justifyContent:"center"},button:{minHeight:50,borderRadius:10,backgroundColor:"#1769E0",alignItems:"center",justifyContent:"center",paddingHorizontal:16,marginTop:4},destructiveButton:{backgroundColor:flowColors.red},buttonContent:{flexDirection:"row",alignItems:"center",justifyContent:"center",gap:10},buttonText:{color:"white",fontWeight:"800"},disabled:{opacity:.55},pressed:{opacity:.65},passkey:{borderWidth:StyleSheet.hairlineWidth,borderRadius:12,padding:12,flexDirection:"row",alignItems:"center",gap:10},rowCopy:{flex:1,gap:2},nameRow:{flexDirection:"row",alignItems:"center",gap:8},rowName:{fontSize:15,fontWeight:"700",flexShrink:1},meta:{fontSize:12,lineHeight:17},badge:{color:"#1769E0",backgroundColor:"#E8F1FF",fontSize:11,fontWeight:"800",paddingHorizontal:7,paddingVertical:2,borderRadius:10,overflow:"hidden"},manage:{width:40,minHeight:44,alignItems:"center",justifyContent:"center"},empty:{borderWidth:StyleSheet.hairlineWidth,borderRadius:12,padding:18,alignItems:"center",gap:5},scrim:{flex:1,backgroundColor:"rgba(0,0,0,0.38)",justifyContent:"flex-end"},sheet:{padding:20,paddingBottom:28,borderTopLeftRadius:20,borderTopRightRadius:20,gap:8},textAction:{minHeight:46,justifyContent:"center"},actionText:{color:"#1769E0",fontWeight:"700",fontSize:16},destructive:{color:flowColors.red},localError:{color:"#B42318",fontWeight:"600",lineHeight:20},localMessage:{color:"#067647",fontWeight:"600",lineHeight:20}});
