import type { MobileLocale } from "../../localization/mobileLocalizationCatalog";

const english = {
  addPasskey: "Add passkey",
  added: "Passkey added",
  yourPasskeys: "Your passkeys",
  noPasskeys: "No passkeys yet",
  emptyHelp: "Add one to sign in faster and more securely.",
  managePasskey: "Manage this passkey",
  synced: "Synced",
  unsupported: "Passkeys are not available in this app build or on this device. Install the latest Kurioticket Preview build and make sure a screen lock is enabled.",
  checkingSupport: "Checking passkey support…",
  created: "Created",
  lastUsed: "Last used",
  neverUsed: "Not used yet",
  rename: "Rename",
  remove: "Remove",
  cancel: "Cancel",
  dismiss: "Dismiss",
  renameTitle: "Rename passkey",
  passkeyName: "Passkey name",
  renameHelp: "Choose a name that helps you recognize this passkey.",
  saveName: "Save",
  invalidName: "Enter a name of no more than 80 characters.",
  renamed: "Renamed",
  removeTitle: "Remove passkey?",
  removeBody: "You won’t be able to use this passkey to sign in anymore.",
  removePasskey: "Remove passkey",
  removed: "Passkey removed",
  verifyTitle: "Verify your account",
  verifyTotp: "Enter an authenticator code or recovery code before continuing.",
  verifyPassword: "Enter your current password to continue.",
  verifyExtra: "This extra step helps protect changes to your passkeys.",
  showPassword: "Show password",
  hidePassword: "Hide password",
  verifyEmail: "We will send a six-digit verification code to your account email.",
  verificationCode: "Verification code",
  currentPassword: "Current password",
  sendEmailCode: "Send verification code",
  emailCodeSent: "A verification code was sent to your account email.",
  continue: "Continue",
  operationFailed: "Unable to update passkeys. Try again.",
  registrationFailed: "Unable to create this passkey. Try again.",
  verificationRequired: "Enter the requested verification before continuing.",
  iosDefaultName: "iPhone passkey",
  androidDefaultName: "Android passkey",
} as const;

export type PasskeyCopy = { [K in keyof typeof english]: string };

const spanish: PasskeyCopy = {
  addPasskey: "Añadir llave de acceso",
  added: "Llave de acceso añadida",
  yourPasskeys: "Tus llaves de acceso",
  noPasskeys: "Aún no hay llaves de acceso",
  emptyHelp: "Añade una para iniciar sesión de forma más rápida y segura.",
  managePasskey: "Gestionar esta llave de acceso",
  synced: "Sincronizada",
  unsupported: "Las llaves de acceso no están disponibles en esta versión de la aplicación o en este dispositivo. Instala la última versión Preview de Kurioticket y asegúrate de tener un bloqueo de pantalla.",
  checkingSupport: "Comprobando la compatibilidad con llaves de acceso…",
  created: "Creada",
  lastUsed: "Último uso",
  neverUsed: "Aún no se ha usado",
  rename: "Cambiar nombre",
  remove: "Eliminar",
  cancel: "Cancelar",
  dismiss: "Cerrar",
  renameTitle: "Cambiar el nombre de la llave",
  passkeyName: "Nombre de la llave de acceso",
  renameHelp: "Elige un nombre que te ayude a reconocer esta llave de acceso.",
  saveName: "Guardar",
  invalidName: "Introduce un nombre de no más de 80 caracteres.",
  renamed: "Nombre cambiado",
  removeTitle: "¿Eliminar llave de acceso?",
  removeBody: "Ya no podrás usar esta llave de acceso para iniciar sesión.",
  removePasskey: "Eliminar llave de acceso",
  removed: "Llave de acceso eliminada",
  verifyTitle: "Verifica tu cuenta",
  verifyTotp: "Introduce un código del autenticador o un código de recuperación antes de continuar.",
  verifyPassword: "Introduce tu contraseña actual para continuar.",
  verifyExtra: "Este paso adicional ayuda a proteger los cambios en tus llaves de acceso.",
  showPassword: "Mostrar contraseña",
  hidePassword: "Ocultar contraseña",
  verifyEmail: "Enviaremos un código de verificación de seis dígitos al correo de tu cuenta.",
  verificationCode: "Código de verificación",
  currentPassword: "Contraseña actual",
  sendEmailCode: "Enviar código de verificación",
  emailCodeSent: "Se envió un código de verificación al correo de tu cuenta.",
  continue: "Continuar",
  operationFailed: "No se pudieron actualizar las llaves de acceso. Inténtalo de nuevo.",
  registrationFailed: "No se pudo crear esta llave de acceso. Inténtalo de nuevo.",
  verificationRequired: "Introduce la verificación solicitada antes de continuar.",
  iosDefaultName: "Llave de acceso del iPhone",
  androidDefaultName: "Llave de acceso de Android",
};

export function passkeyCopyForLocale(locale: MobileLocale): PasskeyCopy {
  return locale === "es-es" ? spanish : english;
}
