import { mobileLocaleCodes, mobileLocales, type MobileLocale } from "../../localization/mobileLocalizationCatalog";

const englishSecurityCopy = {
  "title": "Security",
  "intro": "Manage sign-in and account security for your Kurioticket account.",
  "loading": "Loading security settings…",
  "loadError": "Unable to load security settings.",
  "retry": "Try again",
  "back": "Go back",
  "close": "Close",
  "password": "Password",
  "passwordHelp": "Change the password used to sign in to your account.",
  "configured": "Configured",
  "notConfigured": "Not configured",
  "current": "Current password",
  "next": "New password",
  "confirm": "Confirm new password",
  "show": "Show password",
  "hide": "Hide password",
  "change": "Change password",
  "changing": "Changing…",
  "passwordRules": "Use at least 8 characters and choose a different password.",
  "passwordInvalid": "Check that passwords match, contain at least 8 characters, and differ from the current password.",
  "passwordSuccess": "Password changed. Other devices were signed out.",
  "oauth": "This account does not have a password. Use password reset to create one.",
  "reset": "Email password reset link",
  "resetSent": "If the account can receive reset email, instructions were sent.",
  "twoFactor": "Two-factor authentication",
  "twoFactorHelp": "Add extra protection with an authenticator app.",
  "passkeys": "Passkeys",
  "passkeysHelp": "Use your device screen lock, Face ID, fingerprint, password manager, or security key to sign in faster and more securely.",
  "activeSessions": "Active sessions",
  "activeSessionsHelp": "Review devices signed in to your account.",
  "yourDevices": "Your devices",
  "devicesHelp": "Review devices that have recently accessed your account.",
  "currentDevice": "Current device",
  "lastActive": "Last active",
  "remove": "Remove device",
  "removeTitle": "Remove this device?",
  "removeBody": "This device will need to sign in again.",
  "cancel": "Cancel",
  "removeFailed": "Unable to remove this device.",
  "signOutAll": "Sign out everywhere",
  "signOutAllHelp": "End every web and mobile session connected to your account.",
  "signOutTitle": "Sign out everywhere?",
  "signOutBody": "Every web and mobile session, including this device, will be ended.",
  "signOutFailed": "Unable to sign out every device. Try again.",
  "notifications": "Security notifications",
  "alertsHelp": "Receive important email about account security.",
  "saving": "Saving…",
  "saved": "Saved",
  "saveFailed": "Unable to save. Your previous setting is unchanged.",
  "activity": "Security activity",
  "activityHelp": "Review recent sign-ins and security changes.",
  "empty": "No recent security activity.",
  "deleteAccount": "Delete account",
  "openFailed": "Unable to open the secure web experience.",
  "unknown": "Security update",
  "enabled": "Enabled",
  "disabled": "Disabled",
  "twoFactorSetupHelp": "Protect your account with a code from an authenticator app.",
  "setupTwoFactor": "Set up two-factor authentication",
  "setupInstructions": "Add this account to your authenticator app using the setup key or URI, then enter its six-digit code.",
  "scanQrInstructions": "Scan this QR code with your authenticator app.",
  "manualSetupInstructions": "Or enter this setup key manually.",
  "twoFactorQrAccessibilityLabel": "Two-factor authentication QR code",
  "authenticatorCode": "Authenticator code",
  "confirmSetup": "Confirm setup",
  "codeInvalid": "Enter exactly 6 digits.",
  "twoFactorError": "Unable to update two-factor authentication.",
  "recoveryTitle": "Recovery codes",
  "recoveryHelp": "Save these codes somewhere secure. They will not be shown again.",
  "disable": "Disable two-factor authentication",
  "disableTitle": "Disable two-factor authentication?",
  "disableBody": "Verify this security change, then disable two-factor authentication.",
  "disableHelp": "Enter an authenticator or recovery code, or your password, to verify this change.",
  "verification": "Authenticator code, recovery code, or password",
  "deletionHelp": "Account deletion becomes permanent after the 7-day grace period. You may reactivate your account during the supported grace period.",
  "requestDeletion": "Request account deletion",
  "deletionConfirmTitle": "Request account deletion?",
  "deletionConfirmBody": "Your account is scheduled for permanent deletion in 7 days. This action is destructive.",
  "pendingDeletion": "Pending deletion",
  "scheduledDate": "Scheduled deletion date",
  "keepAccount": "Keep my account / Cancel deletion",
  "reactivated": "Account deletion cancelled.",
  "deletionError": "Unable to update account deletion.",
  "addPasskey": "Add passkey",
  "passkeyPreviewRequired": "A new Preview app binary with native Passkey support is required to add credentials.",
  "created": "Created",
  "passkeysLoadError": "Unable to load passkeys."
} as const;
export type SecurityCopy = { [K in keyof typeof englishSecurityCopy]: string };

const es_es: SecurityCopy = {
  "title": "Seguridad",
  "intro": "Gestiona el acceso y la seguridad de tu cuenta de Kurioticket.",
  "loading": "Cargando configuración de seguridad…",
  "loadError": "No se pudo cargar la configuración de seguridad.",
  "retry": "Intentar de nuevo",
  "back": "Volver",
  "close": "Cerrar",
  "password": "Contraseña",
  "passwordHelp": "Cambia la contraseña que usas para acceder a tu cuenta.",
  "configured": "Configurada",
  "notConfigured": "No configurada",
  "current": "Contraseña actual",
  "next": "Nueva contraseña",
  "confirm": "Confirmar nueva contraseña",
  "show": "Mostrar contraseña",
  "hide": "Ocultar contraseña",
  "change": "Cambiar contraseña",
  "changing": "Cambiando…",
  "passwordRules": "Usa al menos 8 caracteres y elige una contraseña diferente.",
  "passwordInvalid": "Comprueba que coincidan, tengan al menos 8 caracteres y sean diferentes de la actual.",
  "passwordSuccess": "Contraseña cambiada. Se cerraron las otras sesiones.",
  "oauth": "Esta cuenta no tiene contraseña. Usa el restablecimiento para crear una.",
  "reset": "Enviar enlace de restablecimiento",
  "resetSent": "Si la cuenta puede recibir el correo, se enviaron instrucciones.",
  "twoFactor": "Autenticación en dos pasos",
  "twoFactorHelp": "Añade protección adicional con una aplicación de autenticación.",
  "passkeys": "Llaves de acceso",
  "passkeysHelp": "Usa el bloqueo de pantalla, Face ID, huella digital, gestor de contraseñas o llave de seguridad para acceder de forma más rápida y segura.",
  "activeSessions": "Sesiones activas",
  "activeSessionsHelp": "Revisa los dispositivos con sesiones abiertas en tu cuenta.",
  "yourDevices": "Tus dispositivos",
  "devicesHelp": "Revisa los dispositivos que han accedido recientemente a tu cuenta.",
  "currentDevice": "Dispositivo actual",
  "lastActive": "Última actividad",
  "remove": "Eliminar dispositivo",
  "removeTitle": "¿Eliminar este dispositivo?",
  "removeBody": "Este dispositivo tendrá que iniciar sesión de nuevo.",
  "cancel": "Cancelar",
  "removeFailed": "No se pudo eliminar el dispositivo.",
  "signOutAll": "Cerrar sesión en todas partes",
  "signOutAllHelp": "Finaliza todas las sesiones web y móviles conectadas a tu cuenta.",
  "signOutTitle": "¿Cerrar sesión en todas partes?",
  "signOutBody": "Finalizarán todas las sesiones web y móviles, incluida esta.",
  "signOutFailed": "No se pudo cerrar sesión en todos los dispositivos. Inténtalo de nuevo.",
  "notifications": "Notificaciones de seguridad",
  "alertsHelp": "Recibe correos importantes sobre la seguridad de la cuenta.",
  "saving": "Guardando…",
  "saved": "Guardado",
  "saveFailed": "No se pudo guardar. Se mantiene la opción anterior.",
  "activity": "Actividad de seguridad",
  "activityHelp": "Revisa los inicios de sesión y cambios de seguridad recientes.",
  "empty": "No hay actividad de seguridad reciente.",
  "deleteAccount": "Eliminar cuenta",
  "openFailed": "No se pudo abrir la experiencia web segura.",
  "unknown": "Actualización de seguridad",
  "enabled": "Activada",
  "disabled": "Desactivada",
  "twoFactorSetupHelp": "Protege tu cuenta con un código de una aplicación de autenticación.",
  "setupTwoFactor": "Configurar la autenticación en dos pasos",
  "setupInstructions": "Añade esta cuenta a tu aplicación con la clave o URI y escribe el código de seis dígitos.",
  "scanQrInstructions": "Escanea este código QR con tu aplicación de autenticación.",
  "manualSetupInstructions": "O introduce esta clave de configuración manualmente.",
  "twoFactorQrAccessibilityLabel": "Código QR de autenticación en dos pasos",
  "authenticatorCode": "Código del autenticador",
  "confirmSetup": "Confirmar configuración",
  "codeInvalid": "Introduce exactamente 6 dígitos.",
  "twoFactorError": "No se pudo actualizar la autenticación en dos pasos.",
  "recoveryTitle": "Códigos de recuperación",
  "recoveryHelp": "Guarda estos códigos en un lugar seguro. No volverán a mostrarse.",
  "disable": "Desactivar la autenticación en dos pasos",
  "disableTitle": "¿Desactivar la autenticación en dos pasos?",
  "disableBody": "Verifica este cambio de seguridad y desactiva la autenticación en dos pasos.",
  "disableHelp": "Introduce un código de autenticador o recuperación, o tu contraseña.",
  "verification": "Código de autenticador, recuperación o contraseña",
  "deletionHelp": "La eliminación será permanente tras el período de gracia de 7 días. Puedes reactivar tu cuenta durante ese período.",
  "requestDeletion": "Solicitar la eliminación de la cuenta",
  "deletionConfirmTitle": "¿Solicitar la eliminación de la cuenta?",
  "deletionConfirmBody": "Tu cuenta se eliminará permanentemente en 7 días. Esta acción es destructiva.",
  "pendingDeletion": "Eliminación pendiente",
  "scheduledDate": "Fecha de eliminación programada",
  "keepAccount": "Conservar mi cuenta / Cancelar eliminación",
  "reactivated": "Se canceló la eliminación de la cuenta.",
  "deletionError": "No se pudo actualizar la eliminación de la cuenta.",
  "addPasskey": "Añadir llave de acceso",
  "passkeyPreviewRequired": "Se necesita una nueva versión de la aplicación Preview con compatibilidad nativa con llaves de acceso para añadir credenciales.",
  "created": "Creada",
  "passkeysLoadError": "No se pudieron cargar las llaves de acceso."
};

const fr: SecurityCopy = {
  "title": "Sécurité",
  "intro": "Modifiez vos paramètres de sécurité, configurez une authentification sécurisée ou gérez l’accès au compte.",
  "loading": "Loading security settings…",
  "loadError": "Unable to load security settings.",
  "retry": "Réessayer",
  "back": "Go back",
  "close": "Fermer",
  "password": "Mot de passe",
  "passwordHelp": "Change the password used to sign in to your account.",
  "configured": "Configured",
  "notConfigured": "Not configured",
  "current": "Current password",
  "next": "Nouveau mot de passe",
  "confirm": "Confirmer le nouveau mot de passe",
  "show": "Show password",
  "hide": "Hide password",
  "change": "Change password",
  "changing": "Changing…",
  "passwordRules": "Use at least 8 characters and choose a different password.",
  "passwordInvalid": "Check that passwords match, contain at least 8 characters, and differ from the current password.",
  "passwordSuccess": "Password changed. Other devices were signed out.",
  "oauth": "This account does not have a password. Use password reset to create one.",
  "reset": "Email password reset link",
  "resetSent": "If the account can receive reset email, instructions were sent.",
  "twoFactor": "Authentification à deux facteurs",
  "twoFactorHelp": "Ajoutez une couche de sécurité supplémentaire à votre compte.",
  "passkeys": "Clés d’accès",
  "passkeysHelp": "Connectez-vous en toute sécurité sans devoir mémoriser un mot de passe.",
  "activeSessions": "Sessions actives",
  "activeSessionsHelp": "Vérifiez où votre compte est connecté et déconnectez les autres appareils.",
  "yourDevices": "Your devices",
  "devicesHelp": "Review devices that have recently accessed your account.",
  "currentDevice": "Current device",
  "lastActive": "Last active",
  "remove": "Remove device",
  "removeTitle": "Remove this device?",
  "removeBody": "This device will need to sign in again.",
  "cancel": "Annuler",
  "removeFailed": "Unable to remove this device.",
  "signOutAll": "Sign out everywhere",
  "signOutAllHelp": "End every web and mobile session connected to your account.",
  "signOutTitle": "Sign out everywhere?",
  "signOutBody": "Every web and mobile session, including this device, will be ended.",
  "signOutFailed": "Unable to sign out every device. Try again.",
  "notifications": "Security notifications",
  "alertsHelp": "Receive important email about account security.",
  "saving": "Saving...",
  "saved": "Enregistrés",
  "saveFailed": "Unable to save. Your previous setting is unchanged.",
  "activity": "Security activity",
  "activityHelp": "Review recent sign-ins and security changes.",
  "empty": "No recent security activity.",
  "deleteAccount": "Supprimer le compte",
  "openFailed": "Unable to open the secure web experience.",
  "unknown": "Security update",
  "enabled": "Enabled",
  "disabled": "Disabled",
  "twoFactorSetupHelp": "Protect your account with a code from an authenticator app.",
  "setupTwoFactor": "Set up two-factor authentication",
  "setupInstructions": "Add this account to your authenticator app using the setup key or URI, then enter its six-digit code.",
  "scanQrInstructions": "Scan this QR code with your authenticator app.",
  "manualSetupInstructions": "Or enter this setup key manually.",
  "twoFactorQrAccessibilityLabel": "Two-factor authentication QR code",
  "authenticatorCode": "Authenticator code",
  "confirmSetup": "Confirm setup",
  "codeInvalid": "Enter exactly 6 digits.",
  "twoFactorError": "Unable to update two-factor authentication.",
  "recoveryTitle": "Recovery codes",
  "recoveryHelp": "Save these codes somewhere secure. They will not be shown again.",
  "disable": "Disable two-factor authentication",
  "disableTitle": "Disable two-factor authentication?",
  "disableBody": "Verify this security change, then disable two-factor authentication.",
  "disableHelp": "Enter an authenticator or recovery code, or your password, to verify this change.",
  "verification": "Authenticator code, recovery code, or password",
  "deletionHelp": "Account deletion becomes permanent after the 7-day grace period. You may reactivate your account during the supported grace period.",
  "requestDeletion": "Request account deletion",
  "deletionConfirmTitle": "Request account deletion?",
  "deletionConfirmBody": "Your account is scheduled for permanent deletion in 7 days. This action is destructive.",
  "pendingDeletion": "Pending deletion",
  "scheduledDate": "Scheduled deletion date",
  "keepAccount": "Keep my account / Cancel deletion",
  "reactivated": "Account deletion cancelled.",
  "deletionError": "Unable to update account deletion.",
  "addPasskey": "Add passkey",
  "passkeyPreviewRequired": "A new Preview app binary with native Passkey support is required to add credentials.",
  "created": "Créée",
  "passkeysLoadError": "Unable to load passkeys."
};

const de_de: SecurityCopy = {
  "title": "Sicherheit",
  "intro": "Ändern Sie Ihre Sicherheitseinstellungen, richten Sie sichere Authentifizierung ein oder verwalten Sie den Kontozugriff.",
  "loading": "Loading security settings…",
  "loadError": "Unable to load security settings.",
  "retry": "Erneut versuchen",
  "back": "Go back",
  "close": "Schließen",
  "password": "Passwort",
  "passwordHelp": "Change the password used to sign in to your account.",
  "configured": "Configured",
  "notConfigured": "Not configured",
  "current": "Current password",
  "next": "Neues Passwort",
  "confirm": "Neues Passwort bestätigen",
  "show": "Show password",
  "hide": "Hide password",
  "change": "Change password",
  "changing": "Changing…",
  "passwordRules": "Use at least 8 characters and choose a different password.",
  "passwordInvalid": "Check that passwords match, contain at least 8 characters, and differ from the current password.",
  "passwordSuccess": "Password changed. Other devices were signed out.",
  "oauth": "This account does not have a password. Use password reset to create one.",
  "reset": "Email password reset link",
  "resetSent": "If the account can receive reset email, instructions were sent.",
  "twoFactor": "Zwei-Faktor-Authentifizierung",
  "twoFactorHelp": "Fügen Sie Ihrem Konto eine zusätzliche Sicherheitsebene hinzu.",
  "passkeys": "Zugangsschlüssel",
  "passkeysHelp": "Melden Sie sich sicher an, ohne sich ein Passwort merken zu müssen.",
  "activeSessions": "Aktive Sitzungen",
  "activeSessionsHelp": "Prüfen Sie, wo Ihr Konto angemeldet ist, und melden Sie andere Geräte ab.",
  "yourDevices": "Your devices",
  "devicesHelp": "Review devices that have recently accessed your account.",
  "currentDevice": "Current device",
  "lastActive": "Last active",
  "remove": "Remove device",
  "removeTitle": "Remove this device?",
  "removeBody": "This device will need to sign in again.",
  "cancel": "Abbrechen",
  "removeFailed": "Unable to remove this device.",
  "signOutAll": "Sign out everywhere",
  "signOutAllHelp": "End every web and mobile session connected to your account.",
  "signOutTitle": "Sign out everywhere?",
  "signOutBody": "Every web and mobile session, including this device, will be ended.",
  "signOutFailed": "Unable to sign out every device. Try again.",
  "notifications": "Security notifications",
  "alertsHelp": "Receive important email about account security.",
  "saving": "Saving...",
  "saved": "Gespeichert",
  "saveFailed": "Unable to save. Your previous setting is unchanged.",
  "activity": "Security activity",
  "activityHelp": "Review recent sign-ins and security changes.",
  "empty": "No recent security activity.",
  "deleteAccount": "Konto löschen",
  "openFailed": "Unable to open the secure web experience.",
  "unknown": "Security update",
  "enabled": "Enabled",
  "disabled": "Disabled",
  "twoFactorSetupHelp": "Protect your account with a code from an authenticator app.",
  "setupTwoFactor": "Set up two-factor authentication",
  "setupInstructions": "Add this account to your authenticator app using the setup key or URI, then enter its six-digit code.",
  "scanQrInstructions": "Scan this QR code with your authenticator app.",
  "manualSetupInstructions": "Or enter this setup key manually.",
  "twoFactorQrAccessibilityLabel": "Two-factor authentication QR code",
  "authenticatorCode": "Authenticator code",
  "confirmSetup": "Confirm setup",
  "codeInvalid": "Enter exactly 6 digits.",
  "twoFactorError": "Unable to update two-factor authentication.",
  "recoveryTitle": "Recovery codes",
  "recoveryHelp": "Save these codes somewhere secure. They will not be shown again.",
  "disable": "Disable two-factor authentication",
  "disableTitle": "Disable two-factor authentication?",
  "disableBody": "Verify this security change, then disable two-factor authentication.",
  "disableHelp": "Enter an authenticator or recovery code, or your password, to verify this change.",
  "verification": "Authenticator code, recovery code, or password",
  "deletionHelp": "Account deletion becomes permanent after the 7-day grace period. You may reactivate your account during the supported grace period.",
  "requestDeletion": "Request account deletion",
  "deletionConfirmTitle": "Request account deletion?",
  "deletionConfirmBody": "Your account is scheduled for permanent deletion in 7 days. This action is destructive.",
  "pendingDeletion": "Pending deletion",
  "scheduledDate": "Scheduled deletion date",
  "keepAccount": "Keep my account / Cancel deletion",
  "reactivated": "Account deletion cancelled.",
  "deletionError": "Unable to update account deletion.",
  "addPasskey": "Add passkey",
  "passkeyPreviewRequired": "A new Preview app binary with native Passkey support is required to add credentials.",
  "created": "Erstellt",
  "passkeysLoadError": "Unable to load passkeys."
};

const it_it: SecurityCopy = {
  "title": "Impostazioni di sicurezza",
  "intro": "Modifica le impostazioni di sicurezza, configura l’autenticazione sicura o gestisci l’accesso all’account.",
  "loading": "Loading security settings…",
  "loadError": "Unable to load security settings.",
  "retry": "Riprova",
  "back": "Go back",
  "close": "Chiudi",
  "password": "Parola d’accesso",
  "passwordHelp": "Change the password used to sign in to your account.",
  "configured": "Configured",
  "notConfigured": "Not configured",
  "current": "Current password",
  "next": "Nuova password",
  "confirm": "Conferma nuova password",
  "show": "Show password",
  "hide": "Hide password",
  "change": "Change password",
  "changing": "Changing…",
  "passwordRules": "Use at least 8 characters and choose a different password.",
  "passwordInvalid": "Check that passwords match, contain at least 8 characters, and differ from the current password.",
  "passwordSuccess": "Password changed. Other devices were signed out.",
  "oauth": "This account does not have a password. Use password reset to create one.",
  "reset": "Email password reset link",
  "resetSent": "If the account can receive reset email, instructions were sent.",
  "twoFactor": "Autenticazione a due fattori",
  "twoFactorHelp": "Aggiungi un livello extra di sicurezza al tuo account.",
  "passkeys": "Passkey",
  "passkeysHelp": "Accedi in modo sicuro senza dover ricordare una password.",
  "activeSessions": "Sessioni attive",
  "activeSessionsHelp": "Controlla dove il tuo account ha effettuato l’accesso e disconnettiti dagli altri dispositivi.",
  "yourDevices": "Your devices",
  "devicesHelp": "Review devices that have recently accessed your account.",
  "currentDevice": "Current device",
  "lastActive": "Last active",
  "remove": "Remove device",
  "removeTitle": "Remove this device?",
  "removeBody": "This device will need to sign in again.",
  "cancel": "Annulla",
  "removeFailed": "Unable to remove this device.",
  "signOutAll": "Sign out everywhere",
  "signOutAllHelp": "End every web and mobile session connected to your account.",
  "signOutTitle": "Sign out everywhere?",
  "signOutBody": "Every web and mobile session, including this device, will be ended.",
  "signOutFailed": "Unable to sign out every device. Try again.",
  "notifications": "Security notifications",
  "alertsHelp": "Receive important email about account security.",
  "saving": "Saving...",
  "saved": "Salvati",
  "saveFailed": "Unable to save. Your previous setting is unchanged.",
  "activity": "Security activity",
  "activityHelp": "Review recent sign-ins and security changes.",
  "empty": "No recent security activity.",
  "deleteAccount": "Elimina account",
  "openFailed": "Unable to open the secure web experience.",
  "unknown": "Security update",
  "enabled": "Enabled",
  "disabled": "Disabled",
  "twoFactorSetupHelp": "Protect your account with a code from an authenticator app.",
  "setupTwoFactor": "Set up two-factor authentication",
  "setupInstructions": "Add this account to your authenticator app using the setup key or URI, then enter its six-digit code.",
  "scanQrInstructions": "Scan this QR code with your authenticator app.",
  "manualSetupInstructions": "Or enter this setup key manually.",
  "twoFactorQrAccessibilityLabel": "Two-factor authentication QR code",
  "authenticatorCode": "Authenticator code",
  "confirmSetup": "Confirm setup",
  "codeInvalid": "Enter exactly 6 digits.",
  "twoFactorError": "Unable to update two-factor authentication.",
  "recoveryTitle": "Recovery codes",
  "recoveryHelp": "Save these codes somewhere secure. They will not be shown again.",
  "disable": "Disable two-factor authentication",
  "disableTitle": "Disable two-factor authentication?",
  "disableBody": "Verify this security change, then disable two-factor authentication.",
  "disableHelp": "Enter an authenticator or recovery code, or your password, to verify this change.",
  "verification": "Authenticator code, recovery code, or password",
  "deletionHelp": "Account deletion becomes permanent after the 7-day grace period. You may reactivate your account during the supported grace period.",
  "requestDeletion": "Request account deletion",
  "deletionConfirmTitle": "Request account deletion?",
  "deletionConfirmBody": "Your account is scheduled for permanent deletion in 7 days. This action is destructive.",
  "pendingDeletion": "Pending deletion",
  "scheduledDate": "Scheduled deletion date",
  "keepAccount": "Keep my account / Cancel deletion",
  "reactivated": "Account deletion cancelled.",
  "deletionError": "Unable to update account deletion.",
  "addPasskey": "Add passkey",
  "passkeyPreviewRequired": "A new Preview app binary with native Passkey support is required to add credentials.",
  "created": "Creato",
  "passkeysLoadError": "Unable to load passkeys."
};

const pt_br: SecurityCopy = {
  "title": "Segurança",
  "intro": "Atualize sua senha e gerencie a segurança da conta.",
  "loading": "Loading security settings…",
  "loadError": "Unable to load security settings.",
  "retry": "Tentar novamente",
  "back": "Go back",
  "close": "Fechar",
  "password": "Senha",
  "passwordHelp": "Change the password used to sign in to your account.",
  "configured": "Configured",
  "notConfigured": "Not configured",
  "current": "Current password",
  "next": "Nova senha",
  "confirm": "Confirmar nova senha",
  "show": "Show password",
  "hide": "Hide password",
  "change": "Change password",
  "changing": "Changing…",
  "passwordRules": "Use at least 8 characters and choose a different password.",
  "passwordInvalid": "Check that passwords match, contain at least 8 characters, and differ from the current password.",
  "passwordSuccess": "Password changed. Other devices were signed out.",
  "oauth": "This account does not have a password. Use password reset to create one.",
  "reset": "Email password reset link",
  "resetSent": "If the account can receive reset email, instructions were sent.",
  "twoFactor": "Autenticação de dois fatores",
  "twoFactorHelp": "Adicione uma camada extra de segurança à sua conta.",
  "passkeys": "Chaves de acesso",
  "passkeysHelp": "Entre com segurança sem precisar lembrar uma senha.",
  "activeSessions": "Sessões ativas",
  "activeSessionsHelp": "Veja onde sua conta está conectada e saia de outros dispositivos.",
  "yourDevices": "Your devices",
  "devicesHelp": "Review devices that have recently accessed your account.",
  "currentDevice": "Current device",
  "lastActive": "Last active",
  "remove": "Remove device",
  "removeTitle": "Remove this device?",
  "removeBody": "This device will need to sign in again.",
  "cancel": "Cancelar",
  "removeFailed": "Unable to remove this device.",
  "signOutAll": "Sign out everywhere",
  "signOutAllHelp": "End every web and mobile session connected to your account.",
  "signOutTitle": "Sign out everywhere?",
  "signOutBody": "Every web and mobile session, including this device, will be ended.",
  "signOutFailed": "Unable to sign out every device. Try again.",
  "notifications": "Security notifications",
  "alertsHelp": "Receive important email about account security.",
  "saving": "Saving...",
  "saved": "Salvos",
  "saveFailed": "Unable to save. Your previous setting is unchanged.",
  "activity": "Security activity",
  "activityHelp": "Review recent sign-ins and security changes.",
  "empty": "No recent security activity.",
  "deleteAccount": "Excluir conta",
  "openFailed": "Unable to open the secure web experience.",
  "unknown": "Security update",
  "enabled": "Enabled",
  "disabled": "Disabled",
  "twoFactorSetupHelp": "Protect your account with a code from an authenticator app.",
  "setupTwoFactor": "Set up two-factor authentication",
  "setupInstructions": "Add this account to your authenticator app using the setup key or URI, then enter its six-digit code.",
  "scanQrInstructions": "Scan this QR code with your authenticator app.",
  "manualSetupInstructions": "Or enter this setup key manually.",
  "twoFactorQrAccessibilityLabel": "Two-factor authentication QR code",
  "authenticatorCode": "Authenticator code",
  "confirmSetup": "Confirm setup",
  "codeInvalid": "Enter exactly 6 digits.",
  "twoFactorError": "Unable to update two-factor authentication.",
  "recoveryTitle": "Recovery codes",
  "recoveryHelp": "Save these codes somewhere secure. They will not be shown again.",
  "disable": "Disable two-factor authentication",
  "disableTitle": "Disable two-factor authentication?",
  "disableBody": "Verify this security change, then disable two-factor authentication.",
  "disableHelp": "Enter an authenticator or recovery code, or your password, to verify this change.",
  "verification": "Authenticator code, recovery code, or password",
  "deletionHelp": "Account deletion becomes permanent after the 7-day grace period. You may reactivate your account during the supported grace period.",
  "requestDeletion": "Request account deletion",
  "deletionConfirmTitle": "Request account deletion?",
  "deletionConfirmBody": "Your account is scheduled for permanent deletion in 7 days. This action is destructive.",
  "pendingDeletion": "Pending deletion",
  "scheduledDate": "Scheduled deletion date",
  "keepAccount": "Keep my account / Cancel deletion",
  "reactivated": "Account deletion cancelled.",
  "deletionError": "Unable to update account deletion.",
  "addPasskey": "Add passkey",
  "passkeyPreviewRequired": "A new Preview app binary with native Passkey support is required to add credentials.",
  "created": "Criado",
  "passkeysLoadError": "Unable to load passkeys."
};

const nl: SecurityCopy = {
  "title": "Beveiliging",
  "intro": "Werk je wachtwoord bij en beheer je accountbeveiliging.",
  "loading": "Loading security settings…",
  "loadError": "Unable to load security settings.",
  "retry": "Opnieuw proberen",
  "back": "Go back",
  "close": "Sluiten",
  "password": "Wachtwoord",
  "passwordHelp": "Change the password used to sign in to your account.",
  "configured": "Configured",
  "notConfigured": "Not configured",
  "current": "Current password",
  "next": "Nieuw wachtwoord",
  "confirm": "Bevestig nieuw wachtwoord",
  "show": "Show password",
  "hide": "Hide password",
  "change": "Change password",
  "changing": "Changing…",
  "passwordRules": "Use at least 8 characters and choose a different password.",
  "passwordInvalid": "Check that passwords match, contain at least 8 characters, and differ from the current password.",
  "passwordSuccess": "Password changed. Other devices were signed out.",
  "oauth": "This account does not have a password. Use password reset to create one.",
  "reset": "Email password reset link",
  "resetSent": "If the account can receive reset email, instructions were sent.",
  "twoFactor": "Twee-factor-authenticatie",
  "twoFactorHelp": "Voeg een extra beveiligingslaag toe aan je account.",
  "passkeys": "Toegangssleutels",
  "passkeysHelp": "Log veilig in zonder een wachtwoord te hoeven onthouden.",
  "activeSessions": "Actieve sessies",
  "activeSessionsHelp": "Bekijk waar je account is ingelogd en meld je af op andere apparaten.",
  "yourDevices": "Your devices",
  "devicesHelp": "Review devices that have recently accessed your account.",
  "currentDevice": "Current device",
  "lastActive": "Last active",
  "remove": "Remove device",
  "removeTitle": "Remove this device?",
  "removeBody": "This device will need to sign in again.",
  "cancel": "Annuleren",
  "removeFailed": "Unable to remove this device.",
  "signOutAll": "Sign out everywhere",
  "signOutAllHelp": "End every web and mobile session connected to your account.",
  "signOutTitle": "Sign out everywhere?",
  "signOutBody": "Every web and mobile session, including this device, will be ended.",
  "signOutFailed": "Unable to sign out every device. Try again.",
  "notifications": "Security notifications",
  "alertsHelp": "Receive important email about account security.",
  "saving": "Saving...",
  "saved": "Opgeslagen",
  "saveFailed": "Unable to save. Your previous setting is unchanged.",
  "activity": "Security activity",
  "activityHelp": "Review recent sign-ins and security changes.",
  "empty": "No recent security activity.",
  "deleteAccount": "Account verwijderen",
  "openFailed": "Unable to open the secure web experience.",
  "unknown": "Security update",
  "enabled": "Enabled",
  "disabled": "Disabled",
  "twoFactorSetupHelp": "Protect your account with a code from an authenticator app.",
  "setupTwoFactor": "Set up two-factor authentication",
  "setupInstructions": "Add this account to your authenticator app using the setup key or URI, then enter its six-digit code.",
  "scanQrInstructions": "Scan this QR code with your authenticator app.",
  "manualSetupInstructions": "Or enter this setup key manually.",
  "twoFactorQrAccessibilityLabel": "Two-factor authentication QR code",
  "authenticatorCode": "Authenticator code",
  "confirmSetup": "Confirm setup",
  "codeInvalid": "Enter exactly 6 digits.",
  "twoFactorError": "Unable to update two-factor authentication.",
  "recoveryTitle": "Recovery codes",
  "recoveryHelp": "Save these codes somewhere secure. They will not be shown again.",
  "disable": "Disable two-factor authentication",
  "disableTitle": "Disable two-factor authentication?",
  "disableBody": "Verify this security change, then disable two-factor authentication.",
  "disableHelp": "Enter an authenticator or recovery code, or your password, to verify this change.",
  "verification": "Authenticator code, recovery code, or password",
  "deletionHelp": "Account deletion becomes permanent after the 7-day grace period. You may reactivate your account during the supported grace period.",
  "requestDeletion": "Request account deletion",
  "deletionConfirmTitle": "Request account deletion?",
  "deletionConfirmBody": "Your account is scheduled for permanent deletion in 7 days. This action is destructive.",
  "pendingDeletion": "Pending deletion",
  "scheduledDate": "Scheduled deletion date",
  "keepAccount": "Keep my account / Cancel deletion",
  "reactivated": "Account deletion cancelled.",
  "deletionError": "Unable to update account deletion.",
  "addPasskey": "Add passkey",
  "passkeyPreviewRequired": "A new Preview app binary with native Passkey support is required to add credentials.",
  "created": "Aangemaakt",
  "passkeysLoadError": "Unable to load passkeys."
};

const ar: SecurityCopy = {
  "title": "Security",
  "intro": "حدّث كلمة المرور وأدر أمان الحساب.",
  "loading": "Loading security settings…",
  "loadError": "Unable to load security settings.",
  "retry": "إعادة المحاولة",
  "back": "Go back",
  "close": "إغلاق",
  "password": "كلمة المرور",
  "passwordHelp": "Change the password used to sign in to your account.",
  "configured": "Configured",
  "notConfigured": "Not configured",
  "current": "Current password",
  "next": "كلمة المرور الجديدة",
  "confirm": "تأكيد كلمة المرور الجديدة",
  "show": "Show password",
  "hide": "Hide password",
  "change": "Change password",
  "changing": "Changing…",
  "passwordRules": "Use at least 8 characters and choose a different password.",
  "passwordInvalid": "Check that passwords match, contain at least 8 characters, and differ from the current password.",
  "passwordSuccess": "Password changed. Other devices were signed out.",
  "oauth": "This account does not have a password. Use password reset to create one.",
  "reset": "Email password reset link",
  "resetSent": "If the account can receive reset email, instructions were sent.",
  "twoFactor": "المصادقة الثنائية",
  "twoFactorHelp": "أضف طبقة أمان إضافية إلى حسابك.",
  "passkeys": "مفاتيح المرور",
  "passkeysHelp": "استخدم مفاتيح المرور لتسجيل دخول أسرع وأكثر أمانًا.",
  "activeSessions": "الجلسات النشطة",
  "activeSessionsHelp": "راجع الأجهزة المسجلة الدخول حاليًا.",
  "yourDevices": "Your devices",
  "devicesHelp": "Review devices that have recently accessed your account.",
  "currentDevice": "Current device",
  "lastActive": "Last active",
  "remove": "Remove device",
  "removeTitle": "Remove this device?",
  "removeBody": "This device will need to sign in again.",
  "cancel": "إلغاء",
  "removeFailed": "Unable to remove this device.",
  "signOutAll": "Sign out everywhere",
  "signOutAllHelp": "End every web and mobile session connected to your account.",
  "signOutTitle": "Sign out everywhere?",
  "signOutBody": "Every web and mobile session, including this device, will be ended.",
  "signOutFailed": "Unable to sign out every device. Try again.",
  "notifications": "Security notifications",
  "alertsHelp": "Receive important email about account security.",
  "saving": "Saving...",
  "saved": "المحفوظات",
  "saveFailed": "Unable to save. Your previous setting is unchanged.",
  "activity": "Security activity",
  "activityHelp": "Review recent sign-ins and security changes.",
  "empty": "No recent security activity.",
  "deleteAccount": "حذف الحساب",
  "openFailed": "Unable to open the secure web experience.",
  "unknown": "Security update",
  "enabled": "Enabled",
  "disabled": "Disabled",
  "twoFactorSetupHelp": "Protect your account with a code from an authenticator app.",
  "setupTwoFactor": "Set up two-factor authentication",
  "setupInstructions": "Add this account to your authenticator app using the setup key or URI, then enter its six-digit code.",
  "scanQrInstructions": "Scan this QR code with your authenticator app.",
  "manualSetupInstructions": "Or enter this setup key manually.",
  "twoFactorQrAccessibilityLabel": "Two-factor authentication QR code",
  "authenticatorCode": "Authenticator code",
  "confirmSetup": "Confirm setup",
  "codeInvalid": "Enter exactly 6 digits.",
  "twoFactorError": "Unable to update two-factor authentication.",
  "recoveryTitle": "Recovery codes",
  "recoveryHelp": "Save these codes somewhere secure. They will not be shown again.",
  "disable": "Disable two-factor authentication",
  "disableTitle": "Disable two-factor authentication?",
  "disableBody": "Verify this security change, then disable two-factor authentication.",
  "disableHelp": "Enter an authenticator or recovery code, or your password, to verify this change.",
  "verification": "Authenticator code, recovery code, or password",
  "deletionHelp": "Account deletion becomes permanent after the 7-day grace period. You may reactivate your account during the supported grace period.",
  "requestDeletion": "Request account deletion",
  "deletionConfirmTitle": "Request account deletion?",
  "deletionConfirmBody": "Your account is scheduled for permanent deletion in 7 days. This action is destructive.",
  "pendingDeletion": "Pending deletion",
  "scheduledDate": "Scheduled deletion date",
  "keepAccount": "Keep my account / Cancel deletion",
  "reactivated": "Account deletion cancelled.",
  "deletionError": "Unable to update account deletion.",
  "addPasskey": "Add passkey",
  "passkeyPreviewRequired": "A new Preview app binary with native Passkey support is required to add credentials.",
  "created": "Created",
  "passkeysLoadError": "Unable to load passkeys."
};

const zh_cn: SecurityCopy = {
  "title": "Security",
  "intro": "更新你的密码并管理账户安全。",
  "loading": "Loading security settings…",
  "loadError": "Unable to load security settings.",
  "retry": "重试",
  "back": "Go back",
  "close": "关闭",
  "password": "密码",
  "passwordHelp": "Change the password used to sign in to your account.",
  "configured": "Configured",
  "notConfigured": "Not configured",
  "current": "Current password",
  "next": "新密码",
  "confirm": "确认新密码",
  "show": "Show password",
  "hide": "Hide password",
  "change": "Change password",
  "changing": "Changing…",
  "passwordRules": "Use at least 8 characters and choose a different password.",
  "passwordInvalid": "Check that passwords match, contain at least 8 characters, and differ from the current password.",
  "passwordSuccess": "Password changed. Other devices were signed out.",
  "oauth": "This account does not have a password. Use password reset to create one.",
  "reset": "Email password reset link",
  "resetSent": "If the account can receive reset email, instructions were sent.",
  "twoFactor": "双重身份验证",
  "twoFactorHelp": "为你的账户增加一层额外安全保护。",
  "passkeys": "通行密钥",
  "passkeysHelp": "无需记住密码，即可安全登录。",
  "activeSessions": "活跃会话",
  "activeSessionsHelp": "查看你的账户在哪些设备上登录，并从其他设备退出。",
  "yourDevices": "Your devices",
  "devicesHelp": "Review devices that have recently accessed your account.",
  "currentDevice": "Current device",
  "lastActive": "Last active",
  "remove": "Remove device",
  "removeTitle": "Remove this device?",
  "removeBody": "This device will need to sign in again.",
  "cancel": "取消",
  "removeFailed": "Unable to remove this device.",
  "signOutAll": "Sign out everywhere",
  "signOutAllHelp": "End every web and mobile session connected to your account.",
  "signOutTitle": "Sign out everywhere?",
  "signOutBody": "Every web and mobile session, including this device, will be ended.",
  "signOutFailed": "Unable to sign out every device. Try again.",
  "notifications": "Security notifications",
  "alertsHelp": "Receive important email about account security.",
  "saving": "Saving...",
  "saved": "已保存",
  "saveFailed": "Unable to save. Your previous setting is unchanged.",
  "activity": "Security activity",
  "activityHelp": "Review recent sign-ins and security changes.",
  "empty": "No recent security activity.",
  "deleteAccount": "删除账户",
  "openFailed": "Unable to open the secure web experience.",
  "unknown": "Security update",
  "enabled": "Enabled",
  "disabled": "Disabled",
  "twoFactorSetupHelp": "Protect your account with a code from an authenticator app.",
  "setupTwoFactor": "Set up two-factor authentication",
  "setupInstructions": "Add this account to your authenticator app using the setup key or URI, then enter its six-digit code.",
  "scanQrInstructions": "Scan this QR code with your authenticator app.",
  "manualSetupInstructions": "Or enter this setup key manually.",
  "twoFactorQrAccessibilityLabel": "Two-factor authentication QR code",
  "authenticatorCode": "Authenticator code",
  "confirmSetup": "Confirm setup",
  "codeInvalid": "Enter exactly 6 digits.",
  "twoFactorError": "Unable to update two-factor authentication.",
  "recoveryTitle": "Recovery codes",
  "recoveryHelp": "Save these codes somewhere secure. They will not be shown again.",
  "disable": "Disable two-factor authentication",
  "disableTitle": "Disable two-factor authentication?",
  "disableBody": "Verify this security change, then disable two-factor authentication.",
  "disableHelp": "Enter an authenticator or recovery code, or your password, to verify this change.",
  "verification": "Authenticator code, recovery code, or password",
  "deletionHelp": "Account deletion becomes permanent after the 7-day grace period. You may reactivate your account during the supported grace period.",
  "requestDeletion": "Request account deletion",
  "deletionConfirmTitle": "Request account deletion?",
  "deletionConfirmBody": "Your account is scheduled for permanent deletion in 7 days. This action is destructive.",
  "pendingDeletion": "Pending deletion",
  "scheduledDate": "Scheduled deletion date",
  "keepAccount": "Keep my account / Cancel deletion",
  "reactivated": "Account deletion cancelled.",
  "deletionError": "Unable to update account deletion.",
  "addPasskey": "Add passkey",
  "passkeyPreviewRequired": "A new Preview app binary with native Passkey support is required to add credentials.",
  "created": "Created",
  "passkeysLoadError": "Unable to load passkeys."
};

const ja: SecurityCopy = {
  "title": "Security",
  "intro": "パスワードを更新し、アカウントのセキュリティを管理します。",
  "loading": "Loading security settings…",
  "loadError": "Unable to load security settings.",
  "retry": "もう一度試す",
  "back": "Go back",
  "close": "閉じる",
  "password": "パスワード",
  "passwordHelp": "Change the password used to sign in to your account.",
  "configured": "Configured",
  "notConfigured": "Not configured",
  "current": "Current password",
  "next": "新しいパスワード",
  "confirm": "新しいパスワードを確認",
  "show": "Show password",
  "hide": "Hide password",
  "change": "Change password",
  "changing": "Changing…",
  "passwordRules": "Use at least 8 characters and choose a different password.",
  "passwordInvalid": "Check that passwords match, contain at least 8 characters, and differ from the current password.",
  "passwordSuccess": "Password changed. Other devices were signed out.",
  "oauth": "This account does not have a password. Use password reset to create one.",
  "reset": "Email password reset link",
  "resetSent": "If the account can receive reset email, instructions were sent.",
  "twoFactor": "2要素認証",
  "twoFactorHelp": "アカウントに追加のセキュリティ層を追加します。",
  "passkeys": "パスキー",
  "passkeysHelp": "パスワードを覚えなくても安全にサインインできます。",
  "activeSessions": "アクティブなセッション",
  "activeSessionsHelp": "アカウントがサインインしている場所を確認し、他のデバイスからサインアウトします。",
  "yourDevices": "Your devices",
  "devicesHelp": "Review devices that have recently accessed your account.",
  "currentDevice": "Current device",
  "lastActive": "Last active",
  "remove": "Remove device",
  "removeTitle": "Remove this device?",
  "removeBody": "This device will need to sign in again.",
  "cancel": "キャンセル",
  "removeFailed": "Unable to remove this device.",
  "signOutAll": "Sign out everywhere",
  "signOutAllHelp": "End every web and mobile session connected to your account.",
  "signOutTitle": "Sign out everywhere?",
  "signOutBody": "Every web and mobile session, including this device, will be ended.",
  "signOutFailed": "Unable to sign out every device. Try again.",
  "notifications": "Security notifications",
  "alertsHelp": "Receive important email about account security.",
  "saving": "Saving...",
  "saved": "保存済み",
  "saveFailed": "Unable to save. Your previous setting is unchanged.",
  "activity": "Security activity",
  "activityHelp": "Review recent sign-ins and security changes.",
  "empty": "No recent security activity.",
  "deleteAccount": "アカウントを削除",
  "openFailed": "Unable to open the secure web experience.",
  "unknown": "Security update",
  "enabled": "Enabled",
  "disabled": "Disabled",
  "twoFactorSetupHelp": "Protect your account with a code from an authenticator app.",
  "setupTwoFactor": "Set up two-factor authentication",
  "setupInstructions": "Add this account to your authenticator app using the setup key or URI, then enter its six-digit code.",
  "scanQrInstructions": "Scan this QR code with your authenticator app.",
  "manualSetupInstructions": "Or enter this setup key manually.",
  "twoFactorQrAccessibilityLabel": "Two-factor authentication QR code",
  "authenticatorCode": "Authenticator code",
  "confirmSetup": "Confirm setup",
  "codeInvalid": "Enter exactly 6 digits.",
  "twoFactorError": "Unable to update two-factor authentication.",
  "recoveryTitle": "Recovery codes",
  "recoveryHelp": "Save these codes somewhere secure. They will not be shown again.",
  "disable": "Disable two-factor authentication",
  "disableTitle": "Disable two-factor authentication?",
  "disableBody": "Verify this security change, then disable two-factor authentication.",
  "disableHelp": "Enter an authenticator or recovery code, or your password, to verify this change.",
  "verification": "Authenticator code, recovery code, or password",
  "deletionHelp": "Account deletion becomes permanent after the 7-day grace period. You may reactivate your account during the supported grace period.",
  "requestDeletion": "Request account deletion",
  "deletionConfirmTitle": "Request account deletion?",
  "deletionConfirmBody": "Your account is scheduled for permanent deletion in 7 days. This action is destructive.",
  "pendingDeletion": "Pending deletion",
  "scheduledDate": "Scheduled deletion date",
  "keepAccount": "Keep my account / Cancel deletion",
  "reactivated": "Account deletion cancelled.",
  "deletionError": "Unable to update account deletion.",
  "addPasskey": "Add passkey",
  "passkeyPreviewRequired": "A new Preview app binary with native Passkey support is required to add credentials.",
  "created": "Created",
  "passkeysLoadError": "Unable to load passkeys."
};

const ko: SecurityCopy = {
  "title": "Security",
  "intro": "비밀번호를 업데이트하고 계정 보안을 관리하세요.",
  "loading": "Loading security settings…",
  "loadError": "Unable to load security settings.",
  "retry": "다시 시도",
  "back": "Go back",
  "close": "닫기",
  "password": "비밀번호",
  "passwordHelp": "Change the password used to sign in to your account.",
  "configured": "Configured",
  "notConfigured": "Not configured",
  "current": "Current password",
  "next": "새 비밀번호",
  "confirm": "새 비밀번호 확인",
  "show": "Show password",
  "hide": "Hide password",
  "change": "Change password",
  "changing": "Changing…",
  "passwordRules": "Use at least 8 characters and choose a different password.",
  "passwordInvalid": "Check that passwords match, contain at least 8 characters, and differ from the current password.",
  "passwordSuccess": "Password changed. Other devices were signed out.",
  "oauth": "This account does not have a password. Use password reset to create one.",
  "reset": "Email password reset link",
  "resetSent": "If the account can receive reset email, instructions were sent.",
  "twoFactor": "2단계 인증",
  "twoFactorHelp": "계정에 보안 단계를 하나 더 추가하세요.",
  "passkeys": "패스키",
  "passkeysHelp": "비밀번호를 기억하지 않아도 안전하게 로그인하세요.",
  "activeSessions": "활성 세션",
  "activeSessionsHelp": "계정이 로그인된 위치를 확인하고 다른 기기에서 로그아웃하세요.",
  "yourDevices": "Your devices",
  "devicesHelp": "Review devices that have recently accessed your account.",
  "currentDevice": "Current device",
  "lastActive": "Last active",
  "remove": "Remove device",
  "removeTitle": "Remove this device?",
  "removeBody": "This device will need to sign in again.",
  "cancel": "취소",
  "removeFailed": "Unable to remove this device.",
  "signOutAll": "Sign out everywhere",
  "signOutAllHelp": "End every web and mobile session connected to your account.",
  "signOutTitle": "Sign out everywhere?",
  "signOutBody": "Every web and mobile session, including this device, will be ended.",
  "signOutFailed": "Unable to sign out every device. Try again.",
  "notifications": "Security notifications",
  "alertsHelp": "Receive important email about account security.",
  "saving": "Saving...",
  "saved": "저장됨",
  "saveFailed": "Unable to save. Your previous setting is unchanged.",
  "activity": "Security activity",
  "activityHelp": "Review recent sign-ins and security changes.",
  "empty": "No recent security activity.",
  "deleteAccount": "계정 삭제",
  "openFailed": "Unable to open the secure web experience.",
  "unknown": "Security update",
  "enabled": "Enabled",
  "disabled": "Disabled",
  "twoFactorSetupHelp": "Protect your account with a code from an authenticator app.",
  "setupTwoFactor": "Set up two-factor authentication",
  "setupInstructions": "Add this account to your authenticator app using the setup key or URI, then enter its six-digit code.",
  "scanQrInstructions": "Scan this QR code with your authenticator app.",
  "manualSetupInstructions": "Or enter this setup key manually.",
  "twoFactorQrAccessibilityLabel": "Two-factor authentication QR code",
  "authenticatorCode": "Authenticator code",
  "confirmSetup": "Confirm setup",
  "codeInvalid": "Enter exactly 6 digits.",
  "twoFactorError": "Unable to update two-factor authentication.",
  "recoveryTitle": "Recovery codes",
  "recoveryHelp": "Save these codes somewhere secure. They will not be shown again.",
  "disable": "Disable two-factor authentication",
  "disableTitle": "Disable two-factor authentication?",
  "disableBody": "Verify this security change, then disable two-factor authentication.",
  "disableHelp": "Enter an authenticator or recovery code, or your password, to verify this change.",
  "verification": "Authenticator code, recovery code, or password",
  "deletionHelp": "Account deletion becomes permanent after the 7-day grace period. You may reactivate your account during the supported grace period.",
  "requestDeletion": "Request account deletion",
  "deletionConfirmTitle": "Request account deletion?",
  "deletionConfirmBody": "Your account is scheduled for permanent deletion in 7 days. This action is destructive.",
  "pendingDeletion": "Pending deletion",
  "scheduledDate": "Scheduled deletion date",
  "keepAccount": "Keep my account / Cancel deletion",
  "reactivated": "Account deletion cancelled.",
  "deletionError": "Unable to update account deletion.",
  "addPasskey": "Add passkey",
  "passkeyPreviewRequired": "A new Preview app binary with native Passkey support is required to add credentials.",
  "created": "Created",
  "passkeysLoadError": "Unable to load passkeys."
};

const hi: SecurityCopy = {
  "title": "Security",
  "intro": "अपना पासवर्ड अपडेट करें और खाते की सुरक्षा प्रबंधित करें।",
  "loading": "Loading security settings…",
  "loadError": "Unable to load security settings.",
  "retry": "फिर से कोशिश करें",
  "back": "Go back",
  "close": "बंद करें",
  "password": "पासवर्ड",
  "passwordHelp": "Change the password used to sign in to your account.",
  "configured": "Configured",
  "notConfigured": "Not configured",
  "current": "Current password",
  "next": "नया पासवर्ड",
  "confirm": "नए पासवर्ड की पुष्टि करें",
  "show": "Show password",
  "hide": "Hide password",
  "change": "Change password",
  "changing": "Changing…",
  "passwordRules": "Use at least 8 characters and choose a different password.",
  "passwordInvalid": "Check that passwords match, contain at least 8 characters, and differ from the current password.",
  "passwordSuccess": "Password changed. Other devices were signed out.",
  "oauth": "This account does not have a password. Use password reset to create one.",
  "reset": "Email password reset link",
  "resetSent": "If the account can receive reset email, instructions were sent.",
  "twoFactor": "दो-कारक प्रमाणीकरण",
  "twoFactorHelp": "अपने खाते में सुरक्षा की एक अतिरिक्त परत जोड़ें।",
  "passkeys": "पासकी",
  "passkeysHelp": "पासवर्ड याद रखने की आवश्यकता के बिना सुरक्षित रूप से साइन इन करें।",
  "activeSessions": "सक्रिय सत्र",
  "activeSessionsHelp": "देखें कि आपका खाता कहाँ साइन इन है और अन्य डिवाइसों से साइन आउट करें।",
  "yourDevices": "Your devices",
  "devicesHelp": "Review devices that have recently accessed your account.",
  "currentDevice": "Current device",
  "lastActive": "Last active",
  "remove": "Remove device",
  "removeTitle": "Remove this device?",
  "removeBody": "This device will need to sign in again.",
  "cancel": "रद्द करें",
  "removeFailed": "Unable to remove this device.",
  "signOutAll": "Sign out everywhere",
  "signOutAllHelp": "End every web and mobile session connected to your account.",
  "signOutTitle": "Sign out everywhere?",
  "signOutBody": "Every web and mobile session, including this device, will be ended.",
  "signOutFailed": "Unable to sign out every device. Try again.",
  "notifications": "Security notifications",
  "alertsHelp": "Receive important email about account security.",
  "saving": "Saving...",
  "saved": "सहेजे गए",
  "saveFailed": "Unable to save. Your previous setting is unchanged.",
  "activity": "Security activity",
  "activityHelp": "Review recent sign-ins and security changes.",
  "empty": "No recent security activity.",
  "deleteAccount": "खाता हटाएँ",
  "openFailed": "Unable to open the secure web experience.",
  "unknown": "Security update",
  "enabled": "Enabled",
  "disabled": "Disabled",
  "twoFactorSetupHelp": "Protect your account with a code from an authenticator app.",
  "setupTwoFactor": "Set up two-factor authentication",
  "setupInstructions": "Add this account to your authenticator app using the setup key or URI, then enter its six-digit code.",
  "scanQrInstructions": "Scan this QR code with your authenticator app.",
  "manualSetupInstructions": "Or enter this setup key manually.",
  "twoFactorQrAccessibilityLabel": "Two-factor authentication QR code",
  "authenticatorCode": "Authenticator code",
  "confirmSetup": "Confirm setup",
  "codeInvalid": "Enter exactly 6 digits.",
  "twoFactorError": "Unable to update two-factor authentication.",
  "recoveryTitle": "Recovery codes",
  "recoveryHelp": "Save these codes somewhere secure. They will not be shown again.",
  "disable": "Disable two-factor authentication",
  "disableTitle": "Disable two-factor authentication?",
  "disableBody": "Verify this security change, then disable two-factor authentication.",
  "disableHelp": "Enter an authenticator or recovery code, or your password, to verify this change.",
  "verification": "Authenticator code, recovery code, or password",
  "deletionHelp": "Account deletion becomes permanent after the 7-day grace period. You may reactivate your account during the supported grace period.",
  "requestDeletion": "Request account deletion",
  "deletionConfirmTitle": "Request account deletion?",
  "deletionConfirmBody": "Your account is scheduled for permanent deletion in 7 days. This action is destructive.",
  "pendingDeletion": "Pending deletion",
  "scheduledDate": "Scheduled deletion date",
  "keepAccount": "Keep my account / Cancel deletion",
  "reactivated": "Account deletion cancelled.",
  "deletionError": "Unable to update account deletion.",
  "addPasskey": "Add passkey",
  "passkeyPreviewRequired": "A new Preview app binary with native Passkey support is required to add credentials.",
  "created": "बनाया गया",
  "passkeysLoadError": "Unable to load passkeys."
};

const tr: SecurityCopy = {
  "title": "Security",
  "intro": "Şifrenizi güncelleyin ve hesap güvenliğinizi yönetin.",
  "loading": "Loading security settings…",
  "loadError": "Unable to load security settings.",
  "retry": "Tekrar deneyin",
  "back": "Go back",
  "close": "Kapat",
  "password": "Şifre",
  "passwordHelp": "Change the password used to sign in to your account.",
  "configured": "Configured",
  "notConfigured": "Not configured",
  "current": "Current password",
  "next": "Yeni şifre",
  "confirm": "Yeni şifreyi onayla",
  "show": "Show password",
  "hide": "Hide password",
  "change": "Change password",
  "changing": "Changing…",
  "passwordRules": "Use at least 8 characters and choose a different password.",
  "passwordInvalid": "Check that passwords match, contain at least 8 characters, and differ from the current password.",
  "passwordSuccess": "Password changed. Other devices were signed out.",
  "oauth": "This account does not have a password. Use password reset to create one.",
  "reset": "Email password reset link",
  "resetSent": "If the account can receive reset email, instructions were sent.",
  "twoFactor": "İki faktörlü kimlik doğrulama",
  "twoFactorHelp": "Hesabınıza ek bir güvenlik katmanı ekleyin.",
  "passkeys": "Geçiş anahtarları",
  "passkeysHelp": "Şifre hatırlamanıza gerek kalmadan güvenli şekilde oturum açın.",
  "activeSessions": "Aktif oturumlar",
  "activeSessionsHelp": "Hesabınızın nerelerde açık olduğunu inceleyin ve diğer cihazlardan çıkış yapın.",
  "yourDevices": "Your devices",
  "devicesHelp": "Review devices that have recently accessed your account.",
  "currentDevice": "Current device",
  "lastActive": "Last active",
  "remove": "Remove device",
  "removeTitle": "Remove this device?",
  "removeBody": "This device will need to sign in again.",
  "cancel": "İptal",
  "removeFailed": "Unable to remove this device.",
  "signOutAll": "Sign out everywhere",
  "signOutAllHelp": "End every web and mobile session connected to your account.",
  "signOutTitle": "Sign out everywhere?",
  "signOutBody": "Every web and mobile session, including this device, will be ended.",
  "signOutFailed": "Unable to sign out every device. Try again.",
  "notifications": "Security notifications",
  "alertsHelp": "Receive important email about account security.",
  "saving": "Saving...",
  "saved": "Kaydedilenler",
  "saveFailed": "Unable to save. Your previous setting is unchanged.",
  "activity": "Security activity",
  "activityHelp": "Review recent sign-ins and security changes.",
  "empty": "No recent security activity.",
  "deleteAccount": "Hesabı sil",
  "openFailed": "Unable to open the secure web experience.",
  "unknown": "Security update",
  "enabled": "Enabled",
  "disabled": "Disabled",
  "twoFactorSetupHelp": "Protect your account with a code from an authenticator app.",
  "setupTwoFactor": "Set up two-factor authentication",
  "setupInstructions": "Add this account to your authenticator app using the setup key or URI, then enter its six-digit code.",
  "scanQrInstructions": "Scan this QR code with your authenticator app.",
  "manualSetupInstructions": "Or enter this setup key manually.",
  "twoFactorQrAccessibilityLabel": "Two-factor authentication QR code",
  "authenticatorCode": "Authenticator code",
  "confirmSetup": "Confirm setup",
  "codeInvalid": "Enter exactly 6 digits.",
  "twoFactorError": "Unable to update two-factor authentication.",
  "recoveryTitle": "Recovery codes",
  "recoveryHelp": "Save these codes somewhere secure. They will not be shown again.",
  "disable": "Disable two-factor authentication",
  "disableTitle": "Disable two-factor authentication?",
  "disableBody": "Verify this security change, then disable two-factor authentication.",
  "disableHelp": "Enter an authenticator or recovery code, or your password, to verify this change.",
  "verification": "Authenticator code, recovery code, or password",
  "deletionHelp": "Account deletion becomes permanent after the 7-day grace period. You may reactivate your account during the supported grace period.",
  "requestDeletion": "Request account deletion",
  "deletionConfirmTitle": "Request account deletion?",
  "deletionConfirmBody": "Your account is scheduled for permanent deletion in 7 days. This action is destructive.",
  "pendingDeletion": "Pending deletion",
  "scheduledDate": "Scheduled deletion date",
  "keepAccount": "Keep my account / Cancel deletion",
  "reactivated": "Account deletion cancelled.",
  "deletionError": "Unable to update account deletion.",
  "addPasskey": "Add passkey",
  "passkeyPreviewRequired": "A new Preview app binary with native Passkey support is required to add credentials.",
  "created": "Oluşturuldu",
  "passkeysLoadError": "Unable to load passkeys."
};

const pl: SecurityCopy = {
  "title": "Security",
  "intro": "Zarządzaj logowaniem i bezpieczeństwem swojego konta Kurioticket.",
  "loading": "Loading security settings…",
  "loadError": "Unable to load security settings.",
  "retry": "Spróbuj ponownie",
  "back": "Go back",
  "close": "Zamknij",
  "password": "Hasło",
  "passwordHelp": "Zmień hasło używane do logowania na konto.",
  "configured": "Configured",
  "notConfigured": "Not configured",
  "current": "Current password",
  "next": "Nowe hasło",
  "confirm": "Potwierdź nowe hasło",
  "show": "Show password",
  "hide": "Hide password",
  "change": "Zmień hasło",
  "changing": "Changing…",
  "passwordRules": "Use at least 8 characters and choose a different password.",
  "passwordInvalid": "Check that passwords match, contain at least 8 characters, and differ from the current password.",
  "passwordSuccess": "Password changed. Other devices were signed out.",
  "oauth": "This account does not have a password. Use password reset to create one.",
  "reset": "Email password reset link",
  "resetSent": "If the account can receive reset email, instructions were sent.",
  "twoFactor": "Uwierzytelnianie dwuskładnikowe",
  "twoFactorHelp": "Dodaj dodatkową ochronę za pomocą aplikacji uwierzytelniającej.",
  "passkeys": "Klucze dostępu",
  "passkeysHelp": "Użyj urządzenia lub klucza bezpieczeństwa, aby logować się szybciej.",
  "activeSessions": "Aktywne sesje",
  "activeSessionsHelp": "Sprawdź urządzenia zalogowane na Twoje konto.",
  "yourDevices": "Your devices",
  "devicesHelp": "Review devices that have recently accessed your account.",
  "currentDevice": "Current device",
  "lastActive": "Last active",
  "remove": "Remove device",
  "removeTitle": "Remove this device?",
  "removeBody": "This device will need to sign in again.",
  "cancel": "Anuluj",
  "removeFailed": "Unable to remove this device.",
  "signOutAll": "Sign out everywhere",
  "signOutAllHelp": "End every web and mobile session connected to your account.",
  "signOutTitle": "Sign out everywhere?",
  "signOutBody": "Every web and mobile session, including this device, will be ended.",
  "signOutFailed": "Unable to sign out every device. Try again.",
  "notifications": "Powiadomienia bezpieczeństwa",
  "alertsHelp": "Receive important email about account security.",
  "saving": "Saving...",
  "saved": "Zapisane",
  "saveFailed": "Unable to save. Your previous setting is unchanged.",
  "activity": "Security activity",
  "activityHelp": "Review recent sign-ins and security changes.",
  "empty": "No recent security activity.",
  "deleteAccount": "Usuń konto",
  "openFailed": "Unable to open the secure web experience.",
  "unknown": "Security update",
  "enabled": "Enabled",
  "disabled": "Disabled",
  "twoFactorSetupHelp": "Protect your account with a code from an authenticator app.",
  "setupTwoFactor": "Set up two-factor authentication",
  "setupInstructions": "Add this account to your authenticator app using the setup key or URI, then enter its six-digit code.",
  "scanQrInstructions": "Scan this QR code with your authenticator app.",
  "manualSetupInstructions": "Or enter this setup key manually.",
  "twoFactorQrAccessibilityLabel": "Two-factor authentication QR code",
  "authenticatorCode": "Authenticator code",
  "confirmSetup": "Confirm setup",
  "codeInvalid": "Enter exactly 6 digits.",
  "twoFactorError": "Unable to update two-factor authentication.",
  "recoveryTitle": "Recovery codes",
  "recoveryHelp": "Save these codes somewhere secure. They will not be shown again.",
  "disable": "Disable two-factor authentication",
  "disableTitle": "Disable two-factor authentication?",
  "disableBody": "Verify this security change, then disable two-factor authentication.",
  "disableHelp": "Enter an authenticator or recovery code, or your password, to verify this change.",
  "verification": "Authenticator code, recovery code, or password",
  "deletionHelp": "Account deletion becomes permanent after the 7-day grace period. You may reactivate your account during the supported grace period.",
  "requestDeletion": "Request account deletion",
  "deletionConfirmTitle": "Request account deletion?",
  "deletionConfirmBody": "Your account is scheduled for permanent deletion in 7 days. This action is destructive.",
  "pendingDeletion": "Pending deletion",
  "scheduledDate": "Scheduled deletion date",
  "keepAccount": "Keep my account / Cancel deletion",
  "reactivated": "Account deletion cancelled.",
  "deletionError": "Unable to update account deletion.",
  "addPasskey": "Add passkey",
  "passkeyPreviewRequired": "A new Preview app binary with native Passkey support is required to add credentials.",
  "created": "Created",
  "passkeysLoadError": "Unable to load passkeys."
};

const sv: SecurityCopy = {
  "title": "Security",
  "intro": "Hantera inloggning och kontosäkerhet för ditt Kurioticket-konto.",
  "loading": "Loading security settings…",
  "loadError": "Unable to load security settings.",
  "retry": "Försök igen",
  "back": "Go back",
  "close": "Stäng",
  "password": "Lösenord",
  "passwordHelp": "Ändra lösenordet som används för att logga in på ditt konto.",
  "configured": "Configured",
  "notConfigured": "Not configured",
  "current": "Current password",
  "next": "Nytt lösenord",
  "confirm": "Bekräfta nytt lösenord",
  "show": "Show password",
  "hide": "Hide password",
  "change": "Ändra lösenord",
  "changing": "Changing…",
  "passwordRules": "Use at least 8 characters and choose a different password.",
  "passwordInvalid": "Check that passwords match, contain at least 8 characters, and differ from the current password.",
  "passwordSuccess": "Password changed. Other devices were signed out.",
  "oauth": "This account does not have a password. Use password reset to create one.",
  "reset": "Email password reset link",
  "resetSent": "If the account can receive reset email, instructions were sent.",
  "twoFactor": "Tvåfaktorsautentisering",
  "twoFactorHelp": "Lägg till extra skydd med en autentiseringsapp.",
  "passkeys": "Passkeys",
  "passkeysHelp": "Använd enhetens skärmlås, Face ID, fingeravtryck, lösenordshanterare eller säkerhetsnyckel för att logga in snabbare och säkrare.",
  "activeSessions": "Aktiva sessioner",
  "activeSessionsHelp": "Granska enheter som är inloggade på ditt konto.",
  "yourDevices": "Your devices",
  "devicesHelp": "Review devices that have recently accessed your account.",
  "currentDevice": "Current device",
  "lastActive": "Last active",
  "remove": "Remove device",
  "removeTitle": "Remove this device?",
  "removeBody": "This device will need to sign in again.",
  "cancel": "Avbryt",
  "removeFailed": "Unable to remove this device.",
  "signOutAll": "Sign out everywhere",
  "signOutAllHelp": "End every web and mobile session connected to your account.",
  "signOutTitle": "Sign out everywhere?",
  "signOutBody": "Every web and mobile session, including this device, will be ended.",
  "signOutFailed": "Unable to sign out every device. Try again.",
  "notifications": "Säkerhetsaviseringar",
  "alertsHelp": "Receive important email about account security.",
  "saving": "Saving...",
  "saved": "Sparade",
  "saveFailed": "Unable to save. Your previous setting is unchanged.",
  "activity": "Security activity",
  "activityHelp": "Review recent sign-ins and security changes.",
  "empty": "No recent security activity.",
  "deleteAccount": "Radera konto",
  "openFailed": "Unable to open the secure web experience.",
  "unknown": "Security update",
  "enabled": "Enabled",
  "disabled": "Disabled",
  "twoFactorSetupHelp": "Protect your account with a code from an authenticator app.",
  "setupTwoFactor": "Set up two-factor authentication",
  "setupInstructions": "Add this account to your authenticator app using the setup key or URI, then enter its six-digit code.",
  "scanQrInstructions": "Scan this QR code with your authenticator app.",
  "manualSetupInstructions": "Or enter this setup key manually.",
  "twoFactorQrAccessibilityLabel": "Two-factor authentication QR code",
  "authenticatorCode": "Authenticator code",
  "confirmSetup": "Confirm setup",
  "codeInvalid": "Enter exactly 6 digits.",
  "twoFactorError": "Unable to update two-factor authentication.",
  "recoveryTitle": "Recovery codes",
  "recoveryHelp": "Save these codes somewhere secure. They will not be shown again.",
  "disable": "Disable two-factor authentication",
  "disableTitle": "Disable two-factor authentication?",
  "disableBody": "Verify this security change, then disable two-factor authentication.",
  "disableHelp": "Enter an authenticator or recovery code, or your password, to verify this change.",
  "verification": "Authenticator code, recovery code, or password",
  "deletionHelp": "Account deletion becomes permanent after the 7-day grace period. You may reactivate your account during the supported grace period.",
  "requestDeletion": "Request account deletion",
  "deletionConfirmTitle": "Request account deletion?",
  "deletionConfirmBody": "Your account is scheduled for permanent deletion in 7 days. This action is destructive.",
  "pendingDeletion": "Pending deletion",
  "scheduledDate": "Scheduled deletion date",
  "keepAccount": "Keep my account / Cancel deletion",
  "reactivated": "Account deletion cancelled.",
  "deletionError": "Unable to update account deletion.",
  "addPasskey": "Add passkey",
  "passkeyPreviewRequired": "A new Preview app binary with native Passkey support is required to add credentials.",
  "created": "Created",
  "passkeysLoadError": "Unable to load passkeys."
};

const id: SecurityCopy = {
  "title": "Security",
  "intro": "Kelola masuk dan keamanan akun untuk akun Kurioticket Anda.",
  "loading": "Loading security settings…",
  "loadError": "Unable to load security settings.",
  "retry": "Coba lagi",
  "back": "Go back",
  "close": "Tutup",
  "password": "Kata sandi",
  "passwordHelp": "Ubah kata sandi yang digunakan untuk masuk ke akun Anda.",
  "configured": "Configured",
  "notConfigured": "Not configured",
  "current": "Current password",
  "next": "Kata sandi baru",
  "confirm": "Konfirmasi kata sandi baru",
  "show": "Show password",
  "hide": "Hide password",
  "change": "Ubah kata sandi",
  "changing": "Changing…",
  "passwordRules": "Use at least 8 characters and choose a different password.",
  "passwordInvalid": "Check that passwords match, contain at least 8 characters, and differ from the current password.",
  "passwordSuccess": "Password changed. Other devices were signed out.",
  "oauth": "This account does not have a password. Use password reset to create one.",
  "reset": "Email password reset link",
  "resetSent": "If the account can receive reset email, instructions were sent.",
  "twoFactor": "Autentikasi dua faktor",
  "twoFactorHelp": "Tambahkan perlindungan ekstra dengan aplikasi autentikator.",
  "passkeys": "Passkey",
  "passkeysHelp": "Gunakan kunci layar perangkat, Face ID, sidik jari, pengelola kata sandi, atau kunci keamanan untuk masuk lebih cepat dan lebih aman.",
  "activeSessions": "Sesi aktif",
  "activeSessionsHelp": "Tinjau perangkat yang masuk ke akun Anda.",
  "yourDevices": "Your devices",
  "devicesHelp": "Review devices that have recently accessed your account.",
  "currentDevice": "Current device",
  "lastActive": "Last active",
  "remove": "Remove device",
  "removeTitle": "Remove this device?",
  "removeBody": "This device will need to sign in again.",
  "cancel": "Batal",
  "removeFailed": "Unable to remove this device.",
  "signOutAll": "Sign out everywhere",
  "signOutAllHelp": "End every web and mobile session connected to your account.",
  "signOutTitle": "Sign out everywhere?",
  "signOutBody": "Every web and mobile session, including this device, will be ended.",
  "signOutFailed": "Unable to sign out every device. Try again.",
  "notifications": "Notifikasi keamanan",
  "alertsHelp": "Receive important email about account security.",
  "saving": "Saving...",
  "saved": "Tersimpan",
  "saveFailed": "Unable to save. Your previous setting is unchanged.",
  "activity": "Security activity",
  "activityHelp": "Review recent sign-ins and security changes.",
  "empty": "No recent security activity.",
  "deleteAccount": "Hapus akun",
  "openFailed": "Unable to open the secure web experience.",
  "unknown": "Security update",
  "enabled": "Enabled",
  "disabled": "Disabled",
  "twoFactorSetupHelp": "Protect your account with a code from an authenticator app.",
  "setupTwoFactor": "Set up two-factor authentication",
  "setupInstructions": "Add this account to your authenticator app using the setup key or URI, then enter its six-digit code.",
  "scanQrInstructions": "Scan this QR code with your authenticator app.",
  "manualSetupInstructions": "Or enter this setup key manually.",
  "twoFactorQrAccessibilityLabel": "Two-factor authentication QR code",
  "authenticatorCode": "Authenticator code",
  "confirmSetup": "Confirm setup",
  "codeInvalid": "Enter exactly 6 digits.",
  "twoFactorError": "Unable to update two-factor authentication.",
  "recoveryTitle": "Recovery codes",
  "recoveryHelp": "Save these codes somewhere secure. They will not be shown again.",
  "disable": "Disable two-factor authentication",
  "disableTitle": "Disable two-factor authentication?",
  "disableBody": "Verify this security change, then disable two-factor authentication.",
  "disableHelp": "Enter an authenticator or recovery code, or your password, to verify this change.",
  "verification": "Authenticator code, recovery code, or password",
  "deletionHelp": "Account deletion becomes permanent after the 7-day grace period. You may reactivate your account during the supported grace period.",
  "requestDeletion": "Request account deletion",
  "deletionConfirmTitle": "Request account deletion?",
  "deletionConfirmBody": "Your account is scheduled for permanent deletion in 7 days. This action is destructive.",
  "pendingDeletion": "Pending deletion",
  "scheduledDate": "Scheduled deletion date",
  "keepAccount": "Keep my account / Cancel deletion",
  "reactivated": "Account deletion cancelled.",
  "deletionError": "Unable to update account deletion.",
  "addPasskey": "Add passkey",
  "passkeyPreviewRequired": "A new Preview app binary with native Passkey support is required to add credentials.",
  "created": "Created",
  "passkeysLoadError": "Unable to load passkeys."
};

const th: SecurityCopy = {
  "title": "Security",
  "intro": "จัดการการเข้าสู่ระบบและความปลอดภัยของบัญชี Kurioticket ของคุณ",
  "loading": "Loading security settings…",
  "loadError": "Unable to load security settings.",
  "retry": "ลองอีกครั้ง",
  "back": "Go back",
  "close": "Close",
  "password": "รหัสผ่าน",
  "passwordHelp": "เปลี่ยนรหัสผ่านที่ใช้เข้าสู่ระบบบัญชีของคุณ",
  "configured": "Configured",
  "notConfigured": "Not configured",
  "current": "Current password",
  "next": "รหัสผ่านใหม่",
  "confirm": "ยืนยันรหัสผ่านใหม่",
  "show": "Show password",
  "hide": "Hide password",
  "change": "เปลี่ยนรหัสผ่าน",
  "changing": "Changing…",
  "passwordRules": "Use at least 8 characters and choose a different password.",
  "passwordInvalid": "Check that passwords match, contain at least 8 characters, and differ from the current password.",
  "passwordSuccess": "Password changed. Other devices were signed out.",
  "oauth": "This account does not have a password. Use password reset to create one.",
  "reset": "Email password reset link",
  "resetSent": "If the account can receive reset email, instructions were sent.",
  "twoFactor": "การยืนยันตัวตนแบบสองขั้นตอน",
  "twoFactorHelp": "เพิ่มการป้องกันด้วยแอปยืนยันตัวตน",
  "passkeys": "พาสคีย์",
  "passkeysHelp": "ใช้การล็อกหน้าจอของอุปกรณ์ Face ID ลายนิ้วมือ ตัวจัดการรหัสผ่าน หรือคีย์ความปลอดภัย เพื่อเข้าสู่ระบบได้รวดเร็วและปลอดภัยยิ่งขึ้น",
  "activeSessions": "เซสชันที่ใช้งานอยู่",
  "activeSessionsHelp": "ตรวจสอบอุปกรณ์ที่เข้าสู่ระบบบัญชีของคุณ",
  "yourDevices": "Your devices",
  "devicesHelp": "Review devices that have recently accessed your account.",
  "currentDevice": "Current device",
  "lastActive": "Last active",
  "remove": "Remove device",
  "removeTitle": "Remove this device?",
  "removeBody": "This device will need to sign in again.",
  "cancel": "ยกเลิก",
  "removeFailed": "Unable to remove this device.",
  "signOutAll": "Sign out everywhere",
  "signOutAllHelp": "End every web and mobile session connected to your account.",
  "signOutTitle": "Sign out everywhere?",
  "signOutBody": "Every web and mobile session, including this device, will be ended.",
  "signOutFailed": "Unable to sign out every device. Try again.",
  "notifications": "การแจ้งเตือนความปลอดภัย",
  "alertsHelp": "Receive important email about account security.",
  "saving": "กำลังบันทึก...",
  "saved": "บันทึกแล้ว",
  "saveFailed": "Unable to save. Your previous setting is unchanged.",
  "activity": "Security activity",
  "activityHelp": "Review recent sign-ins and security changes.",
  "empty": "No recent security activity.",
  "deleteAccount": "ลบบัญชี",
  "openFailed": "Unable to open the secure web experience.",
  "unknown": "Security update",
  "enabled": "Enabled",
  "disabled": "Disabled",
  "twoFactorSetupHelp": "Protect your account with a code from an authenticator app.",
  "setupTwoFactor": "Set up two-factor authentication",
  "setupInstructions": "Add this account to your authenticator app using the setup key or URI, then enter its six-digit code.",
  "scanQrInstructions": "Scan this QR code with your authenticator app.",
  "manualSetupInstructions": "Or enter this setup key manually.",
  "twoFactorQrAccessibilityLabel": "Two-factor authentication QR code",
  "authenticatorCode": "Authenticator code",
  "confirmSetup": "Confirm setup",
  "codeInvalid": "Enter exactly 6 digits.",
  "twoFactorError": "Unable to update two-factor authentication.",
  "recoveryTitle": "Recovery codes",
  "recoveryHelp": "Save these codes somewhere secure. They will not be shown again.",
  "disable": "Disable two-factor authentication",
  "disableTitle": "Disable two-factor authentication?",
  "disableBody": "Verify this security change, then disable two-factor authentication.",
  "disableHelp": "Enter an authenticator or recovery code, or your password, to verify this change.",
  "verification": "Authenticator code, recovery code, or password",
  "deletionHelp": "Account deletion becomes permanent after the 7-day grace period. You may reactivate your account during the supported grace period.",
  "requestDeletion": "Request account deletion",
  "deletionConfirmTitle": "Request account deletion?",
  "deletionConfirmBody": "Your account is scheduled for permanent deletion in 7 days. This action is destructive.",
  "pendingDeletion": "Pending deletion",
  "scheduledDate": "Scheduled deletion date",
  "keepAccount": "Keep my account / Cancel deletion",
  "reactivated": "Account deletion cancelled.",
  "deletionError": "Unable to update account deletion.",
  "addPasskey": "Add passkey",
  "passkeyPreviewRequired": "A new Preview app binary with native Passkey support is required to add credentials.",
  "created": "Created",
  "passkeysLoadError": "Unable to load passkeys."
};

const vi: SecurityCopy = {
  "title": "Security",
  "intro": "Quản lý đăng nhập và bảo mật tài khoản Kurioticket của bạn.",
  "loading": "Loading security settings…",
  "loadError": "Unable to load security settings.",
  "retry": "Thử lại",
  "back": "Go back",
  "close": "Đóng",
  "password": "Mật khẩu",
  "passwordHelp": "Thay đổi mật khẩu dùng để đăng nhập vào tài khoản của bạn.",
  "configured": "Configured",
  "notConfigured": "Not configured",
  "current": "Current password",
  "next": "Mật khẩu mới",
  "confirm": "Xác nhận mật khẩu mới",
  "show": "Show password",
  "hide": "Hide password",
  "change": "Thay đổi mật khẩu",
  "changing": "Changing…",
  "passwordRules": "Use at least 8 characters and choose a different password.",
  "passwordInvalid": "Check that passwords match, contain at least 8 characters, and differ from the current password.",
  "passwordSuccess": "Password changed. Other devices were signed out.",
  "oauth": "This account does not have a password. Use password reset to create one.",
  "reset": "Email password reset link",
  "resetSent": "If the account can receive reset email, instructions were sent.",
  "twoFactor": "Xác thực hai yếu tố",
  "twoFactorHelp": "Thêm lớp bảo vệ bằng ứng dụng xác thực.",
  "passkeys": "Khóa đăng nhập",
  "passkeysHelp": "Sử dụng khóa màn hình thiết bị, Face ID, vân tay, trình quản lý mật khẩu hoặc khóa bảo mật để đăng nhập nhanh hơn và an toàn hơn.",
  "activeSessions": "Phiên hoạt động",
  "activeSessionsHelp": "Xem lại các thiết bị đã đăng nhập vào tài khoản của bạn.",
  "yourDevices": "Your devices",
  "devicesHelp": "Review devices that have recently accessed your account.",
  "currentDevice": "Current device",
  "lastActive": "Last active",
  "remove": "Remove device",
  "removeTitle": "Remove this device?",
  "removeBody": "This device will need to sign in again.",
  "cancel": "Hủy",
  "removeFailed": "Unable to remove this device.",
  "signOutAll": "Sign out everywhere",
  "signOutAllHelp": "End every web and mobile session connected to your account.",
  "signOutTitle": "Sign out everywhere?",
  "signOutBody": "Every web and mobile session, including this device, will be ended.",
  "signOutFailed": "Unable to sign out every device. Try again.",
  "notifications": "Thông báo bảo mật",
  "alertsHelp": "Receive important email about account security.",
  "saving": "Saving...",
  "saved": "Đã lưu",
  "saveFailed": "Unable to save. Your previous setting is unchanged.",
  "activity": "Security activity",
  "activityHelp": "Review recent sign-ins and security changes.",
  "empty": "No recent security activity.",
  "deleteAccount": "Xóa tài khoản",
  "openFailed": "Unable to open the secure web experience.",
  "unknown": "Security update",
  "enabled": "Enabled",
  "disabled": "Disabled",
  "twoFactorSetupHelp": "Protect your account with a code from an authenticator app.",
  "setupTwoFactor": "Set up two-factor authentication",
  "setupInstructions": "Add this account to your authenticator app using the setup key or URI, then enter its six-digit code.",
  "scanQrInstructions": "Scan this QR code with your authenticator app.",
  "manualSetupInstructions": "Or enter this setup key manually.",
  "twoFactorQrAccessibilityLabel": "Two-factor authentication QR code",
  "authenticatorCode": "Authenticator code",
  "confirmSetup": "Confirm setup",
  "codeInvalid": "Enter exactly 6 digits.",
  "twoFactorError": "Unable to update two-factor authentication.",
  "recoveryTitle": "Recovery codes",
  "recoveryHelp": "Save these codes somewhere secure. They will not be shown again.",
  "disable": "Disable two-factor authentication",
  "disableTitle": "Disable two-factor authentication?",
  "disableBody": "Verify this security change, then disable two-factor authentication.",
  "disableHelp": "Enter an authenticator or recovery code, or your password, to verify this change.",
  "verification": "Authenticator code, recovery code, or password",
  "deletionHelp": "Account deletion becomes permanent after the 7-day grace period. You may reactivate your account during the supported grace period.",
  "requestDeletion": "Request account deletion",
  "deletionConfirmTitle": "Request account deletion?",
  "deletionConfirmBody": "Your account is scheduled for permanent deletion in 7 days. This action is destructive.",
  "pendingDeletion": "Pending deletion",
  "scheduledDate": "Scheduled deletion date",
  "keepAccount": "Keep my account / Cancel deletion",
  "reactivated": "Account deletion cancelled.",
  "deletionError": "Unable to update account deletion.",
  "addPasskey": "Add passkey",
  "passkeyPreviewRequired": "A new Preview app binary with native Passkey support is required to add credentials.",
  "created": "Đã tạo",
  "passkeysLoadError": "Unable to load passkeys."
};

export const securityCopy: Record<MobileLocale, SecurityCopy> = { "en-us": englishSecurityCopy, "es-es": es_es, "fr": fr, "de-de": de_de, "it-it": it_it, "pt-br": pt_br, "nl": nl, "ar": ar, "zh-cn": zh_cn, "ja": ja, "ko": ko, "hi": hi, "tr": tr, "pl": pl, "sv": sv, "id": id, "th": th, "vi": vi };
export const securityEventTypes = ["PASSWORD_CHANGED","SIGN_IN","MOBILE_SESSION_CREATED","SESSION_REVOKED","ALL_SESSIONS_REVOKED"] as const;
export type SecurityEventType = typeof securityEventTypes[number];
export const securityEventLabels: Record<SecurityEventType, Record<MobileLocale,string>> = Object.fromEntries(securityEventTypes.map(type => [type, Object.fromEntries(mobileLocaleCodes.map(locale => [locale, {"en-us":{"PASSWORD_CHANGED":"Password changed","SIGN_IN":"Signed in","MOBILE_SESSION_CREATED":"Mobile session started","SESSION_REVOKED":"Device removed","ALL_SESSIONS_REVOKED":"Signed out everywhere"},"es-es":{"PASSWORD_CHANGED":"Contraseña cambiada","SIGN_IN":"Inicio de sesión","MOBILE_SESSION_CREATED":"Sesión móvil iniciada","SESSION_REVOKED":"Dispositivo eliminado","ALL_SESSIONS_REVOKED":"Sesión cerrada en todas partes"},"fr":{"PASSWORD_CHANGED":"Security update","SIGN_IN":"Security update","MOBILE_SESSION_CREATED":"Security update","SESSION_REVOKED":"Security update","ALL_SESSIONS_REVOKED":"Security update"},"de-de":{"PASSWORD_CHANGED":"Security update","SIGN_IN":"Security update","MOBILE_SESSION_CREATED":"Security update","SESSION_REVOKED":"Security update","ALL_SESSIONS_REVOKED":"Security update"},"it-it":{"PASSWORD_CHANGED":"Security update","SIGN_IN":"Security update","MOBILE_SESSION_CREATED":"Security update","SESSION_REVOKED":"Security update","ALL_SESSIONS_REVOKED":"Security update"},"pt-br":{"PASSWORD_CHANGED":"Security update","SIGN_IN":"Security update","MOBILE_SESSION_CREATED":"Security update","SESSION_REVOKED":"Security update","ALL_SESSIONS_REVOKED":"Security update"},"nl":{"PASSWORD_CHANGED":"Security update","SIGN_IN":"Security update","MOBILE_SESSION_CREATED":"Security update","SESSION_REVOKED":"Security update","ALL_SESSIONS_REVOKED":"Security update"},"ar":{"PASSWORD_CHANGED":"Security update","SIGN_IN":"Security update","MOBILE_SESSION_CREATED":"Security update","SESSION_REVOKED":"Security update","ALL_SESSIONS_REVOKED":"Security update"},"zh-cn":{"PASSWORD_CHANGED":"Security update","SIGN_IN":"Security update","MOBILE_SESSION_CREATED":"Security update","SESSION_REVOKED":"Security update","ALL_SESSIONS_REVOKED":"Security update"},"ja":{"PASSWORD_CHANGED":"Security update","SIGN_IN":"Security update","MOBILE_SESSION_CREATED":"Security update","SESSION_REVOKED":"Security update","ALL_SESSIONS_REVOKED":"Security update"},"ko":{"PASSWORD_CHANGED":"Security update","SIGN_IN":"Security update","MOBILE_SESSION_CREATED":"Security update","SESSION_REVOKED":"Security update","ALL_SESSIONS_REVOKED":"Security update"},"hi":{"PASSWORD_CHANGED":"Security update","SIGN_IN":"Security update","MOBILE_SESSION_CREATED":"Security update","SESSION_REVOKED":"Security update","ALL_SESSIONS_REVOKED":"Security update"},"tr":{"PASSWORD_CHANGED":"Security update","SIGN_IN":"Security update","MOBILE_SESSION_CREATED":"Security update","SESSION_REVOKED":"Security update","ALL_SESSIONS_REVOKED":"Security update"},"pl":{"PASSWORD_CHANGED":"Security update","SIGN_IN":"Security update","MOBILE_SESSION_CREATED":"Security update","SESSION_REVOKED":"Security update","ALL_SESSIONS_REVOKED":"Security update"},"sv":{"PASSWORD_CHANGED":"Security update","SIGN_IN":"Security update","MOBILE_SESSION_CREATED":"Security update","SESSION_REVOKED":"Security update","ALL_SESSIONS_REVOKED":"Security update"},"id":{"PASSWORD_CHANGED":"Security update","SIGN_IN":"Security update","MOBILE_SESSION_CREATED":"Security update","SESSION_REVOKED":"Security update","ALL_SESSIONS_REVOKED":"Security update"},"th":{"PASSWORD_CHANGED":"Security update","SIGN_IN":"Security update","MOBILE_SESSION_CREATED":"Security update","SESSION_REVOKED":"Security update","ALL_SESSIONS_REVOKED":"Security update"},"vi":{"PASSWORD_CHANGED":"Security update","SIGN_IN":"Security update","MOBILE_SESSION_CREATED":"Security update","SESSION_REVOKED":"Security update","ALL_SESSIONS_REVOKED":"Security update"}}[locale][type]]))])) as Record<SecurityEventType, Record<MobileLocale,string>>;
export function securityEventLabel(type: string, locale: MobileLocale): string { return securityEventTypes.includes(type as SecurityEventType) ? securityEventLabels[type as SecurityEventType][locale] : securityCopy[locale].unknown; }
export function formatSecurityDate(value: string, locale: MobileLocale): string { const intl = mobileLocales.find(option => option.code === locale)!.intl; return new Intl.DateTimeFormat(intl, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
