import type { MobileLocale } from "../../localization/mobileLocalizationCatalog";

type TwoFactorPolishCopy = {
  verifyAnotherWay: string;
  setupTitle: string;
  cantScan: string;
  setupKey: string;
  codePlaceholder: string;
  recoveryPlaceholder: string;
  passwordPlaceholder: string;
  enabledTitle: string;
  savedCodesAction: string;
  copyHint: string;
};

export const twoFactorPolishCopy: Record<MobileLocale, TwoFactorPolishCopy> = {
  "en-us": { verifyAnotherWay: "Verify another way", setupTitle: "Set up your authenticator", cantScan: "Can’t scan it?", setupKey: "Setup key", codePlaceholder: "6-digit code", recoveryPlaceholder: "Enter recovery code", passwordPlaceholder: "Enter password", enabledTitle: "Two-factor authentication is on", savedCodesAction: "I’ve saved these codes", copyHint: "Press and hold to copy." },
  "es-es": { verifyAnotherWay: "Verifica de otra forma", setupTitle: "Configura tu autenticador", cantScan: "¿No puedes escanearlo?", setupKey: "Clave de configuración", codePlaceholder: "Código de 6 dígitos", recoveryPlaceholder: "Introduce el código de recuperación", passwordPlaceholder: "Introduce la contraseña", enabledTitle: "La autenticación en dos pasos está activada", savedCodesAction: "He guardado estos códigos", copyHint: "Mantén pulsado para copiar." },
  fr: { verifyAnotherWay: "Vérifiez autrement", setupTitle: "Configurez votre authentificateur", cantScan: "Impossible de le scanner ?", setupKey: "Clé de configuration", codePlaceholder: "Code à 6 chiffres", recoveryPlaceholder: "Saisissez le code de récupération", passwordPlaceholder: "Saisissez le mot de passe", enabledTitle: "L’authentification à deux facteurs est activée", savedCodesAction: "J’ai enregistré ces codes", copyHint: "Appuyez longuement pour copier." },
  "de-de": { verifyAnotherWay: "Anders bestätigen", setupTitle: "Authenticator einrichten", cantScan: "Scannen nicht möglich?", setupKey: "Einrichtungsschlüssel", codePlaceholder: "6-stelliger Code", recoveryPlaceholder: "Wiederherstellungscode eingeben", passwordPlaceholder: "Passwort eingeben", enabledTitle: "Zwei-Faktor-Authentifizierung ist aktiviert", savedCodesAction: "Ich habe diese Codes gespeichert", copyHint: "Zum Kopieren gedrückt halten." },
  "it-it": { verifyAnotherWay: "Verifica in un altro modo", setupTitle: "Configura l’autenticatore", cantScan: "Non riesci a scansionarlo?", setupKey: "Chiave di configurazione", codePlaceholder: "Codice a 6 cifre", recoveryPlaceholder: "Inserisci il codice di recupero", passwordPlaceholder: "Inserisci la password", enabledTitle: "L’autenticazione a due fattori è attiva", savedCodesAction: "Ho salvato questi codici", copyHint: "Tieni premuto per copiare." },
  "pt-br": { verifyAnotherWay: "Verifique de outra forma", setupTitle: "Configure seu autenticador", cantScan: "Não consegue escanear?", setupKey: "Chave de configuração", codePlaceholder: "Código de 6 dígitos", recoveryPlaceholder: "Digite o código de recuperação", passwordPlaceholder: "Digite a senha", enabledTitle: "A autenticação de dois fatores está ativada", savedCodesAction: "Salvei estes códigos", copyHint: "Toque e segure para copiar." },
  nl: { verifyAnotherWay: "Op een andere manier verifiëren", setupTitle: "Authenticator instellen", cantScan: "Kun je dit niet scannen?", setupKey: "Instelsleutel", codePlaceholder: "6-cijferige code", recoveryPlaceholder: "Voer herstelcode in", passwordPlaceholder: "Voer wachtwoord in", enabledTitle: "Tweestapsverificatie is ingeschakeld", savedCodesAction: "Ik heb deze codes opgeslagen", copyHint: "Houd ingedrukt om te kopiëren." },
  ar: { verifyAnotherWay: "التحقق بطريقة أخرى", setupTitle: "إعداد تطبيق المصادقة", cantScan: "تعذر المسح؟", setupKey: "مفتاح الإعداد", codePlaceholder: "رمز من 6 أرقام", recoveryPlaceholder: "أدخل رمز الاسترداد", passwordPlaceholder: "أدخل كلمة المرور", enabledTitle: "المصادقة الثنائية مفعّلة", savedCodesAction: "لقد حفظت هذه الرموز", copyHint: "اضغط مطولاً للنسخ." },
  "zh-cn": { verifyAnotherWay: "使用其他方式验证", setupTitle: "设置身份验证器", cantScan: "无法扫描？", setupKey: "设置密钥", codePlaceholder: "6 位代码", recoveryPlaceholder: "输入恢复代码", passwordPlaceholder: "输入密码", enabledTitle: "双重验证已开启", savedCodesAction: "我已保存这些代码", copyHint: "长按即可复制。" },
  ja: { verifyAnotherWay: "別の方法で確認", setupTitle: "認証アプリを設定", cantScan: "スキャンできませんか？", setupKey: "セットアップキー", codePlaceholder: "6桁のコード", recoveryPlaceholder: "リカバリーコードを入力", passwordPlaceholder: "パスワードを入力", enabledTitle: "2要素認証はオンです", savedCodesAction: "これらのコードを保存しました", copyHint: "長押ししてコピーします。" },
  ko: { verifyAnotherWay: "다른 방법으로 인증", setupTitle: "인증 앱 설정", cantScan: "스캔할 수 없나요?", setupKey: "설정 키", codePlaceholder: "6자리 코드", recoveryPlaceholder: "복구 코드 입력", passwordPlaceholder: "비밀번호 입력", enabledTitle: "2단계 인증이 켜져 있습니다", savedCodesAction: "이 코드를 저장했습니다", copyHint: "길게 눌러 복사하세요." },
  hi: { verifyAnotherWay: "दूसरे तरीके से सत्यापित करें", setupTitle: "अपना ऑथेंटिकेटर सेट करें", cantScan: "स्कैन नहीं कर पा रहे हैं?", setupKey: "सेटअप कुंजी", codePlaceholder: "6 अंकों का कोड", recoveryPlaceholder: "रिकवरी कोड दर्ज करें", passwordPlaceholder: "पासवर्ड दर्ज करें", enabledTitle: "दो-कारक प्रमाणीकरण चालू है", savedCodesAction: "मैंने ये कोड सहेज लिए हैं", copyHint: "कॉपी करने के लिए दबाकर रखें।" },
  tr: { verifyAnotherWay: "Başka bir yöntemle doğrulayın", setupTitle: "Kimlik doğrulayıcınızı ayarlayın", cantScan: "Tarayamıyor musunuz?", setupKey: "Kurulum anahtarı", codePlaceholder: "6 haneli kod", recoveryPlaceholder: "Kurtarma kodunu girin", passwordPlaceholder: "Parolayı girin", enabledTitle: "İki faktörlü kimlik doğrulama açık", savedCodesAction: "Bu kodları kaydettim", copyHint: "Kopyalamak için basılı tutun." },
  pl: { verifyAnotherWay: "Zweryfikuj w inny sposób", setupTitle: "Skonfiguruj aplikację uwierzytelniającą", cantScan: "Nie możesz zeskanować?", setupKey: "Klucz konfiguracji", codePlaceholder: "6-cyfrowy kod", recoveryPlaceholder: "Wpisz kod odzyskiwania", passwordPlaceholder: "Wpisz hasło", enabledTitle: "Uwierzytelnianie dwuskładnikowe jest włączone", savedCodesAction: "Mam zapisane te kody", copyHint: "Przytrzymaj, aby skopiować." },
  sv: { verifyAnotherWay: "Verifiera på ett annat sätt", setupTitle: "Konfigurera autentiseringsappen", cantScan: "Kan du inte skanna?", setupKey: "Konfigurationsnyckel", codePlaceholder: "6-siffrig kod", recoveryPlaceholder: "Ange återställningskod", passwordPlaceholder: "Ange lösenord", enabledTitle: "Tvåfaktorsautentisering är aktiverad", savedCodesAction: "Jag har sparat koderna", copyHint: "Tryck och håll för att kopiera." },
  id: { verifyAnotherWay: "Verifikasi dengan cara lain", setupTitle: "Siapkan aplikasi autentikator", cantScan: "Tidak dapat memindai?", setupKey: "Kunci penyiapan", codePlaceholder: "Kode 6 digit", recoveryPlaceholder: "Masukkan kode pemulihan", passwordPlaceholder: "Masukkan kata sandi", enabledTitle: "Autentikasi dua faktor aktif", savedCodesAction: "Saya sudah menyimpan kode ini", copyHint: "Tekan dan tahan untuk menyalin." },
  th: { verifyAnotherWay: "ยืนยันด้วยวิธีอื่น", setupTitle: "ตั้งค่าแอปยืนยันตัวตน", cantScan: "สแกนไม่ได้ใช่ไหม?", setupKey: "คีย์ตั้งค่า", codePlaceholder: "รหัส 6 หลัก", recoveryPlaceholder: "ป้อนรหัสกู้คืน", passwordPlaceholder: "ป้อนรหัสผ่าน", enabledTitle: "เปิดการยืนยันตัวตนแบบสองปัจจัยแล้ว", savedCodesAction: "ฉันบันทึกรหัสเหล่านี้แล้ว", copyHint: "แตะค้างไว้เพื่อคัดลอก" },
  vi: { verifyAnotherWay: "Xác minh theo cách khác", setupTitle: "Thiết lập ứng dụng xác thực", cantScan: "Không quét được?", setupKey: "Khóa thiết lập", codePlaceholder: "Mã 6 chữ số", recoveryPlaceholder: "Nhập mã khôi phục", passwordPlaceholder: "Nhập mật khẩu", enabledTitle: "Xác thực hai yếu tố đang bật", savedCodesAction: "Tôi đã lưu các mã này", copyHint: "Nhấn và giữ để sao chép." },
};
