import type { MobileLocale } from "../../localization/mobileLocalizationCatalog";

type TwoFactorPolishCopy = {
  verifyAnotherWay: string;
  copy: string;
  copied: string;
  saveRecoveryCodesTitle: string;
  recoveryCodesIntro: string;
  recoveryCodesLabel: string;
  copyAllRecoveryCodes: string;
  setupTitle: string;
  cantScan: string;
  setupKey: string;
  codePlaceholder: string;
  recoveryPlaceholder: string;
  passwordPlaceholder: string;
  enabledTitle: string;
  savedCodesAction: string;
  copyHint: string;
};

export const twoFactorPolishCopy: Record<MobileLocale, TwoFactorPolishCopy> = {
  "en-us": { verifyAnotherWay: "Verify another way", copy: "Copy", copied: "Copied", saveRecoveryCodesTitle: "Save your recovery codes", recoveryCodesIntro: "Two-factor authentication is now enabled. Use these codes if you lose access to your authenticator app.", recoveryCodesLabel: "Recovery codes", copyAllRecoveryCodes: "Copy all recovery codes", setupTitle: "Set up your authenticator", cantScan: "Can’t scan it?", setupKey: "Setup key", codePlaceholder: "6-digit code", recoveryPlaceholder: "Enter recovery code", passwordPlaceholder: "Enter password", enabledTitle: "Two-factor authentication is on", savedCodesAction: "I’ve saved these codes", copyHint: "Press and hold to copy." },
  "es-es": { verifyAnotherWay: "Verifica de otra forma", copy: "Copiar", copied: "Copiado", saveRecoveryCodesTitle: "Guarda tus códigos de recuperación", recoveryCodesIntro: "La autenticación en dos pasos ya está activada. Usa estos códigos si pierdes el acceso a tu aplicación de autenticación.", recoveryCodesLabel: "Códigos de recuperación", copyAllRecoveryCodes: "Copiar todos los códigos de recuperación", setupTitle: "Configura tu autenticador", cantScan: "¿No puedes escanearlo?", setupKey: "Clave de configuración", codePlaceholder: "Código de 6 dígitos", recoveryPlaceholder: "Introduce el código de recuperación", passwordPlaceholder: "Introduce la contraseña", enabledTitle: "La autenticación en dos pasos está activada", savedCodesAction: "He guardado estos códigos", copyHint: "Mantén pulsado para copiar." },
  fr: { verifyAnotherWay: "Vérifiez autrement", copy: "Copier", copied: "Copié", saveRecoveryCodesTitle: "Enregistrez vos codes de récupération", recoveryCodesIntro: "L’authentification à deux facteurs est maintenant activée. Utilisez ces codes si vous perdez l’accès à votre application d’authentification.", recoveryCodesLabel: "Codes de récupération", copyAllRecoveryCodes: "Copier tous les codes de récupération", setupTitle: "Configurez votre authentificateur", cantScan: "Impossible de le scanner ?", setupKey: "Clé de configuration", codePlaceholder: "Code à 6 chiffres", recoveryPlaceholder: "Saisissez le code de récupération", passwordPlaceholder: "Saisissez le mot de passe", enabledTitle: "L’authentification à deux facteurs est activée", savedCodesAction: "J’ai enregistré ces codes", copyHint: "Appuyez longuement pour copier." },
  "de-de": { verifyAnotherWay: "Anders bestätigen", copy: "Kopieren", copied: "Kopiert", saveRecoveryCodesTitle: "Wiederherstellungscodes speichern", recoveryCodesIntro: "Die Zwei-Faktor-Authentifizierung ist jetzt aktiviert. Verwenden Sie diese Codes, wenn Sie den Zugriff auf Ihre Authenticator-App verlieren.", recoveryCodesLabel: "Wiederherstellungscodes", copyAllRecoveryCodes: "Alle Wiederherstellungscodes kopieren", setupTitle: "Authenticator einrichten", cantScan: "Scannen nicht möglich?", setupKey: "Einrichtungsschlüssel", codePlaceholder: "6-stelliger Code", recoveryPlaceholder: "Wiederherstellungscode eingeben", passwordPlaceholder: "Passwort eingeben", enabledTitle: "Zwei-Faktor-Authentifizierung ist aktiviert", savedCodesAction: "Ich habe diese Codes gespeichert", copyHint: "Zum Kopieren gedrückt halten." },
  "it-it": { verifyAnotherWay: "Verifica in un altro modo", copy: "Copia", copied: "Copiato", saveRecoveryCodesTitle: "Salva i codici di recupero", recoveryCodesIntro: "L’autenticazione a due fattori è ora attiva. Usa questi codici se perdi l’accesso all’app di autenticazione.", recoveryCodesLabel: "Codici di recupero", copyAllRecoveryCodes: "Copia tutti i codici di recupero", setupTitle: "Configura l’autenticatore", cantScan: "Non riesci a scansionarlo?", setupKey: "Chiave di configurazione", codePlaceholder: "Codice a 6 cifre", recoveryPlaceholder: "Inserisci il codice di recupero", passwordPlaceholder: "Inserisci la password", enabledTitle: "L’autenticazione a due fattori è attiva", savedCodesAction: "Ho salvato questi codici", copyHint: "Tieni premuto per copiare." },
  "pt-br": { verifyAnotherWay: "Verifique de outra forma", copy: "Copiar", copied: "Copiado", saveRecoveryCodesTitle: "Salve seus códigos de recuperação", recoveryCodesIntro: "A autenticação de dois fatores agora está ativada. Use estes códigos se perder o acesso ao aplicativo autenticador.", recoveryCodesLabel: "Códigos de recuperação", copyAllRecoveryCodes: "Copiar todos os códigos de recuperação", setupTitle: "Configure seu autenticador", cantScan: "Não consegue escanear?", setupKey: "Chave de configuração", codePlaceholder: "Código de 6 dígitos", recoveryPlaceholder: "Digite o código de recuperação", passwordPlaceholder: "Digite a senha", enabledTitle: "A autenticação de dois fatores está ativada", savedCodesAction: "Salvei estes códigos", copyHint: "Toque e segure para copiar." },
  nl: { verifyAnotherWay: "Op een andere manier verifiëren", copy: "Kopiëren", copied: "Gekopieerd", saveRecoveryCodesTitle: "Sla je herstelcodes op", recoveryCodesIntro: "Tweestapsverificatie is nu ingeschakeld. Gebruik deze codes als je geen toegang meer hebt tot je authenticator-app.", recoveryCodesLabel: "Herstelcodes", copyAllRecoveryCodes: "Alle herstelcodes kopiëren", setupTitle: "Authenticator instellen", cantScan: "Kun je dit niet scannen?", setupKey: "Instelsleutel", codePlaceholder: "6-cijferige code", recoveryPlaceholder: "Voer herstelcode in", passwordPlaceholder: "Voer wachtwoord in", enabledTitle: "Tweestapsverificatie is ingeschakeld", savedCodesAction: "Ik heb deze codes opgeslagen", copyHint: "Houd ingedrukt om te kopiëren." },
  ar: { verifyAnotherWay: "التحقق بطريقة أخرى", copy: "نسخ", copied: "تم النسخ", saveRecoveryCodesTitle: "احفظ رموز الاسترداد", recoveryCodesIntro: "تم تفعيل المصادقة الثنائية. استخدم هذه الرموز إذا فقدت الوصول إلى تطبيق المصادقة.", recoveryCodesLabel: "رموز الاسترداد", copyAllRecoveryCodes: "نسخ جميع رموز الاسترداد", setupTitle: "إعداد تطبيق المصادقة", cantScan: "تعذر المسح؟", setupKey: "مفتاح الإعداد", codePlaceholder: "رمز من 6 أرقام", recoveryPlaceholder: "أدخل رمز الاسترداد", passwordPlaceholder: "أدخل كلمة المرور", enabledTitle: "المصادقة الثنائية مفعّلة", savedCodesAction: "لقد حفظت هذه الرموز", copyHint: "اضغط مطولاً للنسخ." },
  "zh-cn": { verifyAnotherWay: "使用其他方式验证", copy: "复制", copied: "已复制", saveRecoveryCodesTitle: "保存恢复代码", recoveryCodesIntro: "双重验证现已开启。如果您无法使用身份验证器应用，请使用这些代码。", recoveryCodesLabel: "恢复代码", copyAllRecoveryCodes: "复制所有恢复代码", setupTitle: "设置身份验证器", cantScan: "无法扫描？", setupKey: "设置密钥", codePlaceholder: "6 位代码", recoveryPlaceholder: "输入恢复代码", passwordPlaceholder: "输入密码", enabledTitle: "双重验证已开启", savedCodesAction: "我已保存这些代码", copyHint: "长按即可复制。" },
  ja: { verifyAnotherWay: "別の方法で確認", copy: "コピー", copied: "コピーしました", saveRecoveryCodesTitle: "リカバリーコードを保存", recoveryCodesIntro: "2要素認証が有効になりました。認証アプリにアクセスできなくなった場合は、これらのコードを使用してください。", recoveryCodesLabel: "リカバリーコード", copyAllRecoveryCodes: "すべてのリカバリーコードをコピー", setupTitle: "認証アプリを設定", cantScan: "スキャンできませんか？", setupKey: "セットアップキー", codePlaceholder: "6桁のコード", recoveryPlaceholder: "リカバリーコードを入力", passwordPlaceholder: "パスワードを入力", enabledTitle: "2要素認証はオンです", savedCodesAction: "これらのコードを保存しました", copyHint: "長押ししてコピーします。" },
  ko: { verifyAnotherWay: "다른 방법으로 인증", copy: "복사", copied: "복사됨", saveRecoveryCodesTitle: "복구 코드 저장", recoveryCodesIntro: "2단계 인증이 켜졌습니다. 인증 앱에 액세스할 수 없는 경우 이 코드를 사용하세요.", recoveryCodesLabel: "복구 코드", copyAllRecoveryCodes: "모든 복구 코드 복사", setupTitle: "인증 앱 설정", cantScan: "스캔할 수 없나요?", setupKey: "설정 키", codePlaceholder: "6자리 코드", recoveryPlaceholder: "복구 코드 입력", passwordPlaceholder: "비밀번호 입력", enabledTitle: "2단계 인증이 켜져 있습니다", savedCodesAction: "이 코드를 저장했습니다", copyHint: "길게 눌러 복사하세요." },
  hi: { verifyAnotherWay: "दूसरे तरीके से सत्यापित करें", copy: "कॉपी करें", copied: "कॉपी किया गया", saveRecoveryCodesTitle: "अपने रिकवरी कोड सेव करें", recoveryCodesIntro: "दो-कारक प्रमाणीकरण अब चालू है। ऑथेंटिकेटर ऐप का एक्सेस खोने पर इन कोड का उपयोग करें।", recoveryCodesLabel: "रिकवरी कोड", copyAllRecoveryCodes: "सभी रिकवरी कोड कॉपी करें", setupTitle: "अपना ऑथेंटिकेटर सेट करें", cantScan: "स्कैन नहीं कर पा रहे हैं?", setupKey: "सेटअप कुंजी", codePlaceholder: "6 अंकों का कोड", recoveryPlaceholder: "रिकवरी कोड दर्ज करें", passwordPlaceholder: "पासवर्ड दर्ज करें", enabledTitle: "दो-कारक प्रमाणीकरण चालू है", savedCodesAction: "मैंने ये कोड सहेज लिए हैं", copyHint: "कॉपी करने के लिए दबाकर रखें।" },
  tr: { verifyAnotherWay: "Başka bir yöntemle doğrulayın", copy: "Kopyala", copied: "Kopyalandı", saveRecoveryCodesTitle: "Kurtarma kodlarınızı kaydedin", recoveryCodesIntro: "İki faktörlü kimlik doğrulama artık açık. Kimlik doğrulayıcı uygulamanıza erişimi kaybederseniz bu kodları kullanın.", recoveryCodesLabel: "Kurtarma kodları", copyAllRecoveryCodes: "Tüm kurtarma kodlarını kopyala", setupTitle: "Kimlik doğrulayıcınızı ayarlayın", cantScan: "Tarayamıyor musunuz?", setupKey: "Kurulum anahtarı", codePlaceholder: "6 haneli kod", recoveryPlaceholder: "Kurtarma kodunu girin", passwordPlaceholder: "Parolayı girin", enabledTitle: "İki faktörlü kimlik doğrulama açık", savedCodesAction: "Bu kodları kaydettim", copyHint: "Kopyalamak için basılı tutun." },
  pl: { verifyAnotherWay: "Zweryfikuj w inny sposób", copy: "Kopiuj", copied: "Skopiowano", saveRecoveryCodesTitle: "Zapisz kody odzyskiwania", recoveryCodesIntro: "Uwierzytelnianie dwuskładnikowe jest teraz włączone. Użyj tych kodów, jeśli utracisz dostęp do aplikacji uwierzytelniającej.", recoveryCodesLabel: "Kody odzyskiwania", copyAllRecoveryCodes: "Kopiuj wszystkie kody odzyskiwania", setupTitle: "Skonfiguruj aplikację uwierzytelniającą", cantScan: "Nie możesz zeskanować?", setupKey: "Klucz konfiguracji", codePlaceholder: "6-cyfrowy kod", recoveryPlaceholder: "Wpisz kod odzyskiwania", passwordPlaceholder: "Wpisz hasło", enabledTitle: "Uwierzytelnianie dwuskładnikowe jest włączone", savedCodesAction: "Mam zapisane te kody", copyHint: "Przytrzymaj, aby skopiować." },
  sv: { verifyAnotherWay: "Verifiera på ett annat sätt", copy: "Kopiera", copied: "Kopierat", saveRecoveryCodesTitle: "Spara dina återställningskoder", recoveryCodesIntro: "Tvåfaktorsautentisering är nu aktiverad. Använd koderna om du förlorar åtkomsten till autentiseringsappen.", recoveryCodesLabel: "Återställningskoder", copyAllRecoveryCodes: "Kopiera alla återställningskoder", setupTitle: "Konfigurera autentiseringsappen", cantScan: "Kan du inte skanna?", setupKey: "Konfigurationsnyckel", codePlaceholder: "6-siffrig kod", recoveryPlaceholder: "Ange återställningskod", passwordPlaceholder: "Ange lösenord", enabledTitle: "Tvåfaktorsautentisering är aktiverad", savedCodesAction: "Jag har sparat koderna", copyHint: "Tryck och håll för att kopiera." },
  id: { verifyAnotherWay: "Verifikasi dengan cara lain", copy: "Salin", copied: "Disalin", saveRecoveryCodesTitle: "Simpan kode pemulihan Anda", recoveryCodesIntro: "Autentikasi dua faktor kini aktif. Gunakan kode ini jika Anda kehilangan akses ke aplikasi autentikator.", recoveryCodesLabel: "Kode pemulihan", copyAllRecoveryCodes: "Salin semua kode pemulihan", setupTitle: "Siapkan aplikasi autentikator", cantScan: "Tidak dapat memindai?", setupKey: "Kunci penyiapan", codePlaceholder: "Kode 6 digit", recoveryPlaceholder: "Masukkan kode pemulihan", passwordPlaceholder: "Masukkan kata sandi", enabledTitle: "Autentikasi dua faktor aktif", savedCodesAction: "Saya sudah menyimpan kode ini", copyHint: "Tekan dan tahan untuk menyalin." },
  th: { verifyAnotherWay: "ยืนยันด้วยวิธีอื่น", copy: "คัดลอก", copied: "คัดลอกแล้ว", saveRecoveryCodesTitle: "บันทึกรหัสกู้คืนของคุณ", recoveryCodesIntro: "เปิดการยืนยันตัวตนแบบสองปัจจัยแล้ว ใช้รหัสเหล่านี้หากคุณไม่สามารถเข้าถึงแอปยืนยันตัวตนได้", recoveryCodesLabel: "รหัสกู้คืน", copyAllRecoveryCodes: "คัดลอกรหัสกู้คืนทั้งหมด", setupTitle: "ตั้งค่าแอปยืนยันตัวตน", cantScan: "สแกนไม่ได้ใช่ไหม?", setupKey: "คีย์ตั้งค่า", codePlaceholder: "รหัส 6 หลัก", recoveryPlaceholder: "ป้อนรหัสกู้คืน", passwordPlaceholder: "ป้อนรหัสผ่าน", enabledTitle: "เปิดการยืนยันตัวตนแบบสองปัจจัยแล้ว", savedCodesAction: "ฉันบันทึกรหัสเหล่านี้แล้ว", copyHint: "แตะค้างไว้เพื่อคัดลอก" },
  vi: { verifyAnotherWay: "Xác minh theo cách khác", copy: "Sao chép", copied: "Đã sao chép", saveRecoveryCodesTitle: "Lưu mã khôi phục của bạn", recoveryCodesIntro: "Xác thực hai yếu tố hiện đã bật. Hãy dùng các mã này nếu bạn mất quyền truy cập vào ứng dụng xác thực.", recoveryCodesLabel: "Mã khôi phục", copyAllRecoveryCodes: "Sao chép tất cả mã khôi phục", setupTitle: "Thiết lập ứng dụng xác thực", cantScan: "Không quét được?", setupKey: "Khóa thiết lập", codePlaceholder: "Mã 6 chữ số", recoveryPlaceholder: "Nhập mã khôi phục", passwordPlaceholder: "Nhập mật khẩu", enabledTitle: "Xác thực hai yếu tố đang bật", savedCodesAction: "Tôi đã lưu các mã này", copyHint: "Nhấn và giữ để sao chép." },
};
