import type { CreateMobileSavedItem,FlightResult,MobileSavedItem } from "../api/travelApi";
import { mapDestinationToSaved,mapFlightToSaved,mapHotelToSaved,savedSignature } from "./savedMapping";
export type SavedSnapshot={destinationIds:Set<string>;flights:Map<string,FlightResult>;items:MobileSavedItem[];loading:boolean;error:string};
export type SavedRepositoryDependencies={readCache:(u:string)=>Promise<MobileSavedItem[]>;writeCache:(u:string,v:MobileSavedItem[])=>Promise<void>;list:()=>Promise<{items:MobileSavedItem[];summary:Record<string,number>}>;create:(v:CreateMobileSavedItem)=>Promise<{item:MobileSavedItem}>;remove:(type:MobileSavedItem["type"],id:string)=>Promise<unknown>;readDestinations:(u:string)=>Promise<string[]>;writeDestinations:(u:string,v:readonly string[])=>Promise<void>;readFlights:(u:string)=>Promise<FlightResult[]>;writeFlights:(u:string,v:readonly FlightResult[])=>Promise<void>};
type Listener=(value:SavedSnapshot)=>void;
export function canonicalItemsNewestFirst(items:readonly MobileSavedItem[]){const sorted=[...items].sort((a,b)=>{const at=Date.parse(typeof a.createdAt==="string"?a.createdAt:"")||0;const bt=Date.parse(typeof b.createdAt==="string"?b.createdAt:"")||0;return bt-at;});const signatures=new Set<string>();return sorted.filter(item=>{const signature=savedSignature(item);if(signatures.has(signature))return false;signatures.add(signature);return true;});}
function project(items:MobileSavedItem[]){const destinationIds=new Set<string>();const flights=new Map<string,FlightResult>();for(const item of items){if(item.type==="search"){const q=item.query as Record<string,unknown>|undefined;if(typeof q?.destinationId==="string")destinationIds.add(q.destinationId);}if(item.type==="flight"){const p=item.payload as Record<string,unknown>|undefined;const result=p?.result as FlightResult|undefined;if(result?.id)flights.set(result.id,result);}}return{destinationIds,flights};}
export class SavedRepository {private value:SavedSnapshot={destinationIds:new Set(),flights:new Map(),items:[],loading:true,error:""};private listeners=new Set<Listener>();private revision=0;constructor(private userId:string,private dependencies:SavedRepositoryDependencies){}snapshot(){return{...this.value,destinationIds:new Set(this.value.destinationIds),flights:new Map(this.value.flights)}}subscribe(l:Listener){this.listeners.add(l);return()=>{this.listeners.delete(l);}}private publish(rawItems:MobileSavedItem[],patch:Partial<SavedSnapshot>={}){const items=canonicalItemsNewestFirst(rawItems);this.value={...this.value,...project(items),items,...patch};this.listeners.forEach(l=>l(this.snapshot()));}
 async refresh(options:{hydrateFromCache?:boolean}={}){const hydrateFromCache=options.hydrateFromCache??true;const requested=++this.revision;const fallback=hydrateFromCache?await this.dependencies.readCache(this.userId):this.value.items;if(requested!==this.revision)return;if(hydrateFromCache)this.publish(fallback,{loading:true,error:""});try{let items=(await this.dependencies.list()).items;const signatures=new Set(items.map(savedSignature));const unsupported:string[]=[];const legacy=[...(await this.dependencies.readDestinations(this.userId)).map(mapDestinationToSaved),...(await this.dependencies.readFlights(this.userId)).map((flight)=>mapFlightToSaved(flight))];for(const candidate of legacy){if(!candidate){unsupported.push("destination");continue;}const signature=savedSignature(candidate);if(signatures.has(signature))continue;try{const created=await this.dependencies.create(candidate);items=[...items,{...created.item,...candidate,type:candidate.type}];signatures.add(signature);}catch{unsupported.push(signature);}}items=canonicalItemsNewestFirst(items);if(requested!==this.revision)return;if(!unsupported.length)await Promise.all([this.dependencies.writeDestinations(this.userId,[]),this.dependencies.writeFlights(this.userId,[])]);await this.dependencies.writeCache(this.userId,items);this.publish(items,{loading:false,error:unsupported.length ? `${unsupported.length} legacy save(s) could not be synchronized.` : ""});}catch{if(requested===this.revision)this.publish(fallback,{loading:false,error:hydrateFromCache?"Saved items are offline. Showing the last synchronized copy.":"Unable to synchronize saved items. Your saved changes remain available."});}}
 async remove(type:MobileSavedItem["type"],id:string){const before=this.value.items;const optimistic=before.filter(item=>item.id!==id);const mutationRevision=++this.revision;this.publish(optimistic,{error:""});try{await this.dependencies.remove(type,id);}catch(error){if(mutationRevision===this.revision){this.publish(before,{error:"Unable to remove saved item. The previous state was restored."});await this.dependencies.writeCache(this.userId,before);}throw error;}if(mutationRevision!==this.revision)return;await this.dependencies.writeCache(this.userId,optimistic);if(mutationRevision!==this.revision)return;await this.refresh({hydrateFromCache:false});}
 async toggleDestination(id:string){const payload=mapDestinationToSaved(id);if(!payload)return;return this.toggle(payload,i=>i.type==="search"&&(i.query as Record<string,unknown>|undefined)?.destinationId===id);}
 async toggleHotel(h:import("../api/travelApi").HotelResult,params:Record<string,unknown>){const payload=mapHotelToSaved(h,params);if(!payload)return;return this.toggle(payload,i=>i.type==="hotel"&&((i.payload as Record<string,unknown>|undefined)?.result as {id?:string}|undefined)?.id===h.id);}
 async toggleFlight(f:FlightResult,params?:Record<string,unknown>){return this.toggle(mapFlightToSaved(f,params),i=>i.type==="flight"&&((i.payload as Record<string,unknown>|undefined)?.result as FlightResult|undefined)?.id===f.id);}
 private async toggle(payload:CreateMobileSavedItem,match:(i:MobileSavedItem)=>boolean){const before=this.value.items;const existing=before.find(match);const optimistic=existing?before.filter(i=>i!==existing):[...before,{...payload,id:`optimistic-${Date.now()}`,createdAt:new Date().toISOString()} as MobileSavedItem];this.revision++;this.publish(optimistic,{error:""});try{if(existing)await this.dependencies.remove(existing.type,existing.id);else await this.dependencies.create(payload);await this.refresh();}catch(error){this.publish(before,{error:"Unable to update saved items. Your previous saved state was restored."});await this.dependencies.writeCache(this.userId,before);throw error;}}
}
