import assert from "node:assert/strict";import test from "node:test";import { SavedRepository,type SavedRepositoryDependencies } from "./savedRepositoryCore";import { mapDestinationToSaved,savedSignature } from "./savedMapping";import type { MobileSavedItem } from "../api/travelApi";
const legacy="fr-paris";function deferred<T>(){let resolve!:(v:T)=>void;const promise=new Promise<T>(r=>resolve=r);return{promise,resolve};}function setup(options:{destinations?:string[];failCreates?:number;offline?:boolean;initial?:MobileSavedItem[]}={}){let server=[...(options.initial||[])],cache:MobileSavedItem[]=[];let destinations=options.destinations||[legacy];let creates=0,clears=0;const deps:SavedRepositoryDependencies={readCache:async()=>cache,writeCache:async(_u,v)=>{cache=[...v]},list:async()=>{if(options.offline)throw Error();return{items:server,summary:{}}},create:async p=>{creates++;if(creates<=(options.failCreates||0))throw Error();const item={...p,id:`server-${creates}`} as MobileSavedItem;server.push(item);return{item}},remove:async(_t,id)=>{server=server.filter(x=>x.id!==id);return{success:true}},readDestinations:async()=>destinations,writeDestinations:async(_u,v)=>{destinations=[...v];clears++},readFlights:async()=>[],writeFlights:async()=>{clears++}};return{repo:new SavedRepository("user-a",deps),deps,get server(){return server},get cache(){return cache},get destinations(){return destinations},get creates(){return creates},get clears(){return clears}};}
test("complete success uploads, caches and clears legacy only after success",async()=>{const f=setup();await f.repo.refresh();assert.equal(f.server.length,1);assert.equal(f.cache.length,1);assert.deepEqual(f.destinations,[]);assert.equal(f.repo.snapshot().error,"");});
test("partial failure retains legacy and retry posts only missing signature",async()=>{const existing={...mapDestinationToSaved(legacy)!,id:"existing"} as MobileSavedItem;const f=setup({destinations:[legacy,"unsupported"],initial:[existing],failCreates:1});await f.repo.refresh();assert.deepEqual(f.destinations,[legacy,"unsupported"]);assert.equal(f.creates,0);assert.match(f.repo.snapshot().error,/legacy save/);await f.repo.refresh();assert.equal(f.server.filter(x=>savedSignature(x)===savedSignature(existing)).length,1);});
test("repeated migration is idempotent",async()=>{const f=setup();await f.repo.refresh();const creates=f.creates;await f.repo.refresh();assert.equal(f.creates,creates);assert.equal(f.server.length,1);});
test("unsupported records are retained separately from offline failure",async()=>{const unsupported=setup({destinations:["unsupported"]});await unsupported.repo.refresh();assert.match(unsupported.repo.snapshot().error,/legacy save/);assert.deepEqual(unsupported.destinations,["unsupported"]);const offline=setup({offline:true});await offline.repo.refresh();assert.match(offline.repo.snapshot().error,/offline/);});
test("failed optimistic deletion and creation rollback canonical state",async()=>{const item={...mapDestinationToSaved(legacy)!,id:"server"} as MobileSavedItem;const deletion=setup({destinations:[],initial:[item]});await deletion.repo.refresh();deletion.deps.remove=async()=>{throw Error()};await assert.rejects(deletion.repo.remove("search","server"));assert.equal(deletion.repo.snapshot().items[0]?.id,"server");const creation=setup({destinations:[]});await creation.repo.refresh();creation.deps.create=async()=>{throw Error()};await assert.rejects(creation.repo.toggleDestination(legacy));assert.equal(creation.repo.snapshot().items.length,0);});
test("deletion cannot reappear from cleared legacy or cache",async()=>{const f=setup();await f.repo.refresh();const id=f.server[0]!.id;await f.repo.remove("search",id);assert.equal(f.repo.snapshot().items.length,0);assert.equal(f.cache.length,0);assert.deepEqual(f.destinations,[]);await f.repo.refresh();assert.equal(f.server.length,0);});
test("stale refresh cannot overwrite newer deletion",async()=>{const item={...mapDestinationToSaved(legacy)!,id:"server"} as MobileSavedItem;const late=deferred<{items:MobileSavedItem[];summary:Record<string,number>}>();const f=setup({destinations:[],initial:[item]});await f.repo.refresh();f.deps.list=()=>late.promise;const refresh=f.repo.refresh();await new Promise(r=>setTimeout(r,0));f.deps.list=async()=>({items:[],summary:{}});await f.repo.remove("search","server");late.resolve({items:[item],summary:{}});await refresh;assert.equal(f.repo.snapshot().items.length,0);});
test("account caches and migration dependencies remain isolated",async()=>{const caches=new Map<string,MobileSavedItem[]>();const base=setup();const deps={...base.deps,readCache:async (u:string)=>caches.get(u)||[],writeCache:async(u:string,v:MobileSavedItem[])=>{caches.set(u,[...v])},readDestinations:async (u:string)=>u==="a"?[legacy]:[]};const a=new SavedRepository("a",deps);const b=new SavedRepository("b",{...deps,list:async()=>({items:[],summary:{}}),create:async p=>({item:{...p,id:"b"} as MobileSavedItem})});await a.refresh();await b.refresh();assert.equal(caches.get("a")?.length,1);assert.equal(caches.get("b")?.length,0);});
test("offline cache remains visible and migration retries after recovery",async()=>{const item={...mapDestinationToSaved(legacy)!,id:"cached"} as MobileSavedItem;let offline=true;const f=setup({destinations:[]});f.deps.readCache=async()=>[item];f.deps.list=async()=>{if(offline)throw Error();return{items:[item],summary:{}}};await f.repo.refresh();assert.equal(f.repo.snapshot().items.length,1);offline=false;await f.repo.refresh();assert.equal(f.repo.snapshot().items.length,1);});
