import type { CreateMobileSavedItem,FlightResult,MobileSavedItem } from "../api/travelApi";
import { mapDestinationToSaved,mapFlightToSaved,mapHotelToSaved,savedSignature } from "./savedMapping";
export type SavedSnapshot={destinationIds:Set<string>;flights:Map<string,FlightResult>;items:MobileSavedItem[];loading:boolean;error:string};
export type SavedRepositoryDependencies={readCache:(u:string)=>Promise<MobileSavedItem[]>;writeCache:(u:string,v:MobileSavedItem[])=>Promise<void>;list:()=>Promise<{items:MobileSavedItem[];summary:Record<string,number>}>;create:(v:CreateMobileSavedItem)=>Promise<{item:MobileSavedItem}>;remove:(type:MobileSavedItem["type"],id:string)=>Promise<unknown>;readDestinations:(u:string)=>Promise<string[]>;writeDestinations:(u:string,v:readonly string[])=>Promise<void>;readFlights:(u:string)=>Promise<FlightResult[]>;writeFlights:(u:string,v:readonly FlightResult[])=>Promise<void>};
type Listener=(value:SavedSnapshot)=>void;
function project(items:MobileSavedItem[]){const destinationIds=new Set<string>();const flights=new Map<string,FlightResult>();for(const item of items){if(item.type==="search"){const q=item.query as Record<string,unknown>|undefined;if(typeof q?.destinationId==="string")destinationIds.add(q.destinationId);}if(item.type==="flight"){const p=item.payload as Record<string,unknown>|undefined;const result=p?.result as FlightResult|undefined;if(result?.id)flights.set(result.id,result);}}return{destinationIds,flights};}
export class SavedRepository {private value:SavedSnapshot={destinationIds:new Set(),flights:new Map(),items:[],loading:true,error:""};private listeners=new Set<Listener>();private revision=0;constructor(private userId:string,private dependencies:SavedRepositoryDependencies){}snapshot(){return{...this.value,destinationIds:new Set(this.value.destinationIds),flights:new Map(this.value.flights)}}subscribe(l:Listener){this.listeners.add(l);return()=>{this.listeners.delete(l);}}private publish(items:MobileSavedItem[],patch:Partial<SavedSnapshot>={}){this.value={...this.value,...project(items),items,...patch};this.listeners.forEach(l=>l(this.snapshot()));}
 async refresh(){const requested=++this.revision;const cached=await this.dependencies.readCache(this.userId);if(requested!==this.revision)return;this.publish(cached,{loading:true,error:""});try{let items=(await this.dependencies.list()).items;const signatures=new Set(items.map(savedSignature));const unsupported:string[]=[];const legacy=[...(await this.dependencies.readDestinations(this.userId)).map(mapDestinationToSaved),...(await this.dependencies.readFlights(this.userId)).map(mapFlightToSaved)];for(const candidate of legacy){if(!candidate){unsupported.push("destination");continue;}const signature=savedSignature(candidate);if(signatures.has(signature))continue;try{const created=await this.dependencies.create(candidate);items=[...items,{...created.item,...candidate,type:candidate.type}];signatures.add(signature);}catch{unsupported.push(signature);}}items=[...new Map(items.map(item=>[savedSignature(item),item])).values()];if(requested!==this.revision)return;if(!unsupported.length)await Promise.all([this.dependencies.writeDestinations(this.userId,[]),this.dependencies.writeFlights(this.userId,[])]);await this.dependencies.writeCache(this.userId,items);this.publish(items,{loading:false,error:unsupported.length ? `${unsupported.length} legacy save(s) could not be synchronized.` : ""});}catch{if(requested===this.revision)this.publish(cached,{loading:false,error:"Saved items are offline. Showing the last synchronized copy."});}}
 async remove(type:MobileSavedItem["type"],id:string){const before=this.value.items;this.revision++;this.publish(before.filter(item=>item.id!==id),{error:""});try{await this.dependencies.remove(type,id);await this.refresh();}catch(error){this.publish(before,{error:"Unable to remove saved item. The previous state was restored."});await this.dependencies.writeCache(this.userId,before);throw error;}}
 async toggleDestination(id:string){const payload=mapDestinationToSaved(id);if(!payload)return;return this.toggle(payload,i=>i.type==="search"&&(i.query as Record<string,unknown>|undefined)?.destinationId===id);}
 async toggleHotel(h:import("../api/travelApi").HotelResult,params:Record<string,unknown>){const payload=mapHotelToSaved(h,params);if(!payload)return;return this.toggle(payload,i=>i.type==="hotel"&&((i.payload as Record<string,unknown>|undefined)?.result as {id?:string}|undefined)?.id===h.id);}
 async toggleFlight(f:FlightResult){return this.toggle(mapFlightToSaved(f),i=>i.type==="flight"&&((i.payload as Record<string,unknown>|undefined)?.result as FlightResult|undefined)?.id===f.id);}
 private async toggle(payload:CreateMobileSavedItem,match:(i:MobileSavedItem)=>boolean){const before=this.value.items;const existing=before.find(match);const optimistic=existing?before.filter(i=>i!==existing):[...before,{...payload,id:`optimistic-${Date.now()}`} as MobileSavedItem];this.revision++;this.publish(optimistic,{error:""});try{if(existing)await this.dependencies.remove(existing.type,existing.id);else await this.dependencies.create(payload);await this.refresh();}catch(error){this.publish(before,{error:"Unable to update saved items. Your previous saved state was restored."});await this.dependencies.writeCache(this.userId,before);throw error;}}
}
