type TravelAccountCopy = readonly [string, string, string, string, string, string, string, string, string, string, string, string];

const keys = [
  "travel.account.hotelAlert.title", "travel.account.hotelAlert.body", "travel.account.hotelAlert.create", "travel.account.hotelAlert.target",
  "travel.account.hotelAlert.save", "travel.account.hotelAlert.saved", "travel.account.hotelAlert.duplicate", "travel.account.hotelAlert.error",
  "travel.account.package.save", "travel.account.package.saved", "travel.account.package.duplicate", "travel.account.package.error",
] as const;

type TravelAccountDictionary = Record<(typeof keys)[number], string>;
const copy = (values: TravelAccountCopy): TravelAccountDictionary => Object.fromEntries(keys.map((key, index) => [key, values[index]])) as TravelAccountDictionary;

export const travelAccountTranslations: Record<string, TravelAccountDictionary> = {
  "en-us": copy(["Track this stay price","Get notified when this complete stay search reaches your target total.","Create price alert","Target total","Save alert","Hotel price alert created.","This Hotel alert already exists. Manage it in Price alerts.","Enter a valid target total and try again.","Save package search","Package search saved.","This package search is already saved.","Package search could not be saved."]),
  "es-es": copy(["Seguir el precio de esta estancia","Recibe un aviso cuando esta búsqueda completa alcance tu total objetivo.","Crear alerta de precio","Total objetivo","Guardar alerta","Alerta de precio de hotel creada.","Esta alerta de hotel ya existe. Adminístrala en Alertas de precio.","Introduce un total objetivo válido e inténtalo de nuevo.","Guardar búsqueda de paquete","Búsqueda de paquete guardada.","Esta búsqueda de paquete ya está guardada.","No se pudo guardar la búsqueda de paquete."]),
  fr: copy(["Suivre le prix de ce séjour","Soyez averti lorsque cette recherche complète atteint votre total cible.","Créer une alerte de prix","Total cible","Enregistrer l’alerte","Alerte de prix d’hôtel créée.","Cette alerte d’hôtel existe déjà. Gérez-la dans Alertes de prix.","Saisissez un total cible valide et réessayez.","Enregistrer la recherche de forfait","Recherche de forfait enregistrée.","Cette recherche de forfait est déjà enregistrée.","Impossible d’enregistrer la recherche de forfait."]),
  de: copy(["Preis dieses Aufenthalts verfolgen","Benachrichtigung, wenn diese vollständige Suche den Zielgesamtpreis erreicht.","Preisalarm erstellen","Zielgesamtpreis","Alarm speichern","Hotel-Preisalarm erstellt.","Dieser Hotelalarm existiert bereits. Verwalte ihn unter Preisalarme.","Gib einen gültigen Zielgesamtpreis ein und versuche es erneut.","Paketsuche speichern","Paketsuche gespeichert.","Diese Paketsuche ist bereits gespeichert.","Paketsuche konnte nicht gespeichert werden."]),
  it: copy(["Segui il prezzo del soggiorno","Ricevi un avviso quando questa ricerca completa raggiunge il totale obiettivo.","Crea avviso di prezzo","Totale obiettivo","Salva avviso","Avviso prezzo hotel creato.","Questo avviso hotel esiste già. Gestiscilo in Avvisi prezzi.","Inserisci un totale obiettivo valido e riprova.","Salva ricerca pacchetto","Ricerca pacchetto salvata.","Questa ricerca pacchetto è già salvata.","Impossibile salvare la ricerca pacchetto."]),
  "pt-br": copy(["Acompanhar o preço desta estadia","Receba um aviso quando esta busca completa atingir o total desejado.","Criar alerta de preço","Total desejado","Salvar alerta","Alerta de preço de hotel criado.","Este alerta de hotel já existe. Gerencie-o em Alertas de preço.","Insira um total desejado válido e tente novamente.","Salvar busca de pacote","Busca de pacote salva.","Esta busca de pacote já está salva.","Não foi possível salvar a busca de pacote."]),
  nl: copy(["Prijs van dit verblijf volgen","Ontvang bericht wanneer deze volledige zoekopdracht je doeltotaal bereikt.","Prijswaarschuwing maken","Doeltotaal","Waarschuwing opslaan","Hotelprijswaarschuwing gemaakt.","Deze hotelwaarschuwing bestaat al. Beheer deze bij Prijswaarschuwingen.","Voer een geldig doeltotaal in en probeer opnieuw.","Pakketzoekopdracht opslaan","Pakketzoekopdracht opgeslagen.","Deze pakketzoekopdracht is al opgeslagen.","Pakketzoekopdracht kon niet worden opgeslagen."]),
  ar: copy(["تتبّع سعر هذه الإقامة","احصل على إشعار عندما يصل هذا البحث الكامل إلى الإجمالي المستهدف.","إنشاء تنبيه سعر","الإجمالي المستهدف","حفظ التنبيه","تم إنشاء تنبيه سعر الفندق.","تنبيه الفندق هذا موجود بالفعل. أدِره في تنبيهات الأسعار.","أدخل إجماليًا مستهدفًا صالحًا وحاول مرة أخرى.","حفظ بحث الباقة","تم حفظ بحث الباقة.","بحث الباقة هذا محفوظ بالفعل.","تعذر حفظ بحث الباقة."]),
  "zh-cn": copy(["跟踪此次住宿价格","当此完整搜索达到目标总价时接收通知。","创建价格提醒","目标总价","保存提醒","酒店价格提醒已创建。","此酒店提醒已存在。请在价格提醒中管理。","请输入有效的目标总价后重试。","保存套餐搜索","套餐搜索已保存。","此套餐搜索已保存。","无法保存套餐搜索。"]),
  ja: copy(["この宿泊料金を追跡","この検索が目標合計に達したら通知します。","料金アラートを作成","目標合計","アラートを保存","ホテル料金アラートを作成しました。","このホテルアラートは既にあります。料金アラートで管理してください。","有効な目標合計を入力して、もう一度お試しください。","パッケージ検索を保存","パッケージ検索を保存しました。","このパッケージ検索は既に保存されています。","パッケージ検索を保存できませんでした。"]),
  ko: copy(["이 숙박 가격 추적","이 전체 검색이 목표 총액에 도달하면 알려드립니다.","가격 알림 만들기","목표 총액","알림 저장","호텔 가격 알림을 만들었습니다.","이 호텔 알림은 이미 있습니다. 가격 알림에서 관리하세요.","유효한 목표 총액을 입력하고 다시 시도하세요.","패키지 검색 저장","패키지 검색을 저장했습니다.","이 패키지 검색은 이미 저장되어 있습니다.","패키지 검색을 저장할 수 없습니다."]),
  hi: copy(["इस ठहराव की कीमत ट्रैक करें","यह पूरी खोज लक्ष्य कुल तक पहुँचे तो सूचना पाएँ।","कीमत अलर्ट बनाएँ","लक्ष्य कुल","अलर्ट सहेजें","होटल कीमत अलर्ट बनाया गया।","यह होटल अलर्ट पहले से मौजूद है। इसे कीमत अलर्ट में प्रबंधित करें।","मान्य लक्ष्य कुल दर्ज करके फिर कोशिश करें।","पैकेज खोज सहेजें","पैकेज खोज सहेजी गई।","यह पैकेज खोज पहले से सहेजी गई है।","पैकेज खोज सहेजी नहीं जा सकी।"]),
  tr: copy(["Bu konaklama fiyatını takip et","Bu tam arama hedef toplama ulaştığında bildirim alın.","Fiyat uyarısı oluştur","Hedef toplam","Uyarıyı kaydet","Otel fiyat uyarısı oluşturuldu.","Bu otel uyarısı zaten var. Fiyat uyarılarında yönetin.","Geçerli bir hedef toplam girip tekrar deneyin.","Paket aramasını kaydet","Paket araması kaydedildi.","Bu paket araması zaten kayıtlı.","Paket araması kaydedilemedi."]),
  pl: copy(["Śledź cenę tego pobytu","Otrzymaj powiadomienie, gdy pełne wyszukiwanie osiągnie sumę docelową.","Utwórz alert cenowy","Suma docelowa","Zapisz alert","Utworzono alert ceny hotelu.","Ten alert hotelowy już istnieje. Zarządzaj nim w Alertach cenowych.","Wpisz prawidłową sumę docelową i spróbuj ponownie.","Zapisz wyszukiwanie pakietu","Wyszukiwanie pakietu zapisane.","To wyszukiwanie pakietu jest już zapisane.","Nie udało się zapisać wyszukiwania pakietu."]),
  sv: copy(["Följ priset för vistelsen","Få ett meddelande när den fullständiga sökningen når måltotalen.","Skapa prisavisering","Måltotal","Spara avisering","Hotellprisaviseringen skapades.","Den här hotellaviseringen finns redan. Hantera den i Prisaviseringar.","Ange en giltig måltotal och försök igen.","Spara paketsökning","Paketsökningen sparades.","Den här paketsökningen är redan sparad.","Paketsökningen kunde inte sparas."]),
  id: copy(["Pantau harga menginap ini","Dapatkan notifikasi saat pencarian lengkap ini mencapai total target.","Buat peringatan harga","Total target","Simpan peringatan","Peringatan harga hotel dibuat.","Peringatan hotel ini sudah ada. Kelola di Peringatan harga.","Masukkan total target yang valid lalu coba lagi.","Simpan pencarian paket","Pencarian paket disimpan.","Pencarian paket ini sudah disimpan.","Pencarian paket tidak dapat disimpan."]),
  th: copy(["ติดตามราคาที่พักนี้","รับการแจ้งเตือนเมื่อการค้นหาที่ครบถ้วนถึงยอดรวมเป้าหมาย","สร้างการแจ้งเตือนราคา","ยอดรวมเป้าหมาย","บันทึกการแจ้งเตือน","สร้างการแจ้งเตือนราคาโรงแรมแล้ว","มีการแจ้งเตือนโรงแรมนี้แล้ว จัดการได้ในหน้าการแจ้งเตือนราคา","ป้อนยอดรวมเป้าหมายที่ถูกต้องแล้วลองอีกครั้ง","บันทึกการค้นหาแพ็กเกจ","บันทึกการค้นหาแพ็กเกจแล้ว","บันทึกการค้นหาแพ็กเกจนี้ไว้แล้ว","ไม่สามารถบันทึกการค้นหาแพ็กเกจได้"]),
  vi: copy(["Theo dõi giá kỳ nghỉ này","Nhận thông báo khi tìm kiếm đầy đủ này đạt tổng mục tiêu.","Tạo cảnh báo giá","Tổng mục tiêu","Lưu cảnh báo","Đã tạo cảnh báo giá khách sạn.","Cảnh báo khách sạn này đã tồn tại. Hãy quản lý trong Cảnh báo giá.","Nhập tổng mục tiêu hợp lệ rồi thử lại.","Lưu tìm kiếm gói","Đã lưu tìm kiếm gói.","Tìm kiếm gói này đã được lưu.","Không thể lưu tìm kiếm gói."]),
};

export { keys as travelAccountTranslationKeys };
