"use client";

import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { BedDouble, Car, Plane, Search } from "lucide-react";
import { useLocale } from "@/components/layout/LocaleProvider";
import { useRouteProgress } from "@/components/layout/RouteProgress";
import { translations as en } from "@/lib/i18n/en";
import { driverAgeOptions, timeOptions } from "@/lib/cars/carsSearchUtils";
import {
  buildDealsResultsUrl, createDefaultDealsSearch, dealsPackageModes,
  getIncludedProducts, parseDealsSearchParams, validateDealsSearch,
  type DealsPackageMode, type DealsSearch, type DealsProduct,
} from "@/lib/deals/dealsSearchParams";
import { formatAirportLabel, type AirportOption } from "@/data/airports";

type HotelSuggestion = { id: string; name: string; country: string; searchValue: string };
const modeKeys: Record<DealsPackageMode, string> = { "hotel-flight": "deals.package.hotelFlight", "hotel-flight-car": "deals.package.hotelFlightCar", "flight-car": "deals.package.flightCar", "hotel-car": "deals.package.hotelCar" };
const field = "min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-base font-medium text-slate-900 outline-none focus:border-[#004BB8] focus:ring-2 focus:ring-[#004BB8]/20";
const label = "mb-1.5 block text-xs font-bold uppercase tracking-[0.1em] text-slate-600";

function Counter({ value, onChange, min = 0, max = 12, text }: { value: number; onChange: (value: number) => void; min?: number; max?: number; text: string }) {
  return <div className="flex min-h-11 items-center justify-between rounded-xl border border-slate-300 px-3"><span className="text-sm font-semibold text-slate-700">{text}: {value}</span><span className="flex gap-2"><button type="button" aria-label={`${text} −`} disabled={value <= min} onClick={() => onChange(value - 1)} className="focus-ring h-8 w-8 rounded-full border disabled:opacity-40">−</button><button type="button" aria-label={`${text} +`} disabled={value >= max} onClick={() => onChange(value + 1)} className="focus-ring h-8 w-8 rounded-full border disabled:opacity-40">+</button></span></div>;
}

export function DealsSearchForm() {
  const params = useSearchParams(); const router = useRouter(); const { start } = useRouteProgress();
  const { t: dictionary } = useLocale(); const t = useCallback((key: string) => dictionary[key] ?? en[key] ?? key, [dictionary]);
  const [search, setSearch] = useState<DealsSearch>(() => params.size ? parseDealsSearchParams(params) : createDefaultDealsSearch());
  const [errors, setErrors] = useState<ReturnType<typeof validateDealsSearch>>({}); const [submitting, setSubmitting] = useState(false);
  const [airportLists, setAirportLists] = useState<Record<"origin" | "destination", AirportOption[]>>({ origin: [], destination: [] });
  const [hotelSuggestions, setHotelSuggestions] = useState<HotelSuggestion[]>([]);
  const dirty = useRef({ hotelDestination: Boolean(search.hotelDestination), hotelDates: params.has("hotelCheckIn"), carLocation: Boolean(search.carPickupLocation), carDates: params.has("carPickupDate") });
  const firstError = useRef<HTMLDivElement>(null);
  const included = getIncludedProducts(search.mode);
  const update = <K extends keyof DealsSearch>(key: K, value: DealsSearch[K]) => setSearch((current) => ({ ...current, [key]: value }));

  const loadAirports = useCallback(async (kind: "origin" | "destination", query: string) => {
    if (query.trim().length < 2) return setAirportLists((all) => ({ ...all, [kind]: [] }));
    const response = await fetch(`/api/flights/places?${new URLSearchParams({ q: query, context: kind })}`); if (!response.ok) return;
    const payload = await response.json() as { suggestions?: AirportOption[] }; setAirportLists((all) => ({ ...all, [kind]: payload.suggestions?.slice(0, 6) ?? [] }));
  }, []);
  const loadHotels = useCallback(async (query: string) => {
    const response = await fetch(`/api/hotels/destinations?${new URLSearchParams({ q: query, limit: "8" })}`); if (!response.ok) return;
    const payload = await response.json() as { suggestions?: HotelSuggestion[] }; setHotelSuggestions(payload.suggestions?.slice(0, 8) ?? []);
  }, []);
  useEffect(() => { const id = setTimeout(() => void loadAirports("origin", search.flightOriginText), 250); return () => clearTimeout(id); }, [loadAirports, search.flightOriginText]);
  useEffect(() => { const id = setTimeout(() => void loadAirports("destination", search.flightDestinationText), 250); return () => clearTimeout(id); }, [loadAirports, search.flightDestinationText]);
  useEffect(() => { const id = setTimeout(() => void loadHotels(search.hotelDestination), 250); return () => clearTimeout(id); }, [loadHotels, search.hotelDestination]);

  const chooseAirport = (kind: "origin" | "destination", option: AirportOption) => {
    const text = formatAirportLabel(option); const codeKey = kind === "origin" ? "flightOriginCode" : "flightDestinationCode"; const textKey = kind === "origin" ? "flightOriginText" : "flightDestinationText";
    setSearch((current) => ({ ...current, [textKey]: text, [codeKey]: option.code.toUpperCase(), ...kind === "destination" && !dirty.current.hotelDestination ? { hotelDestination: option.city } : {}, ...kind === "destination" && !dirty.current.carLocation ? { carPickupLocation: option.city } : {} }));
    setAirportLists((all) => ({ ...all, [kind]: [] }));
  };
  const syncFlightDates = (key: "flightDepartureDate" | "flightReturnDate", value: string) => setSearch((current) => ({ ...current, [key]: value, ...!dirty.current.hotelDates ? { [key === "flightDepartureDate" ? "hotelCheckIn" : "hotelCheckOut"]: value } : {}, ...!dirty.current.carDates ? { [key === "flightDepartureDate" ? "carPickupDate" : "carReturnDate"]: value } : {} }));
  const submit = (event: FormEvent) => { event.preventDefault(); if (submitting) return; const found = validateDealsSearch(search); setErrors(found); if (Object.keys(found).length) { requestAnimationFrame(() => firstError.current?.scrollIntoView({ behavior: "smooth", block: "center" })); return; } setSubmitting(true); start(); router.push(buildDealsResultsUrl(search)); };
  const errorBlock = (product: DealsProduct) => errors[product] ? <div ref={firstError} role="alert" aria-live="polite" className="mt-3 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm font-semibold text-rose-700">{Object.values(errors[product] ?? {}).map(t).join(" ")}</div> : null;

  return <form onSubmit={submit} noValidate className="mx-auto w-full max-w-[1120px] rounded-3xl border border-slate-200 bg-white p-4 shadow-[0_18px_46px_rgba(15,23,42,0.12)] sm:p-6">
    <fieldset><legend className="sr-only">{t("deals.packageLegend")}</legend><div className="-mx-1 flex gap-2 overflow-x-auto px-1 pb-4">{dealsPackageModes.map((mode) => <label key={mode} className={`shrink-0 cursor-pointer rounded-full border px-4 py-2 text-sm font-extrabold ${search.mode === mode ? "border-[#004BB8] bg-[#004BB8]/10 text-[#004BB8]" : "border-slate-200 text-slate-700"}`}><input className="sr-only" type="radio" name="packageMode" checked={search.mode === mode} onChange={() => update("mode", mode)} />{t(modeKeys[mode])}</label>)}</div></fieldset>
    {included.flight && <section aria-labelledby="deals-flight-heading" className="border-t border-slate-200 py-5"><h2 id="deals-flight-heading" className="mb-4 flex items-center gap-2 text-base font-extrabold text-[#021C2B]"><Plane className="h-5 w-5 text-[#004BB8]" />{t("flights")}</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
      {(["origin", "destination"] as const).map((kind) => { const textKey = kind === "origin" ? "flightOriginText" : "flightDestinationText"; const codeKey = kind === "origin" ? "flightOriginCode" : "flightDestinationCode"; return <div className="relative" key={kind}><label className={label} htmlFor={`flight-${kind}`}>{t(kind === "origin" ? "deals.originLabel" : "deals.destinationLabel")}</label><input id={`flight-${kind}`} role="combobox" aria-expanded={airportLists[kind].length > 0} aria-controls={`flight-${kind}-options`} value={search[textKey]} onChange={(e) => setSearch((current) => ({ ...current, [textKey]: e.target.value, [codeKey]: /^[a-z]{3}$/i.test(e.target.value.trim()) ? e.target.value.trim().toUpperCase() : "" }))} className={field} autoComplete="off" />{airportLists[kind].length > 0 && <ul id={`flight-${kind}-options`} role="listbox" className="absolute z-30 mt-1 max-h-64 w-full overflow-auto rounded-xl border bg-white p-1 shadow-xl">{airportLists[kind].map((option) => <li key={option.code}><button type="button" className="w-full rounded-lg p-2 text-start text-sm hover:bg-slate-100" onClick={() => chooseAirport(kind, option)}>{formatAirportLabel(option)}</button></li>)}</ul>}</div>; })}
      <div className="grid grid-cols-2 gap-2"><label><span className={label}>{t("departureDate")}</span><input type="date" value={search.flightDepartureDate} onChange={(e) => syncFlightDates("flightDepartureDate", e.target.value)} className={field} /></label><label><span className={label}>{t("returnDate")}</span><input type="date" value={search.flightReturnDate} onChange={(e) => syncFlightDates("flightReturnDate", e.target.value)} className={field} /></label></div>
      <div><span className={label}>{t("deals.travelersCabinLabel")}</span><div className="grid grid-cols-3 gap-1"><Counter text={t("adults")} value={search.flightAdults} min={1} max={9} onChange={(v) => update("flightAdults", v)} /><Counter text={t("children")} value={search.flightChildren} max={8} onChange={(v) => update("flightChildren", v)} /><Counter text={t("infants")} value={search.flightInfants} max={8} onChange={(v) => update("flightInfants", v)} /></div><select aria-label={t("deals.cabinClass")} value={search.flightCabinClass} onChange={(e) => update("flightCabinClass", e.target.value as DealsSearch["flightCabinClass"])} className={`${field} mt-2`}><option value="economy">{t("deals.cabin.economy")}</option><option value="business">{t("deals.cabin.business")}</option><option value="first">{t("deals.cabin.first")}</option></select></div>
    </div>{errorBlock("flight")}</section>}
    {included.hotel && <section aria-labelledby="deals-hotel-heading" className="border-t border-slate-200 py-5"><h2 id="deals-hotel-heading" className="mb-4 flex items-center gap-2 text-base font-extrabold text-[#021C2B]"><BedDouble className="h-5 w-5 text-[#004BB8]" />{t("hotels")}</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="relative"><label className={label} htmlFor="hotel-destination">{t("deals.destinationLabel")}</label><input id="hotel-destination" role="combobox" aria-controls="hotel-destination-options" aria-expanded={hotelSuggestions.length > 0} value={search.hotelDestination} onChange={(e) => { dirty.current.hotelDestination = true; update("hotelDestination", e.target.value); }} className={field} autoComplete="off" />{hotelSuggestions.length > 0 && <ul id="hotel-destination-options" role="listbox" className="absolute z-20 mt-1 max-h-64 w-full overflow-auto rounded-xl border bg-white p-1 shadow-xl">{hotelSuggestions.map((option) => <li key={option.id}><button type="button" className="w-full rounded-lg p-2 text-start text-sm hover:bg-slate-100" onClick={() => { dirty.current.hotelDestination = true; update("hotelDestination", option.searchValue); setHotelSuggestions([]); }}>{option.name}, {option.country}</button></li>)}</ul>}</div><div className="grid grid-cols-2 gap-2"><label><span className={label}>{t("checkIn")}</span><input type="date" value={search.hotelCheckIn} onChange={(e) => { dirty.current.hotelDates = true; update("hotelCheckIn", e.target.value); }} className={field} /></label><label><span className={label}>{t("checkOut")}</span><input type="date" value={search.hotelCheckOut} onChange={(e) => { dirty.current.hotelDates = true; update("hotelCheckOut", e.target.value); }} className={field} /></label></div><div className="grid grid-cols-2 gap-2"><Counter text={t("adults")} value={search.hotelAdults} min={1} onChange={(v) => update("hotelAdults", v)} /><Counter text={t("children")} value={search.hotelChildren} onChange={(v) => update("hotelChildren", v)} /></div><div><Counter text={t("rooms")} value={search.hotelRooms} min={1} max={6} onChange={(v) => update("hotelRooms", v)} /><label className="mt-2 flex min-h-11 items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={search.hotelPetFriendly} onChange={(e) => update("hotelPetFriendly", e.target.checked)} />{t("petFriendly")}</label></div></div>{errorBlock("hotel")}</section>}
    {included.car && <section aria-labelledby="deals-car-heading" className="border-t border-slate-200 py-5"><h2 id="deals-car-heading" className="mb-4 flex items-center gap-2 text-base font-extrabold text-[#021C2B]"><Car className="h-5 w-5 text-[#004BB8]" />{t("cars")}</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label><span className={label}>{t("carsSearch.pickupLocationLabel")}</span><input value={search.carPickupLocation} onChange={(e) => { dirty.current.carLocation = true; update("carPickupLocation", e.target.value); }} className={field} /></label><div className="grid grid-cols-2 gap-2"><label><span className={label}>{t("departureDate")}</span><input type="date" value={search.carPickupDate} onChange={(e) => { dirty.current.carDates = true; update("carPickupDate", e.target.value); }} className={field} /></label><label><span className={label}>{t("returnDate")}</span><input type="date" value={search.carReturnDate} onChange={(e) => { dirty.current.carDates = true; update("carReturnDate", e.target.value); }} className={field} /></label></div><div className="grid grid-cols-2 gap-2"><label><span className={label}>{t("carsSearch.pickupTimeLabel")}</span><select value={search.carPickupTime} onChange={(e) => update("carPickupTime", e.target.value)} className={field}>{timeOptions.map((v) => <option key={v}>{v}</option>)}</select></label><label><span className={label}>{t("carsSearch.returnTimeLabel")}</span><select value={search.carReturnTime} onChange={(e) => update("carReturnTime", e.target.value)} className={field}>{timeOptions.map((v) => <option key={v}>{v}</option>)}</select></label></div><label><span className={label}>{t("carsSearch.driverAgeLabel")}</span><select value={search.carDriverAge} onChange={(e) => update("carDriverAge", e.target.value)} className={field}>{driverAgeOptions.map((v) => <option key={v}>{v === "18-70" ? t("carsSearch.driverAgeAnyAgeRange") : v}</option>)}</select></label></div><label className="mt-3 flex min-h-11 items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={search.carReturnToDifferentLocation} onChange={(e) => update("carReturnToDifferentLocation", e.target.checked)} />{t("carsSearch.differentReturnLocation")}</label>{search.carReturnToDifferentLocation && <label className="mt-2 block max-w-md"><span className={label}>{t("carsSearch.returnLocationPlaceholder")}</span><input value={search.carReturnLocation} onChange={(e) => update("carReturnLocation", e.target.value)} className={field} /></label>}{errorBlock("car")}</section>}
    <div className="flex justify-end border-t border-slate-200 pt-5"><button type="submit" disabled={submitting} aria-busy={submitting} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#004BB8] px-8 text-sm font-extrabold text-white shadow-lg shadow-blue-900/20 hover:bg-[#021C2B] disabled:opacity-70 sm:w-auto"><Search className="h-4 w-4" />{t("deals.searchButton")}</button></div>
  </form>;
}
