import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";
const source=readFileSync(resolve("src/features/search/NativeFlightDetails.tsx"),"utf8");
const itinerary=source.slice(source.indexOf("function Itinerary"),source.indexOf("function FareSurface"));
test("authoritative route summary uses the shared complete route model",()=>assert.match(source,/flightDetailsRouteLabel\(details\.search\.tripType,offer\.legs\?\?\[\]/));
test("itinerary includes provider airport and journey facts",()=>{for(const fact of ["point.name","point.cityName","point.terminal","point.timeZone","leg.duration","leg.layovers"])assert.match(itinerary,new RegExp(fact.replace(".","\\.")));});
test("segments preserve carrier, schedule, equipment, distance, cabins and technical stop times",()=>{for(const fact of ["resolveSegmentCarrierName","segment.departureTime","segment.arrivalTime","operatingFlightNumber","segment.aircraft","segment.distanceKm","segment.cabinDetails","stop.arrivalTime","stop.departureTime"])assert.match(itinerary,new RegExp(fact.replace(".","\\.")));});
test("passenger connections and technical stops remain distinct",()=>{assert.match(itinerary,/passenger stop/);assert.match(itinerary,/technical stop/);assert.match(itinerary,/Connection:/);});
