import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";
const shell=readFileSync("src/features/search/FlightResultsSheetShell.tsx","utf8");
test("Flight quick filters use only the Hotel backdrop color while shared consumers retain legacy blur",()=>{
  assert.match(shell,/transparent=\{!fullScreen\}/);
  assert.match(shell,/animationType=\{fullScreen \? "slide" : "none"\}/);
  assert.match(shell,/"overFullScreen"/);
  assert.match(shell,/type QuickBackdropVariant = "flight" \| "legacy"/);
  assert.match(shell,/quickBackdropVariant = "flight"/);
  assert.match(shell,/const flightQuickBackdrop = quickBackdropVariant === "flight"/);
  assert.match(shell,/flightQuickBackdrop \? <View style=\{\[StyleSheet\.absoluteFill, styles\.quickBackdropScrim\]\}\/> : <BlurView intensity=\{12\} tint="dark"/);
  assert.match(shell,/quickBackdropScrim: \{ backgroundColor: "rgba\(15, 23, 42, 0\.35\)" \}/);
  assert.doesNotMatch(shell,/quickBackdropIntensity|quickBackdropTint|flightQuickBackdrop \? 4 : 12|intensity=\{4\}/);
  assert.match(shell,/Animated\.View/);
  assert.match(shell,/Animated\.timing\(quickBackdropOpacity/);
  assert.match(shell,/duration: 160/);
  assert.match(shell,/Animated\.timing\(quickSheetTranslateY/);
  assert.match(shell,/KeyboardAvoidingView/);
  assert.match(shell,/onRequestClose=\{onClose\}/);
  assert.match(shell,/onAccessibilityEscape=\{onClose\}/);
  assert.match(shell,/borderTopLeftRadius: 24/);
  assert.doesNotMatch(shell,/animationType="fade"|compactMenu|measureInWindow/);
});
test("main Flight Filter remains full screen",()=>{assert.match(shell,/presentationStyle=\{fullScreen \? "fullScreen"/);assert.match(shell,/styles\.fullScreen/);});
test("Flight quick sheets use a symmetric outer inset without changing shared legacy sheets",()=>{
  const filter=readFileSync("src/features/search/FlightFilterSheet.tsx","utf8");
  const sort=readFileSync("src/features/search/FlightSortSheet.tsx","utf8");
  const cars=readFileSync("src/features/search/CarFilterSheet.tsx","utf8");
  assert.match(shell,/FLIGHT_QUICK_SHEET_HORIZONTAL_INSET = 12/);
  assert.match(shell,/insetFlightQuickSheet = false/);
  assert.match(shell,/insetFlightQuickSheet: \{ width: "auto", marginHorizontal: FLIGHT_QUICK_SHEET_HORIZONTAL_INSET \}/);
  assert.match(shell,/insetFlightQuickSheet \? <SafeAreaView edges=\{\["left", "right"\]\}>/);
  assert.match(filter,/insetFlightQuickSheet=\{!full\}/);
  assert.match(sort,/insetFlightQuickSheet/);
  assert.doesNotMatch(cars,/insetFlightQuickSheet/);
});
test("only inset Flight quick sheets float above the safe area with four matching corners",()=>{
  const cars=readFileSync("src/features/search/CarFilterSheet.tsx","utf8");
  assert.match(shell,/FLIGHT_FLOATING_SHEET_BOTTOM_GAP = 12/);
  assert.match(shell,/const floatingBottomGap = FLIGHT_FLOATING_SHEET_BOTTOM_GAP/);
  assert.match(shell,/insetFlightQuickSheet && \{ marginBottom: floatingBottomGap \}/);
  assert.match(shell,/insetFlightQuickSheet && styles\.floatingFlightSheet/);
  assert.match(shell,/floatingFlightSheet: \{ borderBottomLeftRadius: 24, borderBottomRightRadius: 24 \}/);
  assert.doesNotMatch(cars,/floatingFlightSheet|FLIGHT_FLOATING_SHEET_BOTTOM_GAP/);
});
test("only inset Flight quick sheets use a balanced centered header with the close control on the right",()=>{
  const cars=readFileSync("src/features/search/CarFilterSheet.tsx","utf8");
  assert.match(shell,/const flightQuickHeader = insetFlightQuickSheet/);
  assert.match(shell,/flightQuickHeader \? <>[\s\S]*?<View accessible=\{false\} importantForAccessibility="no-hide-descendants" style=\{styles\.headerSlot\} \/>[\s\S]*?<View style=\{\[styles\.headerCopy, styles\.quickHeaderCopy\]\}[\s\S]*?<Pressable accessibilityRole="button" accessibilityLabel=\{closeLabel\} onPress=\{onClose\} style=\{styles\.headerSlot\}>/);
  assert.match(shell,/headerSlot: \{ width: 44, height: 44/);
  assert.match(shell,/quickHeader: \{ paddingHorizontal: 10, borderBottomWidth: 0 \}/);
  assert.match(shell,/quickTitle: \{ textAlign: "center" \}/);
  assert.match(shell,/quickSubtitle: \{ textAlign: "center" \}/);
  assert.match(shell,/flightQuickHeader \? <>[\s\S]*?subtitle \? <Text style=\{\[styles\.subtitle, styles\.quickSubtitle/);
  assert.doesNotMatch(cars,/insetFlightQuickSheet|quickHeaderCopy|headerSlot/);
});
test("inset Flight quick sheets alone remove dividers and share the body surface",()=>{
  assert.match(shell,/FLIGHT_RESULTS_LIGHT_CANVAS = "#F5F7FB"/);
  assert.match(shell,/FLIGHT_FILTER_LIGHT_CANVAS = "#F2F4F8"/);
  assert.match(shell,/const usesFlightFilterCanvas = insetFlightQuickSheet \|\| flightFilterAppearance/);
  assert.match(shell,/const flightFilterCanvas = theme\.dark \? theme\.background : FLIGHT_FILTER_LIGHT_CANVAS/);
  assert.match(shell,/backgroundColor: usesFlightFilterCanvas \? flightFilterCanvas : theme\.surface/);
  assert.match(shell,/quickHeader: \{ paddingHorizontal: 10, borderBottomWidth: 0 \}/);
  assert.match(shell,/insetFlightQuickSheet && styles\.quickFooter/);
  assert.match(shell,/backgroundColor: sheetBackground/);
  assert.match(shell,/quickFooter: \{ borderTopWidth: 0 \}/);
  assert.match(shell,/header: \{[^}]*borderBottomWidth: StyleSheet\.hairlineWidth/);
  assert.match(shell,/footer: \{[^}]*borderTopWidth: StyleSheet\.hairlineWidth/);
});
test("full Flight and Cars filters use the approved filter canvas",()=>{
  const filter=readFileSync("src/features/search/FlightFilterSheet.tsx","utf8");
  const cars=readFileSync("src/features/search/CarFilterSheet.tsx","utf8");
  assert.match(shell,/flightFilterAppearance = false/);
  assert.match(shell,/flightFilterAppearance && styles\.flightFilterHeader/);
  assert.match(shell,/flightFilterHeader: \{ borderBottomWidth: 0 \}/);
  assert.match(filter,/flightFilterAppearance=\{full\}/);
  assert.match(cars,/FLIGHT_FILTER_LIGHT_CANVAS/);
});
test("full-screen Flight filters bypass the quick-sheet inset frame",()=>{
  assert.match(shell,/\{fullScreen \? <SafeAreaProvider><SafeAreaView edges=\{\["top", "bottom", "left", "right"\]\}/);
  assert.match(shell,/fullScreen: \{ flex: 1, minHeight: 0, borderRadius: 0 \}/);
  assert.match(shell,/insetFlightQuickSheet \? <SafeAreaView/);
});
test("anchor positioning module is deleted",()=>assert.equal(existsSync("src/features/search/flightResultsQuickMenuAnchor.ts"),false));
test("full and quick sheet bodies have distinct sizing contracts",()=>{
  assert.match(shell,/fullScreen \? styles\.fullScreenContent : styles\.quickContent/);
  assert.match(shell,/fullScreenContent: \{ flex: 1, minHeight: 0 \}/);
  assert.match(shell,/quickContent: \{ flexShrink: 1, minHeight: 0 \}/);
  assert.match(shell,/Math\.min\(height \* \.76, 620\)/);
  assert.doesNotMatch(shell,/maxHeight: fullScreen \? "100%"/);
  assert.match(shell,/fullScreen: \{ flex: 1, minHeight: 0/);
  assert.doesNotMatch(shell,/quickContent: \{[^}]*flex: 1/);
});
test("full-screen Flight filters use the modal viewport's native safe area",()=>{
  assert.ok(shell.indexOf("styles.quickContent") < shell.indexOf("styles.footer"));
  const footerStyle=/footer: \{([^}]*)\}/.exec(shell)?.[1] ?? "";
  assert.doesNotMatch(footerStyle,/position:\s*["']absolute["']/);
  assert.match(footerStyle,/flexShrink: 0/);
  assert.match(shell,/import \{ SafeAreaProvider, SafeAreaView, useSafeAreaInsets \}/);
  assert.match(shell,/<Modal[\s\S]*?<SafeAreaProvider><SafeAreaView edges=\{\["top", "bottom", "left", "right"\]\}/);
  assert.match(shell,/fullScreen[\s\S]*?\? 12[\s\S]*?: insetFlightQuickSheet[\s\S]*?Math\.max\(12, inset\.bottom - floatingBottomGap\)[\s\S]*?: Math\.max\(inset\.bottom, 12\)/);
  assert.match(shell,/paddingBottom: footerBottomPadding/);
  assert.doesNotMatch(shell,/paddingTop: fullScreen \? inset\.top|fullScreenFooter(?:Minimum|Extra)BottomPadding/);
});
