import { useEffect, useMemo, useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import type { FlightResult } from "../../api/travelApi";
import { useAppTheme } from "../../theme/AppTheme";
import { formatCurrency } from "../currency/displayCurrency";
import { FlowIcon } from "../flow/FlowIcon";
import { AirlineLogo } from "./AirlineLogo";
import { FlightRangeSlider } from "./FlightRangeSlider";
import { Button, ui } from "./SearchUi";
import { emptyFlightFilters, flightFilterInsight, isPriceFilteringAvailable, journeyKey, matchingFlightCount, withAirlinePreview, withAirportPreview, withStopsPreview, withTimePreview, type FlightFilterInsight, type FlightFilterOptions, type FlightFilters, type NumericRange, type TimeBucket } from "./flightFilters";
import { clampNumericRange, priceRangeStep } from "./flightRange";
export type FlightFilterSectionName = "all" | "stops" | "airlines";
const windows: {value:TimeBucket;label:string}[]=[{value:"overnight",label:"12:00 AM – 5:59 AM"},{value:"morning",label:"6:00 AM – 11:59 AM"},{value:"afternoon",label:"12:00 PM – 5:59 PM"},{value:"evening",label:"6:00 PM – 11:59 PM"}];
export const formatFlightDuration=(v:number)=>{const n=Math.max(0,Math.round(v)),h=Math.floor(n/60),m=n%60;return h?(m?`${h}h ${m}m`:`${h}h`):`${m}m`};
export const formatFlightFilterInsight=(insight:FlightFilterInsight,currency:string)=>insight.count===0?"No matching flights":`${insight.lowestPrice==null?"":`From ${formatCurrency(insight.lowestPrice,currency)} · `}${insight.count} ${insight.count===1?"flight":"flights"}`;
export function FlightFilterSection({title,actions,children}:{title:string;actions?:React.ReactNode;children:React.ReactNode}){const {theme}=useAppTheme();return <View style={s.section}><View style={s.sectionHead}><Text style={[s.sectionTitle,{color:theme.textPrimary}]}>{title}</Text>{actions}</View>{children}</View>}
type Props={visible:boolean;section:FlightFilterSectionName;filters:FlightFilters;options:FlightFilterOptions;results:readonly FlightResult[];priceValue?:(r:FlightResult)=>number|null;currency:string;priceFilteringReady:boolean;onChange:(f:FlightFilters)=>void;onClose:()=>void};
export function FlightFilterSheet({visible,section,filters,options,results,priceValue,currency,priceFilteringReady,onChange,onClose}:Props){
 const {theme}=useAppTheme(),inset=useSafeAreaInsets();const [draft,setDraft]=useState(filters),[dragging,setDragging]=useState(false),[tab,setTab]=useState(0);
 useEffect(()=>{if(visible){setDraft(filters);setDragging(false);setTab(0)}},[visible,filters]);
 const count=useMemo(()=>matchingFlightCount(results,draft,priceValue),[results,draft,priceValue]);const logos=useMemo(()=>results.reduce((m,r)=>{if(r.airlineLogo&&!m.has(r.airlineName))m.set(r.airlineName,r.airlineLogo);return m},new Map<string,string>()),[results]);
 const legs=useMemo(()=>{const sample=results.find(r=>r.legs?.length),structured=sample?.legs?.filter(l=>["outbound","return","leg"].includes(l.direction))??[],first=results[0];return structured.length?structured:(first?[{direction:"outbound" as const,originAirport:first.originAirport,destinationAirport:first.destinationAirport,departureTime:first.departureTime,arrivalTime:first.arrivalTime,duration:first.duration,durationMinutes:first.durationMinutes,stops:first.stops,layovers:first.layovers,segments:[]}]:[])},[results]);const leg=legs[tab],key=leg?journeyKey(leg,tab):"outbound",selection=draft.journeyTimes[key]??{departure:[],arrival:[]};const full=section==="all";
 const toggle=(field:"airlines"|"fromAirports"|"toAirports",value:string)=>setDraft(x=>({...x,[field]:x[field].includes(value)?x[field].filter(v=>v!==value):[...x[field],value]}));
 const toggleTime=(field:"departure"|"arrival",value:TimeBucket)=>setDraft(x=>{const group=x.journeyTimes[key]??{departure:[],arrival:[]},s=group[field];return {...x,journeyTimes:{...x.journeyTimes,[key]:{...group,[field]:s.includes(value)?s.filter(v=>v!==value):[...s,value]}}}});
 const slider=(field:"maximumPrice"|"maximumDuration"|"maximumLayover",range:NumericRange,label:string,format:(v:number)=>string,step:number)=>{const selected=clampNumericRange({min:range.min,max:draft[field]??range.max},range);return <><Text style={[s.value,{color:theme.textPrimary}]}>{field==="maximumPrice"?`Up to ${format(selected.max)}`:format(selected.max)}</Text><FlightRangeSlider available={range} selected={selected} step={step} singleMaximum accessibilityLabel={label} formatValue={format} onDragStateChange={setDragging} onChange={v=>setDraft(x=>({...x,[field]:v.max}))}/></>};
 const insightPriceValue=priceFilteringReady?priceValue:undefined,insightCurrency=options.priceCurrency??currency;
 const insights=useMemo(()=>{const get=(candidate:FlightFilters)=>formatFlightFilterInsight(flightFilterInsight(results,candidate,insightPriceValue),insightCurrency);return {
  stops:new Map<FlightFilters["maxStops"],string>(([null,0,1,2] as const).map(value=>[value,get(withStopsPreview(draft,value))])),
  airlines:new Map(options.airlines.map(name=>[name,get(withAirlinePreview(draft,name))])),
  fromAirports:new Map(options.fromAirports.map(airport=>[airport,get(withAirportPreview(draft,"fromAirports",airport))])),
  toAirports:new Map(options.toAirports.map(airport=>[airport,get(withAirportPreview(draft,"toAirports",airport))])),
  time:Object.fromEntries(legs.flatMap((candidateLeg,index)=>{const candidateKey=journeyKey(candidateLeg,index);return (["departure","arrival"] as const).flatMap(field=>windows.map(window=>[`${candidateKey}:${field}:${window.value}`,get(withTimePreview(draft,candidateKey,field,window.value))]))})),
  baggage:get({...draft,baggageIncluded:true}),refundable:get({...draft,refundable:true})
 }},[results,draft,insightPriceValue,insightCurrency,options.airlines,options.fromAirports,options.toAirports,legs]);
 const close=()=>{setDragging(false);onClose()};const row=(field:"fromAirports"|"toAirports",v:string)=><Check key={field+v} label={v} detail={insights[field].get(v)} selected={draft[field].includes(v)} onPress={()=>toggle(field,v)}/>;
 return <Modal visible={visible} animationType="slide" presentationStyle="fullScreen" onRequestClose={close} accessibilityViewIsModal><View accessibilityLabel="Flight filters" style={[s.screen,{backgroundColor:theme.surface,paddingTop:inset.top,paddingBottom:Math.max(inset.bottom,8)}]}>
 <View style={s.header}><Pressable accessibilityRole="button" accessibilityLabel="Close filters" onPress={close} style={s.close}><FlowIcon name="close" color={theme.icon}/></Pressable><Text accessibilityRole="header" style={[s.title,{color:theme.textPrimary}]}>Filter by</Text><Text accessibilityRole="button" onPress={()=>setDraft(emptyFlightFilters())} style={s.action}>Reset</Text></View>
 <ScrollView style={s.scroll} scrollEnabled={!dragging} contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
 {(full||section==="stops")&&<FlightFilterSection title="Stops">{([{v:null,l:"Any"},{v:0,l:"Direct only"},{v:1,l:"Max 1 stop per flight"},{v:2,l:"Max 2 stops per flight"}] as const).map(x=><Radio key={String(x.v)} label={x.l} detail={insights.stops.get(x.v)} selected={draft.maxStops===x.v} onPress={()=>setDraft(f=>({...f,maxStops:x.v,stops:undefined}))}/>)}</FlightFilterSection>}
 {(full||section==="airlines")&&<FlightFilterSection title="Airlines" actions={<View style={s.actions}><Text onPress={()=>setDraft(x=>({...x,airlines:[]}))} style={s.action}>Select all</Text><Text onPress={()=>setDraft(x=>({...x,airlines:[]}))} style={s.action}>Reset</Text></View>}>{options.airlines.map(name=><Check key={name} label={name} detail={insights.airlines.get(name)} logo={<AirlineLogo airlineName={name} logoUrl={logos.get(name)}/>} selected={!draft.airlines.length||draft.airlines.includes(name)} onPress={()=>{const chosen=draft.airlines.length?draft.airlines:options.airlines;setDraft(x=>({...x,airlines:chosen.includes(name)?chosen.filter(v=>v!==name):[...chosen,name]}))}}/>)}</FlightFilterSection>}
 {full&&legs.length>0&&<FlightFilterSection title="Flight times">{legs.length>1&&<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.tabs}>{legs.map((l,i)=><Text accessibilityRole="tab" key={journeyKey(l,i)} onPress={()=>setTab(i)} style={[s.tab,{color:tab===i?ui.blue:theme.textSecondary,borderBottomColor:tab===i?ui.blue:"transparent"}]}>{l.direction==="outbound"?"Departing flight":l.direction==="return"?"Return flight":`Flight ${(l.legIndex??i)+1}`}</Text>)}</ScrollView>}<Text style={[s.subhead,{color:theme.textPrimary}]}>Departs from {leg.originAirport}</Text>{windows.map(w=><Check key={'d'+w.value} label={w.label} detail={insights.time[`${key}:departure:${w.value}`]} selected={selection.departure.includes(w.value)} onPress={()=>toggleTime("departure",w.value)}/>)}<Text style={[s.subhead,{color:theme.textPrimary}]}>Arrives to {leg.destinationAirport}</Text>{windows.map(w=><Check key={'a'+w.value} label={w.label} detail={insights.time[`${key}:arrival:${w.value}`]} selected={selection.arrival.includes(w.value)} onPress={()=>toggleTime("arrival",w.value)}/>)}</FlightFilterSection>}
 {full&&(options.duration||options.layover)&&<FlightFilterSection title="Duration">{options.duration&&<View><Text style={s.control}>Maximum travel time</Text>{slider("maximumDuration",options.duration,"Maximum travel time",formatFlightDuration,5)}</View>}{options.layover&&<View><Text style={s.control}>Maximum layover time</Text>{slider("maximumLayover",options.layover,"Maximum layover time",formatFlightDuration,5)}</View>}</FlightFilterSection>}
 {full&&isPriceFilteringAvailable(options,priceFilteringReady)&&<FlightFilterSection title="Price">{slider("maximumPrice",options.price!,"Maximum price",v=>formatCurrency(v,options.priceCurrency??currency),priceRangeStep(options.price!.min,options.price!.max))}</FlightFilterSection>}
 {full&&options.showAirports&&<FlightFilterSection title="Airports">{options.fromAirports.length>1&&<><Text style={s.subhead}>From</Text>{options.fromAirports.map(v=>row("fromAirports",v))}</>}{options.toAirports.length>1&&<><Text style={s.subhead}>To</Text>{options.toAirports.map(v=>row("toAirports",v))}</>}</FlightFilterSection>}
 {full&&(options.baggage||options.refundable)&&<FlightFilterSection title="More options">{options.baggage&&<Check label="Baggage included" detail={insights.baggage} selected={draft.baggageIncluded} onPress={()=>setDraft(x=>({...x,baggageIncluded:!x.baggageIncluded}))}/>} {options.refundable&&<Check label="Flexible / refundable" detail={insights.refundable} selected={draft.refundable} onPress={()=>setDraft(x=>({...x,refundable:!x.refundable}))}/>}</FlightFilterSection>}
 </ScrollView><View style={[s.footer,{borderTopColor:theme.border,backgroundColor:theme.surface}]}><Button label={`Show ${count} ${count===1?"flight":"flights"}`} flightResults onPress={()=>{onChange(draft);setDragging(false);onClose()}}/></View></View></Modal>}
function Check({label,detail,selected,logo,onPress}:{label:string;detail?:string;selected:boolean;logo?:React.ReactNode;onPress:()=>void}){const {theme}=useAppTheme();return <Pressable accessibilityLabel={detail?`${label}, ${detail}`:label} accessibilityRole="checkbox" accessibilityState={{checked:selected}} onPress={onPress} style={s.row}>{logo}<View style={s.rowCopy}><Text style={[s.rowText,{color:theme.textPrimary}]}>{label}</Text>{detail&&<Text numberOfLines={1} style={[s.rowInsight,{color:theme.textSecondary}]}>{detail}</Text>}</View><View style={[s.box,{borderColor:selected?ui.blue:theme.border,backgroundColor:selected?ui.blue:"transparent"}]}>{selected&&<Text style={s.check}>✓</Text>}</View></Pressable>};
function Radio({label,detail,selected,onPress}:{label:string;detail?:string;selected:boolean;onPress:()=>void}){const {theme}=useAppTheme();return <Pressable accessibilityLabel={detail?`${label}, ${detail}`:label} accessibilityRole="radio" accessibilityState={{selected}} onPress={onPress} style={s.row}><View style={s.rowCopy}><Text style={[s.rowText,{color:theme.textPrimary}]}>{label}</Text>{detail&&<Text numberOfLines={1} style={[s.rowInsight,{color:theme.textSecondary}]}>{detail}</Text>}</View><View style={[s.radio,{borderColor:selected?ui.blue:theme.border}]}>{selected&&<View style={s.dot}/>}</View></Pressable>};
const s=StyleSheet.create({screen:{flex:1},header:{height:58,paddingHorizontal:10,flexDirection:"row",alignItems:"center"},close:{width:44,height:44,alignItems:"center",justifyContent:"center"},title:{flex:1,fontSize:21,fontWeight:"800"},action:{color:ui.blue,fontSize:13,fontWeight:"700",padding:8},actions:{flexDirection:"row",gap:8},scroll:{flex:1},content:{paddingHorizontal:20,paddingBottom:28,gap:30},section:{gap:7},sectionHead:{minHeight:30,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},sectionTitle:{fontSize:18,fontWeight:"800"},row:{minHeight:50,flexDirection:"row",alignItems:"center",gap:11},rowCopy:{flex:1,minWidth:0},rowText:{fontSize:14,fontWeight:"500"},rowInsight:{fontSize:11.5,lineHeight:15,marginTop:2},box:{width:20,height:20,borderWidth:1.5,borderRadius:4,alignItems:"center",justifyContent:"center"},check:{color:"white",fontWeight:"900"},radio:{width:21,height:21,borderWidth:2,borderRadius:11,alignItems:"center",justifyContent:"center"},dot:{width:11,height:11,borderRadius:6,backgroundColor:ui.blue},tabs:{gap:18},tab:{paddingVertical:11,borderBottomWidth:2,fontWeight:"700"},subhead:{fontSize:14,fontWeight:"700",marginTop:9},control:{fontSize:13,fontWeight:"600",marginTop:4},value:{fontSize:16,fontWeight:"800",marginTop:4},footer:{borderTopWidth:StyleSheet.hairlineWidth,paddingHorizontal:20,paddingTop:12}});
