import assert from "node:assert/strict";import test from "node:test";import type {FlightResult} from "../../api/travelApi";import {activeFlightFilterCount,emptyFlightFilters,filterAndSortFlights,flightFilterDurationMinutes,flightMaximumLayoverMinutes,flightMaximumStops,matchingFlightCount,timeBucket} from "./flightFilters";
const result=(id:string,legs:any[]=[],extra:any={})=>({id,provider:"p",airlineName:extra.airlineName??"Air",originAirport:"LOS",destinationAirport:"ABV",departureTime:"2026-01-01T06:00:00+01:00",arrivalTime:"2026-01-01T07:00:00+01:00",duration:"1h",durationMinutes:60,stops:0,layovers:[],price:extra.price??100,currency:extra.currency??"NGN",valueScore:1,...extra,legs}) as FlightResult;
const leg=(direction:"outbound"|"return"|"leg",index:number,stops:number,departure="2026-01-01T06:00:00+01:00",arrival="2026-01-01T07:00:00+01:00",durationMinutes=60,layovers:any[]=[])=>({direction,legIndex:index,originAirport:index?"ABV":"LOS",destinationAirport:index?"LHR":"ABV",departureTime:departure,arrivalTime:arrival,duration:"1h",durationMinutes,stops,layovers,segments:[]});
test("stop maximum uses worst authoritative leg and exact limits",()=>{const flights=[0,1,2,3].map(n=>result(String(n),[leg("outbound",0,n)]));assert.equal(matchingFlightCount(flights,emptyFlightFilters()),4);for(const n of [0,1,2])assert.equal(matchingFlightCount(flights,{...emptyFlightFilters(),maxStops:n as 0|1|2}),n+1);assert.equal(flightMaximumStops(result("rt",[leg("outbound",0,0),leg("return",1,2)])),2);assert.equal(flightMaximumStops(result("mc",[leg("leg",0,1),leg("leg",1,3)])),3)});
test("time boundaries are provider-local",()=>{for(const [clock,bucket] of [["00:00","overnight"],["05:59","overnight"],["06:00","morning"],["11:59","morning"],["12:00","afternoon"],["17:59","afternoon"],["18:00","evening"],["23:59","evening"]])assert.equal(timeBucket(`2026-01-01T${clock}:00+10:00`),bucket);assert.equal(timeBucket("bad"),undefined)});
test("journey departure and arrival groups OR internally and AND across legs",()=>{const f=result("rt",[leg("outbound",0,0,"2026-01-01T06:00:00Z","2026-01-01T18:00:00Z"),leg("return",1,0,"2026-01-02T12:00:00Z","2026-01-02T23:59:00Z")]);const filters={...emptyFlightFilters(),journeyTimes:{outbound:{departure:["morning","afternoon"] as any,arrival:["evening"] as any},return:{departure:["afternoon"] as any,arrival:[]}}};assert.equal(matchingFlightCount([f],filters),1);assert.equal(matchingFlightCount([f],{...filters,journeyTimes:{...filters.journeyTimes,return:{departure:["morning"] as any,arrival:[]}}}),0)});
test("multi-city journey identities remain independent",()=>{const f=result("mc",[leg("leg",0,0,"2026-01-01T06:00:00Z"),leg("leg",1,0,"2026-01-02T18:00:00Z")]);assert.equal(matchingFlightCount([f],{...emptyFlightFilters(),journeyTimes:{"leg:0":{departure:["morning"],arrival:[]},"leg:1":{departure:["evening"],arrival:[]}}}),1)});
test("travel and layover maxima use longest individual structured value",()=>{const f=result("x",[leg("outbound",0,0,undefined,undefined,60,[{duration:"1h 20m"}]),leg("return",1,1,undefined,undefined,180,[{duration:"bad"},{duration:"4h"}])]);assert.equal(flightFilterDurationMinutes(f),180);assert.equal(flightMaximumLayoverMinutes(f),240);assert.equal(flightMaximumLayoverMinutes(result("nonstop")),0);assert.equal(matchingFlightCount([f],{...emptyFlightFilters(),maximumDuration:179}),0);assert.equal(matchingFlightCount([f],{...emptyFlightFilters(),maximumLayover:240}),1)});
test("price maximum, airlines, composition, sort and immutability",()=>{const source=[result("a",[],{price:100,airlineName:"A"}),result("b",[],{price:200,airlineName:"B"})],snapshot=[...source];assert.equal(matchingFlightCount(source,{...emptyFlightFilters(),maximumPrice:100}),1);assert.equal(matchingFlightCount(source,{...emptyFlightFilters(),airlines:["A","B"]}),2);assert.deepEqual(filterAndSortFlights(source,{...emptyFlightFilters(),airlines:["B"],maximumPrice:200},"price").map(x=>x.id),["b"]);assert.deepEqual(source,snapshot);assert.equal(activeFlightFilterCount({...emptyFlightFilters(),airlines:["A","B"]},{airlines:["A","B"]} as any),0)});
