import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
const source=readFileSync("src/features/search/HotelResultsQuickFilterSheet.tsx","utf8");
test("shared quick sheet uses model-aligned native kinds and bottom overlay",()=>{assert.match(source,/"sort" \| "price" \| "stars" \| "facilities" \| "roomTypes"/);assert.doesNotMatch(source,/"amenities"/);assert.match(source,/transparent animationType="slide" presentationStyle="overFullScreen"/);assert.match(source,/rgba\(15, 23, 42, 0\.35\)/);assert.match(source,/justifyContent:"flex-end"/);assert.match(source,/width:"100%"/);assert.match(source,/borderTopLeftRadius:24,borderTopRightRadius:24/);assert.match(source,/Math\.min\(height\*\.76,620\)/)});
test("shared backdrop uses minimal web-like blur behind the dismissible slate scrim",()=>{assert.match(source,/import \{ BlurView \} from "expo-blur"/);assert.equal(source.match(/<BlurView/g)?.length,1);assert.match(source,/<BlurView pointerEvents="none" intensity=\{1\} tint="default" experimentalBlurMethod=\{Platform\.OS==="android"\?"dimezisBlurView":undefined\} style=\{StyleSheet\.absoluteFill\}\/\>\s*<Pressable accessible=\{false\} onPress=\{onClose\} style=\{\[StyleSheet\.absoluteFill,styles\.backdropScrim\]\}\/\>\s*<KeyboardAvoidingView/);assert.doesNotMatch(source,/intensity=\{10\}/);assert.match(source,/backdropScrim:\{backgroundColor:"rgba\(15, 23, 42, 0\.35\)"\}/)});
test("header dismissal and fixed draft footer are present",()=>{for(const text of ["Sort","Choose one option","Total price","Hotel class","Facilities","Room & bed","Choose one or more options","Close filters","Reset","Apply"])assert.ok(source.includes(text));assert.match(source,/onRequestClose=\{onClose\}/);assert.match(source,/onAccessibilityEscape=\{onClose\}/);assert.match(source,/onPress=\{onClose\}/);assert.match(source,/const reset=/);assert.match(source,/const apply=.*if\(kind==="sort"\).*onSortChange\(sortMode\).*return;.*onChange\(current=>/)});
test("Flight tokens style the Hotel canvas without replacing its sheet architecture",()=>{assert.match(source,/import \{ FLIGHT_FILTER_LIGHT_CANVAS, FLIGHT_FILTER_LIGHT_OUTLINE \} from "\.\/FlightResultsSheetShell"/);assert.match(source,/filterCanvas=theme\.dark\?theme\.background:FLIGHT_FILTER_LIGHT_CANVAS/);assert.match(source,/filterOutline=theme\.dark\?theme\.border:FLIGHT_FILTER_LIGHT_OUTLINE/);assert.match(source,/backgroundColor:filterCanvas/);assert.match(source,/borderBottomColor:filterOutline/);assert.match(source,/borderTopColor:filterOutline/);assert.doesNotMatch(source,/<FlightResultsSheetShell/);assert.match(source,/header:\{minHeight:76[\s\S]*borderBottomWidth:StyleSheet\.hairlineWidth/);assert.match(source,/title:\{fontSize:18,fontFamily:appFonts\.bold,fontWeight:"700"\}/);assert.match(source,/close:\{width:44,height:44/)});
test("Sort uses flat descriptive radio rows",()=>{assert.match(source,/option\.description/);assert.match(source,/sortOptions:\{paddingHorizontal:16\}/);assert.match(source,/sortOption:\{minHeight:52,flexDirection:"row",alignItems:"center",gap:8,paddingHorizontal:10,paddingVertical:7\}/);assert.match(source,/sortCopy:\{flex:1,minWidth:0\}/);assert.match(source,/sortLabel:\{fontSize:14,lineHeight:18,fontWeight:"600",fontFamily:appFonts\.semibold\}/);assert.match(source,/sortDescription:\{marginTop:1,fontSize:10\.5,lineHeight:14,fontWeight:"500",fontFamily:appFonts\.medium\}/);assert.match(source,/<Check size=\{17\} strokeWidth=\{2\.2\}/);assert.match(source,/accessibilityRole="radiogroup"/);assert.match(source,/accessibilityRole="radio" accessibilityState=\{\{selected\}\}/);assert.doesNotMatch(source,/accessibilityRole="radio"[\s\S]{0,300}choiceBox/)});
test("multi-selects use flat rows with one left checkbox and aligned counts",()=>{assert.match(source,/choice:\{minHeight:52,paddingHorizontal:10,paddingVertical:6,flexDirection:"row",alignItems:"center",gap:10\}/);assert.match(source,/choiceBox:\{width:20,height:20,borderRadius:4,borderWidth:1\.5/);assert.match(source,/borderColor:selected\?ui\.blue:filterOutline,backgroundColor:selected\?ui\.blue:"transparent"/);assert.match(source,/<Check size=\{14\} strokeWidth=\{2\.2\} color="white"\/>/);assert.match(source,/choiceLabel:\{flex:1,fontSize:14,lineHeight:20,fontWeight:"600",fontFamily:appFonts\.semibold\}/);assert.match(source,/count:\{fontSize:13,fontFamily:appFonts\.medium\}/);assert.doesNotMatch(source,/choice:\{[^}]*borderRadius/);assert.doesNotMatch(source,/style=\{\[styles\.choice,\{backgroundColor/)});
test("price controls use distinct Flight-like surfaces without duplicate help copy",()=>{assert.match(source,/inputLabel:\{fontSize:12,lineHeight:16,fontWeight:"600",fontFamily:appFonts\.semibold,marginBottom:6\}/);assert.match(source,/input:\{height:44,borderWidth:1,borderRadius:10,paddingHorizontal:12/);assert.match(source,/borderColor:filterOutline,backgroundColor:theme\.surface/);assert.equal(source.match(/Estimated total for/g)?.length,1);assert.match(source,/inputs:\{flexDirection:"row",gap:10/);assert.match(source,/content:\{padding:16,gap:6\}/);assert.match(source,/priceCard:\{paddingVertical:4\}/);assert.doesNotMatch(source,/priceCard:\{[^}]*borderWidth|priceCard:\{[^}]*borderRadius/)});
test("price uses total-stay currency-safe draft controls",()=>{assert.match(source,/Minimum/);assert.match(source,/Maximum/);assert.match(source,/<FlightRangeSlider/);assert.match(source,/convertAmount/);assert.match(source,/formatMarketCurrency/);assert.match(source,/minimumPrice:range\.min/);assert.match(source,/maximumPrice:range\.max/)});
test("stars and facilities are draft multi-select checkboxes",()=>{assert.match(source,/starRatings:stars/);assert.match(source,/filters\.facilities/);assert.match(source,/options\.facilities/);assert.match(source,/case "facilities":return \{\.\.\.current,facilities\}/);assert.match(source,/case "facilities":setFacilities\(\[\]\)/);assert.match(source,/accessibilityRole="checkbox"/);assert.match(source,/options\.starCounts\[star\]>0/);assert.match(source,/`\$\{star\}-star hotel`/);assert.match(source,/No facilities available for this search/);assert.match(source,/<Check /)});
test("Room & bed owns an independent roomTypes draft and never uses bedTypes",()=>{assert.match(source,/useState<string\[\]>\(\[\.\.\.filters\.roomTypes\]\)/);assert.match(source,/options\.roomTypes/);assert.match(source,/case "roomTypes":setRoomTypes\(\[\]\)/);assert.match(source,/case "roomTypes":return \{\.\.\.current,roomTypes\}/);assert.match(source,/toggleRoomType/);assert.doesNotMatch(source,/bedTypes/)});
test("Facilities and Room & bed apply through explicit non-falling switch branches",()=>{const apply=source.slice(source.indexOf("const apply="),source.indexOf("const toggleStar"));assert.match(apply,/switch\(kind\)/);assert.match(apply,/case "facilities":return \{\.\.\.current,facilities\};case "roomTypes":return \{\.\.\.current,roomTypes\}/)});

test("Sort uses a separate radio draft and corrected early-return Apply flow",()=>{
  assert.match(source,/sort:HotelSortMode/);
  assert.match(source,/onSortChange:\(next:HotelSortMode\)=>void/);
  assert.match(source,/const \[sortMode,setSortMode\]=useState<HotelSortMode>\(sort\)/);
  assert.match(source,/accessibilityRole="radiogroup"/);
  assert.match(source,/accessibilityRole="radio"/);
  assert.match(source,/setSortMode\(defaultHotelSort\)/);
  assert.match(source,/hotelSortOptions\.map/);
  const apply=source.slice(source.indexOf("const apply="),source.indexOf("const toggleStar"));
  assert.match(apply,/if\(kind==="sort"\)\{onSortChange\(sortMode\);onClose\(\);return;\}/);
  const postGuardSwitch=apply.slice(apply.indexOf("onChange(current=>"));
  assert.deepEqual([...postGuardSwitch.matchAll(/case "([^"]+)"/g)].map(match=>match[1]),["price","stars","facilities","roomTypes"]);
  assert.doesNotMatch(postGuardSwitch,/case "sort"/);
});
test("Sort reuses selection feedback only for real draft changes",()=>{
  assert.match(source,/const selectSortMode=\(next:HotelSortMode\)=>\{if\(next===sortMode\)return;markUpdating\(\);setSortMode\(next\);\};/);
  assert.match(source,/onPress=\{\(\)=>selectSortMode\(option\.value\)\}/);
  assert.doesNotMatch(source,/onPress=\{\(\)=>setSortMode\(option\.value\)\}/);
  const reset=source.slice(source.indexOf("const reset="),source.indexOf("const apply="));
  assert.match(reset,/case "sort":if\(sortMode!==defaultHotelSort\)markUpdating\(\);setSortMode\(defaultHotelSort\);break;/);
});
test("shared updating footer remains timed, busy, and disabled",()=>{
  assert.match(source,/setTimeout\(\(\)=>setFilterUpdating\(false\),NATIVE_FILTER_SELECTION_FEEDBACK_MS\)/);
  assert.match(source,/accessibilityState=\{\{disabled:filterUpdating,busy:filterUpdating\}\}/);
  assert.match(source,/disabled=\{filterUpdating\}/);
  assert.match(source,/<ActivityIndicator size="small" color="white"\/>/);
  assert.match(source,/Updating filters…/);
});
