import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
const source=readFileSync("src/features/search/HotelResultsQuickFilterSheet.tsx","utf8");
const shell=readFileSync("src/features/search/FlightResultsSheetShell.tsx","utf8");
test("Hotel quick sheets use the Flight floating-sheet footprint and motion owner",()=>{assert.match(source,/"sort" \| "price" \| "stars" \| "facilities" \| "roomTypes"/);assert.doesNotMatch(source,/"amenities"/);assert.match(source,/<FlightResultsSheetShell visible title=\{title\} closeLabel="Close filters" onClose=\{onClose\} insetFlightQuickSheet flightFilterAppearance quickBackdropVariant="flight" footer=\{footer\}>/);assert.doesNotMatch(source,/<Modal|BlurView|animationType="slide"|width:"100%"|backdropScrim/);assert.match(shell,/FLIGHT_QUICK_SHEET_HORIZONTAL_INSET = 12/);assert.match(shell,/FLIGHT_FLOATING_SHEET_BOTTOM_GAP = 12/);assert.match(shell,/maxHeight: Math\.min\(height \* \.76, 620\)/);assert.match(shell,/borderBottomLeftRadius: 24, borderBottomRightRadius: 24/);assert.match(shell,/duration: 160/);assert.match(shell,/duration: 220/);assert.match(shell,/new Animated\.Value\(28\)/)});
test("Flight shell exclusively owns the Hotel quick-sheet backdrop",()=>{assert.doesNotMatch(source,/BlurView|backdropScrim|quickBackdropOpacity|quickSheetTranslateY/);assert.match(shell,/quickBackdropVariant === "flight"/);assert.match(shell,/quickBackdropScrim: \{ backgroundColor: "rgba\(15, 23, 42, 0\.35\)" \}/);assert.match(shell,/animationType=\{fullScreen \? "slide" : "none"\}/)});
test("header dismissal and fixed draft footer are delegated without changing Hotel copy",()=>{for(const text of ["Sort","Total price","Hotel class","Facilities","Room & bed","Close filters","Reset","Apply"])assert.ok(source.includes(text));for(const subtitle of ["Choose one option","Choose one or more options","Estimated total for"])assert.doesNotMatch(source,new RegExp(subtitle));assert.match(source,/onClose=\{onClose\}/);assert.match(source,/const reset=/);assert.match(source,/const apply=.*if\(kind==="sort"\).*onSortChange\(sortMode\).*return;.*onChange\(current=>/)});
test("Flight shell supplies the balanced accessible quick header",()=>{assert.match(source,/insetFlightQuickSheet flightFilterAppearance/);assert.match(shell,/<View accessible=\{false\} importantForAccessibility="no-hide-descendants" style=\{styles\.headerSlot\} \/>/);assert.match(shell,/accessibilityLabel=\{closeLabel\}/);assert.match(shell,/headerSlot: \{ width: 44, height: 44/);assert.match(shell,/quickHeaderCopy: \{ alignItems: "center" \}/);assert.match(shell,/quickTitle: \{ textAlign: "center" \}/)});
test("Flight filter tokens retain Hotel content styling inside the shared shell",()=>{assert.match(source,/FLIGHT_FILTER_LIGHT_CANVAS, FLIGHT_FILTER_LIGHT_OUTLINE, FlightResultsSheetShell/);assert.match(source,/filterCanvas=theme\.dark\?theme\.background:FLIGHT_FILTER_LIGHT_CANVAS/);assert.match(source,/filterOutline=theme\.dark\?theme\.border:FLIGHT_FILTER_LIGHT_OUTLINE/);assert.match(source,/backgroundColor:filterCanvas/);assert.match(source,/footer=\{footer\}/)});
test("Sort uses flat descriptive radio rows",()=>{assert.match(source,/option\.description/);assert.match(source,/sortOptions:\{paddingHorizontal:16\}/);assert.match(source,/sortOption:\{minHeight:52,flexDirection:"row",alignItems:"center",gap:8,paddingHorizontal:10,paddingVertical:7\}/);assert.match(source,/sortCopy:\{flex:1,minWidth:0\}/);assert.match(source,/sortLabel:\{fontSize:14,lineHeight:18,fontWeight:"600",fontFamily:appFonts\.semibold\}/);assert.match(source,/sortDescription:\{marginTop:1,fontSize:10\.5,lineHeight:14,fontWeight:"500",fontFamily:appFonts\.medium\}/);assert.match(source,/<Check size=\{17\} strokeWidth=\{2\.2\}/);assert.match(source,/accessibilityRole="radiogroup"/);assert.match(source,/accessibilityRole="radio" accessibilityState=\{\{selected\}\}/);assert.doesNotMatch(source,/accessibilityRole="radio"[\s\S]{0,300}choiceBox/)});
test("multi-selects use flat rows with one left checkbox and aligned counts",()=>{assert.match(source,/choice:\{minHeight:52,paddingHorizontal:10,paddingVertical:6,flexDirection:"row",alignItems:"center",gap:10\}/);assert.match(source,/choiceBox:\{width:20,height:20,borderRadius:4,borderWidth:1\.5/);assert.match(source,/borderColor:selected\?ui\.blue:filterOutline,backgroundColor:selected\?ui\.blue:"transparent"/);assert.match(source,/<Check size=\{14\} strokeWidth=\{2\.2\} color="white"\/>/);assert.match(source,/choiceLabel:\{flex:1,fontSize:14,lineHeight:20,fontWeight:"600",fontFamily:appFonts\.semibold\}/);assert.match(source,/count:\{fontSize:13,fontFamily:appFonts\.medium\}/);assert.doesNotMatch(source,/choice:\{[^}]*borderRadius/);assert.doesNotMatch(source,/style=\{\[styles\.choice,\{backgroundColor/)});
test("price controls use distinct Flight-like surfaces without duplicate help copy",()=>{assert.match(source,/inputLabel:\{fontSize:12,lineHeight:16,fontWeight:"600",fontFamily:appFonts\.semibold,marginBottom:6\}/);assert.match(source,/input:\{height:44,borderWidth:1,borderRadius:10,paddingHorizontal:12/);assert.match(source,/borderColor:filterOutline,backgroundColor:theme\.surface/);assert.equal(source.match(/Estimated total for/g)?.length??0,0);assert.match(source,/inputs:\{flexDirection:"row",gap:10/);assert.match(source,/content:\{padding:16,gap:6\}/);assert.match(source,/priceCard:\{paddingVertical:4\}/);assert.doesNotMatch(source,/priceCard:\{[^}]*borderWidth|priceCard:\{[^}]*borderRadius/)});
test("price uses total-stay currency-safe draft controls",()=>{assert.match(source,/Minimum/);assert.match(source,/Maximum/);assert.match(source,/<FlightRangeSlider/);assert.match(source,/convertAmount/);assert.match(source,/formatMarketCurrency/);assert.match(source,/minimumPrice:range\.min/);assert.match(source,/maximumPrice:range\.max/)});
test("stars and facilities are draft multi-select checkboxes",()=>{assert.match(source,/starRatings:stars/);assert.match(source,/filters\.facilities/);assert.match(source,/options\.facilities/);assert.match(source,/case "facilities":return \{\.\.\.current,facilities\}/);assert.match(source,/case "facilities":setFacilities\(\[\]\)/);assert.match(source,/accessibilityRole="checkbox"/);assert.match(source,/options\.starCounts\[star\]>0/);assert.match(source,/`\$\{star\}-star hotel`/);assert.match(source,/No facilities available for this search/);assert.match(source,/<Check /)});
test("Room & bed supports a single-option independent roomTypes draft and never uses bedTypes",()=>{assert.match(source,/useState<string\[\]>\(\[\.\.\.filters\.roomTypes\]\)/);assert.match(source,/options\.roomTypes\.length\?options\.roomTypes\.map\(/);assert.match(source,/case "roomTypes":setRoomTypes\(\[\]\)/);assert.match(source,/case "roomTypes":return \{\.\.\.current,roomTypes\}/);assert.match(source,/toggleRoomType/);assert.doesNotMatch(source,/roomTypes\.length\s*(?:>=\s*2|>\s*1)|bedTypes/)});
test("Facilities and Room & bed apply through explicit non-falling switch branches",()=>{const apply=source.slice(source.indexOf("const apply="),source.indexOf("const toggleStar"));assert.match(apply,/switch\(kind\)/);assert.match(apply,/case "facilities":return \{\.\.\.current,facilities\};case "roomTypes":return \{\.\.\.current,roomTypes\}/)});

test("Sort uses a separate radio draft and corrected early-return Apply flow",()=>{
  assert.match(source,/sort:HotelSortMode/);
  assert.match(source,/onSortChange:\(next:HotelSortMode\)=>void/);
  assert.match(source,/const \[sortMode,setSortMode\]=useState<HotelSortMode>\(sort\)/);
  assert.match(source,/accessibilityRole="radiogroup"/);
  assert.match(source,/accessibilityRole="radio"/);
  assert.match(source,/setSortMode\(defaultHotelSort\)/);
  assert.match(source,/hotelSortOptions\.map/);
  const apply=source.slice(source.indexOf("const apply="),source.indexOf("const toggleStar"));
  assert.match(apply,/if\(kind==="sort"\)\{onSortChange\(sortMode\);onClose\(\);return;\}/);
  const postGuardSwitch=apply.slice(apply.indexOf("onChange(current=>"));
  assert.deepEqual([...postGuardSwitch.matchAll(/case "([^"]+)"/g)].map(match=>match[1]),["price","stars","facilities","roomTypes"]);
  assert.doesNotMatch(postGuardSwitch,/case "sort"/);
});
test("Sort updates its local draft immediately without an artificial feedback wait",()=>{
  assert.match(source,/const selectSortMode=\(next:HotelSortMode\)=>\{if\(next!==sortMode\)setSortMode\(next\);\};/);
  assert.match(source,/onPress=\{\(\)=>selectSortMode\(option\.value\)\}/);
  assert.doesNotMatch(source,/markUpdating|NATIVE_FILTER_SELECTION_FEEDBACK_MS/);
});
test("Hotel quick-filter Apply remains available while editing the local draft",()=>{
  assert.match(source,/const footer=<View style=\{styles\.footerActions\}>/);
  assert.match(source,/<Pressable accessibilityRole="button" onPress=\{apply\} style=\{styles\.apply\}>/);
  assert.doesNotMatch(source,/filterUpdating|Updating filters|ActivityIndicator|disabled=\{filterUpdating\}/);
});
