import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
const source=readFileSync("src/features/search/HotelFilterSheet.tsx","utf8");
const screen=readFileSync("src/features/search/ApprovedResultsScreen.tsx","utf8");

test("Hotel filters remain a safe-area-aware full-screen native modal",()=>{assert.match(source,/<Modal[\s\S]*presentationStyle="fullScreen"[\s\S]*onRequestClose=\{onClose\}[\s\S]*accessibilityViewIsModal/);assert.match(source,/paddingTop:inset\.top/);assert.match(source,/paddingBottom:Math\.max\(inset\.bottom,12\)/);assert.match(source,/<KeyboardAvoidingView/);assert.match(source,/keyboardShouldPersistTaps="handled"/)});
test("compact header has icon, status, conditional clear, and accessible close",()=>{for(const text of ["SlidersHorizontal","Filters","All stays shown","applied","Clear all","Close filters"])assert.ok(source.includes(text),text);assert.match(source,/activeCount>0\?<Pressable/);assert.match(source,/close:\{width:44,height:44/);assert.match(source,/appFonts\.bold/)});
test("web-parity cards and dual total-price controls are present",()=>{for(const text of ["Property name","Search properties","Budget / Price","Estimated total for","Minimum","Maximum","Hotel class","Good for your trip","Area","Property type","Facilities","Accessibility","Room & bed","Bed options"])assert.ok(source.includes(text),text);assert.match(source,/<TextInput/);assert.match(source,/<FlightRangeSlider[\s\S]*available=\{\{min:price\.minimum,max:price\.maximum\}\}[\s\S]*selected=\{\{min:selectedMin,max:selectedMax\}\}/);assert.doesNotMatch(source,/singleMaximum/)});
test("sections independently expand, retain checkbox/radio accessibility, and show remaining counts",()=>{assert.match(source,/accessibilityState=\{\{expanded\}\}/);assert.match(source,/setExpanded\(x=>\(\{\.\.\.x,/);assert.match(source,/accessibilityRole=\{radio\?"radio":"checkbox"\}/);assert.match(source,/accessibilityRole="radiogroup"/);assert.match(source,/`Show more \(\$\{values\.length-limit\}\)`/);assert.match(source,/<Check /)});
test("legacy primary sections and old two-action footer are absent",()=>{assert.doesNotMatch(source,/title="MEALS"|title="CANCELLATION POLICY"|>Done</);assert.match(source,/View all \$\{totalCount\} stays/);assert.match(source,/View \$\{matchingCount\} matching/);assert.match(source,/No matching stays/);assert.match(source,/disabled=\{matchingCount===0\}/)});
test("Results passes raw and live filtered counts plus real stay dates",()=>{assert.match(screen,/totalCount=\{results\.length\} matchingCount=\{sorted\.length\}/);assert.match(screen,/stayNights=\{hotelStayNightCount\(one\(params\.checkIn\),one\(params\.checkOut\)\)\}/);assert.match(screen,/sortHotelsForResults\([\s\S]*filterHotels\(results as HotelResult\[\], hotelFilters, hotelOptions\)/)});
