import { useEffect, useRef, useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useAppTheme } from "../../theme/AppTheme";
import { convertAmount, formatCurrency, type ExchangeRates } from "../currency/displayCurrency";
import { FlowIcon } from "../flow/FlowIcon";
import { FlightRangeSlider } from "./FlightRangeSlider";
import { ui } from "./SearchUi";
import { activeHotelFilterCount, emptyHotelFilters, type HotelFilterGroup, type HotelFilterOption, type HotelFilterOptions, type HotelFilters, type HotelStarRating } from "./hotelFilters";

export type HotelFilterSectionName = "all" | "price" | "rating" | "propertyTypes" | "facilities";
type Props={visible:boolean;section:HotelFilterSectionName;filters:HotelFilters;options:HotelFilterOptions;displayCurrency:string;rates:ExchangeRates;onChange:(filters:HotelFilters)=>void;onClose:()=>void};
const groupSections: {group:HotelFilterGroup;title:string;limit:number}[]=[{group:"areas",title:"AREA",limit:5},{group:"propertyTypes",title:"PROPERTY TYPE",limit:5},{group:"roomTypes",title:"ROOM TYPE",limit:5},{group:"bedTypes",title:"BED TYPE",limit:5},{group:"meals",title:"MEALS",limit:5},{group:"cancellationPolicies",title:"CANCELLATION POLICY",limit:5},{group:"facilities",title:"FACILITIES",limit:6}];

export function HotelFilterSheet({visible,section,filters,options,displayCurrency,rates,onChange,onClose}:Props){
 const {theme}=useAppTheme(),inset=useSafeAreaInsets(),scroll=useRef<ScrollView>(null);const [expanded,setExpanded]=useState<HotelFilterGroup[]>([]);const requested=section==="rating"?"rating":section;
 useEffect(()=>{if(visible)setExpanded([])},[visible]);
 const update=(next:HotelFilters)=>onChange(next);const toggle=(group:HotelFilterGroup,value:string)=>update({...filters,[group]:filters[group].includes(value)?filters[group].filter(v=>v!==value):[...filters[group],value]});
 const price=options.price;const displayMaximum=price?convertAmount(filters.maximumPrice??price.maximum,"USD",displayCurrency,rates):null;const visibleCurrency=displayMaximum===null?"USD":displayCurrency;const formatPrice=(usd:number)=>formatCurrency(convertAmount(usd,"USD",visibleCurrency,rates)??usd,visibleCurrency);
 const anchor=(name:string)=>(event:{nativeEvent:{layout:{y:number}}})=>{if(visible&&requested===name)scroll.current?.scrollTo({y:Math.max(0,event.nativeEvent.layout.y-12),animated:false})};
 return <Modal visible={visible} animationType="slide" presentationStyle="fullScreen" onRequestClose={onClose} accessibilityViewIsModal>
  <View accessibilityLabel="Hotel filters" style={[styles.screen,{backgroundColor:theme.surface,paddingTop:inset.top}]}>
   <View style={[styles.header,{borderBottomColor:theme.border}]}><Text accessibilityRole="header" style={[styles.title,{color:theme.textPrimary}]}>Filters</Text><Pressable accessibilityRole="button" accessibilityLabel="Close filters" onPress={onClose} style={[styles.close,{backgroundColor:theme.background}]}><FlowIcon name="close" color={theme.icon}/></Pressable></View>
   <ScrollView ref={scroll} style={styles.scroll} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    {price?<Section title="BUDGET / PRICE" onLayout={anchor("price")}><View style={styles.priceLine}><Text style={[styles.rowLabel,{color:theme.textPrimary}]}>Total up to</Text><Text style={[styles.price,{color:theme.textPrimary}]}>{formatPrice(filters.maximumPrice??price.maximum)}</Text></View><FlightRangeSlider available={{min:price.minimum,max:price.maximum}} selected={{min:price.minimum,max:filters.maximumPrice??price.maximum}} step={25} singleMaximum accessibilityLabel="Maximum total stay price" formatValue={formatPrice} onChange={range=>update({...filters,maximumPrice:range.max===price.maximum?null:range.max})}/></Section>:null}
    <Section title="STAR RATING" onLayout={anchor("rating")}><View accessibilityRole="radiogroup"><OptionRow label="All" count={options.starCounts[0]} selected={filters.starRating===null} radio onPress={()=>update({...filters,starRating:null})}/>{([5,4,3,2,1] as HotelStarRating[]).map(stars=><OptionRow key={stars} label={"★".repeat(stars)} gold count={options.starCounts[stars]} selected={filters.starRating===stars} radio onPress={()=>update({...filters,starRating:stars})}/>)}</View></Section>
    {groupSections.map(({group,title,limit})=>{const values=options[group];if(!values.length)return null;const open=expanded.includes(group),shown=open?values:values.slice(0,limit);return <Section key={group} title={title} onLayout={anchor(group)}>{shown.map(option=><OptionRow key={option.value} label={option.label} count={option.count} selected={filters[group].includes(option.value)} onPress={()=>toggle(group,option.value)}/>)}{values.length>limit?<Pressable accessibilityRole="button" onPress={()=>setExpanded(x=>open?x.filter(v=>v!==group):[...x,group])} style={styles.more}><Text style={styles.moreText}>{open?"Show less":"Show more"}</Text></Pressable>:null}</Section>})}
   </ScrollView>
   <View style={[styles.footer,{borderTopColor:theme.border,backgroundColor:theme.surface,paddingBottom:Math.max(inset.bottom,12)}]}><Pressable accessibilityRole="button" accessibilityState={{disabled:activeHotelFilterCount(filters,options)===0}} disabled={activeHotelFilterCount(filters,options)===0} onPress={()=>update(emptyHotelFilters())} style={styles.footerAction}><Text style={{color:activeHotelFilterCount(filters,options)?theme.textPrimary:theme.textMuted,fontWeight:"700"}}>Clear all</Text></Pressable><Pressable accessibilityRole="button" onPress={onClose} style={styles.done}><Text style={styles.doneText}>Done</Text></Pressable></View>
  </View>
 </Modal>;
}
function Section({title,onLayout,children}:{title:string;onLayout?:(event:any)=>void;children:React.ReactNode}){const {theme}=useAppTheme();return <View onLayout={onLayout} style={styles.section}><Text style={[styles.sectionTitle,{color:theme.textSecondary}]}>{title}</Text>{children}</View>}
function OptionRow({label,count,selected,onPress,radio=false,gold=false}:{label:string;count:number;selected:boolean;onPress:()=>void;radio?:boolean;gold?:boolean}){const {theme}=useAppTheme();return <Pressable accessibilityRole={radio?"radio":"checkbox"} accessibilityLabel={`${label}, ${count}`} accessibilityState={radio?{selected}:{checked:selected}} onPress={onPress} style={styles.row}><View style={[styles.box,{borderColor:selected?ui.blue:theme.border,backgroundColor:selected?ui.blue:"transparent"}]}>{selected?<Text style={styles.check}>✓</Text>:null}</View><Text style={[styles.rowLabel,{color:gold?"#E3A008":theme.textPrimary}]}>{label}</Text><Text style={[styles.count,{color:theme.textSecondary}]}>{count}</Text></Pressable>}
const styles=StyleSheet.create({screen:{flex:1},header:{height:60,paddingHorizontal:16,flexDirection:"row",alignItems:"center",borderBottomWidth:StyleSheet.hairlineWidth},title:{flex:1,fontSize:22,fontWeight:"800"},close:{width:44,height:44,borderRadius:22,alignItems:"center",justifyContent:"center"},scroll:{flex:1},content:{paddingHorizontal:20,paddingVertical:24,gap:30},section:{gap:5},sectionTitle:{fontSize:12,fontWeight:"800",letterSpacing:1,marginBottom:8},priceLine:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},price:{fontSize:16,fontWeight:"800"},row:{minHeight:44,flexDirection:"row",alignItems:"center",gap:12},box:{width:21,height:21,borderWidth:1.5,borderRadius:4,alignItems:"center",justifyContent:"center"},check:{color:"white",fontWeight:"900"},rowLabel:{fontSize:15,fontWeight:"500",flex:1},count:{fontSize:14,minWidth:28,textAlign:"right"},more:{minHeight:44,justifyContent:"center"},moreText:{color:ui.blue,fontWeight:"700"},footer:{flexDirection:"row",alignItems:"center",gap:16,borderTopWidth:StyleSheet.hairlineWidth,paddingHorizontal:20,paddingTop:12},footerAction:{minHeight:48,justifyContent:"center",paddingHorizontal:8},done:{flex:1,minHeight:48,borderRadius:12,backgroundColor:ui.blue,alignItems:"center",justifyContent:"center"},doneText:{color:"white",fontSize:16,fontWeight:"800"}});
