import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
const source=readFileSync("src/features/search/HotelResultsQuickFilterSheet.tsx","utf8");
test("shared quick sheet uses three web kinds and bottom overlay",()=>{assert.match(source,/"price" \| "stars" \| "amenities"/);assert.doesNotMatch(source,/"sort"/);assert.match(source,/transparent animationType="slide" presentationStyle="overFullScreen"/);assert.match(source,/rgba\(15, 23, 42, 0\.35\)/);assert.match(source,/justifyContent:"flex-end"/);assert.match(source,/width:"100%"/);assert.match(source,/borderTopLeftRadius:24,borderTopRightRadius:24/);assert.match(source,/Math\.min\(height\*\.76,620\)/)});
test("shared backdrop subtly blurs behind the dismissible slate scrim",()=>{assert.match(source,/import \{ BlurView \} from "expo-blur"/);assert.equal(source.match(/<BlurView/g)?.length,1);assert.match(source,/<BlurView pointerEvents="none" intensity=\{10\} tint="default" experimentalBlurMethod=\{Platform\.OS==="android"\?"dimezisBlurView":undefined\} style=\{StyleSheet\.absoluteFill\}\/\>\s*<Pressable accessible=\{false\} onPress=\{onClose\} style=\{\[StyleSheet\.absoluteFill,styles\.backdropScrim\]\}\/\>\s*<KeyboardAvoidingView/);assert.match(source,/backdropScrim:\{backgroundColor:"rgba\(15, 23, 42, 0\.35\)"\}/)});
test("header dismissal and fixed draft footer are present",()=>{for(const text of ["Total price","Hotel class","Amenities","Choose one or more options","Close filters","Reset","Apply"])assert.ok(source.includes(text));assert.match(source,/onRequestClose=\{onClose\}/);assert.match(source,/onAccessibilityEscape=\{onClose\}/);assert.match(source,/onPress=\{onClose\}/);assert.match(source,/const reset=/);assert.match(source,/const apply=.*onChange\(current=>/)});
test("price uses total-stay currency-safe draft controls",()=>{assert.match(source,/Minimum/);assert.match(source,/Maximum/);assert.match(source,/<FlightRangeSlider/);assert.match(source,/convertAmount/);assert.match(source,/formatCurrency/);assert.match(source,/minimumPrice:range\.min/);assert.match(source,/maximumPrice:range\.max/)});
test("stars and amenities are draft multi-select checkboxes",()=>{assert.match(source,/starRatings:stars/);assert.match(source,/facilities\}/);assert.match(source,/accessibilityRole="checkbox"/);assert.match(source,/options\.starCounts\[star\]>0/);assert.match(source,/`\$\{star\}-star hotel`/);assert.match(source,/No amenities available for this search/);assert.match(source,/<Check /)});
