import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
const screen=readFileSync("src/features/search/ApprovedResultsScreen.tsx","utf8");
test("Hotel rail matches Filter Price Stars Amenities",()=>{const rail=screen.slice(screen.indexOf("const filterRail"),screen.indexOf("const resultContent"));const labels=["Filter","Price","Stars","Amenities"].map(x=>rail.indexOf(`label=\"${x}\"`));assert.ok(labels.every(x=>x>=0)&&labels.every((x,i)=>i===0||labels[i-1]<x));assert.match(rail,/hotelOptions\.price \?/);assert.match(rail,/openHotelQuickFilter\("price"\)/);assert.match(rail,/starRatings\.length \|\| undefined/);assert.match(rail,/facilities\.length \|\| undefined/);assert.doesNotMatch(rail,/hotelSortLabel|Cheapest/)});
test("anchored plumbing is removed and default sorting remains",()=>{for(const stale of ["measureInWindow","hotelShortcutAnchor","sortShortcutRef","starsShortcutRef","amenitiesShortcutRef","HotelResultsShortcutAnchor"])assert.doesNotMatch(screen,new RegExp(stale));assert.match(screen,/sortHotelsForResults\([\s\S]*defaultHotelSort/);assert.match(screen,/<FlightSortSheet/)});
test("Hotel shortcuts match the compact Flight visual contract",()=>{
  const component=screen.slice(screen.indexOf("const HotelResultsShortcut"),screen.indexOf("function FlightCard"));
  const styles=screen.slice(screen.indexOf("hotelShortcut:"),screen.indexOf("hotelShortcutCount:"));
  const shell=styles.slice(0,styles.indexOf("hotelShortcutPressed:"));
  const pressed=styles.slice(styles.indexOf("hotelShortcutPressed:"),styles.indexOf("hotelShortcutLabel:"));
  const label=styles.slice(styles.indexOf("hotelShortcutLabel:"));
  assert.match(shell,/height: 38/);assert.match(shell,/paddingHorizontal: 10/);assert.match(shell,/borderRadius: 8/);assert.match(shell,/borderWidth: 1/);assert.match(shell,/gap: 6/);
  assert.doesNotMatch(shell,/borderRadius: 19|paddingHorizontal: 12/);
  assert.match(label,/fontSize: 12/);assert.match(label,/lineHeight: 16/);assert.match(label,/fontWeight: "600"/);assert.match(label,/fontFamily: appFonts\.semibold/);
  assert.doesNotMatch(label,/fontSize: 13|fontWeight: "700"|fontFamily: appFonts\.bold/);
  assert.match(component,/backgroundColor: theme\.dark \? theme\.surface : ui\.pale/);assert.match(component,/borderColor: theme\.border/);
  assert.match(pressed,/opacity: 0\.82/);assert.match(pressed,/scale: 0\.985/);assert.doesNotMatch(pressed,/opacity: 0\.72/);
  assert.match(component,/<SlidersHorizontal size=\{17\} strokeWidth=\{2\}/);assert.match(component,/<ChevronDown size=\{15\} strokeWidth=\{1\.9\}/);assert.doesNotMatch(component,/<ChevronRight/);
  assert.match(component,/expanded \? \{ transform: \[\{ rotate: "180deg" \}\] \}/);
  assert.match(component,/const active = Boolean\(count\)/);assert.doesNotMatch(component,/const active = .*expanded/);
  assert.match(component,/#EEF4FF/);assert.match(component,/#142B55/);assert.match(component,/borderColor: ui\.blue/);assert.match(component,/#8FB5FF/);
  assert.match(component,/hotelShortcutCount/);assert.match(component,/hotelShortcutCountText/);assert.match(component,/Filter, \$\{count\} active filters/);
});
