import { useEffect, useRef, useState } from "react";
import { ActivityIndicator, KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { Check, X } from "lucide-react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useAppTheme } from "../../theme/AppTheme";
import { appFonts } from "../../theme/typography";
import { convertAmount, formatMarketCurrency, type ExchangeRates } from "../currency/displayCurrency";
import { FlightRangeSlider } from "./FlightRangeSlider";
import { FLIGHT_FILTER_LIGHT_CANVAS, FLIGHT_FILTER_LIGHT_OUTLINE } from "./FlightResultsSheetShell";
import { ui } from "./SearchUi";
import { activeHotelFilterCount, emptyHotelFilters, type HotelFilterGroup, type HotelFilterOptions, type HotelFilters, type HotelStarRating } from "./hotelFilters";
import { NATIVE_FILTER_SELECTION_FEEDBACK_MS } from "./filterResultsTransition";

export type HotelFilterSectionName = "all" | "price" | "rating" | "facilities";
type Props={visible:boolean;section:HotelFilterSectionName;filters:HotelFilters;options:HotelFilterOptions;displayCurrency:string;rates:ExchangeRates;stayNights:number;totalCount:number;matchingCount:number;onChange:(filters:HotelFilters)=>void;onClose:()=>void};
type PostPriceSection={kind:"group";group:HotelFilterGroup;title:string;limit:number;minimum?:number}|{kind:"hotelClass";title:"Hotel class"};
const postPriceSections:PostPriceSection[]=[
 {kind:"group",group:"travellerFeatures",title:"Good for your trip",limit:4},
 {kind:"hotelClass",title:"Hotel class"},
 {kind:"group",group:"areas",title:"Area",limit:5},
 {kind:"group",group:"propertyTypes",title:"Property type",limit:5},
 {kind:"group",group:"facilities",title:"Facilities",limit:6},
 {kind:"group",group:"accessibility",title:"Accessibility",limit:5},
 {kind:"group",group:"roomTypes",title:"Room & bed",limit:5},
 {kind:"group",group:"bedTypes",title:"Bed options",limit:5,minimum:2},
];

export function HotelFilterSheet({visible,section,filters,options,displayCurrency,rates,stayNights,totalCount,matchingCount,onChange,onClose}:Props){
 const {theme}=useAppTheme(),inset=useSafeAreaInsets(),scroll=useRef<ScrollView>(null),price=options.price;
 const filterCanvas=theme.dark?theme.background:FLIGHT_FILTER_LIGHT_CANVAS,filterOutline=theme.dark?theme.border:FLIGHT_FILTER_LIGHT_OUTLINE;
 const [showAll,setShowAll]=useState<Record<string,boolean>>({});
 const selectedMin=filters.minimumPrice??price?.minimum??0,selectedMax=filters.maximumPrice??price?.maximum??0;
 const visibleCurrency=displayCurrency==="USD"||convertAmount(1,"USD",displayCurrency,rates)!==null?displayCurrency:"USD";
 const toDisplay=(usd:number)=>convertAmount(usd,"USD",visibleCurrency,rates)??usd;
 const fromDisplay=(amount:number)=>convertAmount(amount,visibleCurrency,"USD",rates);
 const [minimumDraft,setMinimumDraft]=useState(""),[maximumDraft,setMaximumDraft]=useState("");
 const [filterUpdating,setFilterUpdating]=useState(false),filterUpdatingTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 const markUpdating=()=>{if(filterUpdatingTimer.current)clearTimeout(filterUpdatingTimer.current);setFilterUpdating(true);filterUpdatingTimer.current=setTimeout(()=>setFilterUpdating(false),NATIVE_FILTER_SELECTION_FEEDBACK_MS);};
 const activeCount=activeHotelFilterCount(filters,options);
 useEffect(()=>{if(visible)setShowAll({});},[visible]);
 useEffect(()=>{if(price){setMinimumDraft(String(Math.round(toDisplay(selectedMin))));setMaximumDraft(String(Math.round(toDisplay(selectedMax))));}},[displayCurrency,filters.minimumPrice,filters.maximumPrice,price?.minimum,price?.maximum,rates]);
 useEffect(()=>{if(!visible){if(filterUpdatingTimer.current)clearTimeout(filterUpdatingTimer.current);filterUpdatingTimer.current=undefined;setFilterUpdating(false);}return()=>{if(filterUpdatingTimer.current)clearTimeout(filterUpdatingTimer.current);};},[visible]);
 const update=(next:HotelFilters)=>onChange(next),toggle=(group:HotelFilterGroup,value:string)=>{markUpdating();update({...filters,[group]:filters[group].includes(value)?filters[group].filter(v=>v!==value):[...filters[group],value]});};
 const commitPrice=(edge:"min"|"max",draft:string)=>{if(!price)return;const parsed=Number(draft);if(!Number.isFinite(parsed))return;const usd=fromDisplay(parsed);if(usd===null)return;markUpdating();if(edge==="min"){const value=Math.min(Math.max(price.minimum,usd),selectedMax);update({...filters,minimumPrice:value<=price.minimum?null:value});}else{const value=Math.max(Math.min(price.maximum,usd),selectedMin);update({...filters,maximumPrice:value>=price.maximum?null:value});}};
 const formatPrice=(usd:number)=>formatMarketCurrency(toDisplay(usd),visibleCurrency);
 const anchor=(name:string)=>(event:{nativeEvent:{layout:{y:number}}})=>{if(visible&&section===name)scroll.current?.scrollTo({y:Math.max(0,event.nativeEvent.layout.y-12),animated:false});};
 const footerLabel=matchingCount===0?"No matching stays":activeCount===0?`View all ${totalCount} stays`:`View ${matchingCount} matching ${matchingCount===1?"stay":"stays"}`;
 const viewAction=<Pressable accessibilityRole="button" accessibilityLiveRegion="polite" accessibilityState={{disabled:matchingCount===0||filterUpdating,busy:filterUpdating}} pointerEvents={filterUpdating?"none":"auto"} disabled={matchingCount===0} onPress={onClose} style={[styles.viewButton,activeCount>0&&styles.viewButtonFlexible,matchingCount===0&&styles.viewButtonDisabled]}>{filterUpdating?<View style={styles.updating}><ActivityIndicator size="small" color="white"/><Text style={styles.viewText}>Updating filters…</Text></View>:<Text style={styles.viewText}>{footerLabel}</Text>}</Pressable>;
 return <Modal visible={visible} animationType="slide" presentationStyle="fullScreen" onRequestClose={onClose} accessibilityViewIsModal>
  <KeyboardAvoidingView behavior={Platform.OS==="ios"?"padding":"height"} style={[styles.screen,{backgroundColor:filterCanvas,paddingTop:inset.top}]}>
   <View accessibilityLabel="Hotel filters" style={[styles.header,{backgroundColor:filterCanvas}]}>
    <View style={styles.headerCopy}><Text accessibilityRole="header" style={[styles.title,{color:theme.textPrimary}]}>Filters</Text>{activeCount>0?<Text style={[styles.subtitle,{color:theme.textSecondary}]}>{`${activeCount} applied`}</Text>:null}</View>
    <Pressable accessibilityRole="button" accessibilityLabel="Close filters" onPress={onClose} style={styles.close}><X size={22} color={theme.icon}/></Pressable>
   </View>
   <ScrollView ref={scroll} style={[styles.scroll,{backgroundColor:filterCanvas}]} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" showsVerticalScrollIndicator={false}>
    <View style={styles.section}><Text style={[styles.propertyTitle,{color:theme.textPrimary}]}>Property name</Text><View style={[styles.searchWrap,{borderColor:filterOutline,backgroundColor:theme.surface}]}><TextInput accessibilityLabel="Search properties by name" placeholder="Search properties" placeholderTextColor={theme.textMuted} value={filters.propertyNameQuery} onChangeText={value=>{markUpdating();update({...filters,propertyNameQuery:value});}} returnKeyType="search" style={[styles.searchInput,{color:theme.textPrimary,fontFamily:appFonts.regular}]}/>{filters.propertyNameQuery?<Pressable accessibilityRole="button" accessibilityLabel="Clear property search" onPress={()=>{markUpdating();update({...filters,propertyNameQuery:""});}} style={styles.inputClear}><X size={16} color={theme.icon}/></Pressable>:null}</View></View>
    {price?<Section title="Budget / Price" onLayout={anchor("price")}>
      <Text style={[styles.help,{color:theme.textSecondary}]}>Estimated total for {stayNights} {stayNights===1?"night":"nights"}.</Text>
      <View style={styles.priceInputs}><PriceInput label="Minimum" accessibilityLabel="Minimum estimated stay total" value={minimumDraft} onChange={value=>{markUpdating();setMinimumDraft(value);}} onEnd={()=>commitPrice("min",minimumDraft)}/><PriceInput label="Maximum" accessibilityLabel="Maximum estimated stay total" value={maximumDraft} onChange={value=>{markUpdating();setMaximumDraft(value);}} onEnd={()=>commitPrice("max",maximumDraft)}/></View>
      <FlightRangeSlider available={{min:price.minimum,max:price.maximum}} selected={{min:selectedMin,max:selectedMax}} step={25} accessibilityLabel="Estimated stay total range" formatValue={formatPrice} onChange={range=>{markUpdating();update({...filters,minimumPrice:range.min<=price.minimum?null:range.min,maximumPrice:range.max>=price.maximum?null:range.max});}}/>
      <View style={styles.endpoints}><Text style={[styles.endpoint,{color:theme.textSecondary}]}>{formatPrice(selectedMin)}</Text><Text style={[styles.endpoint,{color:theme.textSecondary}]}>{formatPrice(selectedMax)}</Text></View>
    </Section>:null}
    {postPriceSections.map(section=>{if(section.kind==="hotelClass")return <Section key={section.kind} title={section.title} onLayout={anchor("rating")}>{([5,4,3,2,1] as HotelStarRating[]).filter(star=>options.starCounts[star]>0).map(star=><OptionRow key={star} label={"★".repeat(star)} gold count={options.starCounts[star]} selected={filters.starRatings.includes(star)} onPress={()=>{markUpdating();update({...filters,starRatings:filters.starRatings.includes(star)?filters.starRatings.filter(value=>value!==star):[...filters.starRatings,star].sort((a,b)=>b-a) as HotelStarRating[]});}}/>)}</Section>;const {group,title,limit,minimum=1}=section,values=options[group];if(values.length<minimum)return null;const all=showAll[group],shown=all?values:values.slice(0,limit);return <Section key={group} title={title} onLayout={anchor(group)}>{shown.map(option=><OptionRow key={option.value} label={option.label} count={option.count} selected={filters[group].includes(option.value)} onPress={()=>toggle(group,option.value)}/>)}{values.length>limit?<Pressable accessibilityRole="button" onPress={()=>setShowAll(x=>({...x,[group]:!all}))} style={styles.more}><Text style={styles.moreText}>{all?"Show less":`Show more (${values.length-limit})`}</Text></Pressable>:null}</Section>})}
   </ScrollView>
   <View style={[styles.footer,{backgroundColor:filterCanvas,borderTopColor:theme.border,paddingBottom:Math.max(inset.bottom,12)}]}>{activeCount>0?<View style={styles.footerActions}><Pressable accessibilityRole="button" accessibilityLabel="Reset hotel filters" onPress={()=>{markUpdating();update(emptyHotelFilters());}} style={[styles.resetButton,{borderColor:filterOutline}]}><Text style={[styles.resetText,{color:theme.textPrimary}]}>Reset</Text></Pressable>{viewAction}</View>:viewAction}</View>
  </KeyboardAvoidingView>
 </Modal>;
}
function Section({title,onLayout,children}:{title:string;onLayout?:(event:any)=>void;children:React.ReactNode}){const {theme}=useAppTheme();return <View onLayout={onLayout} style={styles.section}><View style={styles.sectionHeader}><Text style={[styles.sectionTitle,{color:theme.textPrimary}]}>{title}</Text></View><View style={styles.sectionBody}>{children}</View></View>}
function PriceInput({label,accessibilityLabel,value,onChange,onEnd}:{label:string;accessibilityLabel:string;value:string;onChange:(value:string)=>void;onEnd:()=>void}){const {theme}=useAppTheme(),filterOutline=theme.dark?theme.border:FLIGHT_FILTER_LIGHT_OUTLINE;return <View style={styles.priceInputColumn}><Text style={[styles.inputLabel,{color:theme.textSecondary}]}>{label}</Text><TextInput accessibilityLabel={accessibilityLabel} keyboardType="decimal-pad" value={value} onChangeText={onChange} onBlur={onEnd} onSubmitEditing={onEnd} style={[styles.numberInput,{borderColor:filterOutline,backgroundColor:theme.surface,color:theme.textPrimary}]}/></View>}
function OptionRow({label,count,selected,onPress,radio=false,gold=false}:{label:string;count:number;selected:boolean;onPress:()=>void;radio?:boolean;gold?:boolean}){const {theme}=useAppTheme(),filterOutline=theme.dark?theme.border:FLIGHT_FILTER_LIGHT_OUTLINE;return <Pressable accessibilityRole={radio?"radio":"checkbox"} accessibilityLabel={`${label}, ${count}`} accessibilityState={radio?{selected}:{checked:selected}} onPress={onPress} style={({pressed})=>[styles.row,pressed&&styles.pressed]}><View style={[styles.box,{borderColor:selected?ui.blue:filterOutline,backgroundColor:selected?ui.blue:"transparent"}]}>{selected?<Check size={14} strokeWidth={3} color="white"/>:null}</View><Text style={[styles.rowLabel,{color:gold?"#E3A008":theme.textPrimary}]}>{label}</Text><Text style={[styles.count,{color:theme.textSecondary}]}>{count}</Text></Pressable>}
const styles=StyleSheet.create({screen:{flex:1},header:{minHeight:76,paddingLeft:20,paddingRight:10,flexDirection:"row",alignItems:"center",gap:11,borderBottomWidth:0},headerCopy:{flex:1,minWidth:0},title:{fontSize:18,lineHeight:23,fontWeight:"700",fontFamily:appFonts.bold},subtitle:{fontSize:12,lineHeight:16,fontWeight:"500",fontFamily:appFonts.medium},close:{width:44,height:44,alignItems:"center",justifyContent:"center"},scroll:{flex:1},content:{paddingHorizontal:24,paddingTop:16,paddingBottom:32,gap:24},section:{gap:5},propertyTitle:{fontSize:15,fontWeight:"800"},searchWrap:{height:44,marginTop:8,borderWidth:1,borderRadius:10,flexDirection:"row",alignItems:"center"},searchInput:{flex:1,height:44,paddingHorizontal:12,fontSize:14},inputClear:{width:42,height:42,alignItems:"center",justifyContent:"center"},sectionHeader:{minHeight:28,flexDirection:"row",alignItems:"center"},sectionTitle:{fontSize:15,fontWeight:"800",flex:1},sectionBody:{gap:5},help:{fontSize:12,lineHeight:18,fontFamily:appFonts.medium,marginBottom:10},priceInputs:{flexDirection:"row",gap:10,marginBottom:12},priceInputColumn:{flex:1,minWidth:0},inputLabel:{fontSize:12,lineHeight:16,fontWeight:"600",fontFamily:appFonts.semibold,marginBottom:6},numberInput:{height:44,borderWidth:1,borderRadius:10,paddingHorizontal:12,fontSize:14,fontFamily:appFonts.medium},endpoints:{flexDirection:"row",justifyContent:"space-between",marginTop:4},endpoint:{fontSize:12,lineHeight:16,fontFamily:appFonts.medium},row:{minHeight:46,flexDirection:"row",alignItems:"center",gap:10},pressed:{opacity:.7},box:{width:20,height:20,flexShrink:0,borderWidth:1.5,borderRadius:4,alignItems:"center",justifyContent:"center"},rowLabel:{fontSize:13,fontWeight:"500",flex:1,minWidth:0},count:{flexShrink:0,maxWidth:"42%",marginLeft:2,textAlign:"right",fontSize:12,lineHeight:16,fontVariant:["tabular-nums"]},more:{minHeight:40,justifyContent:"center"},moreText:{color:ui.blue,fontSize:13,fontWeight:"700",fontFamily:appFonts.bold},footer:{borderTopWidth:StyleSheet.hairlineWidth,paddingHorizontal:16,paddingTop:12},footerActions:{flexDirection:"row",alignItems:"center",gap:14},resetButton:{minWidth:116,height:49,borderWidth:1,borderRadius:12,alignItems:"center",justifyContent:"center"},resetText:{fontSize:15,fontWeight:"700",fontFamily:appFonts.bold},viewButton:{width:"100%",minHeight:50,borderRadius:10,backgroundColor:ui.blue,alignItems:"center",justifyContent:"center"},viewButtonFlexible:{width:"auto",flex:1},viewButtonDisabled:{opacity:.45},updating:{flexDirection:"row",alignItems:"center",gap:8},viewText:{color:"white",fontSize:16,lineHeight:22,fontWeight:"700",fontFamily:appFonts.bold}});
