import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
const source=readFileSync("src/features/search/HotelFilterSheet.tsx","utf8");
const screen=readFileSync("src/features/search/ApprovedResultsScreen.tsx","utf8");
const web=readFileSync("../../src/components/results/HotelResultsClient.tsx","utf8");

test("Hotel filters remain a safe-area-aware full-screen native modal",()=>{assert.match(source,/<Modal[\s\S]*presentationStyle="fullScreen"[\s\S]*onRequestClose=\{onClose\}[\s\S]*accessibilityViewIsModal/);assert.match(source,/paddingTop:inset\.top/);assert.match(source,/paddingBottom:Math\.max\(inset\.bottom,12\)/);assert.match(source,/<KeyboardAvoidingView/);assert.match(source,/keyboardShouldPersistTaps="handled"/)});
test("compact header omits reset actions and empty status while retaining applied count and accessible close",()=>{const header=source.slice(source.indexOf('<View accessibilityLabel="Hotel filters"'),source.indexOf("</View>\n   <ScrollView"));for(const text of ["Filters","applied","Close filters"])assert.ok(header.includes(text),text);for(const text of ["Clear all","Reset"])assert.ok(!header.includes(text),text);assert.doesNotMatch(source,/All stays shown/);assert.match(header,/activeCount>0\?<Text[^>]*styles\.subtitle[^>]*>\{`\$\{activeCount\} applied`\}<\/Text>:null/);assert.doesNotMatch(source,/SlidersHorizontal/);assert.match(source,/close:\{width:44,height:44/);assert.match(source,/appFonts\.bold/)});
test("full Hotel filters share the Flight canvas and dark-mode fallbacks",()=>{assert.match(source,/import \{ FLIGHT_FILTER_LIGHT_CANVAS, FLIGHT_FILTER_LIGHT_OUTLINE \} from "\.\/FlightResultsSheetShell"/);assert.match(source,/filterCanvas=theme\.dark\?theme\.background:FLIGHT_FILTER_LIGHT_CANVAS/);assert.match(source,/filterOutline=theme\.dark\?theme\.border:FLIGHT_FILTER_LIGHT_OUTLINE/);assert.match(source,/backgroundColor:filterCanvas/);assert.match(source,/borderColor:filterOutline/)});
test("Hotel full filters match the Flight header, content, row, checkbox, and type geometry",()=>{for(const pattern of [/header:\{minHeight:76,paddingLeft:20,paddingRight:10/,/title:\{fontSize:18,lineHeight:23,fontWeight:"700",fontFamily:appFonts\.bold\}/,/close:\{width:44,height:44/,/<X size=\{22\}/,/content:\{paddingHorizontal:24,paddingTop:16,paddingBottom:32,gap:24\}/,/section:\{gap:5\}/,/sectionTitle:\{fontSize:15,fontWeight:"800"/,/row:\{minHeight:46,flexDirection:"row",alignItems:"center",gap:10\}/,/box:\{width:20,height:20,flexShrink:0,borderWidth:1\.5,borderRadius:4/,/rowLabel:\{fontSize:13,fontWeight:"500"/,/count:\{flexShrink:0,maxWidth:"42%",marginLeft:2,textAlign:"right",fontSize:12,lineHeight:16,fontVariant:\["tabular-nums"\]\}/])assert.match(source,pattern);assert.doesNotMatch(source,/styles\.card|card:\{|shadowOpacity|shadowRadius|elevation/);});
test("property search and price fields share polished control geometry",()=>{const search=source.match(/searchWrap:\{([^}]*)\}/)?.[1]??"",priceInput=source.match(/numberInput:\{([^}]*)\}/)?.[1]??"";for(const style of [search,priceInput]){assert.match(style,/height:44/);assert.match(style,/borderWidth:1/);assert.match(style,/borderRadius:10/)}assert.match(source,/searchWrap,\{borderColor:filterOutline,backgroundColor:theme\.surface\}/);assert.match(source,/numberInput,\{borderColor:filterOutline,backgroundColor:theme\.surface/);assert.match(source,/searchInput:\{[^}]*paddingHorizontal:12/);assert.match(priceInput,/paddingHorizontal:12/)});
test("native filter sections and dual total-price controls are present",()=>{for(const text of ["Property name","Search properties","Budget / Price","Estimated total for","Minimum","Maximum","Hotel class","Good for your trip","Area","Facilities","Accessibility","Room & bed","Bed options"])assert.ok(source.includes(text),text);assert.match(source,/<TextInput/);assert.match(source,/<FlightRangeSlider[\s\S]*available=\{\{min:price\.minimum,max:price\.maximum\}\}[\s\S]*selected=\{\{min:selectedMin,max:selectedMax\}\}/);assert.doesNotMatch(source,/singleMaximum/)});
test("post-price sections include Property type in mobile web order", () => { const descriptor=source.slice(source.indexOf("const postPriceSections"),source.indexOf("];",source.indexOf("const postPriceSections"))); assert.ok(descriptor.indexOf('title:"Area"') < descriptor.indexOf('title:"Property type"')); assert.ok(descriptor.indexOf('title:"Property type"') < descriptor.indexOf('title:"Facilities"')); assert.doesNotMatch(descriptor,/Cancellation/); });
test("Property type is a native presentation section", () => { assert.match(source,/group:"propertyTypes",title:"Property type"/); });
test("sections stay expanded and retain checkbox accessibility and show-more controls",()=>{assert.doesNotMatch(source,/ChevronDown|accessibilityState=\{\{expanded\}\}|setExpanded|onToggle/);assert.match(source,/function Section\([^)]*\)[^{]*\{[^;]*;return <View[^>]*><View style=\{styles\.sectionHeader\}>[\s\S]*<View style=\{styles\.sectionBody\}>\{children\}<\/View><\/View>\}/);assert.match(source,/accessibilityRole=\{radio\?"radio":"checkbox"\}/);assert.doesNotMatch(source,/accessibilityRole="radiogroup"/);assert.doesNotMatch(source,/label="All"/);assert.match(source,/selected=\{filters\.starRatings\.includes\(star\)\}/);assert.match(source,/<Check /);for(const text of ["showAll","setShowAll","Show more","Show less"])assert.ok(source.includes(text),text);for(const anchor of ['anchor("price")','anchor("rating")','anchor(group)'])assert.ok(source.includes(anchor),anchor)});
test("Hotel Reset appears immediately when filters become active and disappears after reset clears the active count.",()=>{assert.match(source,/const update=\(next:HotelFilters\)=>onChange\(next\)/);assert.match(source,/const viewAction=<Pressable[\s\S]*disabled=\{matchingCount===0\}[\s\S]*onPress=\{onClose\}/);assert.match(source,/activeCount>0\?<View style=\{styles\.footerActions\}>[\s\S]*accessibilityLabel="Reset hotel filters"[\s\S]*\{viewAction\}<\/View>:viewAction/);assert.match(source,/accessibilityLabel="Reset hotel filters" onPress=\{\(\)=>\{markUpdating\(\);update\(emptyHotelFilters\(\)\);\}\}/);const reset=source.slice(source.indexOf('accessibilityLabel="Reset hotel filters"'),source.indexOf("{viewAction}</View>:viewAction"));assert.doesNotMatch(reset,/onClose|disabled=\{matchingCount===0\}/);assert.match(source,/viewButton:\{width:"100%",minHeight:50,borderRadius:10/);assert.match(source,/viewButtonFlexible:\{width:"auto",flex:1\}/);assert.match(source,/style=\{\[styles\.viewButton,activeCount>0&&styles\.viewButtonFlexible/);assert.doesNotMatch(source,/draftFilters|setDraftFilters|Apply filters/);});
test("legacy sections are absent and footer labels preserve all count states",()=>{assert.doesNotMatch(source,/title="MEALS"|title="CANCELLATION POLICY"|>Done</);assert.match(source,/View all \$\{totalCount\} stays/);assert.match(source,/View \$\{matchingCount\} matching/);assert.match(source,/No matching stays/);assert.match(source,/disabled=\{matchingCount===0\}/)});
test("Results passes raw and live filtered counts plus real stay dates",()=>{assert.match(screen,/totalCount=\{results\.length\} matchingCount=\{sorted\.length\}/);assert.match(screen,/stayNights=\{hotelStayNightCount\(one\(params\.checkIn\),one\(params\.checkOut\)\)\}/);assert.match(screen,/sortHotelsForResults\([\s\S]*filterHotels\(results as HotelResult\[\], hotelFilters, hotelOptions\)/)});
test("Hotel class keeps square checkbox visuals and multi-select semantics",()=>{assert.doesNotMatch(source,/accessibilityRole="radiogroup"/);assert.doesNotMatch(source,/label="All"/);assert.match(source,/selected=\{filters\.starRatings\.includes\(star\)\}/);assert.match(source,/starRatings:filters\.starRatings\.includes/);assert.match(source,/<Check /);assert.match(source,/onLayout=\{anchor\("rating"\)\}/)});
test("Hotel Web parity retains immediate edits and every visible Mobile Web dimension",()=>{assert.doesNotMatch(source,/draftFilters|setDraftFilters|Apply filters/);assert.match(source,/const update=\(next:HotelFilters\)=>onChange\(next\)/);for(const label of ["Property name","Budget / Price","Good for your trip","Hotel class","Area","Property type","Facilities","Accessibility","Room & bed","Bed options"])assert.ok(source.includes(label),label);const rendered=source.slice(source.indexOf("return <Modal"));assert.ok(rendered.indexOf("Property name")<rendered.indexOf("Budget / Price"));});
test("Web and Native retain the same Hotel filter dimensions",()=>{for(const nativeLabel of ["Property name","Budget / Price","Good for your trip","Hotel class","Area","Property type","Facilities","Accessibility","Room & bed","Bed options"])assert.ok(source.includes(nativeLabel),nativeLabel);for(const webSignal of ["Property name","hotelResults.budgetPrice","Good for your trip","Hotel class","hotelResults.locationArea","hotelResults.propertyType","hotelResults.facilities","Accessibility","Room & bed","Bed options"])assert.ok(web.includes(webSignal),webSignal);});

test("Hotel budget prices use market-distinct currency symbols",()=>{assert.match(source,/formatMarketCurrency/);assert.doesNotMatch(source,/\bformatCurrency\(/);});
