import { useEffect, useRef, useState, type Dispatch, type SetStateAction } from "react";
import { BlurView } from "expo-blur";
import { ActivityIndicator, KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, useWindowDimensions, View } from "react-native";
import { Check, X } from "lucide-react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useAppTheme } from "../../theme/AppTheme";
import { appFonts } from "../../theme/typography";
import { convertAmount, formatMarketCurrency, type ExchangeRates } from "../currency/displayCurrency";
import { FlightRangeSlider } from "./FlightRangeSlider";
import { FLIGHT_FILTER_LIGHT_CANVAS, FLIGHT_FILTER_LIGHT_OUTLINE } from "./FlightResultsSheetShell";
import { ui } from "./SearchUi";
import type { HotelFilterOptions, HotelFilters, HotelStarRating } from "./hotelFilters";
import { defaultHotelSort, hotelSortOptions, type HotelSortMode } from "./hotelSort";
import { NATIVE_FILTER_SELECTION_FEEDBACK_MS } from "./filterResultsTransition";

export type HotelResultsQuickFilterKind = "sort" | "price" | "stars" | "facilities" | "roomTypes";
type Props={kind:HotelResultsQuickFilterKind;sort:HotelSortMode;filters:HotelFilters;options:HotelFilterOptions;displayCurrency:string;rates:ExchangeRates;stayNights:number;onSortChange:(next:HotelSortMode)=>void;onChange:Dispatch<SetStateAction<HotelFilters>>;onClose:()=>void};

export function HotelResultsQuickFilterSheet({kind,sort,filters,options,displayCurrency,rates,stayNights,onSortChange,onChange,onClose}:Props){
 const {theme}=useAppTheme(),inset=useSafeAreaInsets(),{height}=useWindowDimensions(),price=options.price;
 const filterCanvas=theme.dark?theme.background:FLIGHT_FILTER_LIGHT_CANVAS;
 const filterOutline=theme.dark?theme.border:FLIGHT_FILTER_LIGHT_OUTLINE;
 const visibleCurrency=displayCurrency==="USD"||convertAmount(1,"USD",displayCurrency,rates)!==null?displayCurrency:"USD";
 const toDisplay=(usd:number)=>convertAmount(usd,"USD",visibleCurrency,rates)??usd;
 const fromDisplay=(value:number)=>convertAmount(value,visibleCurrency,"USD",rates);
 const initialMin=filters.minimumPrice??price?.minimum??0,initialMax=filters.maximumPrice??price?.maximum??0;
 const [range,setRange]=useState({min:initialMin,max:initialMax});
 const [minimumText,setMinimumText]=useState(String(Math.round(toDisplay(initialMin))));
 const [maximumText,setMaximumText]=useState(String(Math.round(toDisplay(initialMax))));
 const [stars,setStars]=useState<HotelStarRating[]>([...filters.starRatings]);
 const [facilities,setFacilities]=useState<string[]>([...filters.facilities]);
 const [roomTypes,setRoomTypes]=useState<string[]>([...filters.roomTypes]);
 const [sortMode,setSortMode]=useState<HotelSortMode>(sort);
 const [filterUpdating,setFilterUpdating]=useState(false),filterUpdatingTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 const markUpdating=()=>{if(filterUpdatingTimer.current)clearTimeout(filterUpdatingTimer.current);setFilterUpdating(true);filterUpdatingTimer.current=setTimeout(()=>setFilterUpdating(false),NATIVE_FILTER_SELECTION_FEEDBACK_MS);};
 useEffect(()=>()=>{if(filterUpdatingTimer.current)clearTimeout(filterUpdatingTimer.current);},[]);
 const title=kind==="sort"?"Sort":kind==="price"?"Total price":kind==="stars"?"Hotel class":kind==="facilities"?"Facilities":"Room & bed";
 const subtitle=kind==="price"?`Estimated total for ${stayNights} ${stayNights===1?"night":"nights"}`:kind==="sort"?"Choose one option":"Choose one or more options";
 const selectSortMode=(next:HotelSortMode)=>{if(next===sortMode)return;markUpdating();setSortMode(next);};
 const syncText=(next:{min:number;max:number})=>{setRange(next);setMinimumText(String(Math.round(toDisplay(next.min))));setMaximumText(String(Math.round(toDisplay(next.max))));};
 const commitText=(edge:"min"|"max",text:string)=>{if(!price||!text.trim())return syncText(range);const parsed=Number(text);if(!Number.isFinite(parsed))return syncText(range);const usd=fromDisplay(parsed);if(usd===null||!Number.isFinite(usd))return syncText(range);markUpdating();syncText(edge==="min"?{min:Math.min(Math.max(price.minimum,usd),range.max),max:range.max}:{min:range.min,max:Math.max(Math.min(price.maximum,usd),range.min)});};
 const reset=()=>{if(kind!=="sort")markUpdating();switch(kind){case "sort":if(sortMode!==defaultHotelSort)markUpdating();setSortMode(defaultHotelSort);break;case "price":if(price)syncText({min:price.minimum,max:price.maximum});break;case "stars":setStars([]);break;case "facilities":setFacilities([]);break;case "roomTypes":setRoomTypes([]);break;}};
 const apply=()=>{if(kind==="sort"){onSortChange(sortMode);onClose();return;}onChange(current=>{switch(kind){case "price":return price?{...current,minimumPrice:range.min<=price.minimum?null:range.min,maximumPrice:range.max>=price.maximum?null:range.max}:current;case "stars":return {...current,starRatings:stars};case "facilities":return {...current,facilities};case "roomTypes":return {...current,roomTypes};}});onClose();};
 const toggleStar=(star:HotelStarRating)=>{markUpdating();setStars(current=>(current.includes(star)?current.filter(value=>value!==star):[...current,star]).sort((a,b)=>b-a) as HotelStarRating[]);};
 const toggleFacility=(value:string)=>{markUpdating();setFacilities(current=>current.includes(value)?current.filter(item=>item!==value):[...current,value]);};
 const toggleRoomType=(value:string)=>{markUpdating();setRoomTypes(current=>current.includes(value)?current.filter(item=>item!==value):[...current,value]);};
 return <Modal visible transparent animationType="slide" presentationStyle="overFullScreen" onRequestClose={onClose} accessibilityViewIsModal>
  <View style={styles.overlay} onAccessibilityEscape={onClose}>
   <BlurView pointerEvents="none" intensity={1} tint="default" experimentalBlurMethod={Platform.OS==="android"?"dimezisBlurView":undefined} style={StyleSheet.absoluteFill}/>
   <Pressable accessible={false} onPress={onClose} style={[StyleSheet.absoluteFill,styles.backdropScrim]}/>
   <KeyboardAvoidingView behavior={Platform.OS==="ios"?"padding":"height"} style={styles.bottom} pointerEvents="box-none">
    <View style={[styles.sheet,{maxHeight:Math.min(height*.76,620),backgroundColor:filterCanvas}]}>
     <View style={[styles.header,{backgroundColor:filterCanvas,borderBottomColor:filterOutline}]}><View style={styles.copy}><Text accessibilityRole="header" style={[styles.title,{color:theme.textPrimary}]}>{title}</Text><Text style={[styles.subtitle,{color:theme.textSecondary}]}>{subtitle}</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Close filters" onPress={onClose} style={styles.close}><X size={22} color={theme.icon}/></Pressable></View>
     <ScrollView style={[styles.body,{backgroundColor:filterCanvas}]} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={kind==="facilities"||kind==="roomTypes"}>
      {kind==="sort"?<View accessibilityRole="radiogroup" style={styles.sortOptions}>{hotelSortOptions.map(option=>{const selected=sortMode===option.value;return <Pressable key={option.value} accessibilityRole="radio" accessibilityState={{selected}} onPress={()=>selectSortMode(option.value)} style={styles.sortOption}><View style={styles.sortCopy}><Text style={[styles.sortLabel,{color:theme.textPrimary}]}>{option.label}</Text><Text style={[styles.sortDescription,{color:theme.textSecondary}]}>{option.description}</Text></View>{selected?<Check size={17} strokeWidth={2.2} color={theme.dark?"#8FB5FF":ui.blue}/>:null}</Pressable>})}</View>:null}
      {kind==="price"&&price?<View style={styles.priceCard}><View style={styles.inputs}><PriceInput label="Minimum" value={minimumText} filterOutline={filterOutline} onChange={value=>{markUpdating();setMinimumText(value);}} onEnd={()=>commitText("min",minimumText)}/><PriceInput label="Maximum" value={maximumText} filterOutline={filterOutline} onChange={value=>{markUpdating();setMaximumText(value);}} onEnd={()=>commitText("max",maximumText)}/></View><FlightRangeSlider available={{min:price.minimum,max:price.maximum}} selected={range} step={25} accessibilityLabel="Estimated stay total range" formatValue={value=>formatMarketCurrency(toDisplay(value),visibleCurrency)} onChange={next=>{markUpdating();syncText(next);}}/><View style={styles.endpoints}><Text style={{color:theme.textSecondary}}>{formatMarketCurrency(toDisplay(range.min),visibleCurrency)}</Text><Text style={{color:theme.textSecondary}}>{formatMarketCurrency(toDisplay(range.max),visibleCurrency)}</Text></View></View>:null}
      {kind==="stars"?([5,4,3,2,1] as HotelStarRating[]).filter(star=>options.starCounts[star]>0).map(star=><Choice key={star} label={`${star}-star hotel`} count={options.starCounts[star]} selected={stars.includes(star)} onPress={()=>toggleStar(star)}/>):null}
      {kind==="facilities"?(options.facilities.length?options.facilities.map(option=><Choice key={option.value} label={option.label} count={option.count} selected={facilities.includes(option.value)} onPress={()=>toggleFacility(option.value)}/>):<Text style={[styles.empty,{color:theme.textSecondary}]}>No facilities available for this search.</Text>):null}
      {kind==="roomTypes"?(options.roomTypes.length?options.roomTypes.map(option=><Choice key={option.value} label={option.label} count={option.count} selected={roomTypes.includes(option.value)} onPress={()=>toggleRoomType(option.value)}/>):<Text style={[styles.empty,{color:theme.textSecondary}]}>No room types available for this search.</Text>):null}
     </ScrollView>
     <View style={[styles.footer,{backgroundColor:filterCanvas,borderTopColor:filterOutline,paddingBottom:Math.max(inset.bottom,12)}]}><Pressable accessibilityRole="button" onPress={reset} style={[styles.reset,{borderColor:filterOutline}]}><Text style={[styles.buttonText,{color:theme.textPrimary}]}>Reset</Text></Pressable><Pressable accessibilityRole="button" accessibilityLiveRegion="polite" accessibilityState={{disabled:filterUpdating,busy:filterUpdating}} disabled={filterUpdating} onPress={apply} style={styles.apply}>{filterUpdating?<View style={styles.updating}><ActivityIndicator size="small" color="white"/><Text style={[styles.buttonText,{color:"white"}]}>Updating filters…</Text></View>:<Text style={[styles.buttonText,{color:"white"}]}>Apply</Text>}</Pressable></View>
    </View>
   </KeyboardAvoidingView>
  </View>
 </Modal>;
}
function PriceInput({label,value,filterOutline,onChange,onEnd}:{label:string;value:string;filterOutline:string;onChange:(v:string)=>void;onEnd:()=>void}){const {theme}=useAppTheme();return <View style={styles.inputColumn}><Text style={[styles.inputLabel,{color:theme.textSecondary}]}>{label}</Text><TextInput accessibilityLabel={`${label} estimated stay total`} keyboardType="decimal-pad" value={value} onChangeText={onChange} onBlur={onEnd} onSubmitEditing={onEnd} style={[styles.input,{color:theme.textPrimary,borderColor:filterOutline,backgroundColor:theme.surface}]}/></View>}
function Choice({label,count,selected,onPress}:{label:string;count?:number;selected:boolean;onPress:()=>void}){const {theme}=useAppTheme();const filterOutline=theme.dark?theme.border:FLIGHT_FILTER_LIGHT_OUTLINE;return <Pressable accessibilityRole="checkbox" accessibilityState={{checked:selected}} onPress={onPress} style={styles.choice}><View style={[styles.choiceBox,{borderColor:selected?ui.blue:filterOutline,backgroundColor:selected?ui.blue:"transparent"}]}>{selected?<Check size={14} strokeWidth={2.2} color="white"/>:null}</View><Text style={[styles.choiceLabel,{color:theme.textPrimary}]}>{label}</Text>{count!==undefined?<Text style={[styles.count,{color:theme.textSecondary}]}>{count}</Text>:null}</Pressable>}
const styles=StyleSheet.create({overlay:{flex:1,justifyContent:"flex-end"},backdropScrim:{backgroundColor:"rgba(15, 23, 42, 0.35)"},bottom:{justifyContent:"flex-end"},sheet:{width:"100%",borderTopLeftRadius:24,borderTopRightRadius:24,overflow:"hidden",shadowColor:"#0F172A",shadowOpacity:.2,shadowRadius:18,elevation:16},header:{minHeight:76,paddingLeft:20,paddingRight:10,flexDirection:"row",alignItems:"center",borderBottomWidth:StyleSheet.hairlineWidth},copy:{flex:1},title:{fontSize:18,fontFamily:appFonts.bold,fontWeight:"700"},subtitle:{fontSize:12,lineHeight:18,fontFamily:appFonts.medium},close:{width:44,height:44,alignItems:"center",justifyContent:"center"},body:{flexShrink:1},content:{padding:16,gap:6},sortOptions:{paddingHorizontal:16},sortOption:{minHeight:52,flexDirection:"row",alignItems:"center",gap:8,paddingHorizontal:10,paddingVertical:7},sortCopy:{flex:1,minWidth:0},sortLabel:{fontSize:14,lineHeight:18,fontWeight:"600",fontFamily:appFonts.semibold},sortDescription:{marginTop:1,fontSize:10.5,lineHeight:14,fontWeight:"500",fontFamily:appFonts.medium},priceCard:{paddingVertical:4},inputs:{flexDirection:"row",gap:10,marginBottom:12},inputColumn:{flex:1},inputLabel:{fontSize:12,lineHeight:16,fontWeight:"600",fontFamily:appFonts.semibold,marginBottom:6},input:{height:44,borderWidth:1,borderRadius:10,paddingHorizontal:12,fontFamily:appFonts.medium},endpoints:{flexDirection:"row",justifyContent:"space-between"},choice:{minHeight:52,paddingHorizontal:10,paddingVertical:6,flexDirection:"row",alignItems:"center",gap:10},choiceBox:{width:20,height:20,borderRadius:4,borderWidth:1.5,alignItems:"center",justifyContent:"center",flexShrink:0},choiceLabel:{flex:1,fontSize:14,lineHeight:20,fontWeight:"600",fontFamily:appFonts.semibold},count:{fontSize:13,fontFamily:appFonts.medium},empty:{paddingVertical:20,textAlign:"center",fontFamily:appFonts.medium},footer:{flexDirection:"row",gap:10,paddingHorizontal:16,paddingTop:12,borderTopWidth:StyleSheet.hairlineWidth},reset:{minWidth:116,height:49,borderWidth:1,borderRadius:12,alignItems:"center",justifyContent:"center"},apply:{flex:1,height:49,borderRadius:12,backgroundColor:ui.blue,alignItems:"center",justifyContent:"center"},updating:{flexDirection:"row",alignItems:"center",gap:8},buttonText:{fontSize:15,fontFamily:appFonts.bold,fontWeight:"700"}});
