import assert from "node:assert/strict";
import test from "node:test";
import type { HotelResult } from "../../api/travelApi";
import { activeHotelFilterCount, buildHotelFilterOptions, emptyHotelFilters, filterHotels } from "./hotelFilters";

const profile=(overrides:Record<string,unknown>={})=>({propertyType:"Hotel",amenities:[],accessibilityFeatures:[],travellerFeatures:[],room:{name:"Deluxe room",bedConfiguration:"King bed"},...overrides});
const hotel=(id:string,overrides:Partial<HotelResult>={}):HotelResult=>({id,provider:"Provider",name:`Hotel ${id}`,rating:9,classificationStars:4,reviewScore:9,reviewScale:10,reviewCount:1,neighbourhood:"Le  Marais",location:"Paris",amenities:["Free Wi-Fi"],roomType:"Deluxe king room, room only",cancellationInfo:"Free cancellation",valueScore:5,travelConfidenceScore:5,arrivalSuitabilityScore:5,recommendationReasons:[],badges:[],pricePerNight:100,totalPrice:200,currency:"USD",bookingUrl:"https://example.com",partnerRedirectUrl:"https://example.com",...overrides} as HotelResult);
const raw=[hotel("a",{classificationStars:5,name:"Grand Resort",amenities:["Free Wi-Fi","Pool"],roomType:"Family suite, king bed, half board",catalogueProfile:profile({propertyType:" Resort ",travellerFeatures:[" Family friendly "],accessibilityFeatures:["Step-free access"],room:{name:"Family Suite",bedConfiguration:"King Bed"}})}),hotel("b",{classificationStars:4,neighbourhood:"Montmartre, Paris",name:"City Apartment",amenities:["Parking"],roomType:"Double room, queen bed, full board",cancellationInfo:"Flexible cancellation",catalogueProfile:profile({propertyType:"Apartment",travellerFeatures:["family FRIENDLY"],accessibilityFeatures:["step-free ACCESS"],room:{name:"Double Room",bedConfiguration:"Queen bed"}})}),hotel("c",{classificationStars:undefined,neighbourhood:" le marais ",name:"Quiet Hostel",amenities:["Pool"],roomType:"Twin room, twin beds, all-inclusive",cancellationInfo:"Cancellation details",catalogueProfile:profile({propertyType:"Hostel",travellerFeatures:[],accessibilityFeatures:[],room:{name:"Twin Room",bedConfiguration:"Twin beds"}})})];
const options=buildHotelFilterOptions(raw,"Paris",{USD:1,EUR:.8});

test("default model includes every field and preserves input order",()=>{assert.deepEqual(emptyHotelFilters(),{propertyNameQuery:"",minimumPrice:null,maximumPrice:null,starRating:null,areas:[],propertyTypes:[],roomTypes:[],bedTypes:[],meals:[],cancellationPolicies:[],facilities:[],travellerFeatures:[],accessibility:[]});assert.deepEqual(filterHotels(raw,emptyHotelFilters(),options).map(x=>x.id),["a","b","c"]);assert.deepEqual(raw.map(x=>x.id),["a","b","c"])});
test("property name is trimmed, case-insensitive, and ANDs",()=>{assert.deepEqual(filterHotels(raw,{...emptyHotelFilters(),propertyNameQuery:"  GRAND  "},options).map(x=>x.id),["a"]);assert.deepEqual(filterHotels(raw,{...emptyHotelFilters(),propertyNameQuery:"hotel",facilities:["pool"]},options).map(x=>x.id),[])});
test("minimum, maximum and combined ranges compare converted total price",()=>{const priced=[hotel("usd",{totalPrice:200,pricePerNight:999,currency:"USD"}),hotel("eur",{totalPrice:160,pricePerNight:1,currency:"EUR"}),hotel("high",{totalPrice:400,pricePerNight:1,currency:"USD"}),hotel("unknown",{totalPrice:100,pricePerNight:1,currency:"XYZ"})],o=buildHotelFilterOptions(priced,"Paris",{USD:1,EUR:.8});assert.equal(o.price?.minimum,0);assert.deepEqual(filterHotels(priced,{...emptyHotelFilters(),minimumPrice:250},o).map(x=>x.id),["high"]);assert.deepEqual(filterHotels(priced,{...emptyHotelFilters(),maximumPrice:200},o).map(x=>x.id),["usd","eur"]);assert.deepEqual(filterHotels(priced,{...emptyHotelFilters(),minimumPrice:190,maximumPrice:210},o).map(x=>x.id),["usd","eur"])});
test("structured traveller and accessibility options normalize identities and preserve labels",()=>{assert.deepEqual(options.travellerFeatures,[{value:"family friendly",label:"Family friendly",count:2}]);assert.deepEqual(options.accessibility,[{value:"step-free access",label:"Step-free access",count:2}]);assert.deepEqual(filterHotels(raw,{...emptyHotelFilters(),travellerFeatures:["family friendly"],accessibility:["step-free access"]},options).map(x=>x.id),["a","b"])});
test("authoritative property, room and bed data wins over legacy text",()=>{assert.ok(options.propertyTypes.some(x=>x.value==="resort"&&x.label==="Resort"));assert.ok(options.roomTypes.some(x=>x.value==="family suite"));assert.ok(options.bedTypes.some(x=>x.value==="queen bed"));assert.deepEqual(filterHotels(raw,{...emptyHotelFilters(),propertyTypes:["apartment"],roomTypes:["double room"],bedTypes:["queen bed"]},options).map(x=>x.id),["b"])});
test("classification stars are exact and multi groups use OR within and AND across",()=>{assert.deepEqual(filterHotels(raw,{...emptyHotelFilters(),starRating:5},options).map(x=>x.id),["a"]);assert.deepEqual(filterHotels(raw,{...emptyHotelFilters(),propertyTypes:["resort","apartment"],facilities:["pool"]},options).map(x=>x.id),["a"]);assert.equal(options.starCounts[0],3)});
test("areas and facilities retain normalized raw-result counts",()=>{assert.deepEqual(options.areas.map(x=>[x.label,x.count]),[["Le Marais, Paris",2],["Montmartre, Paris",1]]);assert.equal(options.facilities.find(x=>x.value==="pool")?.count,2)});
test("active count treats query and entire price range as one then counts selections",()=>{const empty=emptyHotelFilters();assert.equal(activeHotelFilterCount(empty,options),0);assert.equal(activeHotelFilterCount({...empty,propertyNameQuery:" x ",minimumPrice:25,maximumPrice:200,starRating:5,areas:["x"],facilities:["pool"],travellerFeatures:["family friendly"],accessibility:["step-free access"]},options),7);assert.deepEqual(emptyHotelFilters(),empty)});
