import assert from "node:assert/strict";
import test from "node:test";
import type { HotelResult } from "../../api/travelApi";
import { activeHotelFilterCount, buildHotelFilterOptions, emptyHotelFilters, filterHotels } from "./hotelFilters";

const hotel=(id:string,overrides:Partial<HotelResult>={}):HotelResult=>({id,provider:"Provider",name:`Hotel ${id}`,rating:9,classificationStars:4,reviewScore:9,reviewScale:10,reviewCount:1,neighbourhood:"Le  Marais",location:"Paris",amenities:["Free Wi-Fi"],roomType:"Deluxe king room, room only",cancellationInfo:"Free cancellation",valueScore:5,travelConfidenceScore:5,arrivalSuitabilityScore:5,recommendationReasons:[],badges:[],pricePerNight:100,totalPrice:200,currency:"USD",bookingUrl:"https://example.com",partnerRedirectUrl:"https://example.com",...overrides} as HotelResult);
const raw=[hotel("a",{classificationStars:5,name:"Grand Resort",amenities:["Free Wi-Fi","Pool"],roomType:"Family suite, king bed, half board"}),hotel("b",{classificationStars:4,neighbourhood:"Montmartre, Paris",name:"City Apartment",amenities:["Parking"],roomType:"Double room, queen bed, full board",cancellationInfo:"Flexible cancellation"}),hotel("c",{classificationStars:undefined,neighbourhood:" le marais ",name:"Hostel",amenities:["Pool"],roomType:"Twin room, twin beds, all-inclusive",cancellationInfo:"Cancellation details"})];
const options=buildHotelFilterOptions(raw,"Paris",{USD:1,EUR:.8});
test("default filters preserve every hotel and input order",()=>assert.deepEqual(filterHotels(raw,emptyHotelFilters(),options).map(x=>x.id),["a","b","c"]));
test("classification stars are exact and never review scores",()=>{assert.deepEqual(filterHotels(raw,{...emptyHotelFilters(),starRating:5},options).map(x=>x.id),["a"]);assert.equal(options.starCounts[0],3);assert.equal(options.starCounts[5],1);assert.equal(options.starCounts[4],1);assert.equal(options.starCounts[1],0)});
test("areas normalize identity, label with destination, count raw results, and OR",()=>{assert.deepEqual(options.areas.map(x=>[x.label,x.count]),[["Le Marais, Paris",2],["Montmartre, Paris",1]]);assert.deepEqual(filterHotels(raw,{...emptyHotelFilters(),areas:["le marais","montmartre, paris"]},options).length,3)});
test("term groups match real text, use OR within and AND across groups",()=>{const f={...emptyHotelFilters(),propertyTypes:["resort","apartment"],bedTypes:["king-bed"]};assert.deepEqual(filterHotels(raw,f,options).map(x=>x.id),["a"]);assert.ok(options.roomTypes.some(x=>x.value==="twin-room"));assert.ok(options.meals.some(x=>x.value==="all-inclusive"));assert.ok(options.cancellationPolicies.some(x=>x.value==="free-cancellation"))});
test("facilities normalize and count, with OR matching",()=>{assert.deepEqual(options.facilities.find(x=>x.value==="pool")?.count,2);assert.deepEqual(filterHotels(raw,{...emptyHotelFilters(),facilities:["wifi","parking"]},options).map(x=>x.id),["a","b"])});
test("price compares convertible total price, never nightly or raw mixed currency",()=>{const priced=[hotel("usd",{totalPrice:200,pricePerNight:999,currency:"USD"}),hotel("eur",{totalPrice:169,pricePerNight:1,currency:"EUR"}),hotel("unknown",{totalPrice:100,pricePerNight:1,currency:"XYZ"})];const o=buildHotelFilterOptions(priced,"Paris",{USD:1,EUR:.8});assert.deepEqual(filterHotels(priced,{...emptyHotelFilters(),maximumPrice:200},o).map(x=>x.id),["usd"])});
test("active count and clear/default model cover each selection",()=>{const empty=emptyHotelFilters();assert.equal(activeHotelFilterCount(empty,options),0);assert.equal(activeHotelFilterCount({...empty,starRating:5,areas:["le marais"],facilities:["wifi"],maximumPrice:200},options),4);assert.deepEqual(emptyHotelFilters(),empty)});
