import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { nativeCarDetailDate, nativeCarPickupTypeLabel, nativeCarRentalDays } from "./nativeCarDetailsModel";
const native=readFileSync("src/features/search/ApprovedCarDetailScreen.tsx","utf8");
const hotelDetail=readFileSync("src/features/search/ApprovedDetailScreen.tsx","utf8");
function styleRule(source:string,name:string,nextName:string){const start=source.indexOf(`${name}:`);const end=source.indexOf(`${nextName}:`,start);assert.notEqual(start,-1,`${name} style must exist`);assert.notEqual(end,-1,`${nextName} style must follow ${name}`);return source.slice(start,end);}
test("ready car detail uses the web hero, sticky navigation, panels, and dock hierarchy",()=>{for(const contract of ['Back to Cars results','{result.modelName}','resizeMode="cover"','aspectRatio:16/10','stickyHeaderIndices={[2]}','Compare prices','Pickup and return','Location','estimated rental total','Continue deal','accessibilityState={{disabled:true}}','WebView','Get directions','Pickup and location details'])assert.ok(native.includes(contract),contract);for(const retired of ['No additional photo','1 / 1','ratingWord','Rental conditions','Price breakdown','Price alert','Booking unavailable','Continue to ${','Continue booking'])assert.ok(!native.includes(retired),retired);assert.equal((native.match(/Continue deal/g)??[]).length,1);assert.match(native,/width:"48%"/);assert.match(native,/height:200/);assert.match(native,/borderTopLeftRadius:22/);});
test("native car and hotel Compare prices headings share the compact hierarchy",()=>{const carHeading=styleRule(native,"compareHeading","stay");const hotelHeading=styleRule(hotelDetail,"hotelCompareHeading","hotelCompareLead");for(const heading of [carHeading,hotelHeading])assert.match(heading,/fontSize: ?18[^}]*lineHeight: ?24[^}]*fontWeight: ?"600"[^}]*fontFamily: ?appFonts\.semibold[^}]*letterSpacing: ?-0?\.25/);assert.match(native,/<Text style=\{\[s\.compareHeading,[^>]*>Compare prices<\/Text>/);assert.match(styleRule(native,"heading","compareHeading"),/fontSize:20[^}]*lineHeight:28[^}]*fontWeight:"800"[^}]*fontFamily:appFonts\.extraBold/);});
test("native car comparison offer uses compact presentation without expanding past page inset",()=>{assert.match(native,/kurioticket-logo-primary-light-bg\.png/);assert.match(native,/resizeMode="contain" style=\{s\.logo\}/);assert.match(styleRule(native,"logo","radio"),/width:108[^}]*height:24[^}]*flexShrink:0/);assert.match(styleRule(native,"radio","radioDot"),/width:16[^}]*height:16[^}]*borderRadius:8[^}]*borderWidth:1\.5[^}]*alignItems:"center"[^}]*justifyContent:"center"/);assert.match(styleRule(native,"radioDot","compareBottom"),/width:6[^}]*height:6[^}]*borderRadius:3/);const card=styleRule(native,"compareCard","compareTop");assert.match(card,/marginTop:20[^}]*borderWidth:1[^}]*borderRadius:14/);assert.doesNotMatch(card,/marginHorizontal\s*:\s*-/);assert.doesNotMatch(card,/position\s*:\s*"absolute"/);assert.match(styleRule(native,"page","compare"),/paddingHorizontal:16/);});
test("native car comparison price stays distinct from its sticky total",()=>{assert.match(styleRule(native,"daily","perDay"),/fontSize:18[^}]*lineHeight:22[^}]*fontWeight:"700"[^}]*fontFamily:appFonts\.bold[^}]*letterSpacing:-\.5[^}]*textAlign:"right"[^}]*fontVariant:\["tabular-nums"\]/);assert.match(styleRule(native,"perDay","pickupSection"),/fontSize:10[^}]*lineHeight:14[^}]*fontWeight:"500"[^}]*fontFamily:appFonts\.medium[^}]*color:"#075EE8"[^}]*textAlign:"right"/);assert.match(native,/\{money\(offer\.currency,offer\.pricePerDay\)\}<\/Text><Text style=\{s\.perDay\}>per day<\/Text>/);assert.match(styleRule(native,"dockTotal","dockPerDay"),/fontSize:24[^}]*lineHeight:30[^}]*fontWeight:"800"[^}]*fontFamily:appFonts\.extraBold[^}]*textAlign:"left"[^}]*fontVariant:\["tabular-nums"\]/);});
test("native date and pickup labels match web",()=>{assert.equal(nativeCarDetailDate("2026-09-06"),"Sun, Sep 6, 2026");assert.equal(nativeCarDetailDate("2026-09-09"),"Wed, Sep 9, 2026");assert.equal(nativeCarRentalDays("2026-09-06","2026-09-09"),3);assert.equal(nativeCarPickupTypeLabel("meet-and-greet"),"Meet and greet");assert.equal(nativeCarPickupTypeLabel("shuttle"),"Shuttle pickup");});
test("mobile source contains no Google credential",()=>{assert.doesNotMatch(native,/EXPO_PUBLIC_GOOGLE_MAPS|googleKey|iframeUrl/);assert.match(native,/getApiBaseUrl\(Platform\.OS,__DEV__\)/);});
test("native car favorite uses the canonical red stroke and state fill",()=>{assert.match(native,/import \{ androidFavoriteColors \} from "\.\.\/home\/AndroidFavoriteButton"/);assert.match(native,/<Heart size=\{20\} color=\{androidFavoriteColors\.stroke\} fill=\{saved\.saved\?androidFavoriteColors\.savedFill:androidFavoriteColors\.unsavedFill\}\/>/);assert.doesNotMatch(native,/<Heart[^>]*(?:#075EE8|theme\.icon|fill="none")/);assert.match(native,/accessibilityState=\{\{selected:saved\.saved\}\} onPress=\{saved\.toggle\}/);});
