import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { nativeCarDetailDate, nativeCarPickupTypeLabel, nativeCarRentalDays } from "./nativeCarDetailsModel";
const native=readFileSync("src/features/search/ApprovedCarDetailScreen.tsx","utf8");
const hotelDetail=readFileSync("src/features/search/HotelDetailsScreen.tsx","utf8");
function styleRule(source:string,name:string,nextName:string){const start=source.indexOf(`${name}:`);const end=source.indexOf(`${nextName}:`,start);assert.notEqual(start,-1,`${name} style must exist`);assert.notEqual(end,-1,`${nextName} style must follow ${name}`);return source.slice(start,end);}
test("ready car detail uses the web hero, sticky navigation, panels, and dock hierarchy",()=>{for(const contract of ['Back to Cars results','{result.modelName}','resizeMode="contain"','heroControlSafeZoneHeight','stickyHeaderIndices={[1]}','Compare deals','Pickup and return','Location','Estimated rental total','Continue deal','accessibilityState={{disabled:true}}','WebView','Get directions','Pickup and location details'])assert.ok(native.includes(contract),contract);for(const retired of ['No additional photo','1 / 1','ratingWord','Rental conditions','Price breakdown','Price alert','Booking unavailable','Continue to ${','Continue booking'])assert.ok(!native.includes(retired),retired);assert.equal((native.match(/Continue deal/g)??[]).length,1);assert.match(styleRule(native,"specs","spec"),/justifyContent:"space-between"/);assert.match(styleRule(native,"spec","specText"),/width:"42%"/);assert.match(native,/height:200/);assert.match(native,/borderTopLeftRadius:22/);});
test("native car Compare deals keeps its compact hierarchy after the Hotel Rates redesign",()=>{const carHeading=styleRule(native,"compareHeading","stay");assert.match(carHeading,/fontSize: ?12[^}]*lineHeight: ?18[^}]*fontWeight: ?"700"[^}]*fontFamily: ?appFonts\.bold[^}]*letterSpacing: ?-0?\.2/);assert.match(styleRule(native,"stay","dealList"),/marginTop:4[^}]*fontSize:11[^}]*lineHeight:16[^}]*fontWeight:"500"[^}]*fontFamily:appFonts\.medium/);assert.match(native,/<Text style=\{\[s\.compareHeading,[^>]*>Compare deals<\/Text>/);assert.match(native,/<Text style=\{\[s\.stay,[^>]*>\{nativeCarDetailDate\(pickupDate\)\}/);assert.match(styleRule(native,"heading","compareHeading"),/fontSize:20[^}]*lineHeight:28[^}]*fontWeight:"800"[^}]*fontFamily:appFonts\.extraBold/);assert.doesNotMatch(hotelDetail,/compareHeading:/);});
test("native car comparison offers use the former compact card geometry and selectable radio treatment",()=>{assert.match(native,/kurioticket-logo-primary-light-bg\.png/);assert.match(native,/accessibilityLabel="Kurioticket" resizeMode="contain" style=\{s\.logo\}/);assert.match(styleRule(native,"logo","radio"),/width:108[^}]*height:24[^}]*flexShrink:0/);assert.match(styleRule(native,"radio","radioDot"),/width:16[^}]*height:16[^}]*borderRadius:8[^}]*borderWidth:1\.5[^}]*alignItems:"center"[^}]*justifyContent:"center"/);assert.match(styleRule(native,"radioDot","compareBottom"),/width:6[^}]*height:6[^}]*borderRadius:3/);const list=styleRule(native,"dealList","compareCard");assert.match(list,/marginTop:20[^}]*gap:10/);const card=styleRule(native,"compareCard","compareCardPressed");assert.match(card,/borderWidth:1[^}]*borderRadius:14[^}]*paddingHorizontal:8[^}]*paddingVertical:12[^}]*overflow:"hidden"/);assert.doesNotMatch(card,/marginHorizontal\s*:\s*-|position\s*:\s*"absolute"/);assert.match(styleRule(native,"compareBottom","benefits"),/marginTop:12[^}]*flexDirection:"row"[^}]*alignItems:"flex-end"[^}]*gap:10/);assert.match(styleRule(native,"comparePrice","daily"),/flexShrink:1[^}]*minWidth:72[^}]*maxWidth:"42%"[^}]*alignItems:"flex-end"/);assert.match(native,/accessibilityRole="radiogroup"/);assert.match(native,/accessibilityRole="radio" accessibilityState=\{\{selected\}\}/);assert.match(styleRule(native,"page","compare"),/paddingHorizontal:16/);});
test("native car comparison and dock prices match the Results-card hierarchy",()=>{assert.match(styleRule(native,"daily","perDay"),/maxWidth:"100%"[^}]*fontSize:19[^}]*lineHeight:22[^}]*fontWeight:"600"[^}]*fontFamily:appFonts\.semibold[^}]*letterSpacing:-0\.25[^}]*textAlign:"right"[^}]*fontVariant:\["tabular-nums"\]/);assert.match(styleRule(native,"perDay","pickupSection"),/fontSize:10[^}]*lineHeight:13[^}]*fontWeight:"500"[^}]*fontFamily:appFonts\.medium[^}]*color:"#075EE8"[^}]*textAlign:"right"/);assert.match(native,/numberOfLines=\{1\} adjustsFontSizeToFit minimumFontScale=\{0\.68\} style=\{\[s\.daily/);assert.match(native,/\{money\(offer\.currency,offer\.pricePerDay\)\}<\/Text><Text style=\{s\.perDay\}>per day<\/Text>/);const compare=native.slice(native.indexOf("function Compare("),native.indexOf("function TimelineEntry"));assert.doesNotMatch(compare,/offer\.totalPrice|Taxes & fees included/);assert.match(styleRule(native,"dockTotal","dockAction"),/maxWidth:"100%"[^}]*fontSize:19[^}]*lineHeight:22[^}]*fontWeight:"600"[^}]*fontFamily:appFonts\.semibold[^}]*letterSpacing:-0\.25[^}]*textAlign:"left"[^}]*fontVariant:\["tabular-nums"\]/);assert.match(styleRule(native,"dockEyebrow","dockTotal"),/flexShrink:1[^}]*minWidth:0[^}]*fontSize:11[^}]*lineHeight:16[^}]*fontWeight:"600"[^}]*fontFamily:appFonts\.semibold/);assert.match(native,/minimumFontScale=\{0\.65\} style=\{\[s\.dockTotal/);});
test("native car Pickup and return uses structured pickup requirements instead of generic instructions",()=>{const start=native.indexOf("function PickupReturn(");const end=native.indexOf("function Location(",start);assert.notEqual(start,-1);assert.notEqual(end,-1);const pickup=native.slice(start,end);assert.match(pickup,/Pickup requirements/);assert.match(pickup,/<IdCard size=\{19\}/);assert.match(pickup,/Valid driver's license/);assert.match(pickup,/result\.requiredDocuments\.some/);assert.doesNotMatch(pickup,/nativeCarPickupTypeLabel/);assert.doesNotMatch(pickup,/Pickup instructions:/);assert.doesNotMatch(pickup,/result\.pickupInstructions/);});
test("native date and pickup labels match web",()=>{assert.equal(nativeCarDetailDate("2026-09-06"),"Sun, Sep 6, 2026");assert.equal(nativeCarDetailDate("2026-09-09"),"Wed, Sep 9, 2026");assert.equal(nativeCarRentalDays("2026-09-06","2026-09-09"),3);assert.equal(nativeCarPickupTypeLabel("meet-and-greet"),"Meet and greet");assert.equal(nativeCarPickupTypeLabel("shuttle"),"Shuttle pickup");});
test("mobile source contains no Google credential",()=>{assert.doesNotMatch(native,/EXPO_PUBLIC_GOOGLE_MAPS|googleKey|iframeUrl/);assert.match(native,/getApiBaseUrl\(Platform\.OS,__DEV__\)/);});
test("native car favorite preserves the canonical saved red state and uses a theme-safe unsaved stroke",()=>{assert.match(native,/import \{ androidFavoriteColors \} from "\.\.\/home\/AndroidFavoriteButton"/);assert.match(native,/<Heart size=\{22\} strokeWidth=\{2\} color=\{saved\.saved\?androidFavoriteColors\.savedStroke:light\?androidFavoriteColors\.unsavedStroke:theme\.icon\} fill=\{saved\.saved\?androidFavoriteColors\.savedFill:androidFavoriteColors\.unsavedFill\}/);assert.doesNotMatch(native,/<Heart[^>]*(?:#075EE8|fill="none")/);assert.match(native,/accessibilityState=\{\{selected:saved\.saved\}\} onPress=\{saved\.toggle\}/);});
