import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const hotelDetails = readFileSync("src/features/search/HotelDetailsScreen.tsx", "utf8");
const bookingDetails = readFileSync("src/features/search/NativeHotelBookingDetails.tsx", "utf8");
const location = readFileSync("src/features/search/NativeHotelLocationSection.tsx", "utf8");
const nativeView = readFileSync("modules/kurioticket-hotel-look-around/ios/KurioticketHotelLookAroundView.swift", "utf8");

test("iOS renders interactive Apple Look Around directly inside Hotel Details", () => {
  assert.match(location, /Platform\.OS === "ios" \? "Look Around" : "Street View"/);
  assert.match(location, /<NativeAppleHotelLookAround key=\{`\$\{hotelId\}:lookaround`\}/);
  assert.doesNotMatch(location, /<View accessibilityElementsHidden pointerEvents="none" style=\{styles\.map\}>/);
  assert.doesNotMatch(location, /NativeHotelFullLookAroundModal|fullLookAroundOpen|lookAroundTapOverlay/);
  assert.match(nativeView, /lookAroundController\.isNavigationEnabled = true/);
  assert.match(nativeView, /override func hitTest\(_ point: CGPoint, with event: UIEvent\?\) -> UIView\?/);
  assert.match(nativeView, /controllerView\.hitTest\(controllerPoint, with: event\)/);
  assert.match(nativeView, /lookAroundController\.view\.isUserInteractionEnabled = true/);
  assert.match(nativeView, /InlineLookAroundViewController: MKLookAroundViewController/);
  assert.match(nativeView, /InlineLookAroundViewController\(scene: scene\)/);
  assert.match(nativeView, /override func present\(/);
  assert.match(nativeView, /override func show\(/);
  assert.match(nativeView, /override func showDetailViewController\(/);
  assert.match(nativeView, /hideFullScreenAffordance\(in: view\)/);
  assert.match(nativeView, /view\.effectiveUserInterfaceLayoutDirection == \.rightToLeft/);
  assert.match(nativeView, /leadingEdgeDistance = view\.bounds\.width - frame\.maxX/);
  assert.match(nativeView, /leadingEdgeDistance = frame\.minX/);
  assert.match(nativeView, /leadingEdgeDistance >= 0[\s\S]*leadingEdgeDistance <= 180/);
  assert.match(nativeView, /subview is UIControl[\s\S]*subview\.isHidden = true/);
  assert.doesNotMatch(nativeView, /lookAroundViewControllerWillPresentFullScreen|lookAroundViewControllerDidDismissFullScreen/);
  assert.match(nativeView, /UILongPressGestureRecognizer\(target: self, action: #selector\(handleInteractionGate/);
  assert.match(nativeView, /interactionGate\.minimumPressDuration = 0/);
  assert.match(nativeView, /scrollView\.panGestureRecognizer\.require\(toFail: interactionGate\)/);
  assert.match(nativeView, /shouldRecognizeSimultaneouslyWith/);
  assert.match(hotelDetails, /const \[lookAroundInteracting, setLookAroundInteracting\] = useState\(false\)/);
  assert.match(hotelDetails, /<ScrollView[\s\S]*scrollEnabled=\{!lookAroundInteracting\}/);
  assert.match(hotelDetails, /onLookAroundInteractionChange=\{setLookAroundInteracting\}/);
  assert.match(bookingDetails, /onLookAroundInteractionChange=\{onLookAroundInteractionChange\}/);
  assert.match(location, /onLookAroundInteractionChange\?\.\(event\.nativeEvent\.touches\.length > 0\)/);
  assert.match(location, /onTouchStart=\{syncLookAroundInteraction\}/);
  assert.match(location, /onTouchEnd=\{syncLookAroundInteraction\}/);
  assert.match(location, /onTouchCancel=\{syncLookAroundInteraction\}/);
  assert.match(location, /if \(status === "unavailable"\) releaseLookAroundInteraction\(\)/);
  assert.match(location, /return releaseLookAroundInteraction/);
});
