import { useCallback, useMemo, useState } from "react";
import { ActivityIndicator, Alert, KeyboardAvoidingView, Modal, Platform, Pressable, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { router, useFocusEffect } from "expo-router";
import { Bell, X } from "lucide-react-native";
import { travelApi, TravelApiError, type CarResult, type MobilePriceAlert } from "../../api/travelApi";
import { readSession } from "../../storage/sessionStorage";
import { useAppTheme } from "../../theme/AppTheme";
import { appFonts } from "../../theme/typography";
import { signInHref } from "../auth/signInIntent";
import { buildCarPriceAlertPayload, carAlertPresentation, matchingCarPriceAlert } from "../flow/carPriceAlertModel";
import type { SearchPlan } from "../flow/travelSearchModel";
import { Button } from "./SearchUi";

export function NativeCarPriceAlert({ plan, results, available }: { plan?: SearchPlan; results: CarResult[]; available: boolean }) {
  const { theme } = useAppTheme(); const presentation = useMemo(() => carAlertPresentation(plan, results), [plan?.key, results]); const currency = presentation.currencies[0] || "";
  const [match, setMatch] = useState<MobilePriceAlert>(); const [loading, setLoading] = useState(true); const [pending, setPending] = useState(false); const [open, setOpen] = useState(false); const [draft, setDraft] = useState(""); const [error, setError] = useState("");
  const reconcile = useCallback(async () => { if (!plan) return; setLoading(true); try { if (!await readSession().catch(() => null)) { setMatch(undefined); return; } setMatch(matchingCarPriceAlert((await travelApi.priceAlerts()).alerts, plan)); } catch (cause) { if (cause instanceof TravelApiError && cause.status === 401) setMatch(undefined); } finally { setLoading(false); } }, [plan?.key]);
  useFocusEffect(useCallback(() => { void reconcile(); }, [reconcile]));
  const signIn = () => Alert.alert("Sign in required", "Sign in to save this price alert to your account.", [{ text: "Sign in", onPress: () => router.push(signInHref("/(tabs)/profile")) }, { text: "Cancel", style: "cancel" }]);
  const closeTargetSheet = () => { setOpen(false); };
  const toggle = async (next: boolean) => { if (!plan || pending || loading) return; if (next) { if (!available || !presentation.enabled) return; if (!await readSession().catch(() => null)) { signIn(); return; } if (!match) { setError(""); setOpen(true); return; } } if (!match) return; setPending(true); try { setMatch((await travelApi.updatePriceAlertStatus(match.id, next ? "ACTIVE" : "PAUSED")).alert); } catch (cause) { Alert.alert("Unable to update price tracking", cause instanceof TravelApiError ? cause.message : "Please try again."); } finally { setPending(false); } };
  const create = async () => { if (!plan) return; const target = Number(draft); if (!/^\d+(?:\.\d{1,2})?$/.test(draft.trim()) || !Number.isFinite(target) || target <= 0) { setError("Enter a positive target rental total."); return; } setPending(true); setError(""); try { const created = await travelApi.createPriceAlert(buildCarPriceAlertPayload(plan, target, currency)); setMatch(created.alert); setOpen(false); setDraft(""); } catch (cause) { if (cause instanceof TravelApiError && cause.status === 409) { await reconcile(); setError("An alert for this rental already exists."); } else if (cause instanceof TravelApiError && cause.status === 401) { setOpen(false); signIn(); } else setError(cause instanceof TravelApiError ? cause.message : "Unable to create price alert."); } finally { setPending(false); } };
  if (!presentation.visible) return null; const tracking = match?.status === "ACTIVE"; const disabled = pending || loading || (!available && !tracking);
  return <><View accessibilityLabel="Track rental car prices" style={[styles.control, { backgroundColor: theme.priceAlertSurface, borderColor: theme.priceAlertBorder }]}><Bell accessible={false} size={17} strokeWidth={2} color={theme.priceAlertAccent}/><Text style={[styles.title, { color: theme.textPrimary }]}>Track rental car prices</Text><View style={styles.switch}>{pending ? <ActivityIndicator size="small" color={theme.priceAlertAccent}/> : null}<Switch style={Platform.OS === "ios" ? styles.iosSwitch : undefined} accessibilityRole="switch" accessibilityLabel="Track rental car prices" accessibilityState={{ checked: tracking, disabled, busy: pending }} disabled={disabled} value={tracking} onValueChange={(next) => void toggle(next)} trackColor={{ false: theme.dark ? "#465269" : "#CBD5E1", true: theme.switchTrackActive }} thumbColor="#FFFFFF" /></View></View>{open ? <Modal visible transparent animationType="none" onRequestClose={() => { if (!pending) closeTargetSheet(); }}><KeyboardAvoidingView style={styles.backdrop} behavior={Platform.OS === "ios" ? "padding" : "height"}><View style={[styles.sheet, { backgroundColor: theme.surface, borderColor: theme.border }]}><View style={styles.sheetHeader}><Text accessibilityRole="header" style={[styles.heading, styles.sheetHeaderTitle, { color: theme.textPrimary }]}>Track rental car prices</Text><Pressable accessibilityRole="button" accessibilityLabel="Close price alert" disabled={pending} onPress={closeTargetSheet} style={styles.sheetClose}><X accessible={false} size={22} color={theme.icon}/></Pressable></View><Text style={{ color: theme.textSecondary }}>Target rental total ({currency})</Text><TextInput autoFocus accessibilityLabel={`Target rental total in ${currency}`} value={draft} onChangeText={(value) => { setDraft(value); setError(""); }} keyboardType="decimal-pad" editable={!pending} style={[styles.input, { color: theme.textPrimary, borderColor: theme.border }]} />{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}<Button label={pending ? "Creating…" : "Create alert"} onPress={() => void create()} /></View></KeyboardAvoidingView></Modal> : null}</>;
}
const styles = StyleSheet.create({ control: { width: "100%", minHeight: 52, borderRadius: 12, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 4, flexDirection: "row", alignItems: "center", gap: 8 }, title: { flex: 1, flexShrink: 1, fontSize: 12.5, lineHeight: 16, fontWeight: "700", fontFamily: appFonts.bold }, switch: { minWidth: 51, minHeight: 44, flexShrink: 0, flexDirection: "row", alignItems: "center", justifyContent: "flex-end", gap: 4 }, iosSwitch: { transform: [{ translateY: 8 }] }, backdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(0,0,0,.45)" }, sheet: { padding: 20, gap: 12, borderTopWidth: 1, borderTopLeftRadius: 18, borderTopRightRadius: 18 }, sheetHeader: { flexDirection: "row", alignItems: "center" }, sheetHeaderTitle: { flex: 1, minWidth: 0 }, sheetClose: { width: 44, height: 44, alignItems: "center", justifyContent: "center" }, heading: { fontSize: 18, fontWeight: "800" }, input: { minHeight: 48, borderWidth: 1, borderRadius: 8, paddingHorizontal: 12, fontSize: 18 }, error: { color: "#A4262C" } });
