import type { FlightResult, HotelResult } from "../../api/travelApi";

const action = (kind: "flights" | "hotels", id: string, bookable: boolean) => ({
  source: kind === "flights" ? "duffel" as const : "kurioticket-static-hotels" as const,
  bookable,
  action: { kind: "internal-detail" as const, href: `/${kind}/details/${id}`, enabled: true as const },
});

export const visualFlights: FlightResult[] = [
  { id:"visual-delta",provider:"Delta Air Lines",airlineName:"Delta Air Lines",flightNumber:"DL 123",originAirport:"JFK",destinationAirport:"LHR",departureTime:"2026-08-20T20:30:00-04:00",arrivalTime:"2026-08-21T08:55:00+01:00",duration:"7h 25m",durationMinutes:445,stops:0,layovers:[],legs:[{direction:"outbound",originAirport:"JFK",destinationAirport:"LHR",departureTime:"2026-08-20T20:30:00-04:00",arrivalTime:"2026-08-21T08:55:00+01:00",duration:"7h 25m",durationMinutes:445,stops:0,layovers:[],segments:[]},{direction:"return",originAirport:"LHR",destinationAirport:"JFK",departureTime:"2026-08-27T11:15:00+01:00",arrivalTime:"2026-08-27T14:55:00-04:00",duration:"7h 40m",durationMinutes:460,stops:0,layovers:[],segments:[]}],cabinClass:"economy",baggageInfo:"Carry-on included",refundInfo:"Free cancellation within 24h",price:542,currency:"USD",bookingUrl:"https://www.delta.com",partnerRedirectUrl:"https://www.delta.com",valueScore:96,riskScore:8,comfortScore:91,travelConfidenceScore:94,travelEffortScore:95,recommendationReasons:["Best overall"],badges:["Best overall","Great price"],searchPolicy:action("flights","visual-delta",true)},
  { id:"visual-ba",provider:"British Airways",airlineName:"British Airways",flightNumber:"BA 178",originAirport:"JFK",destinationAirport:"LHR",departureTime:"2026-08-20T22:15:00-04:00",arrivalTime:"2026-08-21T10:00:00+01:00",duration:"6h 45m",durationMinutes:405,stops:0,layovers:[],cabinClass:"economy",baggageInfo:"Carry-on included",refundInfo:"Free cancellation within 24h",price:578,currency:"USD",bookingUrl:"https://www.britishairways.com",partnerRedirectUrl:"https://www.britishairways.com",valueScore:88,riskScore:10,comfortScore:86,travelConfidenceScore:90,travelEffortScore:90,recommendationReasons:["2nd best"],badges:["2nd best"],searchPolicy:action("flights","visual-ba",true)},
  { id:"visual-united",provider:"United Airlines",airlineName:"United Airlines",flightNumber:"UA 146",originAirport:"JFK",destinationAirport:"LHR",departureTime:"2026-08-20T18:45:00-04:00",arrivalTime:"2026-08-21T06:05:00+01:00",duration:"11h 20m",durationMinutes:680,stops:1,layovers:[{airport:"EWR",duration:"1h 45m",quality:"good"}],cabinClass:"economy",baggageInfo:"Carry-on included",refundInfo:"Free cancellation within 24h",price:486,currency:"USD",bookingUrl:"https://www.united.com",partnerRedirectUrl:"https://www.united.com",valueScore:81,riskScore:18,comfortScore:75,travelConfidenceScore:84,travelEffortScore:72,recommendationReasons:["Low fare"],badges:["1 stop"],searchPolicy:action("flights","visual-united",true)},
];

const hotel = (id:string,name:string,imageUrl:string,pricePerNight:number,totalPrice:number,rating:number,reviewCount:number,distance:string,badge:string):HotelResult => ({id,provider:"Booking.com",name,imageUrl,imageUrls:[imageUrl,imageUrl,imageUrl],rating:5,classificationStars:5,reviewScore:rating,reviewScale:10,reviewCount,neighbourhood:"Downtown Houston",location:"Houston, TX",distanceFromCenter:distance,amenities:["Breakfast included","Free cancellation","Pay at property","Pool","Free Wi-Fi","Fitness center","Parking available"],roomType:"Deluxe King Room",cancellationInfo:"Free cancellation until May 18",taxesAndFeesIncluded:true,dataSource:"demo",valueScore:95,travelConfidenceScore:92,arrivalSuitabilityScore:90,recommendationReasons:[badge],badges:[badge],pricePerNight,totalPrice,currency:"USD",bookingUrl:"https://booking.com",partnerRedirectUrl:"https://booking.com",searchPolicy:action("hotels",id,false)});
export const visualHotels: HotelResult[] = [
  hotel("visual-westin","The Westin Houston Downtown","https://images.unsplash.com/photo-1566073771259-6a8506099945?w=900",184,426,9.1,2840,"0.3 mi","Best overall"),
  hotel("visual-hyatt","Hyatt Place Houston Downtown","https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=900",152,352,8.6,1563,"0.6 mi","Great price"),
  hotel("visual-marriott","Marriott Marquis Houston","https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=900",196,454,9.0,3215,"0.4 mi","Highly rated"),
];
