import { useLayoutEffect, useState } from "react";
import { Animated, Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { FlowIcon } from "./FlowIcon";
import { PickerSheetHeader, PrimaryButton } from "./FlowPrimitives";
import { useFlowTheme } from "./flowStyles";
import { localIsoDate } from "./localDateModel";
import { timeOptions } from "./carSearchModel";
import { DateRangeSheet } from "./DateRangeSheet";
import { HotelResultsEditPickerShell } from "./HotelResultsEditPickerShell";
import { SEARCH_PICKER_BACKDROP_COLOR, useSearchPickerMotion } from "./searchPickerPresentation";
import { useMobileLocalization } from "../../localization/MobileLocalizationProvider";
import { carFormatTime, carIntlLocale, carText } from "../search/carMobileLocalization";

type PickerPresentation = "sheet" | "resultsEditFullScreen";

export function CarRentalDatesSheet({ visible, pickupDate, returnDate, title, presentation = "sheet", onDone, onCancel }: { visible: boolean; pickupDate: string; returnDate: string; title?: string; presentation?: PickerPresentation; onDone: (pickupDate: string, returnDate: string) => void; onCancel: () => void }) {
  const {locale}=useMobileLocalization();
  const resolvedTitle=title??carText(locale,"carsSearch.rentalDatesLabel","Rental dates");
  return <DateRangeSheet visible={visible} title={resolvedTitle} startLabel={carText(locale,"carsSearch.pickupDateLabel","Pick-up date")} endLabel={carText(locale,"carsSearch.returnDateLabel","Return date")} startDate={pickupDate} endDate={returnDate} minimumStartDate={localIsoDate(new Date())} presentation={presentation} locale={carIntlLocale(locale)} doneLabel={carText(locale,"carsSearch.done","Done")} selectLabel={carText(locale,"carsSearch.select","Select")} previousMonthLabel={carText(locale,"carsSearch.previousMonth","Previous month")} nextMonthLabel={carText(locale,"carsSearch.nextMonth","Next month")} backAccessibilityLabel={carText(locale,"carsResults.editSearch","Back to edit car search")} onDone={onDone} onCancel={onCancel}/>;
}

export function CarTimeRangeSheet({ visible, pickupTime, returnTime, presentation = "sheet", onDone, onCancel }: { visible: boolean; pickupTime: string; returnTime: string; presentation?: PickerPresentation; onDone: (pickupTime: string, returnTime: string) => void; onCancel: () => void }) {
  const ft=useFlowTheme(); const {locale}=useMobileLocalization(); const sheetVisible=presentation === "sheet" ? visible : false; const motion=useSearchPickerMotion(sheetVisible); const [draftPickup,setDraftPickup]=useState(pickupTime); const [draftReturn,setDraftReturn]=useState(returnTime);
  useLayoutEffect(()=>{if(visible){setDraftPickup(pickupTime);setDraftReturn(returnTime);}},[visible,pickupTime,returnTime]);
  const pickupLabel=carText(locale,"carsSearch.pickupTimeLabel","Pick-up time"),returnLabel=carText(locale,"carsSearch.returnTimeLabel","Return time"),title=carText(locale,"carsSearch.pickupReturnTimeLabel","Pick-up / Return time"),done=carText(locale,"carsSearch.done","Done");
  const content=<View style={styles.timeColumns}><TimeColumn label={pickupLabel} selected={draftPickup} onSelect={setDraftPickup}/><TimeColumn label={returnLabel} selected={draftReturn} onSelect={setDraftReturn}/></View>;
  if(presentation === "resultsEditFullScreen") return <HotelResultsEditPickerShell visible={visible} title={title} backAccessibilityLabel={carText(locale,"carsResults.editSearch","Back to edit car search")} onBack={onCancel} footer={<PrimaryButton label={done} icon={null} disabled={!draftPickup||!draftReturn} onPress={()=>onDone(draftPickup,draftReturn)}/>}><View style={styles.fullScreenContent}>{content}</View></HotelResultsEditPickerShell>;
  if(!motion.rendered)return null;
  return <Modal transparent animationType="none" visible onRequestClose={onCancel}><View pointerEvents={motion.pointerEvents} style={styles.modalRoot}><Animated.View pointerEvents="none" accessible={false} style={[StyleSheet.absoluteFill,styles.scrim,motion.backdropStyle]}/><Pressable style={StyleSheet.absoluteFill} accessibilityRole="button" accessibilityLabel={carText(locale,"carsSearch.cancelTimeChanges","Cancel time changes")} onPress={onCancel}/><View style={styles.safeLayer} pointerEvents="box-none"><Animated.View accessibilityViewIsModal onLayout={motion.onSheetLayout} style={[styles.sheet,styles.timeSheet,{backgroundColor:ft.colors.surface,paddingBottom:16+motion.bottomSafeAreaInset},motion.sheetStyle]}><PickerSheetHeader title={title} onClose={onCancel}/>{content}<PrimaryButton label={done} icon={null} disabled={!draftPickup||!draftReturn} onPress={()=>onDone(draftPickup,draftReturn)}/></Animated.View></View></View></Modal>;
}

function TimeColumn({label,selected,onSelect}:{label:string;selected:string;onSelect:(time:string)=>void}) { const ft=useFlowTheme(); const {locale}=useMobileLocalization(); return <View style={styles.timeColumn}><Text style={[ft.styles.label,styles.timeLabel]}>{label}</Text><ScrollView accessibilityLabel={`${label} ${carText(locale,"carsSearch.options","options")}`} nestedScrollEnabled>{timeOptions.map(time=>{const chosen=time===selected;const display=carFormatTime(locale,time);return <Pressable key={time} accessibilityRole="button" accessibilityState={{selected:chosen}} accessibilityLabel={`${display}${chosen?`, ${carText(locale,"carsResults.selected","selected")}`:""}`} onPress={()=>onSelect(time)} style={[styles.timeChoice,{borderBottomColor:ft.colors.border},chosen&&{backgroundColor:ft.colors.selected}]}><Text style={[ft.styles.value,chosen&&{color:ft.colors.selectedPrimaryText}]}>{display}</Text>{chosen?<FlowIcon name="check" size={17} color={ft.colors.selectedBorder}/>:null}</Pressable>;})}</ScrollView></View>; }

const styles=StyleSheet.create({modalRoot:{flex:1,justifyContent:"flex-end"},scrim:{backgroundColor:SEARCH_PICKER_BACKDROP_COLOR},safeLayer:{flex:1,justifyContent:"flex-end"},fullScreenContent:{flex:1,padding:16},sheet:{borderTopLeftRadius:24,borderTopRightRadius:24,padding:16,gap:10,maxHeight:"94%"},rangeHeader:{flexDirection:"row",gap:12},rangeValue:{flex:1,minWidth:0,padding:10},monthRow:{minHeight:48,flexDirection:"row",alignItems:"center",gap:4},month:{flex:1,textAlign:"center",fontSize:18,fontWeight:"800"},monthControl:{width:44,height:44,borderRadius:22,borderWidth:1,alignItems:"center",justifyContent:"center"},controlText:{fontSize:25},week:{flexDirection:"row"},weekday:{width:"14.285%",textAlign:"center",fontSize:11},grid:{flexDirection:"row",flexWrap:"wrap"},day:{width:"14.285%",minHeight:44,alignItems:"center",justifyContent:"center",borderRadius:8},dayText:{fontSize:13},selectedText:{fontWeight:"800"},disabled:{opacity:.35},cancel:{minHeight:44,alignItems:"center",justifyContent:"center"},link:{fontWeight:"800"},timeSheet:{height:"82%"},timeColumns:{flex:1,flexDirection:"row",gap:10,minHeight:0},timeColumn:{flex:1,minWidth:0},timeLabel:{fontSize:12,paddingVertical:8},timeChoice:{minHeight:50,borderBottomWidth:1,paddingHorizontal:8,flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:4}});
