import assert from "node:assert/strict"; import { readFileSync } from "node:fs"; import test from "node:test";
const panel=readFileSync("src/features/flow/HotelSearchPanel.tsx","utf8");const sheet=panel.slice(panel.indexOf("function HotelDestinationSheet"),panel.indexOf("type GuestsRoomsDraft"));
test("Hotel picker focuses after the current visible open settles",()=>{assert.match(sheet,/!visible \|\| !motion\.openSettled/);assert.match(sheet,/\[visible, motion\.openSettled, value\]/);assert.doesNotMatch(sheet,/requestAnimationFrame\(\(\)=>inputRef\.current\?\.focus/);assert.doesNotMatch(sheet,/autoFocus/);assert.match(sheet,/KeyboardAvoidingView/);assert.match(sheet,/const clear = .*inputRef\.current\?\.focus\(\)/);});
test("Hotel gates API work and preserves cancellation",()=>{assert.match(sheet,/!hasMinimumLocationSearchLetters\(trimmedQuery\)/);assert.match(sheet,/searchHotelDestinations\(trimmedQuery/);assert.match(sheet,/\}, 180\)/);assert.match(sheet,/AbortController/);assert.match(sheet,/sequence !== requestSequence\.current/);});
test("Hotel selection is local until explicit Done",()=>{assert.match(sheet,/setDraft\(item\); setQuery\(item\.searchValue\)/);assert.match(sheet,/disabled=\{!draft\}/);assert.match(sheet,/onDone\(draft\.searchValue\)/);assert.doesNotMatch(sheet,/onPress=\{\(\) => onDone\(item\.searchValue\)\}/);});
test("Hotel editing and Clear invalidate draft",()=>{assert.match(sheet,/next !== draft\.searchValue\) setDraft\(undefined\)/);assert.match(sheet,/const clear = \(\) => \{ setQuery\(""\); setDraft\(undefined\)/);assert.match(sheet,/onRequestClose=\{onCancel\}/);});
test("Hotel retains canonical visual and search contracts",()=>{assert.match(sheet,/FlowIcon name="location"/);assert.match(sheet,/keyboardShouldPersistTaps="handled"/);assert.match(sheet,/Finding destinations…/);assert.match(sheet,/Type at least 2 letters/);});
test("Hotel selection preserves suggestions and cannot show a false empty state",()=>{assert.match(sheet,/trimmedQuery === programmaticFilledQuery\.current\) \{ programmaticFilledQuery\.current=""; setLoading\(false\); setError\(false\); return; \}/);assert.match(sheet,/ListEmptyComponent=\{draft\?null:/);assert.match(sheet,/next\.trim\(\)!==programmaticFilledQuery\.current\)programmaticFilledQuery\.current=""/);});

test("Hotel uses a discard close header and keeps conditional Clear inside the search shell",()=>{assert.match(sheet,/<PickerSheetHeader title="Choose destination" onClose=\{onCancel\} closeLabel="Close hotel destination picker"\/>/);const search=sheet.slice(sheet.indexOf("<View style={[styles.destinationSearch"),sheet.indexOf("</View>",sheet.indexOf("<View style={[styles.destinationSearch")));assert.match(search,/trimmedQuery \? <Pressable[^>]+accessibilityLabel="Clear hotel destination search"/);assert.doesNotMatch(sheet,/>Cancel<|accessibilityLabel="Cancel destination changes"/);});
