import assert from "node:assert/strict"; import { readFileSync } from "node:fs"; import test from "node:test";
const panel=readFileSync("src/features/flow/HotelSearchPanel.tsx","utf8");const sheet=panel.slice(panel.indexOf("function HotelDestinationSheet"),panel.indexOf("type GuestsRoomsDraft"));
test("Hotel picker coordinates focus with each presentation lifecycle",()=>{assert.match(sheet,/useSearchPickerKeyboardPresentation\(sheetVisible, motion\.rendered, value, inputRef, motion, \{ focusOnPresentation: true \}\)/);assert.match(sheet,/onShow=\{keyboardPresentation\.onModalShow\}/);assert.match(sheet,/HotelResultsEditPickerShell[\s\S]*?onShow=\{\(\) => inputRef\.current\?\.focus\(\)\}/);assert.match(sheet,/onFocus=\{keyboardPresentation\.onInputFocus\}/);assert.doesNotMatch(sheet,/motion\.openSettled/);assert.doesNotMatch(sheet,/requestAnimationFrame\(\(\)=>inputRef\.current\?\.focus/);assert.doesNotMatch(sheet,/autoFocus/);assert.match(sheet,/KeyboardAvoidingView/);});
test("Hotel gates API work and preserves cancellation",()=>{assert.match(sheet,/!hasMinimumLocationSearchLetters\(trimmedQuery\)/);assert.match(sheet,/searchHotelDestinations\(trimmedQuery/);assert.match(sheet,/\}, 180\)/);assert.match(sheet,/AbortController/);assert.match(sheet,/sequence !== requestSequence\.current/);});
test("Hotel suggestions commit immediately without Done",()=>{assert.match(sheet,/setDraft\(item\); setQuery\(item\.searchValue\)[\s\S]*?Keyboard\.dismiss\(\); onChoose\(item\.searchValue\)/);assert.doesNotMatch(sheet,/<PrimaryButton label="Done"/);assert.match(sheet,/onChoose: \(destination: string\) => void/);});
test("Hotel editing invalidates draft and dismissal discards it after dismissing the keyboard",()=>{assert.match(sheet,/next !== draft\.searchValue\) setDraft\(undefined\)/);assert.match(sheet,/const dismissDestinationSheet = \(\) => \{ Keyboard\.dismiss\(\); onCancel\(\); \};/);assert.match(sheet,/onRequestClose=\{dismissDestinationSheet\}/);});
test("Hotel retains canonical visual and search contracts",()=>{assert.match(sheet,/FlowIcon name="location"/);assert.match(sheet,/keyboardShouldPersistTaps="handled"/);assert.match(sheet,/Finding destinations…/);assert.match(sheet,/Start typing to find a destination\./);assert.match(sheet,/trimmedQuery\.length===0/);assert.match(sheet,/hasMinimumLocationSearchLetters\(query\)\?null/);assert.doesNotMatch(sheet,/Type at least 2 letters/);});

test("Hotel uses a discard close header and no trailing Clear action",()=>{assert.match(sheet,/<PickerSheetHeader title="Choose destination" onClose=\{dismissDestinationSheet\} closeLabel="Close hotel destination picker"\/>/);assert.doesNotMatch(sheet,/accessibilityLabel="Clear hotel destination search"|>Clear</);assert.doesNotMatch(sheet,/>Cancel<|accessibilityLabel="Cancel destination changes"/);});

test("Hotel destination icons default to Hotel and support retained Package overrides",()=>{assert.match(panel,/HOTEL_DESTINATION_SUGGESTION_ICONS = \["hotel"\] as const/);assert.match(sheet,/suggestionIcons\?: readonly SearchResultProductIconName\[\]/);assert.match(sheet,/useRetainedPickerContext\(visible, \{ suggestionIcons \}\)/);});
