import { useCallback, useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { router, useFocusEffect } from "expo-router";
import { travelApi } from "../../api/travelApi";
import { useMobileLocalization } from "../../localization/MobileLocalizationProvider";
import { mobileLocales } from "../../localization/mobileLocalizationCatalog";
import { useAppTheme } from "../../theme/AppTheme";
import { FlowIcon, type FlowIconName } from "./FlowIcon";
import { flowColors } from "./flowStyles";
import { filterCurrencyPresentations, getCurrencyPresentations, getSelectableCurrencyCodes } from "../currency/currencySelectionModel";

function Header({ title }: { title: string }) { const { theme } = useAppTheme(); return <View style={[styles.header, { borderBottomColor: theme.border }]}><Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={() => router.back()} style={styles.touch}><FlowIcon name="back" color={theme.icon} /></Pressable><Text accessibilityRole="header" style={[styles.title, { color: theme.text }]}>{title}</Text><View style={styles.touch} /></View>; }
type RowProps = { label: string; icon: FlowIconName; value?: string; onPress: () => void };
function Row({ label, icon, value, onPress }: RowProps) { const { theme } = useAppTheme(); return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={[styles.row, { borderBottomColor: theme.border }]}><FlowIcon name={icon} color={flowColors.blue} /><Text style={[styles.rowText, { color: theme.text }]}>{label}</Text>{value ? <Text style={{ color: theme.muted }}>{value}</Text> : null}<FlowIcon name="chevron" color={theme.icon} size={18} /></Pressable>; }
export function SettingsScreen() {
  const { theme, darkMode, setDarkMode } = useAppTheme(); const { t, locale, currency, refresh: refreshPreferences } = useMobileLocalization();
  useFocusEffect(useCallback(() => { void refreshPreferences(); }, [refreshPreferences]));
  return <SafeAreaView style={[styles.safe, { backgroundColor: theme.background }]}><Header title={t("customizationPreferences")} /><ScrollView alwaysBounceVertical={false} bounces={false} overScrollMode="never" contentContainerStyle={styles.content}><Text accessibilityRole="header" style={[styles.section, { color: theme.text }]}>{t("appPreferences")}</Text><View style={[styles.card, { backgroundColor: theme.surface, borderColor: theme.border }]}><Row label={t("language")} icon="globe" value={mobileLocales.find((item) => item.code === locale)?.label} onPress={() => router.push("/language")} /><Row label={t("currency")} icon="currency" value={currency} onPress={() => router.push("/currency")} /><View style={styles.row}><FlowIcon name="moon" color={flowColors.blue} /><Text style={[styles.rowText, { color: theme.text }]}>{t("darkMode")}</Text><View style={styles.trailingControl}><Switch accessibilityLabel={t("darkMode")} accessibilityRole="switch" accessibilityState={{ checked: darkMode }} value={darkMode} onValueChange={(v) => void setDarkMode(v).catch(() => Alert.alert("Unable to update dark mode", "Please try again."))} /></View></View></View></ScrollView></SafeAreaView>;
}
export function CurrencyScreen() {
  const { theme } = useAppTheme(); const { currency: selected, setCurrency, t } = useMobileLocalization(); const [currencies, setCurrencies] = useState<string[]>([]); const [query, setQuery] = useState(""); const [error, setError] = useState("");
  useEffect(() => { void travelApi.currencyRates().then((payload) => setCurrencies(getSelectableCurrencyCodes(payload.rates))).catch(() => setError("Unable to load current exchange rates. Try again.")); }, []);
  const select = async (currency: string) => { setError(""); try { await setCurrency(currency); } catch { setError("Currency was saved for offline use but could not be synchronized."); } };
  const visibleCurrencies = filterCurrencyPresentations(getCurrencyPresentations(currencies), query);
  const currencySearch = t("currencySearch");
  return <SafeAreaView style={[styles.safe, { backgroundColor: theme.background }]}><Header title={t("currency")} /><ScrollView keyboardShouldPersistTaps="handled" alwaysBounceVertical={false} bounces={false} overScrollMode="never" contentContainerStyle={styles.content}><Text style={{ color: theme.muted }}>Choose the currency used for price display.</Text><TextInput accessibilityLabel={currencySearch} autoFocus={false} placeholder={currencySearch} placeholderTextColor={theme.muted} value={query} onChangeText={setQuery} style={[styles.currencySearch, { backgroundColor: theme.surface, borderColor: theme.border, color: theme.text }]} />{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}<View>{visibleCurrencies.map((currency) => { const hasDistinctSymbol = currency.symbol !== currency.code; return <Pressable key={currency.code} accessibilityRole="radio" accessibilityLabel={`${currency.code}, ${currency.name}`} accessibilityState={{ checked: selected === currency.code }} onPress={() => void select(currency.code)} style={[styles.currencyRow, { borderBottomColor: theme.border }, selected === currency.code && { backgroundColor: theme.priceAlertSurface }]}><View accessible={false} importantForAccessibility="no-hide-descendants" style={styles.currencySymbolColumn}>{hasDistinctSymbol ? <Text numberOfLines={1} adjustsFontSizeToFit minimumFontScale={0.7} style={[styles.currencySymbol, { color: theme.text }]}>{currency.symbol}</Text> : null}</View><View style={styles.currencyTextColumn}><Text style={[styles.currencyCode, { color: theme.text }]}>{currency.code}</Text><Text numberOfLines={1} style={[styles.currencyName, { color: theme.textMuted }]}>{currency.name}</Text></View><View style={styles.currencyTrailing}>{selected === currency.code ? <FlowIcon name="check" color="#0754F7" /> : null}</View></Pressable>; })}{visibleCurrencies.length === 0 && currencies.length > 0 ? <Text style={[styles.currencyEmpty, { color: theme.muted }]}>{t("currencyEmpty")}</Text> : null}</View></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1 }, header: { minHeight: 62, flexDirection: "row", alignItems: "center", borderBottomWidth: StyleSheet.hairlineWidth }, touch: { width: 52, height: 52, alignItems: "center", justifyContent: "center" }, title: { flex: 1, textAlign: "center", fontSize: 22, fontWeight: "800" }, content: { padding: 18, gap: 12 }, section: { fontSize: 16, fontWeight: "800", marginTop: 8 }, card: { borderWidth: 1, borderRadius: 14, overflow: "hidden" }, row: { minHeight: 58, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", gap: 12, borderBottomWidth: StyleSheet.hairlineWidth }, rowText: { flex: 1, fontWeight: "700" }, trailingControl: { flexShrink: 0, alignItems: "flex-end", justifyContent: "center" }, currencySearch: { minHeight: 46, borderWidth: 1, borderRadius: 10, paddingHorizontal: 14, fontSize: 16 }, currencyRow: { minHeight: 74, paddingHorizontal: 10, flexDirection: "row", alignItems: "center", borderBottomWidth: StyleSheet.hairlineWidth }, currencySymbolColumn: { width: 42, flexShrink: 0, alignItems: "flex-start", justifyContent: "center", marginRight: 10 }, currencySymbol: { fontSize: 17, fontWeight: "600" }, currencyTextColumn: { flex: 1 }, currencyCode: { fontSize: 16, fontWeight: "700" }, currencyName: { fontSize: 14, lineHeight: 19, marginTop: 3 }, currencyTrailing: { width: 30, flexShrink: 0, alignItems: "flex-end", justifyContent: "center" }, currencyEmpty: { paddingVertical: 18 }, error: { color: "#D92D20" } });
