import { useCallback, useEffect, useState } from "react";
import Constants from "expo-constants";
import { Alert, Linking, Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { router, useFocusEffect } from "expo-router";
import { travelApi } from "../../api/travelApi";
import { useMobileLocalization } from "../../localization/MobileLocalization";
import { mobileLocales } from "../../localization/mobileLocalization";
import { useAppTheme } from "../../theme/AppTheme";
import { FlowIcon, type FlowIconName } from "./FlowIcon";
import { flowColors } from "./flowStyles";

function Header({ title }: { title: string }) { const { theme } = useAppTheme(); return <View style={[styles.header, { borderBottomColor: theme.border }]}><Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={() => router.back()} style={styles.touch}><FlowIcon name="back" color={theme.icon} /></Pressable><Text accessibilityRole="header" style={[styles.title, { color: theme.text }]}>{title}</Text><View style={styles.touch} /></View>; }
async function openExternal(url: string, label: string) { try { if (!await Linking.canOpenURL(url)) throw new Error(); await Linking.openURL(url); } catch { Alert.alert(`Unable to open ${label}`, "Check your connection and try again."); } }
type RowProps = { label: string; icon: FlowIconName; value?: string; external?: boolean; onPress: () => void };
function Row({ label, icon, value, external, onPress }: RowProps) { const { theme } = useAppTheme(); return <Pressable accessibilityRole="button" accessibilityLabel={`${label}${external ? ", opens website" : ""}`} accessibilityHint={external ? "Opens in your web browser; mobile and web sign-in sessions are separate" : undefined} onPress={onPress} style={[styles.row, { borderBottomColor: theme.border }]}><FlowIcon name={icon} color={flowColors.blue} /><Text style={[styles.rowText, { color: theme.text }]}>{label}</Text>{value ? <Text style={{ color: theme.muted }}>{value}</Text> : null}<FlowIcon name={external ? "external" : "chevron"} color={theme.icon} size={18} /></Pressable>; }
export function SettingsScreen() {
  const { theme, darkMode, setDarkMode } = useAppTheme(); const { t, locale, currency, refresh: refreshPreferences } = useMobileLocalization();
  useFocusEffect(useCallback(() => { void refreshPreferences(); }, [refreshPreferences]));
  const web = (path: string, label: string) => void openExternal(`https://kurioticket.com${path}`, label);
  return <SafeAreaView style={[styles.safe, { backgroundColor: theme.background }]}><Header title={t("customizationPreferences")} /><ScrollView alwaysBounceVertical={false} bounces={false} overScrollMode="never" contentContainerStyle={styles.content}><Text accessibilityRole="header" style={[styles.section, { color: theme.text }]}>{t("appPreferences")}</Text><View style={[styles.card, { backgroundColor: theme.surface, borderColor: theme.border }]}><Row label={t("language")} icon="globe" value={mobileLocales.find((item) => item.code === locale)?.label} onPress={() => router.push("/language")} /><Row label={t("currency")} icon="currency" value={currency} onPress={() => router.push("/currency")} /><View style={styles.row}><FlowIcon name="moon" color={flowColors.blue} /><Text style={[styles.rowText, { color: theme.text }]}>{t("darkMode")}</Text><Switch accessibilityLabel={t("darkMode")} accessibilityRole="switch" accessibilityState={{ checked: darkMode }} value={darkMode} onValueChange={(v) => void setDarkMode(v).catch(() => Alert.alert("Unable to update dark mode", "Please try again."))} /></View></View><Text accessibilityRole="header" style={[styles.section, { color: theme.text }]}>{t("aboutLegal")}</Text><View style={[styles.card, { backgroundColor: theme.surface, borderColor: theme.border }]}><Row label={t("terms")} icon="document" external onPress={() => web("/terms", t("terms"))} /><Row label={t("privacy")} icon="shield" external onPress={() => web("/privacy", t("privacy"))} /><View style={styles.row}><FlowIcon name="settings" color={flowColors.blue} /><Text style={[styles.rowText, { color: theme.text }]}>{t("appVersion")}</Text><Text style={{ color: theme.muted }}>{Constants.expoConfig?.version || "0.1.0"}</Text></View></View></ScrollView></SafeAreaView>;
}
export function CurrencyScreen() {
  const { theme } = useAppTheme(); const { currency: selected, setCurrency, t } = useMobileLocalization(); const [currencies, setCurrencies] = useState<string[]>([]); const [error, setError] = useState("");
  useEffect(() => { void travelApi.currencyRates().then((payload) => setCurrencies(Object.keys(payload.rates).sort())).catch(() => setError("Unable to load current exchange rates. Try again.")); }, []);
  const select = async (currency: string) => { setError(""); try { await setCurrency(currency); } catch { setError("Currency was saved for offline use but could not be synchronized."); } };
  return <SafeAreaView style={[styles.safe, { backgroundColor: theme.background }]}><Header title={t("currency")} /><ScrollView alwaysBounceVertical={false} bounces={false} overScrollMode="never" contentContainerStyle={styles.content}><Text style={{ color: theme.muted }}>Choose the currency used for price display.</Text>{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}<View style={[styles.card, { backgroundColor: theme.surface, borderColor: theme.border }]}>{currencies.map((currency) => <Pressable key={currency} accessibilityRole="radio" accessibilityState={{ checked: selected === currency }} onPress={() => void select(currency)} style={[styles.row, { borderBottomColor: theme.border }]}><Text style={[styles.rowText, { color: theme.text }]}>{currency}</Text>{selected === currency ? <FlowIcon name="check" color={flowColors.blue} /> : null}</Pressable>)}</View></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1 }, header: { minHeight: 62, flexDirection: "row", alignItems: "center", borderBottomWidth: StyleSheet.hairlineWidth }, touch: { width: 52, height: 52, alignItems: "center", justifyContent: "center" }, title: { flex: 1, textAlign: "center", fontSize: 22, fontWeight: "800" }, content: { padding: 18, gap: 12 }, section: { fontSize: 16, fontWeight: "800", marginTop: 8 }, card: { borderWidth: 1, borderRadius: 14, overflow: "hidden" }, row: { minHeight: 58, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", gap: 12, borderBottomWidth: StyleSheet.hairlineWidth }, rowText: { flex: 1, fontWeight: "700" }, error: { color: "#D92D20" } });
