import { mobileLocaleCodes, type MobileLocale } from "./mobileLocalizationCatalog";
import { securityCopy, type SecurityCopy } from "../features/profile/securityLocalization";
import { localizedSecurityCopy } from "../features/profile/securityTranslationCorrections";

type SessionCopy = Pick<SecurityCopy, "manageSession" | "removeSession" | "noActiveSessions" | "noActiveSessionsHelp" | "kurioticketApp" | "iphone" | "android" | "removeTitle" | "removeBody" | "removeFailed">;

const activeSessionCorrections: Partial<Record<MobileLocale, SessionCopy>> = {
  fr: { manageSession:"Gérer la session", removeSession:"Supprimer la session", noActiveSessions:"Aucune session active", noActiveSessionsHelp:"Aucun appareil n’est actuellement connecté à votre compte.", kurioticketApp:"Application Kurioticket", iphone:"iPhone", android:"Android", removeTitle:"Supprimer cette session ?", removeBody:"Cet appareil sera déconnecté de votre compte Kurioticket.", removeFailed:"Impossible de supprimer cette session." },
  "de-de": { manageSession:"Sitzung verwalten", removeSession:"Sitzung entfernen", noActiveSessions:"Keine aktiven Sitzungen", noActiveSessionsHelp:"Derzeit ist kein Gerät bei Ihrem Konto angemeldet.", kurioticketApp:"Kurioticket-App", iphone:"iPhone", android:"Android", removeTitle:"Diese Sitzung entfernen?", removeBody:"Dieses Gerät wird von Ihrem Kurioticket-Konto abgemeldet.", removeFailed:"Diese Sitzung konnte nicht entfernt werden." },
  "it-it": { manageSession:"Gestisci sessione", removeSession:"Rimuovi sessione", noActiveSessions:"Nessuna sessione attiva", noActiveSessionsHelp:"Nessun dispositivo ha attualmente effettuato l’accesso al tuo account.", kurioticketApp:"App Kurioticket", iphone:"iPhone", android:"Android", removeTitle:"Rimuovere questa sessione?", removeBody:"Questo dispositivo verrà disconnesso dal tuo account Kurioticket.", removeFailed:"Impossibile rimuovere questa sessione." },
  "pt-br": { manageSession:"Gerenciar sessão", removeSession:"Remover sessão", noActiveSessions:"Nenhuma sessão ativa", noActiveSessionsHelp:"Nenhum dispositivo está conectado à sua conta no momento.", kurioticketApp:"App Kurioticket", iphone:"iPhone", android:"Android", removeTitle:"Remover esta sessão?", removeBody:"Este dispositivo será desconectado da sua conta Kurioticket.", removeFailed:"Não foi possível remover esta sessão." },
  nl: { manageSession:"Sessie beheren", removeSession:"Sessie verwijderen", noActiveSessions:"Geen actieve sessies", noActiveSessionsHelp:"Er zijn momenteel geen apparaten aangemeld bij je account.", kurioticketApp:"Kurioticket-app", iphone:"iPhone", android:"Android", removeTitle:"Deze sessie verwijderen?", removeBody:"Dit apparaat wordt afgemeld bij je Kurioticket-account.", removeFailed:"Deze sessie kon niet worden verwijderd." },
  ar: { manageSession:"إدارة الجلسة", removeSession:"إزالة الجلسة", noActiveSessions:"لا توجد جلسات نشطة", noActiveSessionsHelp:"لا توجد أجهزة مسجّلة الدخول إلى حسابك حاليًا.", kurioticketApp:"تطبيق Kurioticket", iphone:"iPhone", android:"Android", removeTitle:"إزالة هذه الجلسة؟", removeBody:"سيتم تسجيل خروج هذا الجهاز من حساب Kurioticket الخاص بك.", removeFailed:"تعذرت إزالة هذه الجلسة." },
  "zh-cn": { manageSession:"管理会话", removeSession:"移除会话", noActiveSessions:"没有活动会话", noActiveSessionsHelp:"目前没有设备登录你的账户。", kurioticketApp:"Kurioticket 应用", iphone:"iPhone", android:"Android", removeTitle:"移除此会话？", removeBody:"此设备将从你的 Kurioticket 账户退出登录。", removeFailed:"无法移除此会话。" },
  ja: { manageSession:"セッションを管理", removeSession:"セッションを削除", noActiveSessions:"アクティブなセッションはありません", noActiveSessionsHelp:"現在、アカウントにサインインしているデバイスはありません。", kurioticketApp:"Kurioticketアプリ", iphone:"iPhone", android:"Android", removeTitle:"このセッションを削除しますか？", removeBody:"このデバイスはKurioticketアカウントからサインアウトされます。", removeFailed:"このセッションを削除できませんでした。" },
  ko: { manageSession:"세션 관리", removeSession:"세션 제거", noActiveSessions:"활성 세션 없음", noActiveSessionsHelp:"현재 계정에 로그인된 기기가 없습니다.", kurioticketApp:"Kurioticket 앱", iphone:"iPhone", android:"Android", removeTitle:"이 세션을 제거할까요?", removeBody:"이 기기가 Kurioticket 계정에서 로그아웃됩니다.", removeFailed:"이 세션을 제거할 수 없습니다." },
  hi: { manageSession:"सत्र प्रबंधित करें", removeSession:"सत्र हटाएँ", noActiveSessions:"कोई सक्रिय सत्र नहीं", noActiveSessionsHelp:"फ़िलहाल आपके खाते में कोई डिवाइस साइन इन नहीं है।", kurioticketApp:"Kurioticket ऐप", iphone:"iPhone", android:"Android", removeTitle:"यह सत्र हटाएँ?", removeBody:"इस डिवाइस को आपके Kurioticket खाते से साइन आउट कर दिया जाएगा।", removeFailed:"यह सत्र हटाया नहीं जा सका।" },
  tr: { manageSession:"Oturumu yönet", removeSession:"Oturumu kaldır", noActiveSessions:"Etkin oturum yok", noActiveSessionsHelp:"Şu anda hesabınızda oturum açmış bir cihaz yok.", kurioticketApp:"Kurioticket uygulaması", iphone:"iPhone", android:"Android", removeTitle:"Bu oturum kaldırılsın mı?", removeBody:"Bu cihaz Kurioticket hesabınızdan çıkarılacak.", removeFailed:"Bu oturum kaldırılamadı." },
  pl: { manageSession:"Zarządzaj sesją", removeSession:"Usuń sesję", noActiveSessions:"Brak aktywnych sesji", noActiveSessionsHelp:"Obecnie żadne urządzenie nie jest zalogowane na Twoim koncie.", kurioticketApp:"Aplikacja Kurioticket", iphone:"iPhone", android:"Android", removeTitle:"Usunąć tę sesję?", removeBody:"To urządzenie zostanie wylogowane z Twojego konta Kurioticket.", removeFailed:"Nie udało się usunąć tej sesji." },
  sv: { manageSession:"Hantera session", removeSession:"Ta bort session", noActiveSessions:"Inga aktiva sessioner", noActiveSessionsHelp:"Inga enheter är för närvarande inloggade på ditt konto.", kurioticketApp:"Kurioticket-appen", iphone:"iPhone", android:"Android", removeTitle:"Ta bort den här sessionen?", removeBody:"Den här enheten loggas ut från ditt Kurioticket-konto.", removeFailed:"Det gick inte att ta bort den här sessionen." },
  id: { manageSession:"Kelola sesi", removeSession:"Hapus sesi", noActiveSessions:"Tidak ada sesi aktif", noActiveSessionsHelp:"Saat ini tidak ada perangkat yang masuk ke akun Anda.", kurioticketApp:"Aplikasi Kurioticket", iphone:"iPhone", android:"Android", removeTitle:"Hapus sesi ini?", removeBody:"Perangkat ini akan dikeluarkan dari akun Kurioticket Anda.", removeFailed:"Sesi ini tidak dapat dihapus." },
  th: { manageSession:"จัดการเซสชัน", removeSession:"นำเซสชันออก", noActiveSessions:"ไม่มีเซสชันที่ใช้งานอยู่", noActiveSessionsHelp:"ขณะนี้ไม่มีอุปกรณ์ที่เข้าสู่ระบบบัญชีของคุณ", kurioticketApp:"แอป Kurioticket", iphone:"iPhone", android:"Android", removeTitle:"นำเซสชันนี้ออกหรือไม่?", removeBody:"อุปกรณ์นี้จะถูกออกจากระบบบัญชี Kurioticket ของคุณ", removeFailed:"ไม่สามารถนำเซสชันนี้ออกได้" },
  vi: { manageSession:"Quản lý phiên", removeSession:"Xóa phiên", noActiveSessions:"Không có phiên hoạt động", noActiveSessionsHelp:"Hiện không có thiết bị nào đăng nhập vào tài khoản của bạn.", kurioticketApp:"Ứng dụng Kurioticket", iphone:"iPhone", android:"Android", removeTitle:"Xóa phiên này?", removeBody:"Thiết bị này sẽ được đăng xuất khỏi tài khoản Kurioticket của bạn.", removeFailed:"Không thể xóa phiên này." },
};

for (const locale of mobileLocaleCodes) {
  Object.assign(securityCopy[locale], localizedSecurityCopy(locale, securityCopy[locale]), activeSessionCorrections[locale]);
}
