import type { MobileLocale } from "./mobileLocalizationCatalog";

export const travelAccountMessageKeys = ["hotelAlertTitle", "hotelAlertBody", "hotelAlertUnavailable", "targetTotal", "createAlert", "creating", "signInRequired", "signInAlertBody", "savePackageSearch", "packageSaved", "packageSaveError"] as const;
export type TravelAccountMessageKey = typeof travelAccountMessageKeys[number];
type Dictionary = Record<TravelAccountMessageKey, string>;

export const travelAccountMessages: Record<MobileLocale, Dictionary> = {
  "en-us": { hotelAlertTitle:"Track this stay price",hotelAlertBody:"Get notified when this complete stay search reaches your target total.",hotelAlertUnavailable:"A comparable hotel result price is required.",targetTotal:"Target total",createAlert:"Create price alert",creating:"Creating…",signInRequired:"Sign in required",signInAlertBody:"Sign in to track prices for this search.",savePackageSearch:"Save package search",packageSaved:"Package search saved.",packageSaveError:"Sign in to save this package search." },
  "es-es": { hotelAlertTitle:"Seguir el precio de esta estancia",hotelAlertBody:"Recibe un aviso cuando esta búsqueda completa alcance tu objetivo.",hotelAlertUnavailable:"Se necesita un precio de hotel comparable.",targetTotal:"Total objetivo",createAlert:"Crear alerta",creating:"Creando…",signInRequired:"Inicio de sesión requerido",signInAlertBody:"Inicia sesión para seguir los precios de esta búsqueda.",savePackageSearch:"Guardar búsqueda de paquete",packageSaved:"Búsqueda de paquete guardada.",packageSaveError:"Inicia sesión para guardar esta búsqueda." },
  fr: { hotelAlertTitle:"Suivre le prix de ce séjour",hotelAlertBody:"Soyez averti lorsque cette recherche complète atteint votre objectif.",hotelAlertUnavailable:"Un prix d’hôtel comparable est requis.",targetTotal:"Total cible",createAlert:"Créer l’alerte",creating:"Création…",signInRequired:"Connexion requise",signInAlertBody:"Connectez-vous pour suivre les prix de cette recherche.",savePackageSearch:"Enregistrer la recherche de forfait",packageSaved:"Recherche de forfait enregistrée.",packageSaveError:"Connectez-vous pour enregistrer cette recherche." },
  "de-de": { hotelAlertTitle:"Preis dieses Aufenthalts verfolgen",hotelAlertBody:"Benachrichtigung, wenn diese vollständige Suche den Zielpreis erreicht.",hotelAlertUnavailable:"Ein vergleichbarer Hotelpreis ist erforderlich.",targetTotal:"Zielgesamtpreis",createAlert:"Alarm erstellen",creating:"Wird erstellt…",signInRequired:"Anmeldung erforderlich",signInAlertBody:"Melde dich an, um Preise für diese Suche zu verfolgen.",savePackageSearch:"Paketsuche speichern",packageSaved:"Paketsuche gespeichert.",packageSaveError:"Melde dich an, um diese Suche zu speichern." },
  "it-it": { hotelAlertTitle:"Segui il prezzo del soggiorno",hotelAlertBody:"Ricevi un avviso quando questa ricerca completa raggiunge il tuo obiettivo.",hotelAlertUnavailable:"È necessario un prezzo hotel confrontabile.",targetTotal:"Totale obiettivo",createAlert:"Crea avviso",creating:"Creazione…",signInRequired:"Accesso richiesto",signInAlertBody:"Accedi per seguire i prezzi di questa ricerca.",savePackageSearch:"Salva ricerca pacchetto",packageSaved:"Ricerca pacchetto salvata.",packageSaveError:"Accedi per salvare questa ricerca." },
  "pt-br": { hotelAlertTitle:"Acompanhar o preço desta estadia",hotelAlertBody:"Receba um aviso quando esta busca completa atingir sua meta.",hotelAlertUnavailable:"É necessário um preço de hotel comparável.",targetTotal:"Total desejado",createAlert:"Criar alerta",creating:"Criando…",signInRequired:"Login necessário",signInAlertBody:"Entre para acompanhar os preços desta busca.",savePackageSearch:"Salvar busca de pacote",packageSaved:"Busca de pacote salva.",packageSaveError:"Entre para salvar esta busca." },
  nl: { hotelAlertTitle:"Prijs van dit verblijf volgen",hotelAlertBody:"Ontvang bericht wanneer deze volledige zoekopdracht je doel bereikt.",hotelAlertUnavailable:"Een vergelijkbare hotelprijs is vereist.",targetTotal:"Doeltotaal",createAlert:"Melding maken",creating:"Maken…",signInRequired:"Inloggen vereist",signInAlertBody:"Log in om prijzen voor deze zoekopdracht te volgen.",savePackageSearch:"Pakketzoekopdracht opslaan",packageSaved:"Pakketzoekopdracht opgeslagen.",packageSaveError:"Log in om deze zoekopdracht op te slaan." },
  ar: { hotelAlertTitle:"تتبّع سعر هذه الإقامة",hotelAlertBody:"احصل على إشعار عندما يصل هذا البحث الكامل إلى السعر المستهدف.",hotelAlertUnavailable:"يلزم توفر سعر فندق قابل للمقارنة.",targetTotal:"الإجمالي المستهدف",createAlert:"إنشاء تنبيه",creating:"جارٍ الإنشاء…",signInRequired:"يلزم تسجيل الدخول",signInAlertBody:"سجّل الدخول لتتبّع أسعار هذا البحث.",savePackageSearch:"حفظ بحث الباقة",packageSaved:"تم حفظ بحث الباقة.",packageSaveError:"سجّل الدخول لحفظ هذا البحث." },
  "zh-cn": { hotelAlertTitle:"跟踪此次住宿价格",hotelAlertBody:"当此完整搜索达到目标价格时接收通知。",hotelAlertUnavailable:"需要可比较的酒店价格。",targetTotal:"目标总价",createAlert:"创建提醒",creating:"正在创建…",signInRequired:"需要登录",signInAlertBody:"登录后可跟踪此次搜索的价格。",savePackageSearch:"保存套餐搜索",packageSaved:"套餐搜索已保存。",packageSaveError:"登录后可保存此次搜索。" },
  ja: { hotelAlertTitle:"この宿泊料金を追跡",hotelAlertBody:"この検索が目標料金に達したら通知します。",hotelAlertUnavailable:"比較可能なホテル料金が必要です。",targetTotal:"目標合計",createAlert:"アラートを作成",creating:"作成中…",signInRequired:"ログインが必要です",signInAlertBody:"この検索の料金を追跡するにはログインしてください。",savePackageSearch:"パッケージ検索を保存",packageSaved:"パッケージ検索を保存しました。",packageSaveError:"この検索を保存するにはログインしてください。" },
  ko: { hotelAlertTitle:"이 숙박 가격 추적",hotelAlertBody:"이 전체 검색이 목표 가격에 도달하면 알려드립니다.",hotelAlertUnavailable:"비교 가능한 호텔 가격이 필요합니다.",targetTotal:"목표 총액",createAlert:"알림 만들기",creating:"만드는 중…",signInRequired:"로그인 필요",signInAlertBody:"이 검색의 가격을 추적하려면 로그인하세요.",savePackageSearch:"패키지 검색 저장",packageSaved:"패키지 검색을 저장했습니다.",packageSaveError:"이 검색을 저장하려면 로그인하세요." },
  hi: { hotelAlertTitle:"इस ठहराव की कीमत ट्रैक करें",hotelAlertBody:"यह पूरी खोज लक्ष्य तक पहुँचे तो सूचना पाएँ।",hotelAlertUnavailable:"तुलना योग्य होटल कीमत आवश्यक है।",targetTotal:"लक्ष्य कुल",createAlert:"अलर्ट बनाएँ",creating:"बन रहा है…",signInRequired:"साइन इन आवश्यक",signInAlertBody:"इस खोज की कीमत ट्रैक करने के लिए साइन इन करें।",savePackageSearch:"पैकेज खोज सहेजें",packageSaved:"पैकेज खोज सहेजी गई।",packageSaveError:"यह खोज सहेजने के लिए साइन इन करें।" },
  tr: { hotelAlertTitle:"Bu konaklama fiyatını takip et",hotelAlertBody:"Bu tam arama hedefinize ulaştığında bildirim alın.",hotelAlertUnavailable:"Karşılaştırılabilir bir otel fiyatı gereklidir.",targetTotal:"Hedef toplam",createAlert:"Uyarı oluştur",creating:"Oluşturuluyor…",signInRequired:"Giriş gerekli",signInAlertBody:"Bu aramanın fiyatlarını takip etmek için giriş yapın.",savePackageSearch:"Paket aramasını kaydet",packageSaved:"Paket araması kaydedildi.",packageSaveError:"Bu aramayı kaydetmek için giriş yapın." },
  pl: { hotelAlertTitle:"Śledź cenę tego pobytu",hotelAlertBody:"Otrzymaj powiadomienie, gdy pełne wyszukiwanie osiągnie cel.",hotelAlertUnavailable:"Wymagana jest porównywalna cena hotelu.",targetTotal:"Suma docelowa",createAlert:"Utwórz alert",creating:"Tworzenie…",signInRequired:"Wymagane logowanie",signInAlertBody:"Zaloguj się, aby śledzić ceny tego wyszukiwania.",savePackageSearch:"Zapisz wyszukiwanie pakietu",packageSaved:"Wyszukiwanie pakietu zapisane.",packageSaveError:"Zaloguj się, aby zapisać to wyszukiwanie." },
  sv: { hotelAlertTitle:"Följ priset för vistelsen",hotelAlertBody:"Få ett meddelande när den fullständiga sökningen når ditt mål.",hotelAlertUnavailable:"Ett jämförbart hotellpris krävs.",targetTotal:"Måltotal",createAlert:"Skapa avisering",creating:"Skapar…",signInRequired:"Inloggning krävs",signInAlertBody:"Logga in för att följa priser för sökningen.",savePackageSearch:"Spara paketsökning",packageSaved:"Paketsökningen sparades.",packageSaveError:"Logga in för att spara sökningen." },
  id: { hotelAlertTitle:"Pantau harga menginap ini",hotelAlertBody:"Dapatkan notifikasi saat pencarian lengkap ini mencapai target.",hotelAlertUnavailable:"Diperlukan harga hotel yang dapat dibandingkan.",targetTotal:"Total target",createAlert:"Buat peringatan",creating:"Membuat…",signInRequired:"Harus masuk",signInAlertBody:"Masuk untuk memantau harga pencarian ini.",savePackageSearch:"Simpan pencarian paket",packageSaved:"Pencarian paket disimpan.",packageSaveError:"Masuk untuk menyimpan pencarian ini." },
  th: { hotelAlertTitle:"ติดตามราคาที่พักนี้",hotelAlertBody:"รับการแจ้งเตือนเมื่อการค้นหาที่ครบถ้วนถึงราคาเป้าหมาย",hotelAlertUnavailable:"ต้องมีราคาโรงแรมที่เปรียบเทียบได้",targetTotal:"ยอดรวมเป้าหมาย",createAlert:"สร้างการแจ้งเตือน",creating:"กำลังสร้าง…",signInRequired:"ต้องเข้าสู่ระบบ",signInAlertBody:"เข้าสู่ระบบเพื่อติดตามราคาของการค้นหานี้",savePackageSearch:"บันทึกการค้นหาแพ็กเกจ",packageSaved:"บันทึกการค้นหาแพ็กเกจแล้ว",packageSaveError:"เข้าสู่ระบบเพื่อบันทึกการค้นหานี้" },
  vi: { hotelAlertTitle:"Theo dõi giá kỳ nghỉ này",hotelAlertBody:"Nhận thông báo khi tìm kiếm đầy đủ này đạt mục tiêu.",hotelAlertUnavailable:"Cần có giá khách sạn có thể so sánh.",targetTotal:"Tổng mục tiêu",createAlert:"Tạo cảnh báo",creating:"Đang tạo…",signInRequired:"Cần đăng nhập",signInAlertBody:"Đăng nhập để theo dõi giá cho tìm kiếm này.",savePackageSearch:"Lưu tìm kiếm gói",packageSaved:"Đã lưu tìm kiếm gói.",packageSaveError:"Đăng nhập để lưu tìm kiếm này." },
};

export function travelAccountMessage(locale: MobileLocale, key: TravelAccountMessageKey) { return travelAccountMessages[locale][key]; }
