import type { ExploreDestinationEditorial, ExploreDestinationEditorialSourceReference } from "./types";

const makeSourceReferences = (lastVerifiedAt: string) =>
  (references: readonly ExploreDestinationEditorialSourceReference[]) => ({
    source: "kurioticket-editorial" as const, sourceReferences: references, lastVerifiedAt,
  });
const africaBatch1SourceReferences = makeSourceReferences("2026-08-10");
const africaBatch2SourceReferences = makeSourceReferences("2026-08-10");
const africaBatch3SourceReferences = makeSourceReferences("2026-08-10");
const africaBatch4SourceReferences = makeSourceReferences("2026-08-10");
const africaBatch5SourceReferences = makeSourceReferences("2026-08-10");
const africaBatch6SourceReferences = makeSourceReferences("2026-08-10");
const finalAfricaBatchSourceReferences = makeSourceReferences("2026-08-10");

export const africaExploreDestinationEditorial = [
  {
    id: "et-addis-ababa",
    summary: "Addis Ababa occupies a highland plateau, with national museums, historic churches, markets and Entoto foothills.",
    description: "Addis Ababa spreads across a high plateau beneath the Entoto hills, where eucalyptus woodland borders the northern city. The National Museum and Ethnological Museum interpret Ethiopian archaeology, art and cultural traditions, while Holy Trinity Cathedral records twentieth-century religious and national history. Merkato's trading streets and the Piazza district reflect the capital's commercial growth and varied urban fabric.",
    highlights: ["Entoto hill landscape", "National Museum of Ethiopia", "Holy Trinity Cathedral", "Merkato trading district"],
    editorialProvenance: africaBatch1SourceReferences([{ title: "Visit Ethiopia - Addis Ababa", url: "https://visitethiopia.et/destinations/addis-ababa/" }, { title: "Addis Ababa City Administration", url: "https://addisababa.gov.et/" }]),
  },
  {
    id: "ke-mombasa",
    summary: "Mombasa occupies a coral island and mainland coast shaped by Swahili heritage, trade and beaches.",
    description: "Mombasa's historic centre occupies an island beside the Indian Ocean, linked to mainland districts and a long trading coastline. UNESCO-listed Fort Jesus records Portuguese presence and later contests over the port, while Old Town retains narrow streets, carved doors and Swahili architecture. Markets, mosques and coastal food traditions reflect exchanges among African, Arab, Asian and European communities.",
    highlights: ["Fort Jesus", "Old Town Swahili architecture", "Mombasa Island waterfront", "Coastal markets and food traditions"],
    editorialProvenance: africaBatch1SourceReferences([{ title: "National Museums of Kenya - Fort Jesus", url: "https://museums.or.ke/fort-jesus/" }, { title: "UNESCO Fort Jesus, Mombasa", url: "https://whc.unesco.org/en/list/1295/" }]),
  },
  {
    id: "tz-dar-es-salaam",
    summary: "Dar es Salaam extends along the Indian Ocean through historic civic quarters, markets and coastal reserves.",
    description: "Dar es Salaam lies around a natural harbour on Tanzania's Indian Ocean coast, with a centre shaped by maritime trade and colonial administration. The National Museum presents archaeological and historical collections, while the open-air Village Museum documents building traditions from across Tanzania. Kariakoo Market, waterfront civic buildings and nearby marine reserves place commerce, architecture and coastal ecology within the city's setting.",
    highlights: ["Indian Ocean harbour", "National Museum of Tanzania", "Village Museum homesteads", "Kariakoo Market"],
    editorialProvenance: africaBatch1SourceReferences([{ title: "Tanzania Tourism - Dar es Salaam", url: "https://www.tanzaniatourism.go.tz/destination/dar-es-salaam" }, { title: "National Museum of Tanzania", url: "https://www.nmt.go.tz/" }]),
  },
  {
    id: "tz-zanzibar",
    summary: "Zanzibar encompasses an Indian Ocean archipelago where Swahili culture, spice farming and coral-stone heritage meet.",
    description: "Zanzibar is an Indian Ocean archipelago whose largest islands are Unguja and Pemba; the canonical destination refers to this wider island setting. Stone Town, the historic quarter of Zanzibar City on Unguja, preserves coral-stone buildings shaped by African, Arab, Indian and European exchange. Spice-growing areas, fishing communities and coastal forests provide further context beyond the urban heritage site.",
    highlights: ["Stone Town of Zanzibar", "Unguja and Pemba islands", "Spice-growing landscapes", "Jozani coastal forest"],
    editorialProvenance: africaBatch1SourceReferences([{ title: "Zanzibar Commission for Tourism", url: "https://zanzibartourism.go.tz/" }, { title: "UNESCO Stone Town of Zanzibar", url: "https://whc.unesco.org/en/list/173/" }]),
  },
  {
    id: "ug-entebbe",
    summary: "Entebbe occupies a Lake Victoria peninsula with botanical collections, wildlife conservation and lakeshore landscapes.",
    description: "Entebbe extends along a peninsula on Lake Victoria, giving the town wooded shores and a close relationship with the lake. The National Botanical Gardens conserve tropical plants and bird habitat, while the Uganda Wildlife Conservation Education Centre cares for native wildlife and supports conservation education. Older administrative buildings and lakeside streets reflect Entebbe's distinct civic history apart from Kampala.",
    highlights: ["Lake Victoria peninsula", "National Botanical Gardens", "Uganda Wildlife Conservation Education Centre", "Lakeside administrative heritage"],
    editorialProvenance: africaBatch1SourceReferences([{ title: "Uganda Wildlife Conservation Education Centre", url: "https://uwec.ug/" }, { title: "National Agricultural Research Organisation", url: "https://www.naro.go.ug/" }]),
  },
  {
    id: "rw-kigali",
    summary: "Kigali spreads across green hills, linking memorial sites, museums, markets and evolving neighbourhood arts districts.",
    description: "Kigali is arranged across ridges and valleys, with neighbourhoods extending over the hilly landscape of Rwanda's capital. The Kigali Genocide Memorial documents the 1994 genocide against the Tutsi through remembrance, archives and education, while the Rwanda Art Museum presents national visual culture. Kimironko Market, Nyamirambo streets and local craft centres illustrate everyday commerce and creative life.",
    highlights: ["Kigali Genocide Memorial", "Rwanda Art Museum", "Kimironko Market", "Nyamirambo neighbourhood"],
    editorialProvenance: africaBatch1SourceReferences([{ title: "Visit Rwanda - Kigali", url: "https://www.visitrwanda.com/destinations/kigali/" }, { title: "Kigali Genocide Memorial", url: "https://kgm.rw/" }]),
  },
  {
    id: "mg-antananarivo",
    summary: "Antananarivo rises across highland ridges, marked by royal heritage, brick neighbourhoods, markets and urban wetlands.",
    description: "Antananarivo occupies steep ridges in Madagascar's central highlands, with stairways and brick houses following the slopes. The Upper Town contains the Rova royal complex, Andafiavaratra Palace and historic churches associated with the Merina kingdom and later state history. Analakely Market, Lake Anosy and the Tsimbazaza museum and botanical grounds add commercial, civic and natural-history perspectives within the capital.",
    highlights: ["Rova of Antananarivo", "Upper Town brick architecture", "Analakely Market", "Lake Anosy"],
    editorialProvenance: africaBatch1SourceReferences([{ title: "UNESCO Upper Town of Antananarivo", url: "https://whc.unesco.org/en/tentativelists/6078/" }, { title: "Madagascar National Tourism Board", url: "https://madagascar-tourisme.com/en/" }]),
  },
  {
    id: "sc-mahe",
    summary: "Mahé is Seychelles' largest island, defined by granitic peaks, forest reserves, beaches and Creole heritage.",
    description: "Mahé is a mountainous granitic island whose forested interior rises above narrow coastal settlements and beaches. Morne Seychellois National Park protects the island's highest landscapes and endemic habitats, while Beau Vallon and southern coves show contrasting shorelines. Victoria, situated on Mahé, contributes markets, museums and Creole civic heritage without defining the whole island destination.",
    highlights: ["Morne Seychellois National Park", "Beau Vallon coastline", "Granitic mountain landscape", "Victoria's Creole market heritage"],
    editorialProvenance: africaBatch1SourceReferences([{ title: "Tourism Seychelles - Mahé", url: "https://www.seychelles.com/destination/mahe" }, { title: "Seychelles Parks and Gardens Authority", url: "https://www.spga.gov.sc/" }]),
  },
  {
    id: "mu-mauritius",
    summary: "Mauritius is a volcanic Indian Ocean island with multicultural heritage, forested uplands and coral-fringed coasts.",
    description: "Mauritius is considered at country and island scale, from coral-fringed shores to a volcanic interior of plateaus, gorges and forest. UNESCO sites at Aapravasi Ghat and Le Morne Cultural Landscape preserve histories of indentured labour, slavery and resistance. Markets, religious places, Creole traditions and protected landscapes reflect the island's African, Asian and European cultural connections.",
    highlights: ["Le Morne Cultural Landscape", "Aapravasi Ghat", "Black River Gorges", "Multicultural market and food traditions"],
    editorialProvenance: africaBatch1SourceReferences([{ title: "Mauritius Tourism Promotion Authority", url: "https://mauritiusnow.com/" }, { title: "UNESCO Aapravasi Ghat", url: "https://whc.unesco.org/en/list/1227/" }, { title: "UNESCO Le Morne Cultural Landscape", url: "https://whc.unesco.org/en/list/1259/" }]),
  },
  {
    id: "re-saint-denis",
    summary: "Saint-Denis frames Réunion's northern coast with Creole architecture, civic gardens, museums and mountain backdrops.",
    description: "Saint-Denis stands on Réunion's northern coast between the Indian Ocean and steep volcanic uplands. Rue de Paris is lined with Creole houses and civic buildings, including Villa Déramond-Barre and the former bishop's palace, while the Jardin de l'État anchors a historic public garden. The Léon Dierx Museum, markets and seafront trace the city's artistic, commercial and colonial layers.",
    highlights: ["Rue de Paris Creole houses", "Jardin de l'État", "Léon Dierx Museum", "Barachois seafront"],
    editorialProvenance: africaBatch1SourceReferences([{ title: "Île de La Réunion Tourisme - Saint-Denis", url: "https://en.reunion.fr/organize/towns-and-villages/saint-denis/" }, { title: "Musée Léon Dierx", url: "https://museesreunion.fr/musee-leon-dierx/" }]),
  },
  {
    id: "dz-algiers",
    summary: "Algiers rises above the Mediterranean through white hillside quarters, Ottoman heritage and a historic casbah.",
    description: "Algiers extends in tiers above a Mediterranean bay, with white buildings giving the capital its long-established visual identity. The UNESCO-listed Casbah preserves a dense historic urban fabric of lanes, houses, mosques and Ottoman palaces descending toward the waterfront. Within its lower edge, the restored Palais des Raïs complex documents domestic architecture and the city's maritime connections.",
    highlights: ["Casbah of Algiers", "Palais des Raïs", "Ottoman palaces and mosques", "Mediterranean hillside quarters"],
    editorialProvenance: africaBatch2SourceReferences([{ title: "UNESCO - Kasbah of Algiers", url: "https://whc.unesco.org/en/list/565/" }, { title: "Palais des Raïs - Bastion 23", url: "https://www.musee-palaisdesrais-bastion23.dz/" }]),
  },
  {
    id: "ma-casablanca",
    summary: "Casablanca faces the Atlantic with twentieth-century boulevards, Art Deco architecture and a working waterfront.",
    description: "Casablanca developed around its Atlantic port, and broad central avenues record the city's rapid twentieth-century expansion. Art Deco and neo-Moorish buildings shape districts around Mohammed V Square, while the older medina retains a tighter street pattern beside the harbour. The Hassan II Mosque stands partly above the ocean, linking monumental Moroccan craftsmanship with the city's coastal setting.",
    highlights: ["Hassan II Mosque", "Mohammed V Square", "Art Deco city centre", "Old medina and Atlantic port"],
    editorialProvenance: africaBatch2SourceReferences([{ title: "Visit Casablanca", url: "https://visitcasablanca.ma/" }, { title: "Hassan II Mosque Foundation", url: "https://www.fmh2.ma/" }]),
  },
  {
    id: "eg-sharm-el-sheikh",
    summary: "Sharm El Sheikh occupies southern Sinai between Red Sea reefs, desert mountains and protected coastal landscapes.",
    description: "Sharm El Sheikh lies at the southern end of the Sinai Peninsula, where arid mountains meet the gulfs of Aqaba and Suez. Coral reefs and clear Red Sea waters define its coastal landscape and marine habitats. South of the city, Ras Mohammed National Park protects reef, mangrove, desert and shoreline environments around the peninsula's southernmost headland.",
    highlights: ["Ras Mohammed National Park", "Red Sea coral reefs", "Southern Sinai mountains", "Gulfs of Aqaba and Suez"],
    editorialProvenance: africaBatch2SourceReferences([{ title: "Experience Egypt - Sharm El Sheikh", url: "https://www.experienceegypt.eg/en/city/13/sharm-el-sheikh" }, { title: "UNESCO - Ras Mohammed", url: "https://whc.unesco.org/en/tentativelists/182/" }]),
  },
  {
    id: "tn-tunis",
    summary: "Tunis centres on a historic medina framed by later boulevards, civic architecture and longstanding craft traditions.",
    description: "Tunis grew from its medina toward a later European-planned quarter, creating contrasting street patterns around the capital's centre. UNESCO recognises the medina for its mosques, madrasas, palaces, houses and souks, with the Zitouna Mosque anchoring its historic fabric. Beyond the old city, Avenue Habib Bourguiba and the Bardo Museum add civic architecture and archaeological collections to the urban context.",
    highlights: ["Medina of Tunis", "Zitouna Mosque", "Avenue Habib Bourguiba", "Bardo Museum collections"],
    editorialProvenance: africaBatch2SourceReferences([{ title: "UNESCO - Medina of Tunis", url: "https://whc.unesco.org/en/list/36/" }, { title: "Discover Tunisia - Tunis and its surroundings", url: "https://www.discovertunisia.com/en/discover/around-tunis" }]),
  },
  {
    id: "za-durban",
    summary: "Durban follows the Indian Ocean through subtropical gardens, beaches, markets and layered port-city heritage.",
    description: "Durban extends around a major Indian Ocean harbour, with the beachfront and central districts reflecting its maritime setting. The Durban Botanic Gardens preserves subtropical plant collections in a historic civic landscape, while markets and museums document Zulu, Indian and colonial influences. Art Deco buildings, harbour views and the KwaMuhle Museum add architectural and social-history context within the city.",
    highlights: ["Indian Ocean beachfront", "Durban Botanic Gardens", "KwaMuhle Museum", "Victoria Street Market"],
    editorialProvenance: africaBatch3SourceReferences([{ title: "Durban Tourism", url: "https://visitdurban.travel/" }, { title: "Durban Botanic Gardens", url: "https://durbanbotanicgardens.org.za/" }]),
  },
  {
    id: "bw-gaborone",
    summary: "Gaborone combines a planned capital centre, cultural collections, public monuments and nearby hill landscapes.",
    description: "Gaborone developed as Botswana's capital beside the Notwane River, with broad roads and government precincts shaping its urban plan. The National Museum and Art Gallery interprets archaeology, ethnography and visual culture, while the Three Dikgosi Monument commemorates a defining episode in national history. Kgale Hill and the Gaborone Dam place rocky terrain and water landscapes close to the city.",
    highlights: ["National Museum and Art Gallery", "Three Dikgosi Monument", "Kgale Hill", "Gaborone Dam"],
    editorialProvenance: africaBatch3SourceReferences([{ title: "Botswana Tourism Organisation", url: "https://www.botswanatourism.co.bw/" }, { title: "Botswana Government - National Museum and Art Gallery", url: "https://www.gov.bw/ministries/national-museum-and-art-gallery" }]),
  },
  {
    id: "zw-harare",
    summary: "Harare spreads across a highveld setting with galleries, archives, civic gardens and modern urban architecture.",
    description: "Harare occupies Zimbabwe's highveld, where broad avenues and jacaranda-lined streets frame its central civic districts. The National Gallery of Zimbabwe presents local and regional visual art, while the National Archives preserves documentary records, photographs and historical collections. Harare Gardens, the Kopje and early twentieth-century buildings provide further perspectives on the capital's landscape and urban development.",
    highlights: ["National Gallery of Zimbabwe", "National Archives collections", "Harare Gardens", "The Kopje"],
    editorialProvenance: africaBatch3SourceReferences([{ title: "National Gallery of Zimbabwe", url: "https://nationalgallery.co.zw/" }, { title: "National Archives of Zimbabwe", url: "https://www.archives.gov.zw/" }]),
  },
  {
    id: "zm-lusaka",
    summary: "Lusaka is a plateau capital shaped by civic institutions, markets, museums and urban nature reserves.",
    description: "Lusaka stands on a broad plateau, with government avenues, commercial districts and residential neighbourhoods forming Zambia's capital. The Lusaka National Museum presents archaeology, ethnography, history and contemporary art, while Kabwata Cultural Village supports craft traditions in an urban setting. Markets and the nearby Munda Wanga environmental park add everyday commercial life and conservation context to the city.",
    highlights: ["Lusaka National Museum", "Kabwata Cultural Village", "City Market", "Munda Wanga environmental park"],
    editorialProvenance: africaBatch3SourceReferences([{ title: "National Museums Board of Zambia", url: "https://www.museumszambia.org/" }, { title: "Zambia Ministry of Tourism", url: "https://www.mot.gov.zm/" }]),
  },
  {
    id: "mz-maputo",
    summary: "Maputo faces its bay through railway heritage, markets, tropical avenues and distinctive architectural layers.",
    description: "Maputo occupies a broad bay on the Indian Ocean, with acacia-lined avenues connecting its centre to waterfront districts. The landmark railway station and CFM museum interpret transport history, while the Central Market reflects the capital's long commercial role. Portuguese-era civic buildings, Mozambican art institutions and the iron Casa de Ferro reveal varied architectural and cultural layers across the city.",
    highlights: ["Maputo railway station", "CFM railway museum", "Mercado Central", "Casa de Ferro"],
    editorialProvenance: africaBatch3SourceReferences([{ title: "Visit Mozambique", url: "https://www.visitmozambique.gov.mz/" }, { title: "Portos e Caminhos de Ferro de Moçambique", url: "https://www.cfm.co.mz/" }]),
  },
  {
    id: "na-windhoek",
    summary: "Windhoek occupies a central highland basin with civic landmarks, museums and layered architectural heritage.",
    description: "Windhoek lies in a central Namibian highland basin, with ridges enclosing the capital's compact civic centre. The Independence Memorial Museum and National Art Gallery interpret national history and visual culture, while the Windhoek City Museum documents local urban development. Christuskirche, Tintenpalast gardens and surviving German colonial-era buildings form part of a complex architectural landscape presented within its historical context.",
    highlights: ["Windhoek City Museum", "Independence Memorial Museum", "Christuskirche", "Tintenpalast gardens"],
    editorialProvenance: africaBatch3SourceReferences([{ title: "City of Windhoek", url: "https://www.windhoekcc.org.na/" }, { title: "Museums Association of Namibia - Windhoek City Museum", url: "https://www.museums.com.na/museums/windhoek/windhoek-city-museum" }]),
  },
  {
    id: "ci-abidjan",
    summary: "Abidjan extends around the Ébrié Lagoon, with civic architecture, museums, markets and protected forest.",
    description: "Abidjan occupies peninsulas and islands around the Ébrié Lagoon, with bridges linking its principal districts. Plateau concentrates civic institutions and modern towers, while the Musée des Civilisations de Côte d'Ivoire preserves archaeological, artistic and ethnographic collections. Banco National Park protects tropical forest beside the urban area, adding an ecological counterpoint to markets and lagoon-side neighbourhoods.",
    highlights: ["Ébrié Lagoon", "Plateau civic district", "Musée des Civilisations", "Banco National Park"],
    editorialProvenance: africaBatch4SourceReferences([{ title: "Côte d'Ivoire Tourisme", url: "https://www.sublimeci.com/" }, { title: "Office Ivoirien des Parcs et Réserves", url: "https://www.oipr.ci/" }]),
  },
  {
    id: "gm-banjul",
    summary: "Banjul occupies a low island at the Gambia River mouth, with museums, markets and civic landmarks.",
    description: "Banjul stands on St Mary's Island where the Gambia River reaches the Atlantic, giving the compact capital a waterfront setting. The National Museum of The Gambia documents archaeology, history and cultural traditions in the city centre. Albert Market, colonial-era civic buildings and Arch 22 trace commercial and political layers within Banjul proper rather than the wider metropolitan area.",
    highlights: ["Gambia River mouth", "National Museum of The Gambia", "Albert Market", "Arch 22"],
    editorialProvenance: africaBatch4SourceReferences([{ title: "National Centre for Arts and Culture", url: "https://ncac.gm/" }, { title: "Ministry of Tourism and Culture, The Gambia", url: "https://motc.gov.gm/" }]),
  },
  {
    id: "bj-cotonou",
    summary: "Cotonou lies between the Gulf of Guinea and Lake Nokoué, centred on markets and civic monuments.",
    description: "Cotonou occupies a narrow coastal strip between the Gulf of Guinea and Lake Nokoué, crossed by a lagoon channel. Dantokpa Market reflects the city's longstanding commercial role, while the Place de l'Amazone anchors a newer civic landscape. Cultural venues, government buildings and busy central streets distinguish Benin's largest urban centre without extending its scope to Ouidah or Abomey.",
    highlights: ["Lake Nokoué lagoon setting", "Dantokpa Market", "Place de l'Amazone", "Cotonou civic centre"],
    editorialProvenance: africaBatch4SourceReferences([{ title: "Benin Tourism", url: "https://benin-tourisme.com/" }, { title: "Government of Benin", url: "https://www.gouv.bj/" }]),
  },
  {
    id: "sn-dakar",
    summary: "Dakar occupies the Cap-Vert Peninsula, shaped by Atlantic shores, museums, markets and national monuments.",
    description: "Dakar extends across the Cap-Vert Peninsula, with Atlantic headlands and bays framing Senegal's capital. The IFAN Museum and Museum of Black Civilisations hold major historical and artistic collections, while markets and civic monuments record the city's regional role. Gorée Island, reached offshore from Dakar by ferry, preserves a distinct UNESCO-listed historic settlement rather than a central-city neighbourhood.",
    highlights: ["Cap-Vert Peninsula", "Museum of Black Civilisations", "IFAN Museum", "Offshore Gorée Island"],
    editorialProvenance: africaBatch4SourceReferences([{ title: "Senegal Tourism", url: "https://www.visitezlesenegal.com/" }, { title: "UNESCO Island of Gorée", url: "https://whc.unesco.org/en/list/26/" }]),
  },
  {
    id: "ng-enugu",
    summary: "Enugu rests below wooded hills, with coal-mining history, markets, museums and established civic institutions.",
    description: "Enugu developed below the Udi hills and became closely associated with coal extraction during the twentieth century. The National Museum presents archaeological and cultural material, while the former colliery landscape records the industrial origins behind the Coal City name. Ogbete Market, civic buildings and neighbourhood streets place that history within a continuing state-capital setting rather than southeastern Nigeria generally.",
    highlights: ["Udi hill setting", "Coal-mining heritage", "National Museum Enugu", "Ogbete Market"],
    editorialProvenance: africaBatch4SourceReferences([{ title: "Enugu State Government", url: "https://enugustate.gov.ng/" }, { title: "National Commission for Museums and Monuments", url: "https://museum.ng/" }]),
  },
  {
    id: "sl-freetown",
    summary: "Freetown rises around a broad natural harbour, with museums, markets and layered settlement heritage.",
    description: "Freetown occupies steep hills beside one of West Africa's broad natural harbours, with streets descending toward the waterfront. The Sierra Leone National Museum interprets archaeology, history and cultural traditions, while surviving civic and religious buildings reflect the city's settlement history. Markets and designated monuments provide durable points of reference without relying on claims about recently altered landmarks.",
    highlights: ["Freetown natural harbour", "Sierra Leone National Museum", "Historic civic buildings", "Central markets"],
    editorialProvenance: africaBatch4SourceReferences([{ title: "Sierra Leone Ministry of Tourism and Cultural Affairs", url: "https://tourism.gov.sl/" }, { title: "Monuments and Relics Commission", url: "https://mrc.gov.sl/" }]),
  },
  {
    id: "tg-lome",
    summary: "Lomé faces the Gulf of Guinea through markets, museums, civic spaces and colonial-era architecture.",
    description: "Lomé extends along Togo's Gulf of Guinea coast, where the seafront meets a compact civic and commercial centre. The National Museum interprets the country's archaeology, history and arts, while the restored Palais de Lomé presents exhibitions within a former gubernatorial complex. Market streets, craft traditions and surviving colonial-era buildings give the capital a distinctly urban context separate from Togo-wide attractions.",
    highlights: ["Gulf of Guinea seafront", "Togo National Museum", "Palais de Lomé", "Grand Market district"],
    editorialProvenance: africaBatch4SourceReferences([{ title: "Togo Tourism", url: "https://togotourisme.tg/" }, { title: "Palais de Lomé", url: "https://palaisdelome.com/" }]),
  },
  {
    id: "lr-monrovia",
    summary: "Monrovia occupies an Atlantic peninsula, with national museums, markets and sites connected to Liberia's founding.",
    description: "Monrovia spreads across a peninsula and adjoining coastal districts between the Atlantic and the Mesurado River. The National Museum of Liberia preserves historical and cultural collections in the city, while Providence Island marks an important site in the settlement narrative of modern Liberia. Waterside Market and civic buildings add commercial and architectural context without extending the record to the distant international airport.",
    highlights: ["Mesurado River peninsula", "National Museum of Liberia", "Providence Island", "Waterside Market"],
    editorialProvenance: africaBatch4SourceReferences([{ title: "Liberia Ministry of Information, Cultural Affairs and Tourism", url: "https://www.micat.gov.lr/" }, { title: "UNESCO Providence Island", url: "https://whc.unesco.org/en/tentativelists/6603/" }]),
  },
  {
    id: "ng-port-harcourt",
    summary: "Port Harcourt developed beside the Bonny River system, with markets, cultural institutions and planned civic districts.",
    description: "Port Harcourt occupies low-lying terrain within the Niger Delta's network of rivers and creeks, giving waterways a central geographic role. The city developed as a port and retains planned civic districts alongside older commercial streets. The Rivers State Museum, cultural centres and Mile One Market document local history, arts and everyday trade without treating attractions elsewhere in Rivers State as city sites.",
    highlights: ["Bonny River waterways", "Rivers State Museum", "Mile One Market", "Port Harcourt civic districts"],
    editorialProvenance: africaBatch4SourceReferences([{ title: "Rivers State Government", url: "https://www.riversstate.gov.ng/" }, { title: "National Commission for Museums and Monuments", url: "https://museum.ng/" }]),
  },
  {
    id: "ml-bamako",
    summary: "Bamako spans both banks of the Niger River, with museums, markets and established musical traditions.",
    description: "Bamako extends along both banks of the Niger River, with bridges linking its principal urban districts. The National Museum of Mali presents archaeological objects, textiles, masks and other material traditions in a purpose-built cultural setting. Central markets, artisan activity and institutions supporting music and the arts give Mali's capital a city-specific cultural profile grounded in the river corridor.",
    highlights: ["Niger River banks", "National Museum of Mali", "Bamako central markets", "Music and artisan traditions"],
    editorialProvenance: africaBatch5SourceReferences([{ title: "Encyclopaedia Britannica — Bamako", url: "https://www.britannica.com/place/Bamako" }, { title: "UNESCO Creative Cities Network — Bamako", url: "https://www.unesco.org/en/creative-cities/bamako" }]),
  },
  {
    id: "ng-kano",
    summary: "Kano preserves walled-city gateways, palace heritage, historic markets and enduring textile craft traditions.",
    description: "Kano's historic core developed within defensive walls whose surviving gates still mark routes into the old city. Kurmi Market, the Emir's Palace precinct and narrow commercial streets express its longstanding role in regional trade. Indigo dye pits and other textile crafts remain closely identified with Kano, while museums interpret the city's civic, architectural and commercial history.",
    highlights: ["Ancient Kano city gates", "Kurmi Market", "Emir's Palace precinct", "Kofar Mata dye pits"],
    editorialProvenance: africaBatch5SourceReferences([{ title: "Encyclopaedia Britannica — Kano", url: "https://www.britannica.com/place/Kano-Nigeria" }, { title: "National Commission for Museums and Monuments", url: "https://museum.ng/" }]),
  },
  {
    id: "ne-niamey",
    summary: "Niamey follows the Niger River through civic districts, markets and national cultural institutions.",
    description: "Niamey stands on the Niger River, which divides central districts from expanding neighbourhoods on the opposite bank. The Boubou Hama National Museum brings archaeological, ethnographic and natural-history collections together within a landscaped cultural complex. Markets, mosques and government institutions trace the capital's urban growth while keeping the record focused on Niamey rather than the wider Sahel.",
    highlights: ["Niger River waterfront", "Boubou Hama National Museum", "Grand Market district", "Niamey civic quarter"],
    editorialProvenance: africaBatch5SourceReferences([{ title: "Encyclopaedia Britannica — Niamey", url: "https://www.britannica.com/place/Niamey" }, { title: "UNESCO — Niger", url: "https://www.unesco.org/en/countries/ne" }]),
  },
  {
    id: "bf-ouagadougou",
    summary: "Ouagadougou centres national museums, craft traditions, markets and institutions devoted to African cinema.",
    description: "Ouagadougou is an inland capital whose broad avenues connect civic districts, markets and long-established residential quarters. The National Museum and National Museum of Music document material culture and musical heritage, while artisan institutions sustain metalwork, textiles and other crafts. The city's durable association with African cinema is expressed through permanent cultural organisations rather than temporary festival schedules or annual claims.",
    highlights: ["Burkina Faso National Museum", "National Museum of Music", "Ouagadougou craft institutions", "African cinema heritage"],
    editorialProvenance: africaBatch5SourceReferences([{ title: "Encyclopaedia Britannica — Ouagadougou", url: "https://www.britannica.com/place/Ouagadougou" }, { title: "UNESCO Creative Cities Network — Ouagadougou", url: "https://www.unesco.org/en/creative-cities/ouagadougou" }]),
  },
  {
    id: "cg-brazzaville",
    summary: "Brazzaville faces the Congo River through Poto-Poto, civic landmarks and distinctive twentieth-century architecture.",
    description: "Brazzaville occupies the north bank of the Congo River, directly across the broad Pool Malebo from Kinshasa. Poto-Poto's streets and painting school represent a longstanding urban arts tradition, while the Basilica of Sainte-Anne contributes a recognisable modern architectural landmark. Riverfront viewpoints, markets and civic buildings reflect the history of Congo - Brazzaville without confusing the capital with its larger neighbour.",
    highlights: ["Congo River and Pool Malebo", "Poto-Poto district", "Poto-Poto School of Painting", "Basilica of Sainte-Anne"],
    editorialProvenance: africaBatch5SourceReferences([{ title: "Encyclopaedia Britannica — Brazzaville", url: "https://www.britannica.com/place/Brazzaville" }, { title: "UNESCO Creative Cities Network — Brazzaville", url: "https://www.unesco.org/en/creative-cities/brazzaville" }]),
  },
  {
    id: "cm-douala",
    summary: "Douala occupies the Wouri estuary, shaped by port history, markets and contemporary cultural institutions.",
    description: "Douala lies beside the Wouri River estuary, where waterways and commercial districts have long shaped Cameroon's principal port city. Historic administrative buildings and the maritime museum interpret trade, navigation and the city's changing architecture. Central markets, public art and cultural spaces such as doual'art provide an urban focus distinct from Cameroon's inland capital and attractions elsewhere in the country.",
    highlights: ["Wouri River estuary", "Douala Maritime Museum", "Historic port architecture", "doual'art urban culture"],
    editorialProvenance: africaBatch5SourceReferences([{ title: "Encyclopaedia Britannica — Douala", url: "https://www.britannica.com/place/Douala" }, { title: "doual'art", url: "https://doualart.org/" }]),
  },
  {
    id: "cd-kinshasa",
    summary: "Kinshasa stretches beside the Congo River, with national collections, markets and influential musical institutions.",
    description: "Kinshasa extends along the south bank of the Congo River at Pool Malebo, facing Brazzaville across the water. The National Museum of the Democratic Republic of the Congo holds archaeological, historical and ethnographic collections within the capital. Markets, academies and performance spaces support a deeply rooted music culture, while older civic districts preserve landmarks specific to Congo - Kinshasa.",
    highlights: ["Congo River and Pool Malebo", "DR Congo National Museum", "Kinshasa music culture", "Central markets and civic districts"],
    editorialProvenance: africaBatch5SourceReferences([{ title: "Encyclopaedia Britannica — Kinshasa", url: "https://www.britannica.com/place/Kinshasa" }, { title: "UNESCO Creative Cities Network — Kinshasa", url: "https://www.unesco.org/en/creative-cities/kinshasa" }]),
  },
  {
    id: "ga-libreville",
    summary: "Libreville lines the Gabon Estuary with coastal districts, markets, churches and national cultural collections.",
    description: "Libreville occupies the north shore of the Gabon Estuary, where coastal roads connect civic, commercial and residential districts. The National Museum of Arts, Rites and Traditions preserves collections connected to Gabon's cultural heritage within the capital. Mont-Bouët Market, churches and waterfront public spaces describe Libreville's urban character without substituting rainforest reserves or distant national parks for city content.",
    highlights: ["Gabon Estuary waterfront", "National Museum collections", "Mont-Bouët Market", "Libreville churches and civic landmarks"],
    editorialProvenance: africaBatch5SourceReferences([{ title: "Encyclopaedia Britannica — Libreville", url: "https://www.britannica.com/place/Libreville" }, { title: "Gabon Ministry of Culture", url: "https://www.culture.gouv.ga/" }]),
  },
  {
    id: "ao-luanda",
    summary: "Luanda curves around an Atlantic bay, marked by fortress heritage, museums and the Ilha waterfront.",
    description: "Luanda occupies a sheltered Atlantic bay, with the Marginal waterfront facing the narrow Ilha de Luanda. Fortaleza de São Miguel and nearby museums preserve material from colonial and postcolonial history while overlooking the old urban centre. Churches, civic architecture and neighbourhood streets reveal successive layers of the Angolan capital beyond its modern shoreline, without relying on current infrastructure claims.",
    highlights: ["Luanda Bay waterfront", "Ilha de Luanda", "Fortaleza de São Miguel", "Museums of the old centre"],
    editorialProvenance: africaBatch5SourceReferences([{ title: "Encyclopaedia Britannica — Luanda", url: "https://www.britannica.com/place/Luanda" }, { title: "Angola Ministry of Culture", url: "https://www.mincult.gov.ao/" }]),
  },
  {
    id: "cm-yaounde",
    summary: "Yaoundé spreads across wooded hills, with national museums, civic monuments, markets and cultural institutions.",
    description: "Yaoundé occupies a succession of wooded hills in Cameroon's interior, giving its districts a markedly undulating form. The National Museum, housed in the former presidential palace, interprets national history and artistic traditions within the capital. Reunification monuments, central markets and civic architecture provide durable city landmarks while keeping coastal sites and wildlife destinations outside this specifically Yaoundé-focused record.",
    highlights: ["Wooded seven-hill setting", "Cameroon National Museum", "Reunification Monument", "Central markets and civic architecture"],
    editorialProvenance: africaBatch5SourceReferences([{ title: "Encyclopaedia Britannica — Yaoundé", url: "https://www.britannica.com/place/Yaounde" }, { title: "Cameroon Ministry of Arts and Culture", url: "https://www.minculture.gov.cm/" }]),
  },
  {
    id: "bi-bujumbura",
    summary: "Bujumbura occupies Lake Tanganyika's northeastern shore, with markets, museums and a longstanding commercial waterfront.",
    description: "Bujumbura extends across low ground beside Lake Tanganyika, where the waterfront and surrounding hills define the city's setting. Its central market districts and civic streets reflect a longstanding role as Burundi's principal commercial centre and former national capital. The Living Museum's cultural and natural-history collections add an institutional perspective to lakeside neighbourhoods and the city's urban history.",
    highlights: ["Lake Tanganyika waterfront", "Living Museum collections", "Central market districts", "Lakeside urban neighbourhoods"],
    editorialProvenance: africaBatch6SourceReferences([{ title: "Encyclopaedia Britannica — Bujumbura", url: "https://www.britannica.com/place/Bujumbura" }, { title: "Encyclopaedia Britannica — Lake Tanganyika", url: "https://www.britannica.com/place/Lake-Tanganyika" }]),
  },
  {
    id: "dj-djibouti",
    summary: "Djibouti occupies a Gulf of Tadjoura peninsula, shaped by port commerce, markets and civic architecture.",
    description: "Djibouti City stands on a peninsula between the Gulf of Tadjoura and the Gulf of Aden, distinct from the wider Republic of Djibouti. Its port setting shaped commercial streets around Place Menelik, where arcades and colonial-era civic fabric meet market districts. Mosques, waterfront roads and the city's grid provide durable urban context without substituting inland national landscapes for city sites.",
    highlights: ["Gulf of Tadjoura waterfront", "Place Menelik", "Central market streets", "Port-city civic architecture"],
    editorialProvenance: africaBatch6SourceReferences([{ title: "Encyclopaedia Britannica — Djibouti", url: "https://www.britannica.com/place/Djibouti-capital-Djibouti" }, { title: "Presidency of the Republic of Djibouti", url: "https://presidence.dj/" }]),
  },
  {
    id: "so-hargeisa",
    summary: "Hargeisa is a major inland Horn of Africa city and Somaliland's administrative and cultural centre.",
    description: "Hargeisa occupies an inland valley and plateau setting in the Horn of Africa and serves as Somaliland's administrative centre. Central markets, including livestock and commercial areas, anchor everyday urban activity among broad avenues and low-rise neighbourhoods. The Hargeysa Cultural Centre preserves archives, literature and oral traditions, while Laas Geel's rock-art shelters lie outside the city and provide wider regional context.",
    highlights: ["Inland valley and plateau", "Hargeisa central markets", "Hargeysa Cultural Centre", "Laas Geel regional rock art"],
    editorialProvenance: africaBatch6SourceReferences([{ title: "Encyclopaedia Britannica — Hargeysa", url: "https://www.britannica.com/place/Hargeysa" }, { title: "Hargeysa Cultural Centre", url: "https://hargeysaculturalcenter.org/" }]),
  },
  {
    id: "ss-juba",
    summary: "Juba stands beside the White Nile, with riverfront districts, markets, churches and layered urban history.",
    description: "Juba extends along the White Nile, whose broad channel and banks give the city its defining geographic setting. Market districts and neighbourhood streets record its growth from a river settlement into South Sudan's principal urban centre. All Saints Cathedral, Saint Teresa Cathedral and University of Juba institutions contribute religious, civic and educational landmarks without extending the record to country-wide attractions.",
    highlights: ["White Nile riverfront", "Juba market districts", "All Saints Cathedral", "University of Juba institutions"],
    editorialProvenance: africaBatch6SourceReferences([{ title: "Encyclopaedia Britannica — Juba", url: "https://www.britannica.com/place/Juba" }, { title: "University of Juba", url: "https://uoj.edu.ss/" }]),
  },
  {
    id: "gn-conakry",
    summary: "Conakry occupies a coastal peninsula where Kaloum, national institutions and cultural heritage shape Guinea's capital.",
    description: "Conakry extends along a peninsula on Guinea's Atlantic coast, with Kaloum forming its historic civic and administrative core. The Musée national de Guinée, also associated with Sandervalia, has held collections representing the country's archaeological, artistic and ethnographic heritage. Official cultural institutions place conservation and public memory within the capital's urban history rather than presenting distant Guinean sites as city attractions.",
    highlights: ["Conakry coastal peninsula", "Kaloum civic core", "Musée national de Guinée", "Sandervalia cultural heritage"],
    editorialProvenance: finalAfricaBatchSourceReferences([{ title: "Ministère de la Culture, du Tourisme et de l’Artisanat — Directions et services", url: "https://mcta.gov.gn/les-directions-et-services/" }, { title: "Ministère de la Culture, du Tourisme et de l’Artisanat — Musée national de Guinée", url: "https://mcta.gov.gn/patrimoine-culturel-16-millions-deuros-pour-la-renaissance-du-musee-national-de-guinee/" }]),
  },
  {
    id: "sd-khartoum",
    summary: "Khartoum developed around the Blue and White Nile confluence, with national institutions reflecting Sudan's archaeological heritage.",
    description: "Khartoum developed where the Blue Nile and White Nile meet, a geography that shaped the Sudanese capital and its metropolitan form. The Sudan National Museum has served as a major repository for archaeological material and collections connected with Sudan's long cultural history. UNESCO documentation records safeguarding and rehabilitation initiatives for this heritage without establishing current access, condition or operating status.",
    highlights: ["Blue and White Nile confluence", "Sudan National Museum heritage", "Sudanese archaeological collections", "Khartoum metropolitan geography"],
    editorialProvenance: finalAfricaBatchSourceReferences([{ title: "UNESCO — Rehabilitating the Sudanese National Museum in Khartoum", url: "https://www.unesco.org/en/articles/launching-project-rehabilitating-sudanese-national-museum-khartoum-sudan" }, { title: "UNESCO Heritage Emergency Fund — Sudan National Museum", url: "https://www.unesco.org/en/culture-emergencies/heritage-emergency-fund/urgent-safeguarding-response-damaged-collections-sudan-national-museum" }]),
  },
  {
    id: "ly-tripoli",
    summary: "Tripoli faces the Mediterranean, with an old medina, civic squares and architecture reflecting Libya's layered history.",
    description: "Tripoli stands on Libya's Mediterranean coast, where the Old City preserves a dense urban fabric shaped through successive historical periods. Sayeda Mariam Square forms part of this medina and reflects civic, religious and architectural development associated with the Karamanli era. UNESCO's Libya-specific material places the square within the capital's heritage context without designating Tripoli itself as a World Heritage Site.",
    highlights: ["Mediterranean coastal setting", "Tripoli Old City", "Sayeda Mariam Square", "Karamanli-era urban heritage"],
    editorialProvenance: finalAfricaBatchSourceReferences([{ title: "UNESCO World Heritage Centre — Sayeda Mariam Square, Old City of Tripoli, Libya", url: "https://whc.unesco.org/en/tentativelists/7020/" }, { title: "UNESCO — Libya country profile", url: "https://www.unesco.org/en/countries/ly" }]),
  },
] as const satisfies readonly ExploreDestinationEditorial[];
