import type { ExploreDestinationEditorial, ExploreDestinationEditorialSourceReference } from "./types";

const makeSourceReferences = (lastVerifiedAt: string) =>
  (references: readonly ExploreDestinationEditorialSourceReference[]) => ({
    source: "kurioticket-editorial" as const, sourceReferences: references, lastVerifiedAt,
  });
const asiaBatch1SourceReferences = makeSourceReferences("2026-08-10");
const asiaBatch2SourceReferences = makeSourceReferences("2026-08-10");
const asiaBatch3SourceReferences = makeSourceReferences("2026-08-10");
const asiaBatch4SourceReferences = makeSourceReferences("2026-08-10");
const asiaBatch5SourceReferences = makeSourceReferences("2026-08-10");
const asiaBatch6SourceReferences = makeSourceReferences("2026-08-10");
const asiaBatch7SourceReferences = makeSourceReferences("2026-08-10");
const asiaFinalBatchSourceReferences = makeSourceReferences("2026-08-10");

export const asiaExploreDestinationEditorial = [
  {
    id: "cn-beijing",
    summary: "Beijing preserves imperial palace complexes, ceremonial gardens and monumental architecture from China's Ming and Qing dynasties.",
    description: "Beijing occupies the northern Chinese plain, where imperial planning shaped a capital of monumental axes, walls and ceremonial spaces. The Forbidden City preserves the palace architecture and political setting of the Ming and Qing dynasties. South of the historic core, the Temple of Heaven forms a fifteenth-century ritual landscape of gardens, altars and precisely arranged ceremonial buildings.",
    highlights: ["Forbidden City palace complex", "Ming and Qing imperial heritage", "Temple of Heaven altars", "Imperial ceremonial gardens"],
    editorialProvenance: asiaBatch1SourceReferences([{ title: "UNESCO — Imperial Palaces of the Ming and Qing Dynasties in Beijing and Shenyang", url: "https://whc.unesco.org/en/list/439/" }, { title: "UNESCO — Temple of Heaven: an Imperial Sacrificial Altar in Beijing", url: "https://whc.unesco.org/en/list/881" }]),
  },
  {
    id: "cn-guangzhou",
    summary: "Guangzhou reflects a long southern Chinese urban history through Lingnan culture, architecture and civic collections.",
    description: "Guangzhou stands on the Pearl River in southern China, with a long urban history shaped by trade and Lingnan culture. Historic neighbourhoods and regional architectural traditions distinguish the city's cultural identity from the wider Guangdong province. Guangzhou Museum, housed in Zhenhai Tower, presents city-history collections that connect the old fortified landscape with Guangzhou's social and cultural development.",
    highlights: ["Pearl River urban setting", "Lingnan cultural heritage", "Guangzhou Museum collections", "Zhenhai Tower setting"],
    editorialProvenance: asiaBatch1SourceReferences([{ title: "Guangzhou Municipal Government — Culture and History", url: "https://www.gz.gov.cn/guangzhouinternational/visitors/whattosee/cultureandhistory/" }, { title: "Guangzhou Museum", url: "https://www.guangzhoumuseum.cn/website_cn/web/MainPage/Index.aspx" }]),
  },
  {
    id: "hk-hong-kong",
    summary: "Hong Kong is shaped by Victoria Harbour, dense waterfront districts and conserved civic architecture in Central.",
    description: "Hong Kong extends around Victoria Harbour, the waterway separating Hong Kong Island from Kowloon and defining its central urban geography. Ferries, promenades and layered waterfront districts reflect the harbour's enduring relationship with the city. In Central, Tai Kwun conserves the former Central Police Station, Central Magistracy and Victoria Prison as an architectural complex devoted to heritage and culture.",
    highlights: ["Victoria Harbour geography", "Hong Kong Island waterfront", "Kowloon harbour frontage", "Tai Kwun heritage complex"],
    editorialProvenance: asiaBatch1SourceReferences([{ title: "Hong Kong Tourism Board — Victoria Harbour", url: "https://www.discoverhongkong.com/eng/place-to-go/travel.guide-victoria-harbour.html" }, { title: "Hong Kong Tourism Board — Tai Kwun", url: "https://www.discoverhongkong.com/eng/place-to-go/travel.guide-tai-kwun.html" }]),
  },
  {
    id: "mo-macau",
    summary: "Macau preserves a historic port cityscape where Chinese and Portuguese architectural traditions meet across civic squares.",
    description: "Macau occupies a compact estuarine setting whose historic centre records centuries of maritime exchange between China and Portugal. Streets, squares, religious buildings and fortifications form an urban landscape where Chinese and Portuguese architectural traditions remain closely interwoven. A-Ma Temple anchors the city's maritime heritage, while civic and religious monuments trace the development of this trading settlement.",
    highlights: ["Historic Centre of Macao", "A-Ma Temple", "Chinese and Portuguese architecture", "Historic squares and fortifications"],
    editorialProvenance: asiaBatch1SourceReferences([{ title: "UNESCO — Historic Centre of Macao", url: "https://whc.unesco.org/en/list/1110/" }, { title: "Macao Government Tourism Office — Macao World Heritage", url: "https://www.macaotourism.gov.mo/en/sightseeing/macao-world-heritage" }]),
  },
  {
    id: "jp-osaka",
    summary: "Osaka's castle heritage and Dotonbori canal landscape express the city's commercial and theatrical history.",
    description: "Osaka developed around waterways and commercial districts on Japan's main island of Honshu, giving the city a distinct urban identity. Osaka Castle recalls Toyotomi Hideyoshi and the political history associated with the fortified site. In Minami, Dotonbori follows a historic canal whose theatres and entertainment culture became closely linked with Osaka's mercantile growth and street-level character.",
    highlights: ["Osaka Castle main keep", "Toyotomi Hideyoshi history", "Dotonbori canal", "Minami theatre heritage"],
    editorialProvenance: asiaBatch1SourceReferences([{ title: "Osaka Official Tourism Guide — Osaka Castle Museum", url: "https://www.osaka-info.jp/en/spot/osaka-castle-main-keep/" }, { title: "Osaka Official Tourism Guide — Dotonbori", url: "https://osaka-info.jp/en/spot/dotonbori/" }]),
  },
  {
    id: "kr-seoul",
    summary: "Seoul's Joseon palaces and hanok neighbourhoods reveal the historic structure of Korea's mountain-ringed capital.",
    description: "Seoul occupies the Han River basin amid surrounding mountains, while its historic core preserves the spatial legacy of Joseon-era Hanyang. Gyeongbokgung served as the dynasty's principal palace and remains central to understanding the capital's royal architecture. Nearby Bukchon retains lanes of traditional hanok residences between palace districts, illustrating the domestic scale of Seoul's architectural and cultural heritage.",
    highlights: ["Gyeongbokgung Palace", "Joseon capital heritage", "Bukchon Hanok Village", "Historic palace districts"],
    editorialProvenance: asiaBatch1SourceReferences([{ title: "Official Travel Guide to Seoul — Gyeongbokgung Palace", url: "https://english.visitseoul.net/attractions/Gyeongbokgung-Palace/ENP000072" }, { title: "Official Travel Guide to Seoul — Bukchon Hanok Village", url: "https://english.visitseoul.net/attractions/bukchon-hanok-village_/263" }]),
  },
  {
    id: "cn-shanghai",
    summary: "Shanghai's Huangpu waterfront and civic collections trace the municipality's transformation into a modern commercial metropolis.",
    description: "Shanghai stands beside the Huangpu River, where the Bund forms a defining waterfront of historic commercial and civic architecture. Its streetscape records the municipality's development into modern Shanghai, while nearby Suzhou Creek bridges extend that layered urban landscape. Shanghai History Museum preserves collections documenting the city's social, political and cultural history across successive periods of metropolitan change.",
    highlights: ["Bund historic waterfront", "Huangpu River setting", "Suzhou Creek bridges", "Shanghai History Museum collections"],
    editorialProvenance: asiaBatch1SourceReferences([{ title: "Shanghai Municipal Government — The Bund Historical and Cultural Block", url: "https://english.shanghai.gov.cn/en-HeritageZones/20231208/f2ac293f546a4d32aba936f2e733a47c.html" }, { title: "Shanghai Municipal Government — Shanghai History Museum", url: "https://english.shanghai.gov.cn/en-MuseumsGalleries/20231229/9b40ec60928148cc89066195dedd4395.html" }]),
  },
  {
    id: "cn-shenzhen",
    summary: "Shenzhen's reform-era cityscape supports a growing network of contemporary art museums and cultural institutions.",
    description: "Shenzhen occupies China's southern coast beside Hong Kong, with a cityscape strongly shaped by reform-era urban development. Contemporary cultural infrastructure provides a durable lens on this modern metropolis without extending its scope across the wider region. Shenzhen Art Museum, Dafen-related institutions and the Shenzhen International Museum of Art connect visual culture with the city's evolving architecture and urban identity.",
    highlights: ["Reform-era urban landscape", "Shenzhen Art Museum", "Dafen cultural institutions", "Shenzhen International Museum of Art"],
    editorialProvenance: asiaBatch1SourceReferences([{ title: "Shenzhen Government Online — Galleries", url: "https://www.sz.gov.cn/en_szgov/life/cultural/galleries/index.html" }, { title: "Shenzhen Government Online — Shenzhen International Museum of Art", url: "https://www.sz.gov.cn/en_szgov/aboutsz/photos/content/post_12814524.html" }]),
  },
  {
    id: "tw-taipei",
    summary: "Taipei's basin cityscape encompasses historic landmarks and major institutions preserving Chinese art and cultural collections.",
    description: "Taipei occupies a river basin in northern Taiwan, where historic districts and cultural landmarks sit within a dense modern cityscape. At Waishuangxi, the National Palace Museum forms a purpose-built complex whose institutional history is closely tied to preserving extensive art and historical collections. Its galleries and architecture provide a focused account of material culture within Taipei's broader civic landscape.",
    highlights: ["Taipei basin cityscape", "National Palace Museum", "Waishuangxi museum complex", "Historic art collections"],
    editorialProvenance: asiaBatch1SourceReferences([{ title: "Taipei City Government — Taipei Travel", url: "https://travel.taipei/en/must-visit/attractions" }, { title: "National Palace Museum — History of NPM", url: "https://www.npm.gov.tw/Articles.aspx?l=2&sno=03012532" }, { title: "National Palace Museum — Architecture", url: "https://www.npm.gov.tw/articles.aspx?l=2&sno=03012533" }]),
  },
  {
    id: "mn-ulaanbaatar",
    summary: "Ulaanbaatar occupies the Tuul River valley beneath Bogd Khan Uul, with Buddhist and museum heritage.",
    description: "Ulaanbaatar lies in the Tuul River valley beneath Bogd Khan Uul, a mountain setting that frames Mongolia's capital. Buddhist institutions and Soviet-era planning reflect distinct layers in the city's architectural and urban history. The National Museum of Mongolia preserves archaeological, historical and ethnographic collections that document the country's cultures while anchoring this national narrative within the capital.",
    highlights: ["Tuul River valley", "Bogd Khan Uul setting", "Buddhist urban heritage", "National Museum of Mongolia"],
    editorialProvenance: asiaBatch1SourceReferences([{ title: "Official Mongolia Tourism — Ulaanbaatar & Surrounding", url: "https://www.mongolia.travel/" }, { title: "National Museum of Mongolia — About Us", url: "https://en.nationalmuseum.mn/about" }]),
  },
  {
    id: "vn-hanoi",
    summary: "Hanoi's lakes, historic quarters and scholarly monuments reflect the layered heritage of Vietnam's capital.",
    description: "Hanoi stands in the Red River delta, with Hoàn Kiếm Lake and the Old Quarter shaping its historic centre. The Temple of Literature preserves an enduring association with scholarship, ceremonial courtyards and traditional architecture. Beyond these landmarks, museums and French-colonial civic buildings document successive chapters in the capital's cultural, political and urban history.",
    highlights: ["Hoàn Kiếm Lake", "Old Quarter streets", "Temple of Literature", "French-colonial civic architecture"],
    editorialProvenance: asiaBatch2SourceReferences([{ title: "Vietnam National Authority of Tourism — Ha Noi", url: "https://vietnam.travel/places-to-go/northern-vietnam/ha-noi" }, { title: "UNESCO — Central Sector of the Imperial Citadel of Thang Long - Hanoi", url: "https://whc.unesco.org/en/list/1328/" }]),
  },
  {
    id: "vn-ho-chi-minh-city",
    summary: "Ho Chi Minh City traces southern Vietnamese urban history through riverfront districts, markets and civic architecture.",
    description: "Ho Chi Minh City developed beside the Saigon River, where commercial streets and civic landmarks frame its historic urban core. Colonial-era architecture and museums record periods when the city was widely known as Saigon, without displacing its canonical name. Chợ Lớn's temples, shophouses and markets preserve a distinct Chinese Vietnamese layer within the wider metropolis.",
    highlights: ["Saigon River setting", "Colonial-era civic landmarks", "Chợ Lớn historic quarter", "City history museums"],
    editorialProvenance: asiaBatch2SourceReferences([{ title: "Vietnam National Authority of Tourism — Ho Chi Minh City", url: "https://vietnam.travel/places-to-go/southern-vietnam/ho-chi-minh-city" }, { title: "Ho Chi Minh City Museum", url: "https://hcmc-museum.edu.vn/" }]),
  },
  {
    id: "kh-phnom-penh",
    summary: "Phnom Penh's riverfront, royal institutions and historic markets express the Cambodian capital's civic heritage.",
    description: "Phnom Penh occupies the meeting place of the Mekong, Tonlé Sap and Bassac rivers, a confluence central to its urban geography. The Royal Palace and National Museum establish a cultural precinct of royal architecture and Khmer collections near the riverfront. Wat Phnom and long-established markets add religious and commercial landmarks to the capital's layered civic history.",
    highlights: ["Three-river confluence", "Royal Palace precinct", "National Museum collections", "Wat Phnom"],
    editorialProvenance: asiaBatch2SourceReferences([{ title: "Cambodia Ministry of Tourism — Phnom Penh", url: "https://www.tourismcambodia.org/provinces/60/phnom-penh" }, { title: "National Museum of Cambodia", url: "https://www.cambodiamuseum.info/" }]),
  },
  {
    id: "kh-siem-reap",
    summary: "Siem Reap links a riverside Cambodian city, living arts and museums with the nearby Angkor landscape.",
    description: "Siem Reap grew along its namesake river as an urban gateway to the Angkor archaeological landscape nearby. The city's museums and cultural institutions interpret Khmer history without placing every Angkor monument within the city itself. Workshops, performance traditions and historic neighbourhoods provide a living-arts context distinct from, yet closely connected to, the region's monumental heritage.",
    highlights: ["Siem Reap River", "Angkor gateway relationship", "Khmer cultural museums", "Traditional arts workshops"],
    editorialProvenance: asiaBatch2SourceReferences([{ title: "UNESCO — Angkor", url: "https://whc.unesco.org/en/list/668/" }, { title: "APSARA National Authority", url: "https://apsaraauthority.gov.kh/" }]),
  },
  {
    id: "th-phuket",
    summary: "Phuket encompasses Andaman Sea coastlines, island communities and Sino-Portuguese heritage centred in its historic town.",
    description: "Phuket is an island and province in the Andaman Sea, with coastal landscapes extending well beyond Phuket City. Its travel-facing identity includes beaches, headlands and long-established communities as well as the historic streets of Old Phuket Town. Sino-Portuguese shophouses and local food traditions reveal cultural connections shaped by maritime trade across the broader island destination.",
    highlights: ["Andaman Sea coastline", "Old Phuket Town", "Sino-Portuguese shophouses", "Island food heritage"],
    editorialProvenance: asiaBatch2SourceReferences([{ title: "Tourism Authority of Thailand — Phuket", url: "https://www.tourismthailand.org/Destinations/Provinces/Phuket/350" }, { title: "UNESCO Creative Cities Network — Phuket", url: "https://www.unesco.org/en/creative-cities/phuket" }]),
  },
  {
    id: "la-vientiane",
    summary: "Vientiane's Mekong riverfront, Buddhist monuments and civic landmarks define the historic character of Laos's capital.",
    description: "Vientiane is the Lao capital on the Mekong River, treated here as the city rather than the wider prefecture or province. Pha That Luang anchors its Buddhist and national architectural heritage, while historic temples preserve distinct religious settings. Patuxai and the city's museums add twentieth-century civic history and curated Lao culture to the riverside urban landscape.",
    highlights: ["Mekong riverfront", "Pha That Luang", "Historic Buddhist temples", "Patuxai monument"],
    editorialProvenance: asiaBatch2SourceReferences([{ title: "Lao National Tourism Administration — Vientiane Capital", url: "https://www.tourismlaos.org/vientiane-capital/" }, { title: "UNESCO — That Luang de Vientiane", url: "https://whc.unesco.org/en/tentativelists/3912/" }]),
  },
  {
    id: "mm-yangon",
    summary: "Yangon's river-oriented historic core encompasses Buddhist monuments, traditional markets and colonial-era civic architecture.",
    description: "Yangon developed near the Yangon River, where a gridded historic core contains religious, commercial and civic landmarks. Shwedagon Pagoda anchors the city's Buddhist heritage, while markets and colonial-era public buildings record other layers of urban history. Museums and preserved streetscapes support an evergreen account of the former Rangoon without implying anything about present political or travel conditions.",
    highlights: ["Yangon River setting", "Shwedagon Pagoda", "Colonial-era civic architecture", "Historic market districts"],
    editorialProvenance: asiaBatch2SourceReferences([{ title: "UNESCO — Historic Urban Landscape of Yangon", url: "https://whc.unesco.org/en/tentativelists/6367/" }, { title: "Shwedagon Pagoda Board of Trustees", url: "https://www.shwedagonpagoda.org.mm/" }]),
  },
  {
    id: "bn-bandar-seri-begawan",
    summary: "Bandar Seri Begawan follows the Brunei River through mosque landmarks, water villages and civic institutions.",
    description: "Bandar Seri Begawan occupies the Brunei River's banks, where the capital's civic centre faces long-established water settlements. Omar Ali Saifuddien Mosque expresses the city's Malay Islamic architectural identity through its dome, lagoon and ceremonial setting. Kampong Ayer, museums and royal institutions connect river-based community history with the urban fabric, without extending the record across Brunei-Muara District.",
    highlights: ["Brunei River waterfront", "Omar Ali Saifuddien Mosque", "Kampong Ayer relationship", "Royal and civic museums"],
    editorialProvenance: asiaBatch3SourceReferences([{ title: "Encyclopaedia Britannica — Bandar Seri Begawan", url: "https://www.britannica.com/place/Bandar-Seri-Begawan" }, { title: "Brunei Tourism", url: "https://www.bruneitourism.com/" }]),
  },
  {
    id: "ph-cebu",
    summary: "Cebu spans an island and province whose maritime heritage, historic city and food traditions remain intertwined.",
    description: "Cebu is treated as the wider island and provincial destination, with Cebu City forming its principal historic urban centre. Magellan's Cross and the Basilica Minore del Santo Niño reflect enduring religious and colonial layers in that city. Coastal communities, maritime trade and regional food traditions extend the record beyond the city while keeping neighbouring islands and Mactan's airport geography distinct.",
    highlights: ["Cebu Island coastline", "Cebu City heritage core", "Magellan's Cross", "Regional food traditions"],
    editorialProvenance: asiaBatch3SourceReferences([{ title: "Encyclopaedia Britannica — Cebu", url: "https://www.britannica.com/place/Cebu-island-Philippines" }, { title: "UNESCO Creative Cities Network — Cebu City", url: "https://www.unesco.org/en/creative-cities/cebu-city" }]),
  },
  {
    id: "tl-dili",
    summary: "Dili extends along Timor-Leste's northern coast, shaped by waterfront landmarks, markets and layered civic heritage.",
    description: "Dili occupies a narrow coastal plain between the mountains and Wetar Strait on Timor-Leste's north shore. Its waterfront and civic streets retain Portuguese architectural traces alongside institutions interpreting Timorese history and culture. The Resistance Museum, traditional markets and religious landmarks provide city-specific context without treating the wider municipality's mountains or the nation's distant sites as parts of central Dili.",
    highlights: ["Wetar Strait waterfront", "Portuguese civic architecture", "Timorese Resistance Archive and Museum", "Dili market districts"],
    editorialProvenance: asiaBatch3SourceReferences([{ title: "Encyclopaedia Britannica — Dili", url: "https://www.britannica.com/place/Dili" }, { title: "UNESCO — On the Birth of a Nation: Turning points", url: "https://www.unesco.org/en/memory-world/birth-nation-turning-points" }]),
  },
  {
    id: "id-jakarta",
    summary: "Jakarta's port heritage, old-town streets, museums and Betawi traditions trace the Indonesian capital's urban history.",
    description: "Jakarta developed on the northwest coast of Java around river mouths and a long-established maritime trading zone. Kota Tua's colonial civic buildings and museums record successive phases of the city's history, while Sunda Kelapa preserves its port relationship. Markets, neighbourhood foodways and Betawi cultural traditions add local context without expanding the record into Jabodetabek or placing CGK airport within Jakarta.",
    highlights: ["Kota Tua civic heritage", "Sunda Kelapa harbour", "National Museum collections", "Betawi cultural traditions"],
    editorialProvenance: asiaBatch3SourceReferences([{ title: "Encyclopaedia Britannica — Jakarta", url: "https://www.britannica.com/place/Jakarta" }, { title: "National Museum of Indonesia", url: "https://www.museumnasional.or.id/" }]),
  },
  {
    id: "my-kuala-lumpur",
    summary: "Kuala Lumpur's civic architecture, cultural museums, markets and neighbourhood foodways reflect Malaysia's layered capital history.",
    description: "Kuala Lumpur grew where the Klang and Gombak rivers meet, a setting still visible near its historic civic core. Merdeka Square, former administrative buildings and religious landmarks express successive architectural and community histories. Museums, markets and neighbourhood food traditions broaden the federal territory's cultural landscape without assigning Klang Valley attractions or KUL airport, both outside its boundary, to the city itself.",
    highlights: ["Klang and Gombak confluence", "Merdeka Square", "Islamic Arts Museum Malaysia", "Historic market neighbourhoods"],
    editorialProvenance: asiaBatch3SourceReferences([{ title: "Encyclopaedia Britannica — Kuala Lumpur", url: "https://www.britannica.com/place/Kuala-Lumpur" }, { title: "Islamic Arts Museum Malaysia", url: "https://www.iamm.org.my/" }]),
  },
  {
    id: "ph-manila",
    summary: "Manila faces its namesake bay through historic districts, national museums, markets and enduring port-city heritage.",
    description: "Manila occupies the eastern shore of Manila Bay around the Pasig River's mouth, distinct from the surrounding metropolitan region. Intramuros and Fort Santiago preserve Spanish colonial fortifications and civic history within the City of Manila. National Museum institutions, Binondo's commercial heritage and market foodways reveal further cultural layers without relocating attractions elsewhere in Metro Manila into the city.",
    highlights: ["Manila Bay waterfront", "Intramuros walls", "Fort Santiago", "Binondo commercial heritage"],
    editorialProvenance: asiaBatch3SourceReferences([{ title: "Intramuros Administration", url: "https://intramuros.gov.ph/" }, { title: "National Museum of the Philippines", url: "https://www.nationalmuseum.gov.ph/" }]),
  },
  {
    id: "my-penang",
    summary: "Penang encompasses island and mainland communities, with George Town heritage, coastal landscapes and multicultural food traditions.",
    description: "Penang is a Malaysian state spanning Penang Island and a mainland section across the strait, rather than one city alone. George Town, the state capital on the island, preserves UNESCO-recognised streetscapes shaped by Malay, Chinese, Indian and European communities. Clan houses, markets, food traditions and Penang Hill place that urban heritage within the canonical destination's broader coastal and island geography.",
    highlights: ["George Town UNESCO heritage", "Multicultural clan houses", "Penang Hill", "Island market and food traditions"],
    editorialProvenance: asiaBatch3SourceReferences([{ title: "UNESCO — Melaka and George Town, Historic Cities of the Straits of Malacca", url: "https://whc.unesco.org/en/list/1223/" }, { title: "Penang Global Tourism", url: "https://mypenang.gov.my/" }]),
  },
  {
    id: "in-bengaluru",
    summary: "Bengaluru preserves garden landscapes, civic architecture and historic neighbourhoods shaped by Kannada cultural traditions.",
    description: "Bengaluru occupies the elevated Deccan Plateau, where the historic pete and former cantonment created distinct urban layers. Cubbon Park, Bengaluru Palace and the monumental Vidhana Soudha mark the city through landscaped, royal and civic architecture. Museums and Kannada cultural institutions add artistic and historical context to a capital long known in English as Bangalore.",
    highlights: ["Cubbon Park", "Bengaluru Palace", "Vidhana Soudha", "Historic pete and cantonment layers"],
    editorialProvenance: asiaBatch4SourceReferences([{ title: "Karnataka Tourism — Bengaluru", url: "https://karnatakatourism.org/tour-item/bengaluru/" }, { title: "Encyclopaedia Britannica — Bengaluru", url: "https://www.britannica.com/place/Bangalore-India" }]),
  },
  {
    id: "in-chennai",
    summary: "Chennai extends along the Bay of Bengal through temple districts, museums and colonial civic landmarks.",
    description: "Chennai stretches along the Bay of Bengal, with historic Mylapore and the colonial core recording different periods of urban growth. Kapaleeshwarar Temple anchors a longstanding religious neighbourhood, while Fort St George reflects the city's history under the name Madras. Government Museum collections and institutions devoted to Carnatic music and Bharatanatyam broaden its cultural landscape.",
    highlights: ["Mylapore temple district", "Kapaleeshwarar Temple", "Fort St George", "Government Museum collections"],
    editorialProvenance: asiaBatch4SourceReferences([{ title: "Tamil Nadu Tourism — Chennai", url: "https://www.tamilnadutourism.tn.gov.in/destinations/chennai" }, { title: "Government Museum Chennai", url: "https://govtmuseumchennai.org/" }]),
  },
  {
    id: "lk-colombo",
    summary: "Colombo faces the Indian Ocean through waterfront districts, historic markets and national cultural institutions.",
    description: "Colombo occupies Sri Lanka's western coast, where the Indian Ocean waterfront meets the commercial districts of Fort and Pettah. Colonial and postcolonial civic buildings record successive phases in the capital's architectural development. The National Museum of Colombo, Gangaramaya Temple and Pettah's market streets present archaeological, religious and mercantile traditions specific to the city.",
    highlights: ["Indian Ocean waterfront", "Colombo Fort", "Pettah market streets", "National Museum of Colombo"],
    editorialProvenance: asiaBatch4SourceReferences([{ title: "Encyclopaedia Britannica — Colombo", url: "https://www.britannica.com/place/Colombo" }, { title: "Department of National Museums Sri Lanka", url: "https://museum.gov.lk/" }]),
  },
  {
    id: "in-hyderabad",
    summary: "Hyderabad preserves Deccani courtly heritage through fortified architecture, old-city markets and extensive museum collections.",
    description: "Hyderabad, India, developed on the Deccan Plateau around a walled old city and later urban districts. Charminar and nearby markets express the Qutb Shahi city's ceremonial and commercial life, while Golconda Fort recalls its earlier fortified centre. Salar Jung Museum collections and Deccani food traditions extend this history through material culture and distinctive regional cuisine.",
    highlights: ["Charminar", "Golconda Fort", "Qutb Shahi heritage", "Salar Jung Museum collections"],
    editorialProvenance: asiaBatch4SourceReferences([{ title: "Telangana Tourism — Hyderabad", url: "https://tourism.telangana.gov.in/destinations/hyderabad" }, { title: "Salar Jung Museum", url: "https://www.salarjungmuseum.in/" }]),
  },
  {
    id: "in-kochi",
    summary: "Kochi reflects an Indian Ocean trading history through waterfront quarters, religious heritage and spice-market traditions.",
    description: "Kochi developed as a port on India's Malabar Coast, with waterways and islands shaping its dispersed urban form. Fort Kochi and Mattancherry preserve churches, synagogues, warehouses and houses connected with successive trading communities and the city's former name, Cochin. The Mattancherry Palace, Paradesi Synagogue and spice-market streets document royal, Jewish and maritime cultural histories.",
    highlights: ["Fort Kochi waterfront", "Mattancherry Palace", "Paradesi Synagogue", "Historic spice-market streets"],
    editorialProvenance: asiaBatch4SourceReferences([{ title: "Kerala Tourism — Fort Kochi", url: "https://www.keralatourism.org/destination/fort-kochi/422/" }, { title: "Kerala Tourism — Mattancherry Palace", url: "https://www.keralatourism.org/destination/mattancherry-palace/178/" }]),
  },
  {
    id: "in-kolkata",
    summary: "Kolkata follows the Hooghly River through monumental civic architecture, historic neighbourhoods and major cultural collections.",
    description: "Kolkata developed beside the Hooghly River, with colonial civic precincts and North Kolkata neighbourhoods expressing contrasting urban forms. Victoria Memorial and the Indian Museum hold prominent places in the city's architectural and collecting history. Markets, literary institutions and houses associated with Bengali cultural life preserve further layers from the period when the city was called Calcutta.",
    highlights: ["Hooghly River setting", "Victoria Memorial", "Indian Museum collections", "North Kolkata neighbourhoods"],
    editorialProvenance: asiaBatch4SourceReferences([{ title: "Victoria Memorial Hall", url: "https://victoriamemorial-cal.org/" }, { title: "Indian Museum Kolkata", url: "https://indianmuseumkolkata.org/" }]),
  },
  {
    id: "in-mumbai",
    summary: "Mumbai's harbour setting frames monumental railway architecture, waterfront landmarks, museums and Art Deco precincts.",
    description: "Mumbai occupies islands and reclaimed shores around a natural harbour on India's western coast. The Gateway of India and Chhatrapati Shivaji Maharaj Terminus represent waterfront ceremony and Victorian railway architecture from the city's Bombay period. Museums, markets and the UNESCO-recognised Art Deco ensembles around the Oval Maidan reveal additional civic and residential layers.",
    highlights: ["Mumbai Harbour", "Gateway of India", "Chhatrapati Shivaji Maharaj Terminus", "Oval Maidan Art Deco ensembles"],
    editorialProvenance: asiaBatch4SourceReferences([{ title: "UNESCO — Chhatrapati Shivaji Terminus", url: "https://whc.unesco.org/en/list/945/" }, { title: "UNESCO — Victorian Gothic and Art Deco Ensembles of Mumbai", url: "https://whc.unesco.org/en/list/1480/" }]),
  },
  {
    id: "in-new-delhi",
    summary: "New Delhi's planned avenues connect national civic monuments, government architecture, museums and landscaped public spaces.",
    description: "New Delhi is the planned capital district laid out south of Old Delhi, rather than a synonym for the entire metropolis. Ceremonial avenues link India Gate with Rashtrapati Bhavan and the government buildings that define its axial civic form. The National Museum and other cultural institutions place archaeology, art and public memory within this deliberately composed urban landscape.",
    highlights: ["India Gate", "Rashtrapati Bhavan", "Ceremonial avenue plan", "National Museum collections"],
    editorialProvenance: asiaBatch4SourceReferences([{ title: "Rashtrapati Bhavan Visitor Portal", url: "https://visit.rashtrapatibhavan.gov.in/" }, { title: "National Museum, New Delhi", url: "https://nationalmuseumindia.gov.in/" }]),
  },
  {
    id: "bd-dhaka",
    summary: "Dhaka follows the Buriganga River through Mughal landmarks, historic markets and Bengali cultural institutions.",
    description: "Dhaka developed beside the Buriganga River, with Old Dhaka preserving dense lanes, mosques and long-established commercial quarters. Lalbagh Fort and Ahsan Manzil document Mughal and later civic histories within the city rather than the wider division. The Bangladesh National Museum and traditional markets extend this account through Bengali art, archaeology, crafts and everyday urban culture.",
    highlights: ["Buriganga River", "Lalbagh Fort", "Ahsan Manzil", "Bangladesh National Museum"],
    editorialProvenance: asiaBatch5SourceReferences([{ title: "Bangladesh Tourism Board — Dhaka", url: "https://beautifulbangladesh.gov.bd/district-destination/dhaka" }, { title: "Department of Archaeology — Lalbagh Fort", url: "https://archaeology.gov.bd/site/page/0555d1ae-8ef2-4d02-a622-79ce38e8fc1b/Lalbagh-Fort" }]),
  },
  {
    id: "pk-islamabad",
    summary: "Islamabad's planned avenues frame civic monuments, cultural museums and the wooded Margalla Hills.",
    description: "Islamabad occupies a planned grid beneath the Margalla Hills, distinct from neighbouring Rawalpindi and its historic core. Faisal Mosque gives the capital a monumental religious landmark, while the Pakistan Monument expresses national history through modern civic architecture. Museums and cultural institutions around the planned sectors interpret archaeology, folk traditions and art without extending the record across the wider metropolitan area.",
    highlights: ["Margalla Hills", "Faisal Mosque", "Pakistan Monument", "Lok Virsa Museum"],
    editorialProvenance: asiaBatch5SourceReferences([{ title: "Capital Development Authority — Islamabad", url: "https://www.cda.gov.pk/aboutIslamabad" }, { title: "National Institute of Folk and Traditional Heritage", url: "https://lokvirsa.org.pk/" }]),
  },
  {
    id: "pk-karachi",
    summary: "Karachi's Arabian Sea setting anchors port-city heritage, monumental architecture and diverse cultural collections.",
    description: "Karachi developed on the Arabian Sea as a port city whose historic commercial districts face a broad coastal landscape. Mazar-e-Quaid commemorates Pakistan's founder through monumental modern architecture, while Mohatta Palace preserves an earlier residential and artistic setting. Museums, Saddar's streets and traditions shaped by Sindhi and migrant communities reveal cultural layers specific to Karachi rather than the wider province.",
    highlights: ["Arabian Sea waterfront", "Mazar-e-Quaid", "Mohatta Palace", "Saddar commercial heritage"],
    editorialProvenance: asiaBatch5SourceReferences([{ title: "Sindh Tourism Development Corporation — Karachi", url: "https://stdc.gos.pk/karachi/" }, { title: "Mohatta Palace Museum", url: "https://www.mohattapalacemuseum.com/" }]),
  },
  {
    id: "np-kathmandu",
    summary: "Kathmandu preserves Newar urban heritage through palace squares, temples, courtyards and living craft traditions.",
    description: "Kathmandu occupies a mountain-ringed valley setting, while the canonical destination remains the city rather than the entire Kathmandu Valley. Kathmandu Durbar Square anchors its historic royal and civic core through palaces, temples and courtyards. Swayambhunath, museums and Newar neighbourhood traditions add religious, artistic and social context without assigning every monument in the UNESCO-listed valley to Kathmandu city.",
    highlights: ["Kathmandu Durbar Square", "Swayambhunath", "Newar courtyard neighbourhoods", "Historic temple architecture"],
    editorialProvenance: asiaBatch5SourceReferences([{ title: "UNESCO — Kathmandu Valley", url: "https://whc.unesco.org/en/list/121/" }, { title: "Nepal Tourism Board — Kathmandu", url: "https://ntb.gov.np/kathmandu" }]),
  },
  {
    id: "pk-lahore",
    summary: "Lahore's walled core preserves Mughal monuments, historic markets and enduring Punjabi cultural traditions.",
    description: "Lahore developed beside the Ravi River, with the Walled City retaining gates, bazaars and tightly patterned historic streets. Lahore Fort, Badshahi Mosque and the nearby Shalimar Gardens express successive achievements of Mughal architecture and landscape design. Museum collections, literary institutions and Punjabi food traditions broaden the city's cultural record without drawing province-wide heritage into the canonical destination.",
    highlights: ["Lahore Fort", "Badshahi Mosque", "Shalimar Gardens", "Walled City bazaars"],
    editorialProvenance: asiaBatch5SourceReferences([{ title: "UNESCO — Fort and Shalamar Gardens in Lahore", url: "https://whc.unesco.org/en/list/171/" }, { title: "Walled City of Lahore Authority", url: "https://walledcitylahore.gop.pk/" }]),
  },
  {
    id: "mv-male",
    summary: "Malé is a compact island capital defined by waterfront streets, mosques, markets and civic institutions.",
    description: "Malé occupies a compact island in the Maldives, with dense streets meeting seawalls and harbour edges on every side. The Old Friday Mosque preserves coral-stone craftsmanship and religious heritage, while the National Museum interprets the country's material history from the capital. Markets and civic spaces shape everyday city life; MLE airport remains physically separate on neighbouring Hulhulé.",
    highlights: ["Old Friday Mosque", "National Museum", "Malé waterfront", "Island market streets"],
    editorialProvenance: asiaBatch5SourceReferences([{ title: "UNESCO — Coral Stone Mosques of Maldives", url: "https://whc.unesco.org/en/tentativelists/5812/" }, { title: "Maldives National Centre for Cultural Heritage", url: "https://ncc.gov.mv/" }]),
  },
  {
    id: "bt-paro",
    summary: "Paro sits within a river valley of traditional architecture, Buddhist institutions and cultivated landscapes.",
    description: "Paro town occupies the floor of Paro Valley beside the Paro Chhu, amid cultivated fields and forested slopes. Rinpung Dzong anchors the town's religious and administrative heritage, while the National Museum of Bhutan occupies the watchtower above it. Traditional houses and Buddhist sites frame the wider valley relationship without treating Paro District or Bhutan generally as the canonical destination.",
    highlights: ["Paro Chhu valley setting", "Rinpung Dzong", "National Museum of Bhutan", "Traditional Bhutanese houses"],
    editorialProvenance: asiaBatch5SourceReferences([{ title: "Tourism Council of Bhutan — Paro", url: "https://bhutan.travel/destinations/paro" }, { title: "National Museum of Bhutan", url: "https://www.nationalmuseum.gov.bt/" }]),
  },
  {
    id: "ir-tehran",
    summary: "Tehran rises toward the Alborz foothills through royal palaces, bazaars and major cultural museums.",
    description: "Tehran spreads southward from the Alborz foothills, with broad avenues linking historic quarters and later civic districts. Golestan Palace preserves Qajar court architecture and gardens near the old bazaar, grounding the capital's royal and commercial history. The National Museum of Iran and other collections interpret archaeology, art and material culture without relying on current political, access or operating conditions.",
    highlights: ["Alborz foothill setting", "Golestan Palace", "Grand Bazaar", "National Museum of Iran"],
    editorialProvenance: asiaBatch5SourceReferences([{ title: "UNESCO — Golestan Palace", url: "https://whc.unesco.org/en/list/1422/" }, { title: "National Museum of Iran", url: "https://irannationalmuseum.ir/en/" }]),
  },
  {
    id: "kz-almaty",
    summary: "Almaty sits below the Trans-Ili Alatau amid parks, cultural institutions and distinctive civic architecture.",
    description: "Almaty occupies Kazakhstan's southeastern foothills, where broad streets and parkland face the Trans-Ili Alatau. Panfilov Park contains the timber Ascension Cathedral, a landmark of the city's late-imperial architectural history. Museum collections, markets and buildings from Soviet and post-Soviet periods document Almaty's development without extending its identity to the region's distant canyons, lakes or mountain resorts.",
    highlights: ["Trans-Ili Alatau setting", "Panfilov Park", "Ascension Cathedral", "Central State Museum collections"],
    editorialProvenance: asiaBatch6SourceReferences([{ title: "UNESCO Creative Cities Network — Almaty", url: "https://www.unesco.org/en/creative-cities/almaty" }, { title: "Kazakhstan Travel — Almaty", url: "https://kazakhstan.travel/tourist-spot/en/14/almaty-city" }]),
  },
  {
    id: "az-baku",
    summary: "Baku faces the Caspian Sea through a fortified old city and oil-era architectural districts.",
    description: "Baku rises from the Caspian shore around Icherisheher, the fortified inner city at its historic core. Within the walls, the Maiden Tower and Palace of the Shirvanshahs record medieval urban and dynastic history. Nineteenth- and early-twentieth-century buildings beyond the walls reflect the oil boom, while museums and the waterfront trace later layers of the city's civic development.",
    highlights: ["Caspian Sea waterfront", "Icherisheher walls", "Maiden Tower", "Palace of the Shirvanshahs"],
    editorialProvenance: asiaBatch6SourceReferences([{ title: "UNESCO — Walled City of Baku with the Shirvanshah's Palace and Maiden Tower", url: "https://whc.unesco.org/en/list/958/" }, { title: "Icherisheher State Historical-Architectural Reserve", url: "https://icherisheher.gov.az/en" }]),
  },
  {
    id: "kg-bishkek",
    summary: "Bishkek is a tree-lined planned capital with civic squares, museums and an Ala-Too mountain backdrop.",
    description: "Bishkek occupies the Chüy Valley beneath the Kyrgyz Ala-Too range, whose ridgeline frames the city's southern horizon. Its broad, tree-lined avenues and formal squares reflect successive phases of planned development during the Soviet period. Ala-Too Square, museum collections and market districts provide civic and cultural context within Bishkek, distinct from mountain destinations such as Ala Archa outside the city.",
    highlights: ["Kyrgyz Ala-Too backdrop", "Ala-Too Square", "Soviet-era avenue plan", "Osh Bazaar"],
    editorialProvenance: asiaBatch6SourceReferences([{ title: "Encyclopaedia Britannica — Bishkek", url: "https://www.britannica.com/place/Bishkek" }, { title: "UNESCO Creative Cities Network — Bishkek", url: "https://www.unesco.org/en/creative-cities/bishkek" }]),
  },
  {
    id: "tj-dushanbe",
    summary: "Dushanbe occupies the Hissar Valley through landscaped avenues, civic architecture and Tajik cultural institutions.",
    description: "Dushanbe stands in the Hissar Valley where the Varzob River descends from mountain terrain north of the capital. Rudaki Avenue forms a principal civic axis, connecting landscaped public spaces with monumental architecture and cultural institutions. The National Museum and institutions devoted to Tajik history, literature and material culture keep the record city-focused rather than extending it to the Pamirs or distant archaeological sites.",
    highlights: ["Hissar Valley setting", "Rudaki Avenue", "National Museum of Tajikistan", "Landscaped civic spaces"],
    editorialProvenance: asiaBatch6SourceReferences([{ title: "Encyclopaedia Britannica — Dushanbe", url: "https://www.britannica.com/place/Dushanbe" }, { title: "UNESCO Creative Cities Network — Dushanbe", url: "https://www.unesco.org/en/creative-cities/dushanbe" }]),
  },
  {
    id: "uz-tashkent",
    summary: "Tashkent preserves market, religious and museum districts within a capital reshaped by modern planning.",
    description: "Tashkent developed as an oasis settlement and trading centre on routes linking Central Asian regions. Chorsu Bazaar and the Hazrati Imam complex retain commercial and religious landmarks within the older urban fabric. Museums, broad Soviet-era avenues and the metro's architectural design document later civic development without substituting the celebrated monuments of Samarkand, Bukhara or Khiva for Tashkent's own history.",
    highlights: ["Chorsu Bazaar", "Hazrati Imam complex", "Tashkent museum collections", "Metro architectural design"],
    editorialProvenance: asiaBatch6SourceReferences([{ title: "Uzbekistan Travel — Tashkent", url: "https://uzbekistan.travel/en/i/tashkent/" }, { title: "Encyclopaedia Britannica — Tashkent", url: "https://www.britannica.com/place/Tashkent" }]),
  },
  {
    id: "ge-tbilisi",
    summary: "Tbilisi follows the Mtkvari River between steep hills, historic quarters and Georgian cultural institutions.",
    description: "Tbilisi occupies a narrow Mtkvari River valley, with neighbourhoods climbing slopes on both sides of the water. Old Tbilisi's lanes, religious buildings and Abanotubani sulfur-bath district preserve layers associated with the city's long role as Georgia's capital. Narikala overlooks this historic fabric, while museums and nineteenth-century civic architecture extend the account through material culture and planned urban growth.",
    highlights: ["Mtkvari River valley", "Old Tbilisi lanes", "Abanotubani sulfur baths", "Narikala context"],
    editorialProvenance: asiaBatch6SourceReferences([{ title: "Georgia Travel — Tbilisi", url: "https://georgia.travel/cities-towns/tbilisi" }, { title: "Georgian National Museum", url: "https://museum.ge/" }]),
  },
  {
    id: "am-yerevan",
    summary: "Yerevan's tuff-stone civic centre contains museums, public squares and institutions preserving Armenian cultural history.",
    description: "Yerevan spreads across the Hrazdan River's eastern terrain, with distant Mount Ararat forming a landscape backdrop beyond the city. Republic Square anchors a planned civic centre whose buildings use locally characteristic pink tuff stone. The Cascade, History Museum and Matenadaran contribute modern public space, archaeological collections and manuscript heritage without drawing Armenia's distant monasteries into the capital's identity.",
    highlights: ["Republic Square", "Pink tuff architecture", "Cascade complex", "Matenadaran manuscripts"],
    editorialProvenance: asiaBatch6SourceReferences([{ title: "Yerevan Municipality — Tourism", url: "https://www.yerevan.am/en/tourism/" }, { title: "Matenadaran — Mesrop Mashtots Institute of Ancient Manuscripts", url: "https://matenadaran.am/en/" }]),
  },
  {
    id: "ae-abu-dhabi",
    summary: "Abu Dhabi follows an island waterfront through civic landmarks, museums and sites recalling its early settlement.",
    description: "Abu Dhabi city occupies an island and adjoining mainland beside the Arabian Gulf, with the Corniche defining its public waterfront. Qasr Al Hosn records the settlement's development from a watchtower and fortified residence into a civic centre. Louvre Abu Dhabi and Sheikh Zayed Grand Mosque contribute established cultural and religious architecture without extending the account across the wider emirate.",
    highlights: ["Abu Dhabi Corniche", "Qasr Al Hosn", "Louvre Abu Dhabi", "Sheikh Zayed Grand Mosque"],
    editorialProvenance: asiaBatch7SourceReferences([{ title: "Experience Abu Dhabi — Qasr Al Hosn", url: "https://visitabudhabi.ae/en/where-to-go/cultural-attractions/qasr-al-hosn" }, { title: "Louvre Abu Dhabi", url: "https://www.louvreabudhabi.ae/" }, { title: "Sheikh Zayed Grand Mosque Centre", url: "https://www.szgmc.gov.ae/en/" }]),
  },
  {
    id: "jo-amman",
    summary: "Amman spreads across steep hills around a historic centre of archaeological sites, markets and museums.",
    description: "Amman rises over a series of hills, with dense neighbourhoods surrounding the downtown district of Al-Balad. The Citadel preserves Roman, Byzantine and Islamic remains above the city, while the Roman Theatre marks ancient Philadelphia's lower civic centre. The Jordan Museum and traditional market streets connect those archaeological layers with the capital's modern cultural life without drawing in Jordan-wide attractions.",
    highlights: ["Amman Citadel", "Roman Theatre", "Al-Balad market streets", "Jordan Museum"],
    editorialProvenance: asiaBatch7SourceReferences([{ title: "Visit Jordan — Amman", url: "https://international.visitjordan.com/Wheretogo/Amman" }, { title: "The Jordan Museum", url: "https://www.jordanmuseum.jo/" }]),
  },
  {
    id: "qa-doha",
    summary: "Doha curves around its namesake bay, linking a long waterfront with markets and national museums.",
    description: "Doha occupies the shore of Doha Bay, where the Corniche traces the city's relationship with the Arabian Gulf. Souq Waqif retains a market setting near the historic waterfront, while the Museum of Islamic Art anchors a purpose-built cultural precinct. The National Museum of Qatar interprets the peninsula's history from within the capital without making countrywide sites part of Doha itself.",
    highlights: ["Doha Corniche", "Souq Waqif", "Museum of Islamic Art", "National Museum of Qatar"],
    editorialProvenance: asiaBatch7SourceReferences([{ title: "Visit Qatar — Doha", url: "https://visitqatar.com/intl-en/about-qatar/doha" }, { title: "Museum of Islamic Art", url: "https://mia.org.qa/en/" }, { title: "National Museum of Qatar", url: "https://nmoq.org.qa/en/" }]),
  },
  {
    id: "sa-jeddah",
    summary: "Jeddah's Red Sea port heritage survives in Al-Balad's coral-stone houses, markets and merchant traditions.",
    description: "Jeddah developed as a Red Sea port and gateway for pilgrimage, with maritime commerce shaping its historic urban core. UNESCO-listed Historic Jeddah, known as Al-Balad, preserves coral-stone tower houses, shaded streets and markets associated with merchant families. Museums and cultural institutions interpret this port-city inheritance without relocating Mecca or other western Saudi heritage into Jeddah.",
    highlights: ["Historic Jeddah — Al-Balad", "Coral-stone tower houses", "Red Sea port heritage", "Traditional market lanes"],
    editorialProvenance: asiaBatch7SourceReferences([{ title: "UNESCO — Historic Jeddah, the Gate to Makkah", url: "https://whc.unesco.org/en/list/1361/" }, { title: "Saudi Tourism Authority — Jeddah", url: "https://www.visitsaudi.com/en/jeddah" }]),
  },
  {
    id: "kw-kuwait-city",
    summary: "Kuwait City faces the Arabian Gulf through landmark towers, museums, markets and maritime cultural institutions.",
    description: "Kuwait City extends along the Arabian Gulf, where waterfront roads and civic architecture frame the national capital. Kuwait Towers form an established element of the shoreline, while Souq Al-Mubarakiya recalls the commercial patterns of the older city. Museum collections and maritime institutions preserve archaeological, trading and seafaring histories without assigning Kuwait's islands or desert landscapes to the city.",
    highlights: ["Kuwait Towers", "Souq Al-Mubarakiya", "Arabian Gulf waterfront", "Maritime heritage collections"],
    editorialProvenance: asiaBatch7SourceReferences([{ title: "State of Kuwait — Kuwait Towers", url: "https://e.gov.kw/sites/kgoenglish/Pages/Visitors/TourismInKuwait/PlanningYourTripInKuwaitTowers.aspx" }, { title: "Dar al Athar al Islamiyyah", url: "https://darmuseum.org.kw/" }]),
  },
  {
    id: "bh-manama",
    summary: "Manama's historic commercial centre preserves market lanes, civic gateways and institutions interpreting Bahrain's trading heritage.",
    description: "Manama developed on Bahrain's northern coast as a port and commercial centre linked to Gulf trade and pearling. Bab Al Bahrain opens into the lanes of Manama Souq, where the older business district remains legible amid later civic growth. The Bahrain National Museum presents archaeology, crafts and social history without implying that Muharraq's UNESCO Pearling Path lies in central Manama.",
    highlights: ["Bab Al Bahrain", "Manama Souq", "Bahrain National Museum", "Northern waterfront setting"],
    editorialProvenance: asiaBatch7SourceReferences([{ title: "Bahrain Authority for Culture and Antiquities — Bab Al Bahrain", url: "https://culture.gov.bh/en/authority/cultural_sites/BabAlBahrain/" }, { title: "Bahrain National Museum", url: "https://culture.gov.bh/en/authority/cultural_sites/BahrainNationalMuseum/" }]),
  },
  {
    id: "om-muscat",
    summary: "Muscat follows the Gulf of Oman through harbour districts, forts, markets and national cultural institutions.",
    description: "Muscat occupies a narrow coastal setting between the Gulf of Oman and rugged mountains, with distinct harbour and civic districts. Mutrah's corniche and souq retain the city's mercantile relationship with its port, overlooked by historic fortifications. The Al Alam Palace precinct and National Museum present architectural and material heritage specific to the capital rather than to Muscat Governorate or Oman broadly.",
    highlights: ["Mutrah Corniche", "Mutrah Souq", "Al Alam Palace precinct", "National Museum of Oman"],
    editorialProvenance: asiaBatch7SourceReferences([{ title: "Experience Oman — Muscat", url: "https://experienceoman.om/destinations/muscat/" }, { title: "The National Museum — Sultanate of Oman", url: "https://www.nm.gov.om/" }]),
  },
  {
    id: "sa-riyadh",
    summary: "Riyadh's Najdi heritage appears through a historic fortress, market quarter and national cultural institutions.",
    description: "Riyadh developed on the Najd plateau around an oasis settlement, later expanding beyond its mud-brick historic core. Masmak Fort and the adjoining market quarter recall the city's earlier political and commercial landscape, while the National Museum interprets Arabian history. Nearby Diriyah is a separate municipality with a connected Najdi legacy, not a neighbourhood or monument within Riyadh city.",
    highlights: ["Masmak Fort", "Najdi urban heritage", "National Museum", "Historic market quarter"],
    editorialProvenance: asiaBatch7SourceReferences([{ title: "Royal Commission for Riyadh City — Riyadh History", url: "https://www.rcrc.gov.sa/en/riyadh/history" }, { title: "UNESCO — At-Turaif District in ad-Dir'iyah", url: "https://whc.unesco.org/en/list/1329/" }]),
  },
  {
    id: "tm-ashgabat",
    summary: "Ashgabat traces its urban history through longstanding museums, fine arts collections and civic cultural institutions.",
    description: "Ashgabat's documented development includes an early twentieth-century urban community and the growth of public cultural life. Museum traditions established in the city developed through historical collections and institutions now associated with the State Cultural Center. The State Museum and Museum of Fine Arts preserve distinct strands of Ashgabat's archaeological, historical and artistic heritage.",
    highlights: ["State Museum collections", "Museum of Fine Arts", "State Cultural Center", "Early urban history"],
    editorialProvenance: asiaFinalBatchSourceReferences([{ title: "Government of Turkmenistan — From the history of museums of Turkmenistan", url: "https://turkmenistan.gov.tm/en/post/54439/history-museums-turkmenistan" }, { title: "Government of Turkmenistan — History of Ashgabat: At the dawn of the XX century", url: "https://www.turkmenistan.gov.tm/en/post/54136/history-ashgabat-dawn-xx-century" }]),
  },
  {
    id: "iq-baghdad",
    summary: "Baghdad's Tigris riverfront links Abbasid architectural heritage, historic scholarship and national archaeological collections.",
    description: "Baghdad extends along the Tigris, where Rusafa retains a historic riverfront sequence of civic and scholarly landmarks. Al-Mustansiriya and the Abbasid Palace represent enduring architectural connections to the city's intellectual and political history. The National Museum of Iraq preserves archaeological collections that place Baghdad at the centre of the country's institutional stewardship of ancient heritage.",
    highlights: ["Tigris riverfront", "Al-Mustansiriya", "Abbasid Palace", "National Museum of Iraq"],
    editorialProvenance: asiaFinalBatchSourceReferences([{ title: "UNESCO — Archaeological museums in Iraq", url: "https://www.unesco.org/en/museums/iraq" }, { title: "UNESCO — Historical Features of the Tigris River in Baghdad Rusafa", url: "https://whc.unesco.org/en/tentativelists/5880" }]),
  },
  {
    id: "lb-beirut",
    summary: "Beirut's cultural landscape is grounded in archaeological collections, historic urban layers and longstanding museum institutions.",
    description: "Beirut's Mediterranean setting holds archaeological layers shaped by successive periods of urban life in its historic centre. The National Museum presents material from Lebanon's archaeological heritage through a major institution located in the capital. At the American University of Beirut, the Archaeological Museum has maintained Near Eastern collections since 1868, extending the city's longstanding scholarly and cultural record.",
    highlights: ["National Museum of Beirut", "AUB Archaeological Museum", "Historic-centre archaeology", "Near Eastern collections"],
    editorialProvenance: asiaFinalBatchSourceReferences([{ title: "Lebanon Ministry of Culture — National Museum", url: "https://culture.gov.lb/en/Affiliates/National-Museum" }, { title: "American University of Beirut — Archaeological Museum", url: "https://www.aub.edu.lb/museum_archeo/Pages/default.aspx" }, { title: "American University of Beirut — Archaeological Fieldwork", url: "https://www.aub.edu.lb/fas/histarc/Archaeological-Fieldwork/Pages/default.aspx" }]),
  },
  {
    id: "il-tel-aviv",
    summary: "Tel Aviv's Mediterranean urban identity is closely associated with the White City's Modern Movement architecture.",
    description: "Tel Aviv was founded in 1909 on the Mediterranean coast and developed through a planned twentieth-century urban framework. Sir Patrick Geddes's plan shaped districts containing a notable concentration of Modern Movement buildings adapted to local conditions. The bounded White City World Heritage property preserves this International Style legacy within Tel Aviv rather than designating the entire city.",
    highlights: ["White City heritage", "Geddes urban plan", "Modern Movement architecture", "International Style conservation"],
    editorialProvenance: asiaFinalBatchSourceReferences([{ title: "UNESCO — White City of Tel-Aviv – the Modern Movement", url: "https://whc.unesco.org/en/list/1096/" }, { title: "Tel Aviv–Yafo Municipality — White City", url: "https://www.tel-aviv.gov.il/en/Visit/WhiteCity/Pages/default.aspx" }]),
  },
] as const satisfies readonly ExploreDestinationEditorial[];
