"use client";
import { useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Field, Input } from "@/components/ui/Input";

export function VerifyEmailForm({ email }: { email: string }) {
  const [code, setCode] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [resending, setResending] = useState(false);
  async function submit(formData: FormData) { setLoading(true); setError(""); setMessage(""); const response = await fetch("/api/auth/verify-email", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, code: String(formData.get("code") || "") }) }); const data = await response.json(); setLoading(false); if (!response.ok) { setError(String(data.error || "The verification code is invalid or expired.")); return; } setMessage("Email verified. Redirecting to login..."); window.setTimeout(() => { window.location.href = "/auth/signin?callbackUrl=/dashboard"; }, 900); }
  async function resendCode() { setResending(true); setError(""); setMessage(""); await fetch("/api/auth/verify-email", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email }) }); setResending(false); setMessage("If this email needs verification, a new code has been sent."); }
  return <Card className="mx-auto w-full max-w-md rounded-2xl border-slate-200 p-6 shadow-lg sm:p-8"><h1 className="text-2xl font-bold text-navy">Verify your email</h1><p className="mt-2 text-sm text-muted">Enter the 6-digit code we sent to your inbox.</p><form action={submit} className="mt-5 grid gap-4"><Field label="Verification code"><Input name="code" inputMode="numeric" maxLength={6} minLength={6} pattern="[0-9]{6}" required value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, "").slice(0, 6))} /></Field>{error ? <p className="rounded-xl border border-red-200 bg-red-50 px-3 py-2 text-sm text-danger">{error}</p> : null}{message ? <p className="rounded-xl border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm text-emerald-700">{message}</p> : null}<Button disabled={loading || code.length !== 6}>{loading ? "Verifying..." : "Verify email"}</Button></form><Button type="button" variant="secondary" className="mt-3 w-full" disabled={resending} onClick={resendCode}>{resending ? "Sending..." : "Resend code"}</Button><p className="mt-4 text-sm text-muted">Already verified? <Link className="font-semibold text-teal-dark" href="/auth/signin?callbackUrl=/dashboard">Log in</Link></p></Card>;
}
